### ISSUE TITLE
:TSInstall is not installing anything

### ISSUE THREAD

**Issue by parask0s** [nvim-treesitter/nvim-treesitter#5872] opened 2024-01-08 00:53 UTC
The problem:
Just set up neovim today and installed tree-sitter via packer with no error messages. Then I tried to install my first parsers, but when I type :TSInstall {any language} (I also tried :TSUpdate, it says everything is up to date) it seems to do nothing, when I look in the \parser directory there are also no .so files.
I ran :TSInstallInfo there it says I have no parsers installed even though I ran :TSInstall lua multiple times. 
I tried to reinstall tree-sitter which also had no effect on the outcome.

When opening any file after installing tree-sitter and reopening nvim I get the following error: "Error executing lua callback: C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:24: Error executing lua: C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:25: function <SNR>32_NetrwBrowseChgDir[197]..BufReadPost Autokommandos für "*"..FileType Autokommandos für "*": Vim(append):Error executing lua callback: ...s\Neovim\share\nvim\runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 2992 for language lua"
I suppose this is because required parsers like lua are not installed but maybe it helps.

Finally here is what I get when I call :checkhealth as you can see it doesn't recognize any parser:
Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- WARNING `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `git` executable found.
- OK `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.19045",
  sysname = "Windows_NT",
  version = "Windows 10"
} ~

Parser/Features         H L F I J

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

Any tips and solutions would be great, if you need another info please tell me

**Comment by clason** [comment] 2024-01-08 08:41
Duplicate of #3092

**Closed by clason** 2024-01-08 08:41 UTC
Labels: platform Windows

**Comment by parask0s** [comment] 2024-01-08 18:02
> Duplicate of #3092

Cannot do the things that this issue is proposing, because the parser don't install in the first place, the :checkhealth parser list is empty and the two commands, which are suggested two look where the parser and query directories are, just output [].

:echo nvim_get_runtime_file('*/<lang>.so', v:true)
:echo nvim_get_runtime_file('queries/<lang>/*.scm', v:true)

**Comment by clason** [comment] 2024-01-08 18:04
Then please 1. focus your issue on the actual problem (not being able to install parsers) and 2. add much more information (environment, exact steps, output if any).

**Comment by clason** [comment] 2024-01-08 18:05
Also packer is unmaintained; you should use a different plugin manager if you're just starting out.

**Comment by parask0s** [comment] 2024-01-10 22:58
Oh thank you for your feedback, I'll try to add more information in this post, also as I hadn't set up anything special yet I changed to lazy.vim as my plugin manager.
So in my init.lua file I make sure tree-sitter is installed as followed
` require("lazy").setup( {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function () 
      local configs = require("nvim-treesitter.configs")
      configs.setup({
          ensure_installed = { "c", "lua", "vim", "vimdoc", "query"},
          sync_install = false,
          highlight = { enable = true },
          indent = { enable = true },  
        })
    end
 })`
Under nvim-data/lazy is now a tree-sitter directory in which is a parser directory, if I understood the instructions right after running :TSInstall <lang> there should be parsers in form of .so files installed there, but the directory is empty.
And I don't get any output when running :TSInstall <lang> the cursor just jumps back to whereever it was and I'm in normal mode again, it doesn't state that it is installing something nor that there was an error.

The checkhealth output is still the same as above, it doesn't show any installed parser.

Running :TSUpdate gives me "All parsers are up-to-date", which is obvious because running TSInstallInfo shows 
<lang> [✗] not installed, for all languages including the ones in ensure_installed.

If there is any other information needed please tell me, this is my first time asking and therefore I'm not really sure what to put in here, but I think this is all.

Hope this helps and as always any feedback and help is really appreciated.

**Comment by parask0s** [comment] 2024-01-15 19:24
> Then please 1. focus your issue on the actual problem (not being able to install parsers) and 2. add much more information (environment, exact steps, output if any).

would be nice that you open it maybe now that I gave more information, still couldn't figure it out sadly

**Comment by clason** [comment] 2024-01-15 19:28
Please give a minimal configuration withou lazy (lazy loading nvim-treesitter is not supported). We require a minimal template for a reason.
