### ISSUE TITLE
Scala: Invalid node at position 18

### ISSUE THREAD

**Issue by simlei** [nvim-treesitter/nvim-treesitter#4938] opened 2023-06-10 13:06 UTC
### Describe the bug

I'm getting the following error when opening scala files. 

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/982379/f2d2ba0e-2372-474d-9186-c07a5195514b)

The problem could be traced to `queries/scala/injections.scm`:

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/982379/b18127e0-4ed8-496d-a95d-3900e8f6e1f8)

I'm on neovim:
```txt
NVIM v0.10.0-dev-492+gb6d2f49b4
Build type: Debug
LuaJIT 2.1.0-beta3
```

nvim-treesitter is on the current master HEAD, i.e. `f9d701176cb9a3e206a4c690920a8993630c3ec8`.

### To Reproduce

Open a scala file with `TSInstall scala` / `TSUpdate scala` run.

### Expected behavior

It should not give errors....

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v14.21.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.15.0-73-generic",
  sysname = "Linux",
  version = "#80~20.04.1-Ubuntu SMP Wed May 17 14:58:14 UTC 2023"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - scala               x ✓ ✓ . x
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR scala(highlights): ...m/target/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 3870 for language scala
  scala(highlights) is concatenated from the following files:
  | [ERROR]:"/home/snuc/.config/nvim/pack/standalone/opt/nvim-treesitter/queries/scala/highlights.scm", failed to load: ...m/target/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 3870 for language scala
- ERROR scala(injections): ...m/target/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 18 for language scala
  scala(injections) is concatenated from the following files:
  | [ERROR]:"/home/snuc/.config/nvim/pack/standalone/opt/nvim-treesitter/queries/scala/injections.scm", failed to load: ...m/target/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 18 for language scala
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-492+gb6d2f49b4
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DNVIM_LOG_DEBUG -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/home/snuc/installations/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/snuc/installations/neovim/.deps/usr/include -I/home/snuc/installations/neovim/build/src/nvim/auto -I/home/snuc/installations/neovim/build/include -I/home/snuc/installations/neovim/build/cmake.config -I/home/snuc/installations/neovim/src

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/snuc/installations/neovim/target/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment] 2023-06-10 13:07
Duplicate of #3092

**Closed by clason** 2023-06-10 13:07 UTC
Labels: bug
