### ISSUE TITLE
Updating past 2bb9bb73 appears to break Javascript and CSS Highlighting

### ISSUE THREAD

**Issue by tingham** [nvim-treesitter/nvim-treesitter#3334] opened 2022-08-21 17:59 UTC
### Describe the bug

Updating to the latest via Packer produces a bunch of "failed to load messages"

### To Reproduce

1. Update your packer plugins configuration to fetch latest updates of nvim-treesitter/nvim-treesitter
2. Reload nvim with an *.js file
3. See redmarks for pretty much everything

Rolling back to "2bb9bb73" via use({"nvim-treesitter/nvim-treesitter", commit = "2bb9bb73", ...}) and re-opening the file displays syntax coloring as before with no redmarks.

### Expected behavior

I expect to be able to load nvim with a *.js buffer and not see redmarks (red background, white text, etc.)

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.7.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - python         ✓ ✓ ✓ ✓ ✓
  - comment        ✓ . . . .
  - lua            ✓ ✓ ✓ ✓ ✓
  - dot            ✓ . . . ✓
  - ledger         ✓ . ✓ ✓ ✓
  - markdown       ✓ . ✓ . ✓
  - typescript     ✓ ✓ ✓ ✓ ✓
  - help           ✓ . . . .
  - bash           ✓ ✓ ✓ . ✓
  - hcl            ✓ . ✓ ✓ ✓
  - cpp            ✓ ✓ ✓ ✓ ✓
  - latex          ✓ . ✓ . ✓
  - css            ✓ . ✓ ✓ ✓
  - regex          ✓ . . . .
  - vim            x ✓ ✓ . x
  - cmake          ✓ . ✓ . .
  - c              ✓ ✓ ✓ ✓ ✓
  - java           ✓ ✓ . ✓ ✓
  - jsdoc          ✓ . . . .
  - yaml           ✓ ✓ ✓ ✓ ✓
  - html           ✓ ✓ ✓ ✓ ✓
  - toml           ✓ ✓ ✓ ✓ ✓
  - scss           ✓ . . ✓ .
  - javascript     x ✓ ✓ ✓ ✓
  - json           ✓ ✓ ✓ ✓ .
  - kotlin         ✓ ✓ ✓ . ✓
  - dockerfile     ✓ . . . ✓
  - go             ✓ ✓ ✓ ✓ ✓
  - c_sharp        ✓ ✓ ✓ . ✓
  - graphql        ✓ . . ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: vim(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:174: query: invalid node type at position 2110
    vim(highlights) is concatenated from the following files:
    | [ERROR]:"/home/tingham/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/vim/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:174: query: invalid node type at position 2110
  - ERROR: vim(injections): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:174: query: invalid structure at position 23
    vim(injections) is concatenated from the following files:
    | [ERROR]:"/home/tingham/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/vim/injections.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:174: query: invalid structure at position 23
  - ERROR: javascript(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:174: query: invalid node type at position 5557
    javascript(highlights) is concatenated from the following files:
    |    [OK]:"/home/tingham/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/ecma/highlights.scm"
    |    [OK]:"/home/tingham/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/jsx/highlights.scm"
    | [ERROR]:"/home/tingham/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/javascript/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:174: query: invalid node type at position 651
```

### Output of `nvim --version`

```text
nvim -v
NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-8J2gXV/neovim-0.8.0~ubuntu1+git202208202347-ff5cfcdea-c99271b19=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-8J2gXV/neovim-0.8.0~ubuntu1+git202208202347-ff5cfcdea-c99271b19/build/cmake.config -I/build/neovim-8J2gXV/neovim-0.8.0~ubuntu1+git202208202347-ff5cfcdea-c99271b19/src -I/build/neovim-8J2gXV/neovim-0.8.0~ubuntu1+git202208202347-ff5cfcdea-c99271b19/.deps/usr/include -I/usr/include -I/build/neovim-8J2gXV/neovim-0.8.0~ubuntu1+git202208202347-ff5cfcdea-c99271b19/build/src/nvim/auto -I/build/neovim-8J2gXV/neovim-0.8.0~ubuntu1+git202208202347-ff5cfcdea-c99271b19/build/include
Compiled by buildd@lcy02-amd64-115

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by clason** [comment] 2022-08-21 18:06
Duplicate of #3092

**Closed by clason** 2022-08-21 18:06 UTC
Labels: bug

**Comment by tomasky** [comment] 2022-08-26 03:54
maybe the same problem

> neovim/share/nvim/runtime/filetype.lua:20: Vim(append):Error executing lua callba
ck: ...y/neovim/share/nvim/runtime/lua/vim/treesitter/query.lua:174: query: invalid structure at position 23
stack traceback:
        [C]: in function '_ts_parse_query'
