### ISSUE TITLE
highlighting disappears after performing a sort

### ISSUE THREAD

**Issue by dimbleby** [nvim-treesitter/nvim-treesitter#1250] opened 2021-04-24 22:48 UTC
**Describe the bug**

Start with this python file
```python
foo = [
    "a list of strings",
    "initially in the sorted order already",
    "on performing a sort operation",
    "the highlighting goes wrong",
]
```
sort the contents of the list, by selecting those lines and `:'<,'>sort`.  The strings are no longer highlighted.

https://asciinema.org/a/OYlWnBjhYlbtqxisq5QaHpC6p

**To Reproduce**

As above.

**Expected behavior**

Highlighting is not broken by sorting.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.4 (6dd41e2e45f8b4a00fda21f28bc0ebc6b172ffed) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v15.14.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - ql             ✓ ✓ . ✓ 
  - zig            ✓ ✓ ✓ ✓ 
  - verilog        ✓ ✓ ✓ . 
  - ocaml          ✓ ✓ ✓ . 
  - ocaml_interface✓ ✓ ✓ . 
  - fortran        ✓ . ✓ . 
  - bibtex         ✓ . ✓ ✓ 
  - ocamllex       ✓ . . . 
  - latex          ✓ . ✓ . 
  - c              ✓ ✓ ✓ ✓ 
  - beancount      ✓ . ✓ . 
  - c_sharp        ✓ . . . 
  - r              ✓ ✓ . . 
  - svelte         ✓ . ✓ ✓ 
  - elm            . . . . 
  - typescript     ✓ ✓ ✓ ✓ 
  - turtle         ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ 
  - sparql         ✓ ✓ ✓ ✓ 
  - clojure        ✓ ✓ . . 
  - swift          . . . . 
  - scala          . . . . 
  - regex          ✓ . . . 
  - supercollider  ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . 
  - jsdoc          ✓ . . . 
  - haskell        . . . . 
  - go             ✓ ✓ ✓ ✓ 
  - ledger         ✓ . ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ 
  - glimmer        ✓ . . . 
  - javascript     ✓ ✓ ✓ ✓ 
  - gdscript       ✓ ✓ . . 
  - toml           ✓ ✓ ✓ ✓ 
  - nix            ✓ ✓ ✓ . 
  - jsonc          ✓ ✓ ✓ ✓ 
  - graphql        ✓ . . ✓ 
  - lua            ✓ ✓ ✓ ✓ 
  - devicetree     ✓ ✓ ✓ ✓ 
  - ruby           ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ 
  - python         ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . 
  - kotlin         ✓ . . . 
  - yaml           ✓ ✓ ✓ ✓ 
  - vue            ✓ . ✓ . 
  - html           ✓ ✓ ✓ ✓ 
  - php            ✓ ✓ ✓ ✓ 
  - julia          ✓ ✓ . . 
  - dart           ✓ ✓ . ✓ 
  - cpp            ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ 
  - rst            ✓ ✓ . . 
  - css            ✓ . ✓ ✓ 
  - fennel         ✓ ✓ . . 
  - scss           ✓ . . ✓ 
  - teal           ✓ ✓ ✓ ✓ 
  - erlang         . . . . 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+1280-gbb7d3790b-dirty
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/dch/neovim/build/config -I/home/dch/neovim/src -I/home/dch/neovim/.deps/usr/include -I/usr/include -I/home/dch/neovim/build/src/nvim/auto -I/home/dch/neovim/build/include
Compiled by dch@PC6648

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/dch/.local/nvim/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

Interestingly the highlighting does not seem to break if the sort actually changes anything, I only reproduce the bug if the lines being sorted are in the sorted order from the start.

**Comment by vigoux** [comment] 2021-04-25 06:58
Hi, thanks for reporting!
That seems like a buffer update issue to me, I'll dig into it.

**Comment by vigoux** [comment] 2021-05-01 09:22
This is a redraw issue in the end, so not a byte update issue.
@bfredl I might need your help on this.

**Comment by biggiesmallsAG** [comment] 2021-08-05 21:06
Having similar issue, only with html open tag elements. I checked in playground, all the elements/attributes seem to be properly assigned. Ive attached a screencap of whats happening.

Im running the latest versions of nvim/tsitter/all plugins. As ive seen in other issues, C-l does redraw the buffer. Have no issues in python/typescript/react/lua/go (that ive seen anyway)

[https://imgur.com/a/mM2SDFK](url)

**Comment by vigoux** [comment] 2021-08-06 09:10
Last time this looked like a redrawing issue, I am going to add that to my todo list.

**Comment by vigoux** [comment] 2021-08-06 10:02
Hey, I think I found a fix, please check to above PR to verify that the issue is gone.

**Comment by biggiesmallsAG** [comment] 2021-08-14 21:36
@vigoux tried your PR, still have the same issue.. in playground the nodes are correctly displayed but when highlighting disappears, TSHighlightCapturesUnderCursor shows "No highlight groups found". This literally happens for HTML files only... every other file type i work in seems completely fine. Im somewhat convinced that its a bug in the html ls or something?

**Comment by vigoux** [comment] 2021-08-16 07:30
Do you still have the issue even when using this python file you provided ?

**Comment by biggiesmallsAG** [comment] 2021-08-23 00:32
i didnt provide the python file and i have no issues with python/typescript/go/(insert anything here) except html files that are mostly angular based.

**Comment by vigoux** [comment] 2021-08-23 08:16
The fix is being worked on, sorry for the delay.

**Comment by biggiesmallsAG** [comment] 2021-08-23 21:40
thanks mate, appreciate your effort, if you need any sample code  i dropped it in [https://github.com/nvim-treesitter/nvim-treesitter/issues/1702](url)

**Comment by vigoux** [comment] 2021-08-24 07:50
Hmmm I don't seem to find this issue somewhere ...

**Comment by biggiesmallsAG** [comment] 2021-08-24 20:19
it was closed. here is the code that causes issues..

```html
<div class="clr-row clr-justify-content-center">
  <form class="clr-form clr-form-compact">
    <div class="clr-col-1" *ngIf="clientId$ | async as routedClient">
      <clr-select-container>
        <label>Client</label>
        <select
          clrSelect
          name="clientid"
          [ngModel]="routedClient"
          (ngModelChange)="clientid($event)"
        >
          <option
            *ngFor="let client of clients$ | async"
            [ngValue]="client.id"
            [selected]="routedClient === client.id"
          >
            {{ client.client_name }}
          </option>
        </select>
      </clr-select-container>
    </div>
    <div class="clr-col-1" *ngIf="clientsProjects$ | async as projects">
      <clr-select-container>
        <label>Project</label>
        <select
          clrSelect
          name="projectid"
          [ngModel]="projectId$ | async"
          (ngModelChange)="projectid($event)"
        >
          <option [selected]="true"></option>
          <option *ngFor="let project of projects" [ngValue]="project.id">
            {{ project.project_name }}
          </option>
        </select>
      </clr-select-container>
    </div>
  </form>
</div>
```

https://imgur.com/a/87po5wz

**Comment by vigoux** [comment] 2021-11-09 12:20
Hi, this should have been fixed by https://github.com/neovim/neovim/pull/15962, which landed on master, could you confirm it is the case and close this issue accordingly ?

**Closed** 2021-11-09 12:22 UTC
Labels: bug, upstream
