### ISSUE TITLE
Got error when `nvim +h`

### ISSUE THREAD

**Issue by zetatez** [nvim-treesitter/nvim-treesitter#3904] opened 2022-12-01 12:00 UTC
### Describe the bug

```bash
nvim +h
```
Got
```
Error detected while processing command line..BufReadPost Autocommands for "*":
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:22: Error executing lua: /usr/share/nvim/runtime/filetype.lua:23: Vim(append):Error executing lua callback: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query:
 invalid node type at position 14 for language help
stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: in function 'get_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:52: in function 'new'
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:45: in function '_create_parser'
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:96: in function 'get_parser'
        .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:34: in function 'start'
        .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:42: in function 'attach'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:505: in function 'attach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:528: in function 'reattach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:131: in function <...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:130>
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:23: in function </usr/share/nvim/runtime/filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
stack traceback:
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:23: in function </usr/share/nvim/runtime/filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
Press ENTER or type command to continue
```

### To Reproduce

```bash
nvim +h
```

### Expected behavior

Enter nvim help manual.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.13.2 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "6.0.10-arch2-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Sat, 26 Nov 2022 16:51:18 +0000"
}

## Parser/Features H L F I J
  - cpp            ✓ ✓ ✓ ✓ ✓
  - latex          ✓ . ✓ . ✓
  - scala          ✓ . ✓ . ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - java           ✓ ✓ . ✓ ✓
  - dockerfile     ✓ . . . ✓
  - sql            ✓ . . . ✓
  - help           x . . . x
  - bash           ✓ ✓ ✓ . ✓
  - gitignore      ✓ . . . .
  - vue            ✓ . ✓ ✓ ✓
  - yaml           ✓ ✓ ✓ ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - vim            ✓ ✓ ✓ . ✓
  - diff           ✓ . . . .
  - markdown       ✓ . ✓ . ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - go             ✓ ✓ ✓ ✓ ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - json           ✓ ✓ ✓ ✓ .
  - cmake          ✓ . ✓ . .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: help(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 428 for language help
    help(highlights) is concatenated from the following files:
    | [ERROR]:"/home/dionysus/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/help/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 428 for language help
  - ERROR: help(injections): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 14 for language help
    help(injections) is concatenated from the following files:
    | [ERROR]:"/home/dionysus/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/help/injections.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 14 for language help
```

### Output of `nvim --version`

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
 
Features: +acl +iconv +tui
See ":help feature-compile"
 
   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
 
Run :checkhealth for more info
```

**Comment by clason** [comment] 2022-12-01 12:01
Duplicate of #3092

**Closed by clason** 2022-12-01 12:01 UTC
Labels: bug
