### ISSUE TITLE
 Why I have this error?

### ISSUE THREAD

**Issue by denstiny** [nvim-treesitter/nvim-treesitter#889] opened 2021-01-30 09:57 UTC
# My work environment :neovim 5.0

# Error is as follows
![image](https://user-images.githubusercontent.com/57088952/106353306-8407ac80-6324-11eb-9153-13037c7cd71d.png)

# My configuration
```lua
lua <<EOF

-- 代码高亮
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained", -- one of "all", "maintained" (parsers with maintainers), or a list of languages
  highlight = {
    enable = true,              -- false将禁用整个扩展
    -- disable = { "c", "rust" },  -- 将被禁用的语言列表
  },
}

-- 代码缩进
require'nvim-treesitter.configs'.setup {
    indent = {
      enable = false
    },
  }

-- 高亮显示光标下符号的定义
require'nvim-treesitter.configs'.setup {
  refactor = {
    highlight_definitions = { enable = true },
  },
}

-- 高亮当前范围
require'nvim-treesitter.configs'.setup {
  refactor = {
    highlight_current_scope = { enable = true },
  },
}

-- 智能重命名
require'nvim-treesitter.configs'.setup {
  refactor = {
    smart_rename = {
      enable = true,
      keymaps = {
        smart_rename = "grr", -- 设置快捷键为 grr
      },
    },
  },
}

-- 转到定义
 require'nvim-treesitter.configs'.setup {
   refactor = {
     navigation = {
       enable = false,
       keymaps = {
         goto_definition = "gnd",
         list_definitions = "gnD",
         list_definitions_toc = "gO",
         goto_next_usage = "<a-*>",
         goto_previous_usage = "<a-#>",
       },
     },
   },
 }

-- 游乐园
require "nvim-treesitter.configs".setup {
  query_linter = {
    enable = true,
    use_virtual_text = true,
    lint_events = {"BufWrite", "CursorHold"},
  },
}

EOF
```

**Comment by elianiva** [comment] 2021-01-30 14:32
#651 and it's easily solved by doing `:edit`

**Comment by stsewd** [comment] 2021-01-30 16:17
Looks like a duplicate of #651, as elianiva mentioned, you can solve it with 

```
:write | edit | TSBufEnable highlight
```

**Closed by stsewd** 2021-01-30 16:17 UTC
Labels: bug
