### ISSUE TITLE
Refactor module points to wrong directory (E5108: Error executing lua [string ":lua"]:1: module 'nvim-treesitter.refactor.highlight_current_scope' not found:)

### ISSUE THREAD

**Issue by sjeon7** [nvim-treesitter/nvim-treesitter#565] opened 2020-10-07 03:18 UTC
**Describe the bug**
Installing external module nvim-treesitter-refactor throws module not found error.
Currently, refactor modules are stored in `nvim-treesitter-refactor/lua/nvim-treesitter-refactor/*.lua` but nvim-treesitter plugin tires to find relevant files in `nvim-treesitter-refactor/lua/nvim-treesitter/refactor/*.lua`.

Creating  `nvim-treesitter-refactor/lua/nvim-treesitter/refactor/` folder and copy lua files resolves the error.

Other external module such as nvim-treesitter-textobjects has lua files stored in `nvim-treesitter-textobjects/lua/nvim-treesitter/textobjects/*.lua`.

**To Reproduce**
1. With Neovim version 0.5.0-736-g07fde6c39 (latest nightly) 
2. With clean init.vim with enabling refactor modules
```
call plug#begin('~/.config/nvim/plugged')
        Plug 'nvim-treesitter/nvim-treesitter'
    Plug 'nvim-treesitter/nvim-treesitter-refactor'
call plug#end()

lua << EOF
require'nvim-treesitter.configs'.setup {
        highlight = {
                enable = true,
        },
        refactor = {
        highlight_definitions = { enable = true },
        highlight_current_scope = { enable = true },
        smart_rename = {
          enable = true,
          keymaps = {
            smart_rename = "grr",
          },
        },
        navigation = {
            enable = true,
            keymaps = {
              goto_definition = "gnd",
              list_definitions = "gnD",
              list_definitions_toc = "gO",
              goto_next_usage = "<a-*>",
              goto_previous_usage = "<a-#>",
            },
        },
        },
        ensure_installed = 'python'
}
EOF
```
3. Plug update for newest nvim-treesitter and nvim-treesitter-refactor.
4. Open any python file (or any other languages).
5. See the error.

**Expected behavior**
There should be no error. External module should point correct directories.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## c parser healthcheck
  - OK: c parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for c
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - OK: `folds.scm` found.

## python parser healthcheck
  - OK: python parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for python
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - OK: `folds.scm` found.

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-736-g07fde6c39
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-67eb7ccd-7b20-47cb-a5a0-339b27e7d3af

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"
```

**Additional context**
Before bug fix, creating `nvim-treesitter-refactor/lua/nvim-treesitter/refactor/` directory and copy *.lua files in `nvim-treesitter-refactor/lua/nvim-treesitter-refactor/` should work.

**Comment by Happy-Dude** [comment] 2020-10-07 03:36
I confirm that I am running into this issue too.

**Comment by stsewd** [comment] 2020-10-07 04:23
Did you try doing a clean installation? (Deleting the folders from the plug for). I'm not at the computer but everything was working recently, if anything this is a regression in this repo, not in the refactor repo

**Comment by Happy-Dude** [comment] 2020-10-07 04:30
@stsewd it was a vestige from when the modules were moved out -- `highlight_current_scope` referred to the module path incorrectly.

When you have a moment, nvim-treesitter/nvim-treesitter-refactor/pull/3 should address it I believe

**Comment by sjeon7** [comment] 2020-10-07 05:52
@stsewd I tested with a clean installation.
@Happy-Dude Thank you for clarifying the issue.

**Comment by stsewd** [comment] 2020-10-07 14:28
I'm not able to replicate this with the latest versions of both plugins. Also, you can see the module path is pointing to the right path. What OS are you using? It works for me in linux fedora 32.

I also tested it with a clean installation.

**Comment by Happy-Dude** [comment] 2020-10-07 14:33
Using macOS Catalina; does the error show up when you enable highlight_current_scope?

I can hop on the neovim gitter and debug in real time if it helps 👍

**Comment by stsewd** [comment] 2020-10-07 14:37
Ok, I can replicate with hightligh_current_scope, but the other modules work fine for me. So I guess something buggy or a typo there.

> I can hop on the neovim gitter and debug in real time if it helps +1

Sorry I'm not available at the moment

**Comment by theHamsta** [comment] 2020-10-07 14:39
https://github.com/nvim-treesitter/nvim-treesitter-refactor/blob/130d9485a983814364ee2094e6073eb9e96f71d8/lua/nvim-treesitter-refactor/highlight_current_scope.lua#L33-L34

**Comment by stsewd** [comment] 2020-10-07 21:45
Fixed in https://github.com/nvim-treesitter/nvim-treesitter-refactor/pull/4

**Closed by stsewd** 2020-10-07 21:45 UTC
Labels: bug
