### ISSUE TITLE
:help breaks when nvim-treesitter is installed

### ISSUE THREAD

**Issue by NSchweers** [nvim-treesitter/nvim-treesitter#6953] opened 2024-07-21 13:28 UTC
### Describe the bug

Opening :help causes a new window to popup (and repeatedly popup upon hitter ENTER) as soon as nvim-treesitter is installed.

The window contains the following:
```
Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...s/.local/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 2:4. Invalid node type "delimiter":
  (delimiter) @markup.heading.1
   ^

stack traceback:
        [C]: in function '_ts_parse_query'
        ...s/.local/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
        ...eers/.local/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
        ...eers/.local/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:240: in function 'get_query'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:188: in function 'fn'
        ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:175: in function 'prepare_highlight_states'
        ...al/share/nvim/runtime/lua/vim/tr
Press ENTER or type command to continue
```

### To Reproduce

1. Install nvim (either 0.10.0 or the current commit e1b7fa2a3a2ad6e91128e20203e226200d9d9bef)
2. Install nvim-treesitter by cloning the git repository to `$HOME/.local/share/nvim/site/pack/nvim-treesitter/start/nvim-treesitter`
3. Start nvim
4. Type `:help`

### Expected behavior

The help page should be shown.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v18.19.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Debian 12.2.0-14) 12.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.1.0-23-amd64",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15)"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              x . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR vimdoc(highlights): ...s/.local/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 2:4. Invalid node type "delimiter":
    (delimiter) @markup.heading.1
     ^
  
  vimdoc(highlights) is concatenated from the following files:
  | [ERROR]:"/home/schweers/.local/share/nvim/site/pack/nvim-treesitter/start/nvim-treesitter/queries/vimdoc/highlights.scm", failed to load: ...s/.local/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 2:4. Invalid node type "delimiter":
    (delimiter) @markup.heading.1
     ^
```

### Output of `nvim --version`

```text
NVIM v0.11.0-dev-477+ge1b7fa2a3
Build type: Release
LuaJIT 2.1.1720049189
Run "nvim -V1 -v" for more info
```

**Comment by NSchweers** [comment] 2024-07-21 13:32
I forgot to mention that I also generate the docs by running nvim with `-u NONE -c 'helptags nvim-treesitter/doc' -c -q from `$HOME/.local/share/nvim/site/pack/nvim-treesitter/start/`

**Comment by clason** [comment] 2024-07-21 13:33
Duplicate of #3092

**Closed by clason** 2024-07-21 13:33 UTC
Labels: bug
