### ISSUE TITLE
Getting a bunch of errors in check health, 

### ISSUE THREAD

**Issue by leet0rz** [nvim-treesitter/nvim-treesitter#5216] opened 2023-08-10 07:00 UTC
### Describe the bug

Can't TSInstall python

### To Reproduce

Just installed treesitter in neovim and tried to run "TSInstall python"

### Expected behavior

Being able to run TSInstall python and have that all working.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v18.17.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: gcc (MinGW.org GCC-6.3.0-1) 6.3.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.19044",
  sysname = "Windows_NT",
  version = "Windows 10 Pro"
} ~

Parser/Features         H L F I J
  - c                   x x x x x
  - javascript          x x x x x
  - lua                 x x x x x
  - vim                 x x x . x
  - vimdoc              x . . . x

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR c(highlights): Failed to load parser for language 'c': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\c.so is not a valid Win32 application.
  
  c(highlights) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\c\highlights.scm", failed to load: Failed to load parser for language 'c': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\c.so is not a valid Win32 application.
- ERROR c(locals): Failed to load parser for language 'c': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\c.so is not a valid Win32 application.
  
  c(locals) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\c\locals.scm", failed to load: Failed to load parser for language 'c': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\c.so is not a valid Win32 application.
- ERROR c(folds): Failed to load parser for language 'c': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\c.so is not a valid Win32 application.
  
  c(folds) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\c\folds.scm", failed to load: Failed to load parser for language 'c': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\c.so is not a valid Win32 application.
- ERROR c(indents): Failed to load parser for language 'c': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\c.so is not a valid Win32 application.
  
  c(indents) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\c\indents.scm", failed to load: Failed to load parser for language 'c': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\c.so is not a valid Win32 application.
- ERROR c(injections): Failed to load parser for language 'c': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\c.so is not a valid Win32 application.
  
  c(injections) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\c\injections.scm", failed to load: Failed to load parser for language 'c': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\c.so is not a valid Win32 application.
- ERROR javascript(highlights): Failed to load parser for language 'javascript': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\javascript.so is not a valid Win32 application.
  
  javascript(highlights) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\ecma\highlights.scm", failed to load: Failed to load parser for language 'javascript': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\javascript.so is not a valid Win32 application.
  
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\jsx\highlights.scm", failed to load: Failed to load parser for language 'javascript': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\javascript.so is not a valid Win32 application.
  
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\javascript\highlights.scm", failed to load: Failed to load parser for language 'javascript': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\javascript.so is not a valid Win32 application.
- ERROR javascript(locals): Failed to load parser for language 'javascript': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\javascript.so is not a valid Win32 application.
  
  javascript(locals) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\ecma\locals.scm", failed to load: Failed to load parser for language 'javascript': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\javascript.so is not a valid Win32 application.
  
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\javascript\locals.scm", failed to load: Failed to load parser for language 'javascript': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\javascript.so is not a valid Win32 application.
- ERROR javascript(folds): Failed to load parser for language 'javascript': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\javascript.so is not a valid Win32 application.
  
  javascript(folds) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\ecma\folds.scm", failed to load: Failed to load parser for language 'javascript': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\javascript.so is not a valid Win32 application.
  
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\jsx\folds.scm", failed to load: Failed to load parser for language 'javascript': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\javascript.so is not a valid Win32 application.
  
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\javascript\folds.scm", failed to load: Failed to load parser for language 'javascript': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\javascript.so is not a valid Win32 application.
- ERROR javascript(indents): Failed to load parser for language 'javascript': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\javascript.so is not a valid Win32 application.
  
  javascript(indents) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\ecma\indents.scm", failed to load: Failed to load parser for language 'javascript': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\javascript.so is not a valid Win32 application.
  
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\jsx\indents.scm", failed to load: Failed to load parser for language 'javascript': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\javascript.so is not a valid Win32 application.
  
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\javascript\indents.scm", failed to load: Failed to load parser for language 'javascript': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\javascript.so is not a valid Win32 application.
- ERROR javascript(injections): Failed to load parser for language 'javascript': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\javascript.so is not a valid Win32 application.
  
  javascript(injections) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\ecma\injections.scm", failed to load: Failed to load parser for language 'javascript': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\javascript.so is not a valid Win32 application.
  
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\jsx\injections.scm", failed to load: Failed to load parser for language 'javascript': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\javascript.so is not a valid Win32 application.
  
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\javascript\injections.scm", failed to load: Failed to load parser for language 'javascript': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\javascript.so is not a valid Win32 application.
- ERROR lua(highlights): Failed to load parser for language 'lua': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\lua.so is not a valid Win32 application.
  
  lua(highlights) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\lua\highlights.scm", failed to load: Failed to load parser for language 'lua': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\lua.so is not a valid Win32 application.
- ERROR lua(locals): Failed to load parser for language 'lua': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\lua.so is not a valid Win32 application.
  
  lua(locals) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\lua\locals.scm", failed to load: Failed to load parser for language 'lua': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\lua.so is not a valid Win32 application.
- ERROR lua(folds): Failed to load parser for language 'lua': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\lua.so is not a valid Win32 application.
  
  lua(folds) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\lua\folds.scm", failed to load: Failed to load parser for language 'lua': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\lua.so is not a valid Win32 application.
- ERROR lua(indents): Failed to load parser for language 'lua': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\lua.so is not a valid Win32 application.
  
  lua(indents) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\lua\indents.scm", failed to load: Failed to load parser for language 'lua': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\lua.so is not a valid Win32 application.
- ERROR lua(injections): Failed to load parser for language 'lua': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\lua.so is not a valid Win32 application.
  
  lua(injections) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\lua\injections.scm", failed to load: Failed to load parser for language 'lua': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\lua.so is not a valid Win32 application.
- ERROR vim(highlights): Failed to load parser for language 'vim': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\vim.so is not a valid Win32 application.
  
  vim(highlights) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\vim\highlights.scm", failed to load: Failed to load parser for language 'vim': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\vim.so is not a valid Win32 application.
- ERROR vim(locals): Failed to load parser for language 'vim': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\vim.so is not a valid Win32 application.
  
  vim(locals) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\vim\locals.scm", failed to load: Failed to load parser for language 'vim': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\vim.so is not a valid Win32 application.
- ERROR vim(folds): Failed to load parser for language 'vim': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\vim.so is not a valid Win32 application.
  
  vim(folds) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\vim\folds.scm", failed to load: Failed to load parser for language 'vim': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\vim.so is not a valid Win32 application.
- ERROR vim(injections): Failed to load parser for language 'vim': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\vim.so is not a valid Win32 application.
  
  vim(injections) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\vim\injections.scm", failed to load: Failed to load parser for language 'vim': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\vim.so is not a valid Win32 application.
- ERROR vimdoc(highlights): Failed to load parser for language 'vimdoc': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\vimdoc.so is not a valid Win32 application.
  
  vimdoc(highlights) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\vimdoc\highlights.scm", failed to load: Failed to load parser for language 'vimdoc': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\vimdoc.so is not a valid Win32 application.
- ERROR vimdoc(injections): Failed to load parser for language 'vimdoc': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\vimdoc.so is not a valid Win32 application.
  
  vimdoc(injections) is concatenated from the following files:
  | [ERROR]:"C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\vimdoc\injections.scm", failed to load: Failed to load parser for language 'vimdoc': uv_dlopen: C:\Users\waffle\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\vimdoc.so is not a valid Win32 application.
```

### Output of `nvim --version`

```text
NVIM v0.9.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by lucario387** [comment] 2023-08-10 12:59
Duplicate of #4699, #4861, and many more

**Closed by lucario387** 2023-08-10 12:59 UTC
Labels: bug
