### ISSUE TITLE
Is it possible to support syntax based spell options like @Spell and @NoSpell

### ISSUE THREAD

**Issue by weilbith** [nvim-treesitter/nvim-treesitter#698] opened 2020-11-24 08:34 UTC
I'm always frustrated when all camel-case variables are marked as spelling mistake.

It would be cool if it would be possible to use the [syntax spell](https://neovim.io/doc/user/syntax.html#:syn-spell) option. Is it possible to set the `@Spell` and `@NoSpell` for the syntax by Treesitter? :thinking: 

Turning of spell checking is not really an option. Also does the highlighting also get shown for syntax keywords, which is even worse.

Maybe I just need to set some options correctly. I would be glad if someone could tell me how to.

Here two screenshots of some TypeScript code, first with `set spell` and second with `set nospell`.

![screenshot_1606206697](https://user-images.githubusercontent.com/12543647/100068631-1167e580-2e38-11eb-8e17-3e629a92509b.png)
![screenshot_1606206706](https://user-images.githubusercontent.com/12543647/100068688-22b0f200-2e38-11eb-872f-b04bc3b227b4.png)

**Comment by vigoux** [comment] 2020-11-24 08:54
This is an interesting idea.
But there is some intermediate steps for that like being able to set an option over a given range.

I think this is, in the end one of the things we want to do, so let's keep that open.

**Comment by lewis6991** [comment] 2020-12-07 16:40
This is the biggest thing stopping me from user treesitter right now as the clutter caused by `set spell` offsets the benefits of using treesitter.

> But there is some intermediate steps for that like being able to set an option over a given range.

Could you elaborate on this a bit more? Is there no way to re-use the old vim syntax groups to achieve this or is the point of treesitter to completely leave them in the dust? 

One naive solution to this would be to support using `@Spell` and `@NoSpell` on highlight groups (as opposed to syntax groups) in some form, but I'm sure there are reasons why that might be an awful solution.

**Comment by lewis6991** [comment] 2020-12-10 10:52
Here's a hacky workaround I came up with for anyone who's interested:

```lua
-- Treesitter stops syntax files from being loaded so need to redefine commentstrings for 
-- languages we care about.
local commentstrings = {
  python  = '#',
  json    = '#',
  bash    = '#',
  lua     = '--',
  verilog = '//'
}

require'nvim-treesitter'.define_modules {
  fixspell = {
    enable = true,
    attach = function(bufnr, lang)
      local cs = commentstrings[lang]
      vim.cmd(
        ('syntax match spellComment "%s.*" contains=@Spell'):format(cs)
      )
    end,
    detach = function(bufnr)
    end,
    is_supported = function(lang)
      if commentstrings[lang] == nil then
        return false
      end
      if require('nvim-treesitter.query').get_query(lang, 'highlights') == nil then
        return false
      end
      return true
    end
  }
}
```

It's very crude but much better than `set nospell`.

**Comment by vigoux** [comment] 2020-12-10 18:09
Oh interesting... I am currently looking into this, but I don't think it'll be easy... I'll keep you up to date.

**Comment by vigoux** [comment] 2021-01-14 17:40
For now no updates, as we are waiting for a feature called "extranges" to be merged upstream, once that'll be done we'll be able to start implementing that

**Comment by lewis6991** [comment] 2021-01-14 17:49
Don't we also need core to expose the spelling functions implemented in C?

**Comment by vigoux** [comment] 2021-01-14 18:18
Not really sure for now, but maybe we will be able to tie things like spell, or folds to those extranges

**Comment by lewis6991** [comment] 2021-02-24 21:36
My new fancy related plugin: https://github.com/lewis6991/spellsitter.nvim

Depends on hunspell to do the spellchecking but maybe that has benefits over using vim's legacy spellchecker.

**Comment by thornomad** [comment] 2021-04-14 12:51
> Interestingly, if I `:syntax enable<CR>` in the file, the spell checker behaves correctly again (and the other highlighting look unaffected, as desired). Unfortunately, upon re-linting (I assume by tree-sitter, e.g. after `:e<CR>`), the issue appears again.

I also have this issue where on first load I have to run `:syntax enable<CR>` to fix it.  However, for me, this "fix" persists longer than a new refresh with `:e<CR>`.  There is something triggers it to revert on occasion but it is not that frequent for me and I can't figure out what exactly is causing it to have to be re-applied.

**Comment by vigoux** [comment] 2021-04-14 13:05
With the new `decorations` api being merge,d this should be a little easier to support, I'll try to see what we can do for this.

**Comment by lewis6991** [comment] 2021-04-14 13:06
What new decorations API?

**Comment by vigoux** [comment] 2021-04-14 13:32
https://github.com/neovim/neovim/pull/14358 and the previous ones, partly what is used to highlight a buffer using tree-sitter.

**Comment by lewis6991** [comment] 2021-04-14 13:37
So [spellsitter.nvim](https://github.com/lewis6991/spellsitter.nvim) already uses the `nvim_set_decoration_provider` and `extmarks`. The challenge of supporting spelling is the spellchecking itself. spellsitter uses hunspell as I can't find any way to use neovims built-in spellchecker. I even looked into using ffi but to no avail.

**Comment by vigoux** [comment] 2021-04-14 13:38
I see what you mean, but now we can integrate the bultin spellchecker to use these decorations, and use tree-sitter to set decorations (just like you did)

**Comment by zoopp** [comment] 2021-06-08 20:42
I don't fully understand how these things work so I might be totally wrong but, In the absence of something better, https://github.com/nvim-treesitter/nvim-treesitter/pull/1042 seems to help with the original issue.

Are there any downsides to having the `additional_vim_regex_highlighting` option always set to true?

**Comment by theHamsta** [comment] 2021-06-08 21:11
@zoopp you will automatically also get the old syntax highlighting running while usually most tree-sitter users want to use tree-sitter highlighting instead of regex highlighting.

**Comment by vigoux** [comment] 2021-06-09 06:25
I forgot to come back to you, but I am working on it (among other things).
I am a stranger to the part of the code handling this specific part, but I promise I'll try my best.

**Comment by weilbith** [comment] 2021-06-09 08:56
I'm not fully up to date with the earlier mentioned `spellsitter.nvim` plugin, but the last time I looked at it, it has become very small and if I'm not mistaken actually re-uses the original NeoVim `C` language tools to identify spelling mistakes. Sounds quite neat to me. 
What would be the alternative approach to tackle this problem? 🤔

**Comment by weilbith** [comment] 2021-06-09 09:25
So I assume it is somehow event triggered and then uses tree-sitter to identify the text which is "allowed" to be checked. It calls the NeoVim original spell checking for those chunks and applies custom highlighting (in fact re-using the native highlight groups) to the sections that have bad spelling.
Sounds pretty lean and straight forward to me. A good solution. So my question is if this issue here still makes sense. Or asked different, what could we do/add in this repository here to improve this solution?

**Comment by akinsho** [comment] 2021-06-09 09:32
@weilbith I think this issue might not be one for this repository but in which case is definitely one for neovim proper. Vim has always had spell functionality which has been super useful, with the move to treesitter that has essentially gone away meaning anyone using treesitter has lost native nvim support for spellchecking. I think an external plugin is great but ultimately part of adding treesitter should be hooking it up to stuff that worked for syntax e.g. conceal, spellchecking  etc (where it makes sense).

In which case given that this plugin has historically been the staging ground for things that might eventually go into neovim after being tested and iterated on by this plugin it's worth either having something here for that purpose or moving this issue to nvim core (IMO).

**Comment by weilbith** [comment] 2021-06-09 09:35
Very good point! 👍🏾

**Comment by lewis6991** [comment] 2021-06-09 14:32
> So I assume it is somehow event triggered and then uses tree-sitter to identify the text which is "allowed" to be checked. It calls the NeoVim original spell checking for those chunks and applies custom highlighting (in fact re-using the native highlight groups) to the sections that have bad spelling.

spellsitter.nvim uses the same mechansim that `vim.treesitter.highlighter` uses. When each line is being redrawn, it looks to see if the line contains any comments, if it does it calls neovims spellcheck code (via FFI) and adds ephemeral extmarks to the mispelled words.

> In which case given that this plugin has historically been the staging ground for things that might eventually go into neovim after being tested and iterated on by this plugin it's worth either having something here for that purpose or moving this issue to nvim core (IMO).

I think the implementation is probably good enough to be ported over here. Longer term this should be integrated into `vim.treesitter.highlighter` so we can do highlights and spellchecking with only one tree traversal.

The FFI code seems to be rock solid as I've had zero issues with it. It works so well that I often forget I have the plugin enabled and get confused on whether the buffer is using treesitter or not. With that said, longer term we need to add a spelling API into `vim.api`.

As mentioned, the plugin just spellchecks comments, but this should be changed to use query files instead like we do for folds and indents.

Lastly the built-in spellchecker really needs a lot of work, it's scrambled over many parts of the core and has many hardwired behaviours. For example you need to have `set spell` in order to use any of the spell mappings. spellsitter hacks this by running `set spell` and `set nospell` before and after a mapping is triggered. Somehow we need to have `set spell` whilst @Spell spellchecking is essentially disabled.

**Comment by lewis6991** [comment] 2022-06-07 11:05
Just to update on this, https://github.com/lewis6991/spellsitter.nvim is feature complete at this point:

* The main module is very small at around 350 LOC
* It uses the builtin spellchecker via `vim.spell`.
* It supports/includes queries that a spelling specific rather than just piggybacking off `@comment`.
* It works fully with `set spell`/`set nospell`.
* All spell related mappings work.
* Does not depend on nvim-treesitter

Closing this ticket as there isn't anything to do in nvim-treesitter or core. However, we may want to consider migrating spellsitter to somewhere more central though.

**Closed by lewis6991** 2022-06-07 11:05 UTC
Labels: enhancement
