### ISSUE TITLE
Treesitter folding makes RustFmt very slow

### ISSUE THREAD

**Issue by dimbleby** [nvim-treesitter/nvim-treesitter#1483] opened 2021-07-04 12:51 UTC
**Describe the bug**

Enabling treesitter folding makes rust formatting via [rust.vim](https://github.com/rust-lang/rust.vim/)'s `:RustFmt` very slow.

**To Reproduce**

Install nvim-treesitter and rust.vim.

Edit a moderately large rust file - in the attached demo I am using https://github.com/dtolnay/serde/blob/master/serde_derive/src/de.rs.

Enable treesitter folding: `:set foldmethod=expr foldexpr=nvim_treesitter#foldexpr()`

Format the code: `:RustFmt`

**Expected behavior**

Formatting is not very very slow.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.4 (6dd41e2e45f8b4a00fda21f28bc0ebc6b172ffed) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v15.14.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - svelte         ✓ . ✓ ✓ ✓ 
  - cuda           ✓ ✓ ✓ ✓ . 
  - dockerfile     ✓ . . . ✓ 
  - scala          . . . . . 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - latex          ✓ . ✓ . ✓ 
  - haskell        ✓ . . . ✓ 
  - hcl            ✓ . ✓ . ✓ 
  - bibtex         ✓ . ✓ ✓ . 
  - graphql        ✓ . . ✓ ✓ 
  - glimmer        ✓ . . . . 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - cmake          ✓ . ✓ . . 
  - bash           ✓ ✓ ✓ . ✓ 
  - vue            ✓ . ✓ . ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - r              ✓ ✓ . . . 
  - java           ✓ ✓ . ✓ ✓ 
  - fortran        ✓ . ✓ ✓ . 
  - nix            ✓ ✓ ✓ . ✓ 
  - kotlin         ✓ . . . ✓ 
  - zig            ✓ ✓ ✓ ✓ ✓ 
  - dart           ✓ ✓ . ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - clojure        ✓ ✓ ✓ . ✓ 
  - julia          ✓ ✓ ✓ . ✓ 
  - beancount      ✓ . ✓ . . 
  - fennel         ✓ ✓ . . ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - ql             ✓ ✓ . ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - c_sharp        ✓ . ✓ . ✓ 
  - verilog        ✓ ✓ ✓ . ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - erlang         . . . . . 
  - elixir         ✓ ✓ . ✓ ✓ 
  - ocamllex       ✓ . . . ✓ 
  - comment        ✓ . . . . 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - jsdoc          ✓ . . . . 
  - ocaml_interface✓ ✓ ✓ . ✓ 
  - gomod          ✓ . . . . 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - elm            . . . . . 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - gdscript       ✓ ✓ . . ✓ 
  - rst            ✓ ✓ . . ✓ 
  - swift          . . . . . 
  - teal           ✓ ✓ ✓ ✓ ✓ 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - commonlisp     ✓ ✓ ✓ . . 
  - devicetree     ✓ ✓ ✓ ✓ ✓ 
  - regex          ✓ . . . . 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - ledger         ✓ . ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.6.0-dev+8-g75f758b99
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/dch/neovim/build/config -I/home/dch/neovim/src -I/home/dch/neovim/.deps/usr/include -I/usr/include -I/home/dch/neovim/build/src/nvim/auto -I/home/dch/neovim/build/include
Compiled by dch@DESKTOP-NA4O3IV

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/dch/.local/nvim/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

This recording shows the formatting first without treesitter folding and then with it.  0:30 through 1:48 is not much fun to sit through.

(Even the 'without' formatting is disappointingly slow, but that seems to be interaction with LSP rather than with treesitter.)

Again, if you want to repro, the file that I am using here is https://github.com/dtolnay/serde/blob/master/serde_derive/src/de.rs.

[![asciicast](https://asciinema.org/a/GvcL84WXlwEe6DwHNWRkRKiej.svg)](https://asciinema.org/a/GvcL84WXlwEe6DwHNWRkRKiej)

**Comment by dimbleby** [comment] 2021-07-04 13:47
Replacing `:RustFmt` with direct use of `rustfmt` sidesteps this... at which point I rediscovered #1424

**Comment by stsewd** [comment] 2021-07-04 18:59
Hi, I think this is the same problem described in https://github.com/nvim-treesitter/nvim-treesitter/issues/1436#issuecomment-871610832, basically nvim calls the foldexpression on each line, and inside that function we call the lua code, the back and forth from lua to vimscript is slow, I'll see if I can do some improvements.

**Comment by dimbleby** [comment] 2021-07-04 19:15
You're probably right of course, but I'll note that opening the file that I was using is not slow.  So there's something specifically about the interaction with `:RustFmt`, I think.

**Comment by theHamsta** [comment] 2021-07-04 19:47
Maybe `:RustFmt` is doing this line by line, where the problem escalated to O^2 complicity. Did you try to format with rust-analyzer whether it can do it much faster?

For experiments please also uninstall the `comment` parser in case you have it installed.

**Comment by stsewd** [comment] 2021-07-04 20:05
I tried caching the results in vimscript, but didn't see any improvements, I think the problem is with `setline` https://github.com/rust-lang/rust.vim/blob/87c745d8d506fc1eecc1d81df15d5bde1658a2fc/autoload/rustfmt.vim#L160, it's called once, but looks like internally neovim does something that makes that call slow when setting multilines https://github.com/nvim-treesitter/nvim-treesitter/issues/1118

**Comment by stsewd** [comment] 2021-07-04 20:09
From the docs

```
		When {text} is a |List| then line {lnum} and following lines
		will be set to the items in the list.  Example: >
			:call setline(5, ['aaa', 'bbb', 'ccc'])
 		This is equivalent to: >
			:for [n, l] in [[5, 'aaa'], [6, 'bbb'], [7, 'ccc']]
			:  call setline(n, l)
			:endfor
```

so, yeah, that is triggering a lot of calls to the indent expression on every setline call.

**Comment by theHamsta** [comment] 2021-07-04 20:15
I guess @folke reported that even an empty Lua function as `foldexpr` was slow.

**Comment by folke** [comment] 2021-07-04 20:25
@theHamsta yep. Just open a large text file (or any file without treesitter). You'll see the same problem. Initially I thought it was the has_parser check, but if I return `0` in the treesitter Lua fold method, it's still very slow. 

The one thing I didn't check yet is wether something odd is going on with the requires at the top. Normally they get cached, but maybe for some reason they're not in this case.

**Comment by stsewd** [comment] 2021-07-04 20:39
I just tested changing `setline` with `nvim_buf_set_lines` and things are faster, so the problem is with `setline`, I'm closing this in favor of https://github.com/nvim-treesitter/nvim-treesitter/issues/1118. I'll send a patch to rust.vim, but after that change you'll now see https://github.com/nvim-treesitter/nvim-treesitter/issues/1424 after running Rustfmt :/

**Closed by stsewd** 2021-07-04 20:39 UTC
Labels: bug

**Comment by stsewd** [comment] 2021-07-04 20:45
I have opened https://github.com/rust-lang/rust.vim/pull/448
