### ISSUE TITLE
Bugs Happend When Encounter Math Equations in Markdown or Latex.

### ISSUE THREAD

**Issue by lazypool** [nvim-treesitter/nvim-treesitter#6693] opened 2024-05-27 20:12 UTC
### Bugs Description

It will report some issues when I encounter the equations (e.g \$ a \$, \$ a + b = c \$) in Markdown or Latex. Like this.

```
Error in decoration provider treesitter/hightlighter.win:
Error executing lua: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 74:3. Impossible pattern:
  name: (curly_group_text_list
  ^

Stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:240: in function 'get_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:188: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:495: in function 'for_each_tree'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:495: in function 'for_each_tree'
        /
``` 

### Example

![tmp](https://github.com/nvim-treesitter/nvim-treesitter/assets/112382793/11681224-625f-4dc4-a32c-a5d3a8ba920d)

And below is what the command  `:InspectTree` output:

```
(document ; [0, 0] - [1, 0]
  (section ; [0, 0] - [1, 0]
    (paragraph ; [0, 0] - [1, 0]
      (inline ; [0, 0] - [0, 3]
        (inline ; [0, 0] - [0, 3]
          (latex_block ; [0, 0] - [0, 3]
            (source_file ; [0, 0] - [0, 3]
              (inline_formula ; [0, 0] - [0, 3]
                (text ; [0, 1] - [0, 2]
                  word: (word)))) ; [0, 1] - [0, 2]
            (latex_span_delimiter) ; [0, 0] - [0, 1]
            (latex_span_delimiter))))))) ; [0, 2] - [0, 3]
```

### To Reproduce

This is my config file, I use the `lazynvim` to manage the plugins.

```lua
return {
	"nvim-treesitter/nvim-treesitter",
	dependencies = {
		"windwp/nvim-ts-autotag",
	},
	config = function()
		require("nvim-treesitter.configs").setup({
			ensure_installed = {
				"bash",  "c", "cpp", "css", "go", "html", "java",
				"latex", "lua", "markdown", "python",
				"vim", "typescript", "tsx", "xml", "javascript",
			},

			highlight = {
				enable = true,
			},

			rainbow = {
				enable = false,
			},

			indent = {
				enable = true,
			},

			autotag = {
				enable = false,
			},
		})
	end,
}
```

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v22.2.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 14.1.1 20240507
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.9.1-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Fri, 17 May 2024 16:56:38 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - xml                 ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info
```

**Comment by clason** [comment] 2024-05-27 21:02
Duplicate of #3092

**Closed by clason** 2024-05-27 21:02 UTC
Labels: bug
