### ISSUE TITLE
treesitter/highlighter: Error executing lua: ...: end_col value outside range

### ISSUE THREAD

**Issue by Yagua** [nvim-treesitter/nvim-treesitter#1201] opened 2021-04-18 19:12 UTC
**Describe the bug**

When editing files that have a parser installed (for example lua), with certain actions, suddenly the following message appears (I have noticed that this happens when making abrupt changes in the content of the file): treesitter/highlighter: " Error executing lua: ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:240: end_col value outside range "
leaving the file being worked on completely blank.

![error tree](https://user-images.githubusercontent.com/65829671/115156316-483dd280-a049-11eb-9e60-c204ceb4c4f3.png)

**To Reproduce**
As I mentioned before, this usually happens with certain actions within the file such as:
1. Replace sections (also happens with the whole line, but mainly in this form) of the file content, like this:

![image](https://user-images.githubusercontent.com/65829671/115156396-b1254a80-a049-11eb-89e3-299802707838.png)

2. Using regular expressions to modify this same content.

![image](https://user-images.githubusercontent.com/65829671/115156622-b3d46f80-a04a-11eb-8998-3e9e04686c1e.png)

**Expected behavior**

When performing actions like the ones mentioned above, an error occurs with the parser leaving the whole file completely blank and only showing the error "Error executing lua: ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:240: end_col value outside range" in each line.

**Output of `:checkhealth nvim_treesitter`**
<details>
<code>

```txt

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.4 (6dd41e2e45f8b4a00fda21f28bc0ebc6b172ffed) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v15.14.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.
 
## Parser/Features H L F I
  - go             ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ 
  - html           ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

```txt

NVIM v0.5.0-dev
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/dilanbar/Downloads/neovim-nightly/build/config -I/home/dilanbar/Downloads/neovim-nightly/src -I/home/dilanbar/Downloads/neovim-nightly/.deps/usr/include -I/usr/include -I/home/dilanbar/Downloads/neovim-nightly/build/src/nvim/auto -I/home/dilanbar/Downloads/neovim-nightly/build/include
Compiled by root@machine

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

```

</code>
</details>

**Additional context**
XXXXXXXXXXXXXXXXX

**Comment by chentau** [comment] 2021-04-19 19:18
Are you using latest master? Some of the issues you are facing should have been fixed.

**Comment by DilanGMB** [comment] 2021-04-19 20:03
Of course I do, I have the latest version, I just keep seeing these problems.
I did not understand concretely what you meant by "a minimal repro"

**Comment by steelsojka** [comment] 2021-04-20 18:36
@DilanGMB A way to reproduce the issue using minimal configuration. This rules out potential issues with your setup vs it being an actual bug. A lot of times this means a very minimal .vimrc

**Comment by erancx** [comment] 2021-04-22 10:25
I'm seeing the same error:

```
$ nvim --version
NVIM v0.5.0-dev+nightly-29-gdf4440024
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210304-74205-1jr9oar/build/config -I/tmp/neovim-20210304-74205-1jr9oar/src -I/usr/local/include -I/usr/local/opt/luv/include -I/usr/local/Cellar/tree-sitter/0.19.1/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210304-74205-1jr9oar/build/src/nvim/auto -I/tmp/neovim-20210304-74205-1jr9oar/build/include
Compiled by erandav@erandav-macbookpro2.roam.corp.google.com

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-df44400_1/share/nvim"

Run :checkhealth for more info
```

```
:checkhealth nvim_treesitter

  The following errors have been detected:
    - ERROR: yaml(highlights): ...f44400_1/share/nvim/runtime/lua/vim/treesitter/query.lua:104: query: invalid node type at position 291
    - ERROR: yaml(locals): ...f44400_1/share/nvim/runtime/lua/vim/treesitter/query.lua:104: query: invalid node type at position 20
```

**Comment by vigoux** [comment] 2021-04-22 10:59
If there's no repro step, we can't do anything, a but without reproduction step is as if this bug never existed.

This issue is long standing because the bug (result of a problem) can be caused by many different problems, so you think about posting in here please provide a _very clean and concise_ set of reproduction steps, otherwise we just can't do anything.

**Comment by vigoux** [comment] 2021-04-22 11:01
It looks like you are not on latest master, could you rebase and rebuild neovim to the master version?

**Comment by erancx** [comment] 2021-04-22 12:20
eh, yep, that did the trick.
I ran `PlugUpdate` thought it's also updating/rebasing to latest.

thanks!

**Comment by DilanGMB** [comment] 2021-04-22 18:16
I am using the latest version of both the editor and the plugins.

**Comment by vigoux** [comment] 2021-04-23 05:58
Could you post your nvim version here?

**Comment by DilanGMB** [comment] 2021-04-23 19:09
![image](https://user-images.githubusercontent.com/65829671/115918769-8a965380-a43d-11eb-9510-dfbbd21f831f.png)

**Comment by vigoux** [comment] 2021-04-24 05:18
I can't reproduce still, could you provide the exact sequence of keys you are pushing, and a minimal file to reproduce the issue?

**Comment by DilanGMB** [comment] 2021-04-24 18:55
specifically, this happens when I make regex changes to very large files.
also replacing large chunks of text with Ctrl + v (allows you to select a certain part of the current line (not all), as shown in the second image I put at the beginning of the conversion).

![image](https://user-images.githubusercontent.com/65829671/115969845-b92b3180-a504-11eb-9138-979f9f74d833.png)

however look, this is my configuration, although I already tried a minimal nvim configuration, with just treesitter and it still happens, which may rule out errors in my settings.
https://github.com/DilanGMB/nvim

**Comment by vigoux** [comment] 2021-04-24 19:05
>  the exact sequence of keys you are pushing

I still can't reproduce, could you really give that ?

**Comment by DilanGMB** [comment] 2021-04-24 19:46
https://user-images.githubusercontent.com/65829671/115971025-ce578e80-a50b-11eb-9822-3f83a367e242.mp4

**Comment by Mofiqul** [comment] 2021-04-27 17:40
I am also getting the same error when auto importing with nvim-compe. 

```
$ nvim --version
NVIM v0.5.0-dev+1263-ga129887c0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az36-146

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

```
health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.0.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - javascript     ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ 
  - php            ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

```

**Comment by whitebyte** [comment] 2021-04-28 12:16
Getting the same error. I can't consistently reproduce it, it happens rendomly and always goes away after a file reload (`:e %`). Usually it doesn't happen immediately after I open a file, it takes some time and actual editing for it to occur. Looks like some internal overflow

**Comment by steelsojka** [comment] 2021-04-28 12:22
Just for reference https://github.com/nvim-treesitter/nvim-treesitter/issues/651. This is an upstream issue and will not be fixed in this plugin. This happens when the highlighter places an extmark on the a column that is past the actual line length. This is caused by certain scenarios not trigger byte updates for the buffer. We've been catching these scenarios and this error frequency has gone down quite a bit. If we get clear steps to reproduce consistently, we can narrow down which scenarios this is still occuring.

**Comment by danielcondemarin** [comment] 2021-05-04 10:32
> eh, yep, that did the trick.
> I ran `PlugUpdate` thought it's also updating/rebasing to latest.
> 
> thanks!

Just to add to this, I also had to update the parsers (`:TSUpdate`). Might not be necessary if you have got,

`Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}` already.

**Comment by chentau** [comment] 2021-05-04 23:29
@DilanGMB  I've found the problem you're facing and have been working on a PR. Unfortunately, the bug is a bit complicated and in a very deep part of the nvim codebase, so it may take some time for me to find the right fix.

**Comment by DilanGMB** [comment] 2021-05-07 14:54
Ok, I have synchronized everything, and updated the parsers, but the problem persists replicating the same actions exposed at the beginning of the conversation.

**Comment by vigoux** [comment] 2021-05-07 15:28
So how do you reproduce the issue ?
Tell us a list of actions, to be sure we reproduce it exactly as you do it.

From here it seems you are doing : blockwise past, then `c` ?

**Comment by DilanGMB** [comment] 2021-05-07 16:22
Of course, as I mentioned before, this behavior usually occurs when sudden actions are performed inside a file that is being transformed by the parser.
Some of the actions that cause this error are:

* paste or replace content in block but by sections (as shown in the video above): this action is performed with CTRL + v (selecting the fragment to be replaced by the content inside the clipboard) (always causes the error).
* cut selected blocks of text in visual mode either with 'd' or 'c' (causes the error very commonly)
* replace file content with regular expressions, either single line or global (e.g. :%s/word/word/g) (commonly causes the error)
* formatting code with a formatter such as Prettier (causes the error in a rare way)
* delete lines using 'dd' (causes the error in a rare way)

I have to clarify something that I have noticed, and that is that this error, taking into account the actions mentioned above, occurs very frequently in files that have a lot of content (referring to about 200 lines or more).

**Comment by hungnguyentiki** [comment] 2021-05-15 01:02
Hello, how's it going. I have same the issue, sometimes I delete or edit a line code, the warning is shown, then I remove and undo this line has warning, the issue is disappear.

**Comment by vladh** [comment] 2021-05-26 17:01
I don't want to spam the issue with “me too”, but I wanted to add that I experienced this issue as soon as I installed `nvim-treesitter`, and that it prevented me from using it. I've uninstalled it for now, but I look forward to this bug being fixed so I can use it again. :)

**Comment by stsewd** [comment] 2021-06-26 18:48
Using plugins that format the buffer content may lead to this as well, linking to https://github.com/nvim-treesitter/nvim-treesitter/issues/1376

**Comment by saltsucker** [comment] 2021-12-12 00:50
I am currently getting this error whenever I load any python or cpp file and set highlight=true in my treesitter config. When I disable the hightlight, the error goes away. It doesn't occur for lua or bash. It doesn't seem this is actually resolved?

**Comment by stsewd** [comment] 2021-12-18 01:54
@saltsucker can you share the files you are editing? And maybe the steps to trigger the error? I use tree-sitter daily with python and haven't seen those errors.

**Comment by ajslater** [comment] 2022-02-04 22:34
This bug appeared for me today for all languages after updating tree-sitter
disabling highlight prevents it, but of course, removes that functionality.
macOS 12.2
homebrew nvim v0.6.1


```
nvim_treesitter: health#nvim_treesitter#check

========================================================================
## Installation
  - OK: tree-sitter` found 0.20.4 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.4.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.0.0 (clang-1300.0.29.30)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.
```

**Comment by theHamsta** [comment] 2022-02-04 23:01
I think this old issue is not related with current issues at all.

**Closed by theHamsta** 2022-02-04 23:01 UTC
Labels: bug, upstream Neovim

**Comment by PorcelainMouse** [comment] 2022-02-05 00:04
Hmm, is there another bug for the same symptoms, because I'm still getting something like this?

**Comment by Dotrar** [comment] 2022-02-09 04:01
Just adding to this; I had the same thing but forgot to do the `:TSUpdate` 

is it possible to make a more helpful error command? something like if there isn't a TS parser for the particular filetype, display an error?

**Comment by saltsucker** [comment] 2022-07-06 16:25
> @saltsucker can you share the files you are editing? And maybe the steps to trigger the error? I use tree-sitter daily with python and haven't seen those errors.

Sorry for late response. I missed this. Unfortunately, I no longer use Neovim, so I can't be much help any more. Cheers.

**Comment by Muntai** [comment] 2022-11-10 18:44
I had a similar problem with lua files.
Solution:
We go into nvim, then
:MasonUninstall lua-language-server
next go :Mason
find the lua server and press "i" to install.
My problem has disappeared.

**Comment by atzx** [comment] 2022-11-11 00:40
I got the same error and solved it running following command on nvim
`:TSUpdate`
copy and paste it and hit Enter key, this will update modules including treesitter/highlighter

If this works for you please react to this comment to acknowledge people this works in more users.

**Comment by Am3ra** [comment] 2022-11-16 18:44
<img width="1382" alt="Screen Shot 2022-11-16 at 12 42 55" src="https://user-images.githubusercontent.com/17537489/202266084-38e35296-2a4a-4467-b833-7d2640ab9b93.png">

I'm getting a similar error, but it's showing up in checkhealth, seems to be due to nvim?

**Comment by SpyrosMourelatos** [comment] 2022-12-05 11:38
`TSUpdate` gives me the root of the problem in my case.
It can't compile treesitter due to some c99 restrictions.
macOS with arm64 :
```sh
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin21.6.0
Thread model: posix
<img width="854" alt="Screenshot 2022-12-05 at 13 37 09" src="https://user-images.githubusercontent.com/26333139/205628212-d7dcf895-813e-48f0-85f1-fa2e39fdcfab.png">

InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by chaoslogick** [comment] 2022-12-28 18:42
Hello, I am having a similar issue with the highlighter in lua:

```
-- fast saving
local function fast_save()
  vim.api.nvim_command("w!")
end
vim.keymap.set("n", "<leader>w", fast_save)

```

which displays the error

`treesitter/highlighter: Error executing lua:...im/0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua`

There may be a better way to write this but both `vim.cmd` and `vim.api.nvim_command` seem to cause this parsing issue. Any insight appreciated

**Comment by chaoslogick** [comment] 2022-12-28 20:18
Hello, I am getting a parser error in my editor when using treesitter/highlighter, specifically around using vim.cmd and pretty much anything relating to executing a vim command. Here are some examples:

﻿`vim.cmd [[colorscheme dracula]]`

`vim.api.nvim_command('colorscheme dracula')`

Both of these produce a parsing error and break sections of highlighting when used. Are there any ideas as to why?

**Comment by taftadjani** [comment] 2023-01-14 16:20
I also got this error and solve it easily.
Here the situation:
I got the error in a lua file where I call vim.cmd [[ packadd packer.nvim ]]. 
In my treesitter config, I only installed the lua parser(I think it is called).  
So I added also the vim one and my issue disappear right after it was installed.

Happy coding.

**Comment by BillyFromTheFutur** [comment] 2023-01-22 18:57
> 

Thanks for the solving

**Comment by gbinux** [comment] 2023-02-03 00:38
> I also got this error and solve it easily. Here the situation: I got the error in a lua file where I call vim.cmd [[ packadd packer.nvim ]]. In my treesitter config, I only installed the lua parser(I think it is called). So I added also the vim one and my issue disappear right after it was installed.
> 
> Happy coding.

Thank you for sharing the vim treesitter issue.
This solves my issue, within `nvim`:
`:TSInstall vim`
Then quit nvm and use it to open any file.

**Comment by ryankhart** [comment] 2023-02-04 06:54
> :TSInstall vim

This one command solved this issue for me. If this issue keeps happening regularly, I might just make it run this command every time I save my plugins.lua file.
