### ISSUE TITLE
rust: invalid node type at positioin 3075 for language rust

### ISSUE THREAD

**Issue by cathaysia** [nvim-treesitter/nvim-treesitter#3800] opened 2022-11-12 07:59 UTC
### Describe the bug

![2022-11-12 15-53-45 的屏幕截图](https://user-images.githubusercontent.com/42114817/201464627-4be86ce9-a69a-498e-b62f-087283213a23.png)

but this rust source just a hello, world...

### To Reproduce

1. install nvim-treesitter and install rust parser
2. create a rust project then open src/main.rs

see error

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.17.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { "ccache gcc", "cc", "gcc", "clang", "cl", "zig" }
    Version: gcc (GCC) 11.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - tiger          ✓ ✓ ✓ ✓ ✓
  - php            ✓ ✓ ✓ ✓ ✓
  - vim            ✓ ✓ ✓ . ✓
  - fish           ✓ ✓ ✓ ✓ ✓
  - regex          ✓ . . . .
  - kotlin         ✓ ✓ ✓ . ✓
  - gowork         ✓ . . . ✓
  - m68k           ✓ ✓ ✓ . ✓
  - gomod          ✓ . . . ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - astro          ✓ ✓ ✓ ✓ ✓
  - elvish         ✓ . . . ✓
  - ledger         ✓ . ✓ ✓ ✓
  - typescript     ✓ ✓ ✓ ✓ ✓
  - julia          x ✓ x x ✓
  - fusion         ✓ ✓ ✓ ✓ .
  - diff           ✓ . . . .
  - lalrpop        ✓ ✓ . . .
  - hlsl           ✓ ✓ ✓ ✓ ✓
  - glsl           ✓ ✓ ✓ ✓ ✓
  - vala           ✓ . ✓ . .
  - proto          ✓ . ✓ . .
  - commonlisp     ✓ ✓ ✓ . .
  - norg           . . . . .
  - hack           ✓ . . . .
  - rst            ✓ ✓ . . ✓
  - foam           ✓ ✓ ✓ ✓ ✓
  - rasi           ✓ ✓ ✓ ✓ .
  - qmljs          ✓ . ✓ . .
  - make           ✓ . ✓ . ✓
  - fennel         ✓ ✓ . . ✓
  - meson          ✓ . ✓ . ✓
  - prisma         ✓ . . . .
  - agda           ✓ . ✓ . .
  - llvm           ✓ . . . .
  - hocon          ✓ . . . ✓
  - hjson          ✓ ✓ ✓ ✓ ✓
  - pioasm         ✓ . . . ✓
  - json5          ✓ . . . ✓
  - help           ✓ . . . .
  - bibtex         ✓ . ✓ ✓ .
  - latex          ✓ . ✓ . ✓
  - elm            ✓ . . . ✓
  - turtle         ✓ ✓ ✓ ✓ ✓
  - jsonc          ✓ ✓ ✓ ✓ ✓
  - r              ✓ ✓ . ✓ ✓
  - gdscript       ✓ ✓ . ✓ ✓
  - org            . . . . .
  - tsx            ✓ ✓ ✓ ✓ ✓
  - cuda           ✓ ✓ ✓ ✓ ✓
  - jsdoc          ✓ . . . .
  - svelte         ✓ . ✓ ✓ ✓
  - twig           ✓ . . . ✓
  - blueprint      ✓ . . . .
  - perl           ✓ . ✓ . .
  - scheme         x . ✓ . ✓
  - git_rebase     ✓ . . . ✓
  - ql             ✓ ✓ . ✓ ✓
  - gitattributes  ✓ . . . ✓
  - dart           ✓ ✓ . ✓ ✓
  - verilog        ✓ ✓ ✓ . ✓
  - css            ✓ . ✓ ✓ ✓
  - graphql        ✓ . . ✓ ✓
  - cpp            ✓ ✓ ✓ ✓ ✓
  - ruby           ✓ ✓ ✓ ✓ ✓
  - http           ✓ . . . ✓
  - yang           ✓ . ✓ ✓ .
  - comment        ✓ . . . .
  - sql            ✓ . . . ✓
  - solidity       ✓ . . . .
  - c              ✓ ✓ ✓ ✓ ✓
  - glimmer        ✓ . . . .
  - tlaplus        ✓ ✓ ✓ . ✓
  - beancount      ✓ . ✓ . .
  - vue            ✓ . ✓ ✓ ✓
  - scala          ✓ . ✓ . ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - dockerfile     ✓ . . . ✓
  - go             ✓ ✓ ✓ ✓ ✓
  - toml           ✓ ✓ ✓ ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - markdown_inline✓ . . . ✓
  - ocaml          ✓ ✓ ✓ . ✓
  - zig            ✓ . ✓ ✓ ✓
  - hcl            ✓ . ✓ ✓ ✓
  - haskell        ✓ . ✓ . ✓
  - v              ✓ ✓ ✓ ✓ ✓
  - supercollider  ✓ ✓ ✓ ✓ ✓
  - rnoweb         ✓ . ✓ . ✓
  - dot            ✓ . . . ✓
  - todotxt        ✓ . . . .
  - nickel         ✓ . . . .
  - erlang         ✓ . ✓ . .
  - c_sharp        ✓ ✓ ✓ . ✓
  - cooklang       ✓ . . . .
  - rego           ✓ . . . ✓
  - json           ✓ ✓ ✓ ✓ .
  - elixir         ✓ ✓ ✓ ✓ ✓
  - menhir         ✓ . . . ✓
  - rust           x x ✓ ✓ ✓
  - slint          ✓ . . ✓ .
  - markdown       ✓ . ✓ . ✓
  - query          ✓ ✓ ✓ ✓ ✓
  - bash           ✓ ✓ ✓ . ✓
  - clojure        ✓ ✓ ✓ . ✓
  - ocaml_interface✓ ✓ ✓ . ✓
  - pug            ✓ . . . ✓
  - heex           ✓ ✓ ✓ ✓ ✓
  - html           ✓ ✓ ✓ ✓ ✓
  - eex            ✓ . . . ✓
  - yaml           ✓ ✓ ✓ ✓ ✓
  - ninja          ✓ . ✓ ✓ .
  - java           ✓ ✓ . ✓ ✓
  - surface        ✓ . ✓ ✓ ✓
  - sparql         ✓ ✓ ✓ ✓ ✓
  - gleam          ✓ ✓ ✓ ✓ ✓
  - scss           ✓ . . ✓ .
  - nix            ✓ ✓ ✓ . ✓
  - pascal         ✓ ✓ ✓ ✓ ✓
  - cmake          ✓ . ✓ . .
  - racket         ✓ . ✓ . ✓
  - embedded_template✓ . . . ✓
  - fortran        ✓ . ✓ ✓ .
  - jsonnet        ✓ . . . .
  - sxhkdrc        ✓ . ✓ . ✓
  - wgsl           ✓ . ✓ ✓ .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: julia(highlights): ...ed-0.8.0/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2381 for language julia
    julia(highlights) is concatenated from the following files:
    | [ERROR]:"/home/tea/.config/nvim/pack/treesitter/opt/nvim-treesitter/queries/julia/highlights.scm", failed to load: ...ed-0.8.0/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2381 for language julia
  - ERROR: julia(folds): ...ed-0.8.0/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 221 for language julia
    julia(folds) is concatenated from the following files:
    | [ERROR]:"/home/tea/.config/nvim/pack/treesitter/opt/nvim-treesitter/queries/julia/folds.scm", failed to load: ...ed-0.8.0/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 221 for language julia
  - ERROR: julia(indents): ...ed-0.8.0/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 199 for language julia
    julia(indents) is concatenated from the following files:
    | [ERROR]:"/home/tea/.config/nvim/pack/treesitter/opt/nvim-treesitter/queries/julia/indents.scm", failed to load: ...ed-0.8.0/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 199 for language julia
  - ERROR: scheme(highlights): ...ed-0.8.0/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid structure at position 1633 for language scheme
    scheme(highlights) is concatenated from the following files:
    | [ERROR]:"/home/tea/.config/nvim/pack/treesitter/opt/nvim-treesitter/queries/scheme/highlights.scm", failed to load: ...ed-0.8.0/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid structure at position 1633 for language scheme
  - ERROR: rust(highlights): ...ed-0.8.0/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 3075 for language rust
    rust(highlights) is concatenated from the following files:
    | [ERROR]:"/home/tea/.config/nvim/pack/treesitter/opt/nvim-treesitter/queries/rust/highlights.scm", failed to load: ...ed-0.8.0/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 3075 for language rust
  - ERROR: rust(locals): ...ed-0.8.0/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 761 for language rust
    rust(locals) is concatenated from the following files:
    | [ERROR]:"/home/tea/.config/nvim/pack/treesitter/opt/nvim-treesitter/queries/rust/locals.scm", failed to load: ...ed-0.8.0/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 761 for language rust
```

### Output of `nvim --version`

```text
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/gy83kq8263p3ym4s62l5fx9jf1ic06zs-neovim-unwrapped-0.8.0/share/nvim
"

Run :checkhealth for more info
```

### Additional context

On my computer, this issue only happens when commits >= dd89cafd

**Comment by clason** [comment] 2022-11-12 08:58
Duplicate of #3902

**Closed by clason** 2022-11-12 08:58 UTC
Labels: bug

**Comment by cathaysia** [comment] 2022-11-12 13:27
could give me a link? it seems there has no #3902

**Comment by clason** [comment] 2022-11-12 13:38
Sorry, #3092
