### ISSUE TITLE
Treesitter is broken for typescript

### ISSUE THREAD

**Issue by jigfox** [nvim-treesitter/nvim-treesitter#3513] opened 2022-09-16 15:20 UTC
### Describe the bug

treesitter is failing for typescript files

### To Reproduce

install treesitter with following config

```lua
require("nvim-treesitter.configs").setup({
	ensure_installed = "all",
	sync_install = false,
	highlight = {
		enable = true,
		-- disable = { "typescript" },
	},
})
```

open any typescript file and see the following output:

```
Error detected while processing FileType Autocommands for "*":                                                                              
Error executing lua callback: .../0.7.2_1/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 3462    
stack traceback:                                                                                                                            
        [C]: in function '_ts_parse_query'                                                                                                  
        .../0.7.2_1/share/nvim/runtime/lua/vim/treesitter/query.lua:172: in function 'get_query'                                            
        ...1/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:37: in function 'new'                                                   
        ...neovim/0.7.2_1/share/nvim/runtime/lua/vim/treesitter.lua:46: in function '_create_parser'                                        
        ...neovim/0.7.2_1/share/nvim/runtime/lua/vim/treesitter.lua:94: in function 'get_parser'                                            
        .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:161: in function 'start'                                                
        .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:167: in function 'attach'                                               
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:477: in function 'attach_module'                                        
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:500: in function 'reattach_module'                                      
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:108: in function <...er/start/nvim-treesitter/lua/nvim-treesitter/config
s.lua:107>
```

Also running `:TSUpdate typescript` says `Parsers are up-to-date!`

But running `:TSUninstall typescript` throws error:
```
E5108: Error executing lua vim/shared.lua:0: t: expected table, got string                                                                  
stack traceback:                                                                                                                            
        [C]: in function 'error'                                                                                                            
        vim/shared.lua: in function 'validate'                                                                                              
        vim/shared.lua: in function 'tbl_contains'                                                                                          
        ...er/start/nvim-treesitter/lua/nvim-treesitter/install.lua:492: in function 'run'                                                  
        [string ":lua"]:1: in main chunk 
```

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.17.6 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 14.0.0 (clang-1400.0.29.102)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - sql            ✓ . . . ✓
  - cpp            ✓ ✓ ✓ ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - godot_resource ✓ ✓ ✓ . .
  - html           ✓ ✓ ✓ ✓ ✓
  - tsx            ✓ ✓ ✓ ✓ ✓
  - turtle         ✓ ✓ ✓ ✓ ✓
  - hcl            ✓ . ✓ ✓ ✓
  - devicetree     ✓ ✓ ✓ ✓ ✓
  - glimmer        ✓ . . . .
  - ocamllex       ✓ . . . ✓
  - verilog        ✓ ✓ ✓ . ✓
  - json           ✓ ✓ ✓ ✓ .
  - vim            ✓ ✓ ✓ . ✓
  - org            . . . . .
  - beancount      ✓ . ✓ . .
  - swift          ✓ ✓ . . .
  - markdown       ✓ . ✓ . ✓
  - rnoweb         ✓ . ✓ . ✓
  - go             ✓ ✓ ✓ ✓ ✓
  - c_sharp        ✓ ✓ ✓ . ✓
  - todotxt        ✓ . . . .
  - typescript     ✓ ✓ ✓ ✓ x
  - agda           ✓ . ✓ . .
  - supercollider  ✓ ✓ ✓ ✓ ✓
  - cmake          ✓ . ✓ . .
  - slint          ✓ . . ✓ .
  - haskell        ✓ . ✓ . ✓
  - qmljs          ✓ . ✓ . .
  - pioasm         ✓ . . . ✓
  - racket         ✓ . ✓ . ✓
  - hjson          ✓ ✓ ✓ ✓ ✓
  - scheme         ✓ . ✓ . ✓
  - markdown_inline✓ . . . ✓
  - rego           ✓ . . . ✓
  - prisma         ✓ . . . .
  - clojure        ✓ ✓ ✓ . ✓
  - rasi           ✓ ✓ ✓ ✓ .
  - commonlisp     ✓ ✓ ✓ . .
  - hack           ✓ . . . .
  - cuda           ✓ ✓ ✓ ✓ ✓
  - norg           . . . . .
  - jsonc          ✓ ✓ ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - elm            ✓ . . . ✓
  - glsl           ✓ ✓ ✓ ✓ ✓
  - yaml           ✓ ✓ ✓ ✓ ✓
  - hlsl           ✓ ✓ ✓ ✓ ✓
  - vala           ✓ . ✓ . .
  - dockerfile     ✓ . . . ✓
  - ninja          ✓ . ✓ ✓ .
  - lalrpop        ✓ ✓ . . .
  - nix            ✓ ✓ ✓ . ✓
  - solidity       ✓ . . . .
  - fusion         ✓ ✓ ✓ ✓ .
  - cooklang       ✓ . . . .
  - ledger         ✓ . ✓ ✓ ✓
  - elvish         ✓ . . . ✓
  - astro          ✓ ✓ ✓ ✓ ✓
  - wgsl           ✓ . ✓ . .
  - gomod          ✓ . . . ✓
  - m68k           ✓ ✓ ✓ . ✓
  - graphql        ✓ . . ✓ ✓
  - d              ✓ . ✓ ✓ ✓
  - ruby           ✓ ✓ ✓ ✓ ✓
  - r              ✓ ✓ . ✓ ✓
  - perl           ✓ . ✓ . .
  - tiger          ✓ ✓ ✓ ✓ ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - sxhkdrc        ✓ . ✓ . ✓
  - gitignore      ✓ . . . .
  - gitattributes  ✓ . . . ✓
  - java           ✓ ✓ . ✓ ✓
  - v              ✓ ✓ ✓ ✓ ✓
  - kotlin         ✓ ✓ ✓ . ✓
  - julia          ✓ ✓ ✓ ✓ ✓
  - jsonnet        ✓ . . . .
  - css            ✓ . ✓ ✓ ✓
  - scss           ✓ . . ✓ .
  - erlang         ✓ . ✓ . .
  - elixir         ✓ ✓ ✓ ✓ ✓
  - gleam          ✓ ✓ ✓ ✓ ✓
  - surface        ✓ . ✓ ✓ ✓
  - make           ✓ . ✓ . ✓
  - eex            ✓ . . . ✓
  - heex           ✓ ✓ ✓ ✓ ✓
  - proto          ✓ . ✓ . .
  - svelte         ✓ . ✓ ✓ ✓
  - blueprint      ✓ . . . .
  - ocaml          ✓ ✓ ✓ . ✓
  - json5          ✓ . . . ✓
  - php            ✓ ✓ ✓ ✓ ✓
  - fish           ✓ ✓ ✓ ✓ ✓
  - meson          ✓ . ✓ . ✓
  - menhir         ✓ . . . ✓
  - dot            ✓ . . . ✓
  - toml           ✓ ✓ ✓ ✓ ✓
  - query          ✓ ✓ ✓ ✓ ✓
  - gowork         ✓ . . . ✓
  - regex          ✓ . . . .
  - dart           ✓ ✓ . ✓ ✓
  - bash           ✓ ✓ ✓ . ✓
  - pug            ✓ . . . ✓
  - rst            ✓ ✓ . . ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - fennel         ✓ ✓ . . ✓
  - ocaml_interface✓ ✓ ✓ . ✓
  - teal           ✓ ✓ ✓ ✓ ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - bibtex         ✓ . ✓ ✓ .
  - ql             ✓ ✓ . ✓ ✓
  - gdscript       ✓ ✓ . ✓ ✓
  - yang           ✓ . ✓ ✓ .
  - vue            ✓ . ✓ ✓ ✓
  - pascal         ✓ ✓ ✓ ✓ ✓
  - latex          ✓ . ✓ . ✓
  - zig            ✓ . ✓ ✓ ✓
  - phpdoc         ✓ . . . .
  - http           ✓ . . . ✓
  - fortran        ✓ . ✓ ✓ .
  - embedded_template✓ . . . ✓
  - comment        ✓ . . . .
  - help           ✓ . . . .
  - jsdoc          ✓ . . . .
  - hocon          ✓ . . . ✓
  - tlaplus        ✓ ✓ ✓ . ✓
  - llvm           ✓ . . . .
  - sparql         ✓ ✓ ✓ ✓ ✓
  - foam           ✓ ✓ ✓ ✓ ✓
  - scala          ✓ . ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: typescript(injections): .../0.7.2_1/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 3462
    typescript(injections) is concatenated from the following files:
    |    [OK]:"/Users/jfahnenbruck/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/ecma/injections.scm"
    |    [OK]:"/Users/jfahnenbruck/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/ecma/injections.scm"
    | [ERROR]:"/Users/jfahnenbruck/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/jsx/injections.scm", failed to load: .../0.7.2_1/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 26
    |    [OK]:"/Users/jfahnenbruck/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/javascript/injections.scm"
    |    [OK]:"/Users/jfahnenbruck/.local/share/nvim/site/pack/packer/start/nvim-treesitter-angular/queries/javascript/injections.scm"
    |    [OK]:"/Users/jfahnenbruck/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/typescript/injections.scm"
    |    [OK]:"/Users/jfahnenbruck/.local/share/nvim/site/pack/packer/start/nvim-treesitter-angular/queries/typescript/injections.scm"
```

### Output of `nvim --version`

```text
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.2_1/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment] 2022-09-16 15:51
Duplicate of #3092

**Closed by clason** 2022-09-16 15:51 UTC
Labels: bug
