### ISSUE TITLE
Impossible Pattern - Error

### ISSUE THREAD

**Issue by Dronakurl** [nvim-treesitter/nvim-treesitter#6548] opened 2024-05-01 17:41 UTC
### Describe the bug

When opening markdown files, I get an error message like this

```
   Error  07:34:02 PM msg_show.emsg Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...-linux64/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 74:3. Impossible pattern:
  name: (curly_group_text_list
  ^

stack traceback:
	[C]: in function '_ts_parse_query'
	...-linux64/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
	...vim-linux64/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
	...vim-linux64/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
	...64/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
	...64/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:240: in function 'get_query'
	...64/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:188: in function 'fn'
	...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:488: in function 'for_each_tree'
	...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:492: in function 'for_each_tree'
	...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lu
   Error  07:34:01 PM msg_show.emsg Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...-linux64/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 74:3. Impossible pattern:
  name: (curly_group_text_list
  ^
```

### To Reproduce

I need some help to isolate this.
It does not appear every time I open a markdown file

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v21.7.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.8.5-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Thu, 11 Apr 2024 01:47:33 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - diff                ✓ . . . .
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - luap                ✓ . . . .
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - mermaid             ✓ . . . .
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - rst                 ✓ ✓ . . ✓
  - sql                 ✓ . . ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - vue                 ✓ . ✓ ✓ ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-3050+gcb24a3907
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

**Comment by clason** [comment] 2024-05-01 17:42
Duplicate of #3092

**Closed by clason** 2024-05-01 17:42 UTC
Labels: bug

**Comment by Dronakurl** [comment] 2024-05-01 19:03
Thank you and sorry for creating a duplicate. I followed the instructions and the error didn't show so far.

**Comment by clason** [comment] 2024-05-01 19:11
No worries; the error message is not the same after all (even though it's the same underlying issue).
