### ISSUE TITLE
Invalid node type "macro_type_specifier"

### ISSUE THREAD

**Issue by Adstart5672** [nvim-treesitter/nvim-treesitter#6913] opened 2024-07-13 01:16 UTC
### Describe the bug

When installing tree-sitter cpp, it throws an error here.
`Failed to execute the following command:
{
  cmd = <function 1>
}
'...iles/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 89:3. Invalid node type "macro_type_s
pecifier":\n((macro_type_specifier\n  ^\n'`
I've been following troubleshooting, and it still does not work.

### To Reproduce

1. Install treesitter cpp
2. See error
3. Reopen neovim
4. Open any cpp files
5. See error

### Expected behavior

Open c++ files without any errors

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.6 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v22.3.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: clang version 18.1.7
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "aarch64",
  release = "4.19.191-28714460-abA146PXXU7DXD3",
  sysname = "Linux",
  version = "#1 SMP PREEMPT Mon Apr 22 15:48:44 KST 2024"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/data/data/com.termux/files/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

`Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: ...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:35: Error executing lua: ...
ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:36: BufReadPost Autocommands for "*"..FileType Autocommands f
or "*": Vim(append):Error executing lua callback: ...iles/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Que
ry error at 89:3. Invalid node type "macro_type_specifier":
((macro_type_specifier
  ^

stack traceback:
        [C]: in function '_ts_parse_query'
        ...iles/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
        ...x/files/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
        ...x/files/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get_query'
        .../nvim/lazy/nvim-treesitter/lua/nvim-treesitter/query.lua:108: in function 'get_query'
        ...e/.local/share/nvim/lazy/tree-setter/lua/tree-setter.lua:16: in function 'is_supported'
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:387: in function 'is_enabled'
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:507: in function 'attach_module'
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...vim/lazy/nvim-treesitter/lua/
nvim-treesitter/configs.lua:132>
        [C]: in function 'nvim_cmd'
        ...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:36: in function <...ata/com.termux/files/usr/share
/nvim/runtime/filetype.lua:35>
        [C]: in function 'nvim_buf_call'
        ...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:35: in function <...ata/com.termux/files/usr/share
/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_cmd'
        ...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:36: in function <...ata/com.termux/files/usr/share
/nvim/runtime/filetype.lua:35>
        [C]: in function 'nvim_buf_call'
        ...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:35: in function <...ata/com.termux/files/usr/share
/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        ...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:35: in function <...ata/com.termux/files/usr/share
/nvim/runtime/filetype.lua:10>`

**Comment by clason** [comment] 2024-07-13 08:56
Duplicate of #3092

**Closed by clason** 2024-07-13 08:56 UTC
Labels: bug
