### ISSUE TITLE
Highlighting doesn't go away

### ISSUE THREAD

**Issue by ddorstijn** [nvim-treesitter/nvim-treesitter#355] opened 2020-08-27 14:58 UTC
**Describe the bug**
Sometimes when write C code (haven't tested it with anything else) the highlighting stays. For example, in the image below: While typing the printf statement the brackets didn't match so the code got highlighted. That's all good. But when I close the bracket the highlighting stays until I restart. 

![image](https://user-images.githubusercontent.com/1730282/91458151-7b96db80-e885-11ea-82ea-efd9a5c09dbc.png)

**To Reproduce**
1. Create a C file
2. Write a basic main function
3. Write printf("
4. Write the closing bracket and semicolon
5. Highlighting stays

**Expected behavior**
The highlight should go away as soon as the error is resolved.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## c parser healthcheck
  - OK: c parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.

## Missing parsers
  - WARNING: Some parsers are not installed:
    elm
    java
    python
    dart
    lua
    ocaml
    go
    nix
    yaml
    json
    jsdoc
    markdown
    julia
    html
    typescript
    fennel
    swift
    query
    cpp
    ruby
    vue
    scala
    tsx
    rust
    bash
    c_sharp
    rst
    css
    php
    javascript
    haskell
    toml
    regex
    - ADVICE:
      - Install them using `:TSInstall language

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-638-g91109ffda
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/ddorstijn/.cache/yay/neovim-git/src/build/config -I/home/ddorstijn/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/ddorstijn/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/ddorstijn/.cache/yay/neovim-git/src/build/include
Compiled by ddorstijn@hp-arch

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Additional context**
Using it together with completion-nvim and completion-treesitter.

**Comment by steelsojka** [comment] 2020-08-27 15:17
I think this is duplicate of https://github.com/nvim-treesitter/nvim-treesitter/issues/235

**Comment by kyazdani42** [comment] 2020-09-08 21:07
closing this in favor of #235

**Closed by kyazdani42** 2020-09-08 21:07 UTC
Labels: bug, duplicate
