### ISSUE TITLE
Error triggers everytime I try to edit text in some files

### ISSUE THREAD

**Issue by Rimann91** [nvim-treesitter/nvim-treesitter#4547] opened 2023-03-22 20:32 UTC
### Describe the bug

When I try to edit a vim or lua file with treesitter enabled I recieve this error on every trigger of `TextChangedI`, the error places my cursor in the command prompt and makes editing in these files nearly impossible.

![image](https://user-images.githubusercontent.com/15174454/227029184-e8ab9803-1674-4292-afbf-b233f0c8543c.png)

`:checkhealth nvim-treesitter` (at bottom)
![image](https://user-images.githubusercontent.com/15174454/227028449-829378e2-394c-439a-a561-31d2d33ffb99.png)

## Things I have already Tried:
**In Neovim 0.8.3**
1.  Updating all plugins
2.  TSUpdate
3.  TSUpdateSync
4. Updating Neovim to prerelease version 0.9
5. repeating steps 1-3

### To Reproduce

1. open neovim from command line or in GUI
2.  open init.vim (or a lua file)
3. attempt to edit file (i.e normal mode `o` to make new line) 

### Expected behavior

No error on editing file, correct highlighting

### Output of `:checkhealth nvim-treesitter`

```markdown
![image](https://user-images.githubusercontent.com/15174454/227028449-829378e2-394c-439a-a561-31d2d33ffb99.png)
```

### Output of `nvim --version`

```text
NVIM v0.9.0-dev-1260+ga7b537c7a
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

### Additional context

I am experiencing the problem on Windows 10 inside of the powershell terminal, in the neovim-qt GUI, and in Neovide. 

I had a similar problem on WSL2, however upgrading from nvim 0.7 to nvim 0.8.3 and running TSUpdate fixed it there.

I DID run TSInstall, and TSUpdate from the VS 2019 cmd to have access to the c compiler

The problem doesn't happen in other file modes (typescript)

**Comment by Rimann91** [comment] 2023-03-23 13:16
I just found that I am still experiencing errors on changes in my WSL config for Norg files
`Error detected while processing TextChangedI Autocommands for "*":                                                                                                                                                                                                                E20: Mark not set `

**Comment by Kordik67** [comment] 2023-04-01 10:58
Same here. Getting the error spammed infinitely when editing.
![Screenshot_2023-04-01_12_57_12](https://user-images.githubusercontent.com/44140877/229284802-83e0dddb-413b-47cc-953e-e0681f864faf.png)

**Comment by clason** [comment] 2023-04-01 11:00
Duplicate of #3092

**Closed by clason** 2023-04-01 11:00 UTC
Labels: bug

**Comment by clason** [comment] 2023-04-01 11:02
@Kordik67 if it's not the same error, it's not the same issue. Please open a new one with all(!) the necessary information instead of a drive-by comment on an unrelated issue.
