### ISSUE TITLE
Error detected while processing BufReadPost Autocommands for "*":

### ISSUE THREAD

**Issue by muyyii** [nvim-treesitter/nvim-treesitter#6289] opened 2024-03-13 15:18 UTC
### Describe the bug

Don't know what is happening. When opening a Lua file.

```
Error detected while processing BufReadPost Autocommands for "*":                                                                                                                          
Error executing lua callback: ...ocal/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:24: Error executing lua: ...ocal/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:25: BufReadP
ost Autocommands for "*"..FileType Autocommands for "*": Vim(append):Error executing lua callback: ...im/0.9.5/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structur
e at position 3158 for language lua                                                                                                                                                        
stack traceback:                                                                                                                                                                           
        [C]: in function '_ts_parse_query'                                                                                                                                                 
        ...im/0.9.5/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get'                                                                                                 
        ...5/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:114: in function 'new'                                                                                                 
        ...r/neovim/0.9.5/share/nvim/runtime/lua/vim/treesitter.lua:61: in function '_create_parser'                                                                                       
        ...r/neovim/0.9.5/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser'                                                                                          
        ...r/neovim/0.9.5/share/nvim/runtime/lua/vim/treesitter.lua:460: in function 'start'                                                                                               
        .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:20: in function 'attach'                                                                                               
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'                                                                                       
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'                                                                                     
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:132>                                     
        [C]: in function 'nvim_cmd'                                                                                                                                                        
        ...ocal/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:25: in function <...ocal/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:24>                                       
        [C]: in function 'nvim_buf_call'                                                                                                                                                   
        ...ocal/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:24: in function <...ocal/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:10>                                       
stack traceback:                                                                                                                                                                           
        [C]: in function 'nvim_cmd'                                                                                                                                                        
        ...ocal/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:25: in function <...ocal/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:24>                                       
        [C]: in function 'nvim_buf_call'                                                                                                                                                   
        ...ocal/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:24: in function <...ocal/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:10>                                       
stack traceback:                                                                                                                                                                           
        [C]: in function 'nvim_buf_call'                                                                                                                                                   
        ...ocal/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:24: in function <...ocal/Cellar/neovim/0.9.5/share/nvim/runtime/filetype.lua:10> `
        
        and then
        
        `Failed to execute the following command:                                                                                                                                                   
{                                                                                                                                                                                          
  cmd = <function 1>                                                                                                                                                                       
}                                                                                                                                                                                          
"...im/0.9.5/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 3158 for language lua" 
```

### To Reproduce

Minimal init.lua config 

```
vim.g.mapleader = ' '
vim.g.maplocalleader = "\\"

local cmd = vim.cmd  -- to execute Vim commands e.g. cmd('pwd')
local fn = vim.fn    -- to call Vim functions e.g. fn.bufnr()
local g = vim.g      -- a table to access global variables
local opt = vim.opt  -- to set options

-- Lazy install {{{ 
local lazypath = fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end
opt.rtp:prepend(lazypath)
--- }}}

require("lazy").setup({
	'tanvirtin/monokai.nvim',
	{"nvim-treesitter/nvim-treesitter", build = ":TSUpdate"},
})

require'nvim-treesitter.configs'.setup {
  -- A list of parser names, or "all" (the five listed parsers should always be installed)
  ensure_installed = { "c", "lua", "vim", "vimdoc", "query" },

  -- Install parsers synchronously (only applied to `ensure_installed`)
  sync_install = false,
  
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
}


opt.termguicolors = true
require('monokai').setup {}

-- Change defaults
opt.relativenumber = true  
opt.number         = true  
```

and then 

### Output of `:checkhealth nvim-treesitter`

```markdown
init.lua  h//                                                                                                                                                                            X
 38                                                                                                                                                                                        
 37 ──────────────────────────────────────────────────────────────────────────────                                                                                                         
 36 nvim-treesitter: require("nvim-treesitter.health").check()                                                                                                                             
 35                                                                                                                                                                                        
 34 Installation                                                                                                                                                                           
 33 - OK tree-sitter found 0.22.1 (parser generator, only needed for :TSInstallFromGrammar)                                                                                                
 32 - OK node found v21.7.1 (only needed for :TSInstallFromGrammar)                                                                                                                        
 31 - OK git executable found.                                                                                                                                                             
 30 - OK cc executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }                                                                                                 
 29   Version: Apple clang version 14.0.0 (clang-1400.0.29.202)                                                                                                                            
 28 - OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.                                                         
 27                                                                                                                                                                                        
 26 OS Info:                                                                                                                                                                               
 25 {                                                                                                                                                                                      
 24   machine = "x86_64",                                                                                                                                                                  
 23   release = "21.6.0",                                                                                                                                                                  
 22   sysname = "Darwin",                                                                                                                                                                  
 21   version = "Darwin Kernel Version 21.6.0: Wed Oct  4 23:55:28 PDT 2023; root:xnu-8020.240.18.704.15~1/RELEASE_X86_64"                                                                 
 20 }                                                                                                                                                                                      
 19                                                                                                                                                                                        
 18 Parser/Features         H L F I J                                                                                                                                                      
 17   - c                   ✓ ✓ ✓ ✓ ✓                                                                                                                                                      
 16   - lua                 ✓ ✓ ✓ ✓ x                                                                                                                                                      
 15   - query               ✓ ✓ ✓ ✓ ✓                                                                                                                                                      
 14   - vim                 ✓ ✓ ✓ . ✓                                                                                                                                                      
 13   - vimdoc              x . . . ✓                                                                                                                                                      
 12                                                                                                                                                                                        
 11   Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections                                                                                                                      
 10          +) multiple parsers found, only one will be used                                                                                                                              
  9          x) errors found in the query, try to run :TSUpdate {lang}                                                                                                                     
  8                                                                                                                                                                                        
  7 The following errors have been detected:                                                                                                                                               
  6 - ERROR lua(injections): ...im/0.9.5/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 3158 for language lua                                   
  5   lua(injections) is concatenated from the following files:                                                                                                                            
  4   | [ERROR]:"/Users/luki/.config/local/share/nvim/lazy/nvim-treesitter/queries/lua/injections.scm", failed to load: ...im/0.9.5/share/nvim/runtime/lua/vim/treesitter/query.lua:259:         query: invalid structure at position 3158 for language lua                                                                                                                           
  3 - ERROR vimdoc(highlights): ...im/0.9.5/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 719 for language vimdoc                              
  2   vimdoc(highlights) is concatenated from the following files:                                                                                                                         
  1   | [ERROR]:"/Users/luki/.config/local/share/nvim/lazy/nvim-treesitter/queries/vimdoc/highlights.scm", failed to load: ...im/0.9.5/share/nvim/runtime/lua/vim/treesitter/query.lua:          259: query: invalid node type at position 719 for language vimdoc                                                                                                                    
39                                                                                                                                                                                         
~
```

### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.9.5/share/nvim"
```

**Comment by lucario387** [comment] 2024-03-13 15:33
soo... which queries are used here again? Because that looks like it's using neovim queries instead of nvim-treesitter

**Comment by clason** [comment] 2024-03-13 15:41
Duplicate of #

**Closed by clason** 2024-03-13 15:41 UTC
Labels: bug

**Comment by sameer-gits** [comment] 2024-03-25 07:01
hello, i am getting the same error after installing treesitter and when i open my init.lua file any update of this? @muyyii

**Comment by lucario387** [comment] 2024-03-25 07:07
This is a duplicate of #3092
