### ISSUE TITLE
Error when using lua parser on windows

### ISSUE THREAD

**Issue by Fluued** [nvim-treesitter/nvim-treesitter#3906] opened 2022-12-01 16:38 UTC
### Describe the bug

When opening a lua file I get this error:
![error](https://user-images.githubusercontent.com/110692163/205107212-d9559341-8c20-4a62-b0e7-427eca41299f.png)

### To Reproduce

Just plain nvim-treesitter instllation with the lua parser and highlighting enabled

### Output of `:checkhealth nvim-treesitter`

```markdown
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.12.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `clang` executable found. Selected from { "clang" }
    Version: clang version 15.0.5
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "10.0.19045",
  sysname = "Windows_NT",
  version = "Windows 10 Pro"
}

## Parser/Features H L F I J
  - html           ✓ ✓ ✓ ✓ ✓
  - css            ✓ . ✓ ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - svelte         ✓ . ✓ ✓ ✓
  - typescript     ✓ ✓ ✓ ✓ ✓
  - help           ✓ . . . ✓
  - go             ✓ ✓ ✓ ✓ ✓
  - gomod          ✓ . . . ✓
  - markdown       ✓ . ✓ . ✓
  - python         ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az30-11

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
```

### Additional context

Running :TSUpdate lua does not help

**Comment by clason** [comment] 2022-12-01 16:39
Duplicate of #3092

**Closed by clason** 2022-12-01 16:39 UTC
Labels: bug

**Comment by clason** [comment] 2022-12-01 16:41
Try installing the `vim` parser as well; that is needed for injections.
