### ISSUE TITLE
Command to toggle modules

### ISSUE THREAD

**Issue by echasnovski** [nvim-treesitter/nvim-treesitter#886] opened 2021-01-29 10:02 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes due to performance reasons (notably just after opening large file) I would like to turn off highlighting module. After some time is passed I found it's OK to turn highlighting on again. Having to execute two different commands or having two different keybindings seems somewhat inconvenient.

**Describe the solution you'd like**
Exported functionality to toggle (enable if disabled and disable if enabled) certain module per buffer. The most natural choice seems to be `TSBufToggle` command that works similarly to `TSBufEnable` and `TSBufDisable`. For the sake of completeness, `TSBufToggleAll` might also be a good idea.

**Describe alternatives you've considered**
Writing my own function, but couldn't find any convenient exported way for a Neovim to find out if module is enabled/disabled.

**Additional context**
I can give PR for this feature a go, but I might need some guidance regarding Lua programming best practices.

**Comment by vigoux** [comment] 2021-01-29 10:04
This is a duplicate of #259.
Closing in favor of the earlier one.

**Closed by vigoux** 2021-01-29 10:04 UTC
Labels: duplicate, enhancement

**Comment by echasnovski** [comment] 2021-01-29 10:06
Oh, sorry, didn't find with search.

**Comment by vigoux** [comment] 2021-01-29 10:07
No worry mate, just wanted to telle you that 😉
