### ISSUE TITLE
r highlighter keeps throwing error output

### ISSUE THREAD

**Issue by samtrek** [nvim-treesitter/nvim-treesitter#6821] opened 2024-06-27 18:14 UTC
### Describe the bug

no highlighting is carried out and error output is continuous, impeding the use of nvim with R 

### To Reproduce

1. update up to 5373c90
2. close and open nvim again
3. open any *.r files

### Expected behavior

normal highlighting of R codes and no error output

### Output of `:checkhealth nvim-treesitter`

```markdown
The following errors have been detected: ~
- ERROR r(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 146:2. Invalid node type "default_argument":
  (default_argument
   ^
  
  r(highlights) is concatenated from the following files:
  |    [OK]:"~/.local/share/nvim/lazy/nvim-treesitter/queries/r/highlights.scm"
  | [ERROR]:"/~/.local/share/nvim/lazy/hlargs.nvim/queries/r/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 3:2. Invalid node type "default_argument":
  (default_argument
   ^
```

### Output of `nvim --version`

```text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478
```

### Additional context

Error in decoration provider treesitter/highlighter.win:
Error executing lua: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 146:2. Invalid node type "default_argument":
(default_argument
 ^

stack traceback:
	[C]: in function '_ts_parse_query'
	/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
	/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
	/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
	/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
	/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:240: in function 'get_query'
	/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:188: in function 'fn'
	/usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
	/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:175: in function 'prepare_highlight_states'
	/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:398: in function </us

error output when a new file is openned

**Comment by clason** [comment] 2024-06-27 18:15
Duplicate of the pinned issue.

**Closed** 2024-06-27 18:15 UTC
Labels: bug
