### ISSUE TITLE
Getting Error In Julia/LaTeX/vimscript files (others too)

### ISSUE THREAD

**Issue by jam1015** [nvim-treesitter/nvim-treesitter#2892] opened 2022-05-02 20:24 UTC
### Describe the bug

Errors in nvim checkhealth for several languages including `latex` `julia` `gleam` `nix` and `vim` and `java`.  Errors when loading those types of files.  Red error messages on screen, inconsistent/no highlighting.

### To Reproduce

Open any of those kinds of files.  Sometimes the error is triggered on a blank file, sometimes you have to write out valid code for it to be triggered (java is an example where the error is only triggered with valid code).

### Expected behavior

Treesitter should work normally.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.15.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - perl           ✓ . ✓ . . 
  - glimmer        ✓ . . . . 
  - d              ✓ . ✓ ✓ ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - latex          x . x . ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - java           x ✓ . ✓ ✓ 
  - markdown       ✓ . ✓ . ✓ 
  - kotlin         ✓ ✓ ✓ . ✓ 
  - julia          x ✓ ✓ x x 
  - scheme         ✓ . ✓ . ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - erlang         . . . . . 
  - rego           ✓ . . . ✓ 
  - elixir         ✓ ✓ ✓ ✓ ✓ 
  - hocon          ✓ . . . ✓ 
  - clojure        ✓ ✓ ✓ . ✓ 
  - gleam          x ✓ x x ✓ 
  - m68k           ✓ ✓ ✓ . ✓ 
  - surface        ✓ . ✓ ✓ ✓ 
  - wgsl           ✓ . ✓ . . 
  - yang           ✓ . ✓ ✓ . 
  - eex            ✓ . . . ✓ 
  - astro          ✓ ✓ ✓ ✓ ✓ 
  - ninja          ✓ . ✓ ✓ . 
  - solidity       ✓ . . . . 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - nix            x x x . ✓ 
  - lalrpop        ✓ ✓ . . . 
  - cooklang       ✓ . . . . 
  - dart           ✓ ✓ . ✓ ✓ 
  - ocaml_interface✓ ✓ ✓ . ✓ 
  - elvish         ✓ . . . ✓ 
  - rst            ✓ ✓ . . ✓ 
  - ocamllex       ✓ . . . ✓ 
  - fennel         ✓ ✓ . . ✓ 
  - org            . . . . . 
  - vala           ✓ . . . . 
  - swift          ✓ ✓ . . . 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - norg           . . . . . 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - hack           ✓ . . . . 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - todotxt        ✓ . . . . 
  - foam           ✓ ✓ ✓ ✓ ✓ 
  - phpdoc         ✓ . . . . 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - rasi           ✓ ✓ ✓ ✓ . 
  - make           ✓ . . . ✓ 
  - prisma         ✓ . . . . 
  - jsdoc          ✓ . . . . 
  - scala          ✓ . ✓ . ✓ 
  - teal           ✓ ✓ ✓ ✓ ✓ 
  - llvm           ✓ . . . . 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - proto          ✓ . ✓ . . 
  - hjson          ✓ ✓ ✓ ✓ ✓ 
  - slint          ✓ . . ✓ . 
  - pioasm         ✓ . . . ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - godot_resource ✓ ✓ ✓ . . 
  - http           ✓ . . . ✓ 
  - vim            x ✓ . . ✓ 
  - cmake          ✓ . ✓ . . 
  - tlaplus        ✓ ✓ ✓ . ✓ 
  - commonlisp     ✓ ✓ ✓ . . 
  - fortran        ✓ . ✓ ✓ . 
  - devicetree     ✓ ✓ ✓ ✓ ✓ 
  - zig            ✓ . ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . . 
  - cuda           ✓ ✓ ✓ ✓ ✓ 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - haskell        ✓ . . . ✓ 
  - svelte         ✓ . ✓ ✓ ✓ 
  - beancount      ✓ . ✓ . . 
  - pug            ✓ . . . ✓ 
  - glsl           ✓ ✓ ✓ ✓ ✓ 
  - gdscript       ✓ ✓ . ✓ ✓ 
  - vue            ✓ . ✓ ✓ ✓ 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - bibtex         ✓ . ✓ ✓ . 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - regex          ✓ . . . . 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - elm            ✓ . . . ✓ 
  - fusion         ✓ ✓ ✓ ✓ . 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - pascal         ✓ ✓ ✓ ✓ ✓ 
  - ledger         ✓ . ✓ ✓ ✓ 
  - verilog        ✓ ✓ ✓ . ✓ 
  - ql             ✓ ✓ . ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - help           ✓ . . . . 
  - hcl            ✓ . ✓ ✓ ✓ 
  - json5          ✓ . . . ✓ 
  - dockerfile     ✓ . . . ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - gomod          ✓ . . . ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - gowork         ✓ . . . ✓ 
  - dot            ✓ . . . ✓ 
  - heex           ✓ ✓ ✓ ✓ ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - r              ✓ ✓ . ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: latex(highlights): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 1199
    latex(highlights) is concatenated from the following files:
    | [ERROR]:"/home/jordan/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/latex/highlights.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 1199
  - ERROR: latex(folds): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 127
    latex(folds) is concatenated from the following files:
    | [ERROR]:"/home/jordan/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/latex/folds.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 127
  - ERROR: java(highlights): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 2028
    java(highlights) is concatenated from the following files:
    | [ERROR]:"/home/jordan/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/java/highlights.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 2028
  - ERROR: julia(highlights): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 3764
    julia(highlights) is concatenated from the following files:
    | [ERROR]:"/home/jordan/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/julia/highlights.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 3764
  - ERROR: julia(indents): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 485
    julia(indents) is concatenated from the following files:
    | [ERROR]:"/home/jordan/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/julia/indents.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 485
  - ERROR: julia(injections): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 109
    julia(injections) is concatenated from the following files:
    | [ERROR]:"/home/jordan/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/julia/injections.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 109
  - ERROR: gleam(highlights): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 54
    gleam(highlights) is concatenated from the following files:
    | [ERROR]:"/home/jordan/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/gleam/highlights.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 54
  - ERROR: gleam(folds): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 57
    gleam(folds) is concatenated from the following files:
    | [ERROR]:"/home/jordan/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/gleam/folds.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 57
  - ERROR: gleam(indents): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 185
    gleam(indents) is concatenated from the following files:
    | [ERROR]:"/home/jordan/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/gleam/indents.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 185
  - ERROR: nix(highlights): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 268
    nix(highlights) is concatenated from the following files:
    | [ERROR]:"/home/jordan/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/nix/highlights.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 268
  - ERROR: nix(locals): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 16
    nix(locals) is concatenated from the following files:
    | [ERROR]:"/home/jordan/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/nix/locals.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 16
  - ERROR: nix(folds): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 86
    nix(folds) is concatenated from the following files:
    | [ERROR]:"/home/jordan/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/nix/folds.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 86
  - ERROR: vim(highlights): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 765
    vim(highlights) is concatenated from the following files:
    | [ERROR]:"/home/jordan/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/vim/highlights.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 765

```
```


### Output of `nvim --version`

```text
NVIM v0.8.0-dev+108-gaf53fa066
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/jordan/github_packages/neovim/build/config -I/home/jordan/github_packages/neovim/src -I/home/jordan/github_packages/neovim/.deps/usr/include -I/usr/include -I/home/jordan/github_packages/neovim/build/src/nvim/auto -I/home/jordan/github_packages/neovim/build/include
Compiled by jordan@jordan-2429bt7

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
```


### Additional context
Let me know if it is more appropriate to submit these issues to the individual parser repos instead of or in addition to this issue.

**Comment by kyazdani42** [comment] 2022-05-07 08:55
Hi ! Did you try reinstalling the parsers ?

**Comment by theHamsta** [comment] 2022-05-07 10:26
Can you try to run `echo nvim_get_runtime_file('parser/julia.so', v:true)` to check whether you have any left-over parsers from a former installation that don't get updated by `:TSUpdate`

**Comment by MTCoster** [comment] 2022-05-07 10:34
I was having the same problem; it was caused by the fact `:TSUpdate` is executed asynchronously - I was using `nvim +TSUpdate +qall` in an automated update script which caused the update to be cancelled almost immediately, and apparently corrupting a bunch of stuff in the process

**Comment by myNameIsPK** [comment] 2022-05-07 21:47
> I was having the same problem; it was caused by the fact `:TSUpdate` is executed asynchronously - I was using `nvim +TSUpdate +qall` in an automated update script which caused the update to be cancelled almost immediately, and apparently corrupting a bunch of stuff in the process.
> 
> I reinstalled the plugin from scratch and switched to `:TSUpdateSync`; now all seems to be well.

@MTCoster I has the same problem, but when I was doing as you said It's not work, because there are some parsers(.so) file somewhere in my `runtimepath`, you must also make sure that you delete all that parsers then it will work.

**Comment by jam1015** [comment] 2022-05-20 19:28
Changed my linux distro and not having the problem anymore. Leaving it open because others reported having the same problem.

**Comment by theHamsta** [comment] 2022-05-20 20:38
I'm for closing since we can no longer find the reason for this. Until now the reason was always hidden parsers in runtime path. We should warn when there are parsers present that are not version controlled by nvim-treesitter.

**Closed by theHamsta** 2022-05-20 20:38 UTC
Labels: bug
