### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by timsofteng** [nvim-treesitter/nvim-treesitter#1115] opened 2021-03-30 14:45 UTC
I got this error by accident. Unfortunately I can't provide steps to reproduce.

![image](https://user-images.githubusercontent.com/51912173/113008382-a6c90c80-917f-11eb-9c5c-3ee65ddc748d.png)

**Comment by clason** [comment] 2021-03-30 15:10
Probably https://github.com/neovim/neovim/issues/12861 (and duplicate of https://github.com/nvim-treesitter/nvim-treesitter/issues/651)

**Comment by stsewd** [comment] 2021-06-26 19:01
yes, this is a duplicate of https://github.com/nvim-treesitter/nvim-treesitter/issues/651, if you have a reproducible example please post it there!

**Closed by stsewd** 2021-06-26 19:01 UTC
Labels: bug
