### ISSUE TITLE
[svelte] highlighting is lost after cursor moves over lines

### ISSUE THREAD

**Issue by jackfranklin** [nvim-treesitter/nvim-treesitter#1644] opened 2021-07-30 16:01 UTC
**Describe the bug**

When loading up a svelte file, the syntax highlighting with treesitter seems to be lost when moving the cursor over certain lines.

Additionally at times the syntax highlighting changes to have crossed out text.

Initially when the file is loaded it looks OK:

![highlighting-good](https://user-images.githubusercontent.com/193238/127679054-6c09f81a-b286-48ec-a5de-b6314a87fda9.png)

Then I use `j` / `k` to move my cursor over the lines and they go black:

![highlighting-bad](https://user-images.githubusercontent.com/193238/127679107-38fef765-5b6a-4e81-bd80-370482d40c41.png)

And sometimes (not been able to pin this down more yet unfortunately) the syntax highlighting crosses the lines out:

![weird-crossing-out](https://user-images.githubusercontent.com/193238/127679163-fca261c0-fd24-4cf7-90f1-a8ee5c9d48c3.png)

Apologies if this should be in the svelte-treesitter repo, I wasn't entirely sure.

**To Reproduce**

Store this file as say `test.svelte`:

```
<script>
  const entries = [];

  function nameMightBeMultipleNames(name) {}
</script>

{#each entries as entry, index}
  <div role="group" aria-labelledby="fake-legend">
    {#if entriesClosedMap.get(entry) !== true}
      <div class="guest-fields">
        <div class="form-group">
          <label for="name-{index}"
            >Name{#if nameMightBeMultipleNames(entry.name)}<span
                class="multiple-warning"
                >Please add one guest per box, and use the "Add Guest" button
                for any additional guests</span
              >{/if}</label
          >
          <input type="text" bind:value={entry.name} id="name-{index}" />
        </div>
        <div>
          <div class="radio">
            <div>
              <label for="can-attend-{index}">Able to attend</label>
              <input
                type="radio"
                bind:group={entry.canAttend}
                id="can-attend-{index}"
                name="can-attend-{index}"
                value="true"
              />
            </div>
          </div>
        </div>
      </div>
    {/if}
  </div>
{/each}
```

1. See that when the cursor moves over the "Please add one guest per box..." text, that it gets syntax highlighted differently with a line through it.
2.  Note then when your cursor moves through the "Able to attend" label and the input, that all syntax highlighting is lost.

**Expected behavior**

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.2.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - kotlin         ✓ . . . ✓·
  - html           ✓ ✓ ✓ ✓ ✓·
  - go             ✓ ✓ ✓ ✓ ✓·
  - julia          ✓ ✓ ✓ ✓ ✓·
  - json           ✓ ✓ ✓ ✓ .·
  - css            ✓ . ✓ ✓ ✓·
  - svelte         ✓ . ✓ ✓ ✓·
  - scss           ✓ . . ✓ .·
  - erlang         . . . . .·
  - beancount      ✓ . ✓ . .·
  - latex          ✓ . ✓ . ✓·
  - ocaml          ✓ ✓ ✓ . ✓·
  - r              ✓ ✓ . . .·
  - query          ✓ ✓ ✓ ✓ ✓·
  - c_sharp        ✓ . ✓ . ✓·
  - cmake          ✓ . ✓ . .·
  - c              ✓ ✓ ✓ ✓ ✓·
  - tsx            ✓ ✓ ✓ ✓ ✓·
  - supercollider  ✓ ✓ ✓ ✓ ✓·
  - hcl            ✓ . ✓ ✓ ✓·
  - toml           ✓ ✓ ✓ ✓ ✓·
  - glimmer        ✓ . . . .·
  - vue            ✓ . ✓ . ✓·
  - jsonc          ✓ ✓ ✓ ✓ ✓·
  - javascript     ✓ ✓ ✓ ✓ ✓·
  - yang           ✓ . ✓ . .·
  - nix            ✓ ✓ ✓ . ✓·
  - dart           ✓ ✓ . ✓ ✓·
  - clojure        ✓ ✓ ✓ . ✓·
  - commonlisp     ✓ ✓ ✓ . .·
  - cpp            ✓ ✓ ✓ ✓ ✓·
  - regex          ✓ . . . .·
  - dockerfile     ✓ . . . ✓·
  - rust           ✓ ✓ ✓ ✓ ✓·
  - ledger         ✓ . ✓ ✓ ✓·
  - zig            ✓ ✓ ✓ ✓ ✓·
  - python         ✓ ✓ ✓ ✓ ✓·
  - bibtex         ✓ . ✓ ✓ .·
  - fennel         ✓ ✓ . . ✓·
  - java           ✓ ✓ . ✓ ✓·
  - gomod          ✓ . . . .·
  - cuda           ✓ ✓ ✓ ✓ ✓·
  - ql             ✓ ✓ . ✓ ✓·
  - typescript     ✓ ✓ ✓ ✓ ✓·
  - php            ✓ ✓ ✓ ✓ ✓·
  - verilog        ✓ ✓ ✓ . ✓·
  - comment        ✓ . . . .·
  - ruby           ✓ ✓ ✓ ✓ ✓·
  - bash           ✓ ✓ ✓ . ✓·
  - yaml           ✓ ✓ ✓ ✓ ✓·
  - lua            ✓ ✓ ✓ ✓ ✓·
  - jsdoc          ✓ . . . .·
  - fish           ✓ ✓ ✓ ✓ ✓·

</code>
</details>

**Output of `nvim --version`**

<details>
<code>
NVIM v0.6.0-dev+94-g7b627ece8
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/jack/git/neovim/build/config -I/home/jack/git/neovim/src -I/home/jack/git/neovim/.deps/usr/include -I/usr/include -I/home/jack/git/neovim/build/src/nvim/auto -I/home/jack/git/neovim/build/include
Compiled by jack@DESKTOP-IR26TVF

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

I have ensured all the relevant plugins & parsers are up to date. The same issue replicates on stable 0.5.0.

**Comment by theHamsta** [comment] 2021-07-30 16:11
This bug has is possibility a duplicate of #1506 . This would be probably a fix: https://github.com/neovim/neovim/pull/15126

**Comment by stsewd** [comment] 2021-09-18 17:59
There are two issues here https://github.com/nvim-treesitter/nvim-treesitter/issues/1506 and https://github.com/nvim-treesitter/nvim-treesitter/issues/1788. Closing in favor of those.

**Closed by stsewd** 2021-09-18 17:59 UTC
Labels: bug
