### ISSUE TITLE
Yaml parser does not load

### ISSUE THREAD

**Issue by EvilGiraffes** [nvim-treesitter/nvim-treesitter#5765] opened 2023-12-05 16:13 UTC
### Describe the bug

The yaml parser has issues loading up, for all sections and thereby doesn't work at all

### To Reproduce

1. Run TSInstall yaml
2. Open any yaml file

### Expected behavior

Load parser and parse file

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v18.18.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: gcc.exe (x86_64-posix-seh-rev2, Built by MinGW-W64 project) 12.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.19045",
  sysname = "Windows_NT",
  version = "Windows 10 Home"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - c_sharp             ✓ ✓ ✓ . ✓
  - gdscript            ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - luap                ✓ . . . .
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                x x x x x

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR yaml(highlights): Failed to load parser for language 'yaml': uv_dlopen: error: 127
  yaml(highlights) is concatenated from the following files:
  | [ERROR]:"C:\Users\Thomas\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\yaml\highlights.scm", failed to load: Failed to load parser for language 'yaml': uv_dlopen: error: 127
- ERROR yaml(locals): Failed to load parser for language 'yaml': uv_dlopen: error: 127
  yaml(locals) is concatenated from the following files:
  | [ERROR]:"C:\Users\Thomas\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\yaml\locals.scm", failed to load: Failed to load parser for language 'yaml': uv_dlopen: error: 127
- ERROR yaml(folds): Failed to load parser for language 'yaml': uv_dlopen: error: 127
  yaml(folds) is concatenated from the following files:
  | [ERROR]:"C:\Users\Thomas\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\yaml\folds.scm", failed to load: Failed to load parser for language 'yaml': uv_dlopen: error: 127
- ERROR yaml(indents): Failed to load parser for language 'yaml': uv_dlopen: error: 127
  yaml(indents) is concatenated from the following files:
  | [ERROR]:"C:\Users\Thomas\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\yaml\indents.scm", failed to load: Failed to load parser for language 'yaml': uv_dlopen: error: 127
- ERROR yaml(injections): Failed to load parser for language 'yaml': uv_dlopen: error: 127
  yaml(injections) is concatenated from the following files:
  | [ERROR]:"C:\Users\Thomas\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\yaml\injections.scm", failed to load: Failed to load parser for language 'yaml': uv_dlopen: error: 127
```

### Output of `nvim --version`

```text
NVIM v0.9.2
Build type: RelWithDebInfo
LuaJIT 2.1.1694082368
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

        vimrc-fil p? systemet: "$VIM\sysinit.vim"
       $VIM faller tilbake p?: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

### Additional context

This is ran on a windows 10 machine

**Comment by clason** [comment] 2023-12-05 16:20
Duplicate of https://github.com/nvim-treesitter/nvim-treesitter/issues/4719

**Closed by clason** 2023-12-05 16:20 UTC
Labels: bug

**Comment by EvilGiraffes** [comment] 2023-12-05 18:06
> Duplicate of #4719
using zig compiler and recompiling did not fix it in my case
