### ISSUE TITLE
error in rust highlights

### ISSUE THREAD

**Issue by klachnkov** [nvim-treesitter/nvim-treesitter#6135] opened 2024-02-18 23:47 UTC
### Describe the highlighting problem

the highlights dont work, the whole thing is white text

### Example snippet that causes the problem

any **.rs/rust** files

### Tree-sitter parsing result

# Used ":InspectTree"
```
(use_declaration) ; [1:1 - 18]
 argument: (use_wildcard) ; [1:5 - 17]
  (scoped_identifier) ; [1:5 - 14]
   path: (identifier) ; [1:5 - 8]
   name: (identifier) ; [1:11 - 14]
(use_declaration) ; [2:1 - 31]
 argument: (scoped_identifier) ; [2:5 - 30]
  path: (scoped_identifier) ; [2:5 - 16]
   path: (identifier) ; [2:5 - 8]
   name: (identifier) ; [2:11 - 16]
  name: (identifier) ; [2:19 - 30]
(use_declaration) ; [3:1 - 13]
 argument: (use_wildcard) ; [3:5 - 12]
  (identifier) ; [3:5 - 9]
(mod_item) ; [3:15 - 24]
 name: (identifier) ; [3:19 - 23]
(mod_item) ; [4:1 - 10]
 name: (identifier) ; [4:5 - 9]
(mod_item) ; [4:12 - 20]
 name: (identifier) ; [4:16 - 19]
(use_declaration) ; [5:1 - 25]
 argument: (scoped_identifier) ; [5:5 - 24]
  path: (scoped_identifier) ; [5:5 - 11]
   path: (identifier) ; [5:5 - 7]
   name: (identifier) ; [5:10 - 11]
  name: (identifier) ; [5:14 - 24]
(function_item) ; [7:1 - 37:1]
 name: (identifier) ; [7:4 - 13]
 parameters: (parameters) ; [7:14 - 47]
  (parameter) ; [7:15 - 28]
   pattern: (identifier) ; [7:15 - 18]
   type: (reference_type) ; [7:20 - 28]
    type: (array_type) ; [7:21 - 28]
     element: (type_identifier) ; [7:22 - 27]
  (parameter) ; [7:30 - 46]
   pattern: (identifier) ; [7:30 - 41]
   type: (reference_type) ; [7:43 - 46]
    type: (primitive_type) ; [7:44 - 46]
 body: (block) ; [7:49 - 37:1]
  (let_declaration) ; [8:5 - 23]
   pattern: (identifier) ; [8:9 - 11]
   value: (reference_expression) ; [8:15 - 22]
    value: (index_expression) ; [8:16 - 22]
     (identifier) ; [8:16 - 19]
     (integer_literal) ; [8:21 - 21]
  (expression_statement) ; [10:5 - 37]
   (call_expression) ; [10:5 - 36]
    function: (scoped_identifier) ; [10:5 - 20]
     path: (identifier) ; [10:5 - 7]
     name: (identifier) ; [10:10 - 20]
    arguments: (arguments) ; [10:21 - 36]
     (identifier) ; [10:22 - 24]
     (reference_expression) ; [10:26 - 35]
      value: (index_expression) ; [10:27 - 35]
       (identifier) ; [10:27 - 30]
       (range_expression) ; [10:32 - 34]
        (integer_literal) ; [10:32 - 32]
  (expression_statement) ; [11:5 - 28]
   (call_expression) ; [11:5 - 27]
    function: (scoped_identifier) ; [11:5 - 22]
     path: (identifier) ; [11:5 - 9]
     name: (identifier) ; [11:12 - 22]
    arguments: (arguments) ; [11:23 - 27]
     (identifier) ; [11:24 - 26]
  (expression_statement) ; [13:5 - 20:5]
   (if_expression) ; [13:5 - 20:5]
    condition: (binary_expression) ; [13:8 - 21]
     left: (call_expression) ; [13:8 - 17]
      function: (field_expression) ; [13:8 - 15]
       value: (identifier) ; [13:8 - 11]
       field: (field_identifier) ; [13:13 - 15]
      arguments: (arguments) ; [13:16 - 17]
     right: (integer_literal) ; [13:21 - 21]
    consequence: (block) ; [13:23 - 17:5]
     (expression_statement) ; [14:9 - 46]
      (call_expression) ; [14:9 - 45]
       function: (scoped_identifier) ; [14:9 - 25]
        path: (identifier) ; [14:9 - 12]
        name: (identifier) ; [14:15 - 25]
       arguments: (arguments) ; [14:26 - 45]
        (identifier) ; [14:27 - 29]
        (call_expression) ; [14:31 - 44]
         function: (identifier) ; [14:31 - 34]
         arguments: (arguments) ; [14:35 - 44]
          (reference_expression) ; [14:36 - 43]
           value: (index_expression) ; [14:37 - 43]
            (identifier) ; [14:37 - 40]
            (integer_literal) ; [14:42 - 42]
     (expression_statement) ; [15:9 - 49]
      (call_expression) ; [15:9 - 48]
       function: (scoped_identifier) ; [15:9 - 28]
        path: (identifier) ; [15:9 - 15]
        name: (identifier) ; [15:18 - 28]
       arguments: (arguments) ; [15:29 - 48]
        (identifier) ; [15:30 - 32]
        (call_expression) ; [15:34 - 47]
         function: (identifier) ; [15:34 - 37]
         arguments: (arguments) ; [15:38 - 47]
          (reference_expression) ; [15:39 - 46]
           value: (index_expression) ; [15:40 - 46]
            (identifier) ; [15:40 - 43]
            (integer_literal) ; [15:45 - 45]
     (expression_statement) ; [16:9 - 47]
      (call_expression) ; [16:9 - 46]
       function: (scoped_identifier) ; [16:9 - 26]
        path: (identifier) ; [16:9 - 13]
        name: (identifier) ; [16:16 - 26]
       arguments: (arguments) ; [16:27 - 46]
        (identifier) ; [16:28 - 30]
        (call_expression) ; [16:32 - 45]
         function: (identifier) ; [16:32 - 35]
         arguments: (arguments) ; [16:36 - 45]
          (reference_expression) ; [16:37 - 44]
           value: (index_expression) ; [16:38 - 44]
            (identifier) ; [16:38 - 41]
            (integer_literal) ; [16:43 - 43]
    alternative: (else_clause) ; [17:7 - 20:5]
     (block) ; [17:12 - 20:5]
      (expression_statement) ; [18:9 - 36]
       (call_expression) ; [18:9 - 35]
        function: (scoped_identifier) ; [18:9 - 25]
         path: (identifier) ; [18:9 - 12]
         name: (identifier) ; [18:15 - 25]
        arguments: (arguments) ; [18:26 - 35]
         (identifier) ; [18:27 - 29]
         (identifier) ; [18:31 - 34]
      (expression_statement) ; [19:9 - 37]
       (call_expression) ; [19:9 - 36]
        function: (scoped_identifier) ; [19:9 - 26]
         path: (identifier) ; [19:9 - 13]
         name: (identifier) ; [19:16 - 26]
        arguments: (arguments) ; [19:27 - 36]
         (identifier) ; [19:28 - 30]
         (identifier) ; [19:32 - 35]
  (expression_statement) ; [22:5 - 36:5]
   (match_expression) ; [22:5 - 36:5]
    value: (call_expression) ; [22:11 - 22]
     function: (field_expression) ; [22:11 - 20]
      value: (identifier) ; [22:11 - 13]
      field: (field_identifier) ; [22:15 - 20]
     arguments: (arguments) ; [22:21 - 22]
    body: (match_block) ; [22:24 - 36:5]
     (match_arm) ; [23:9 - 55]
      pattern: (match_pattern) ; [23:9 - 38]
       (or_pattern) ; [23:9 - 38]
        (or_pattern) ; [23:9 - 28]
         (string_literal) ; [23:9 - 14]
         (string_literal) ; [23:21 - 28]
        (string_literal) ; [23:35 - 38]
      value: (call_expression) ; [23:43 - 54]
       function: (identifier) ; [23:43 - 52]
       arguments: (arguments) ; [23:53 - 54]
     (match_arm) ; [24:9 - 72]
      pattern: (match_pattern) ; [24:9 - 39]
       (or_pattern) ; [24:9 - 39]
        (or_pattern) ; [24:9 - 28]
         (string_literal) ; [24:9 - 14]
         (string_literal) ; [24:21 - 28]
        (string_literal) ; [24:35 - 39]
      value: (call_expression) ; [24:44 - 71]
       function: (scoped_identifier) ; [24:44 - 69]
        path: (identifier) ; [24:44 - 55]
        name: (identifier) ; [24:58 - 69]
       arguments: (arguments) ; [24:70 - 71]
     (match_arm) ; [25:9 - 65]
      pattern: (match_pattern) ; [25:9 - 38]
       (or_pattern) ; [25:9 - 38]
        (or_pattern) ; [25:9 - 27]
         (string_literal) ; [25:9 - 13]
         (string_literal) ; [25:21 - 27]
        (string_literal) ; [25:35 - 38]
      value: (call_expression) ; [25:43 - 64]
       function: (scoped_identifier) ; [25:43 - 62]
        path: (scoped_identifier) ; [25:43 - 51]
         path: (identifier) ; [25:43 - 46]
         name: (identifier) ; [25:49 - 51]
        name: (identifier) ; [25:54 - 62]
       arguments: (arguments) ; [25:63 - 64]
     (match_arm) ; [26:9 - 85]
      pattern: (match_pattern) ; [26:9 - 55]
       (or_pattern) ; [26:9 - 55]
        (or_pattern) ; [26:9 - 42]
         (or_pattern) ; [26:9 - 29]
          (string_literal) ; [26:9 - 15]
          (string_literal) ; [26:21 - 29]
         (string_literal) ; [26:35 - 42]
        (string_literal) ; [26:46 - 55]
      value: (call_expression) ; [26:60 - 84]
       function: (scoped_identifier) ; [26:60 - 82]
        path: (scoped_identifier) ; [26:60 - 68]
         path: (identifier) ; [26:60 - 63]
         name: (identifier) ; [26:66 - 68]
        name: (identifier) ; [26:71 - 82]
       arguments: (arguments) ; [26:83 - 84]
     (match_arm) ; [27:9 - 79]
      pattern: (match_pattern) ; [27:9 - 59]
       (or_pattern) ; [27:9 - 59]
        (or_pattern) ; [27:9 - 52]
         (or_pattern) ; [27:9 - 39]
          (or_pattern) ; [27:9 - 31]
           (string_literal) ; [27:9 - 17]
           (string_literal) ; [27:21 - 31]
          (string_literal) ; [27:35 - 39]
         (string_literal) ; [27:46 - 52]
        (string_literal) ; [27:56 - 59]
      value: (call_expression) ; [27:64 - 78]
       function: (identifier) ; [27:64 - 76]
       arguments: (arguments) ; [27:77 - 78]
     (match_arm) ; [28:9 - 30:10]
      pattern: (match_pattern) ; [28:9 - 24]
       (or_pattern) ; [28:9 - 24]
        (string_literal) ; [28:9 - 15]
        (string_literal) ; [28:19 - 24]
      value: (block) ; [28:29 - 30:9]
       (expression_statement) ; [29:13 - 52]
        (macro_invocation) ; [29:13 - 51]
         macro: (identifier) ; [29:13 - 19]
         (token_tree) ; [29:21 - 51]
          (expression_statement) ; [29:21 - 51]
           (tuple_expression) ; [29:21 - 51]
            (string_literal) ; [29:22 - 37]
             (escape_sequence) ; [29:31 - 32]
             (escape_sequence) ; [29:35 - 36]
            (identifier) ; [29:39 - 50]
          (string_literal) ; [29:22 - 37]
           (escape_sequence) ; [29:31 - 32]
           (escape_sequence) ; [29:35 - 36]
          (identifier) ; [29:39 - 50]
     (match_arm) ; [31:9 - 34:10]
      pattern: (match_pattern) ; [31:9 - 19]
       (string_literal) ; [31:9 - 19]
      value: (block) ; [31:24 - 34:9]
       (expression_statement) ; [32:13 - 35]
        (call_expression) ; [32:13 - 34]
         function: (scoped_identifier) ; [32:13 - 32]
          path: (scoped_identifier) ; [32:13 - 24]
           path: (identifier) ; [32:13 - 16]
           name: (identifier) ; [32:19 - 24]
          name: (identifier) ; [32:27 - 32]
         arguments: (arguments) ; [32:33 - 34]
       (expression_statement) ; [33:13 - 47]
        (call_expression) ; [33:13 - 46]
         function: (field_expression) ; [33:13 - 44]
          value: (call_expression) ; [33:13 - 37]
           function: (identifier) ; [33:13 - 23]
           arguments: (arguments) ; [33:24 - 37]
            (identifier) ; [33:25 - 36]
          field: (field_identifier) ; [33:39 - 44]
         arguments: (arguments) ; [33:45 - 46]
     (match_arm) ; [35:9 - 15]
      pattern: (match_pattern) ; [35:9 - 9]
      value: (block) ; [35:14 - 15]
(function_item) ; [39:1 - 47:1]
 name: (identifier) ; [39:4 - 7]
 parameters: (parameters) ; [39:8 - 9]
 body: (block) ; [39:11 - 47:1]
  (expression_statement) ; [40:5 - 25]
   (call_expression) ; [40:5 - 24]
    function: (scoped_identifier) ; [40:5 - 22]
     path: (scoped_identifier) ; [40:5 - 16]
      path: (identifier) ; [40:5 - 8]
      name: (identifier) ; [40:11 - 16]
     name: (identifier) ; [40:19 - 22]
    arguments: (arguments) ; [40:23 - 24]
  (let_declaration) ; [41:5 - 33]
   pattern: (identifier) ; [41:9 - 12]
   value: (call_expression) ; [41:16 - 32]
    function: (scoped_identifier) ; [41:16 - 30]
     path: (identifier) ; [41:16 - 20]
     name: (identifier) ; [41:23 - 30]
    arguments: (arguments) ; [41:31 - 32]
  (expression_statement) ; [42:5 - 46:5]
   (if_expression) ; [42:5 - 46:5]
    condition: (unary_expression) ; [42:8 - 28]
     (call_expression) ; [42:9 - 28]
      function: (field_expression) ; [42:9 - 26]
       value: (field_expression) ; [42:9 - 17]
        value: (identifier) ; [42:9 - 12]
        field: (field_identifier) ; [42:14 - 17]
       field: (field_identifier) ; [42:19 - 26]
      arguments: (arguments) ; [42:27 - 28]
    consequence: (block) ; [42:30 - 44:5]
     (expression_statement) ; [43:9 - 46]
      (call_expression) ; [43:9 - 45]
       function: (identifier) ; [43:9 - 18]
       arguments: (arguments) ; [43:19 - 45]
        (reference_expression) ; [43:20 - 29]
         value: (field_expression) ; [43:21 - 29]
          value: (identifier) ; [43:21 - 24]
          field: (field_identifier) ; [43:26 - 29]
        (reference_expression) ; [43:31 - 44]
         value: (field_expression) ; [43:32 - 44]
          value: (identifier) ; [43:32 - 35]
          field: (field_identifier) ; [43:37 - 44]
    alternative: (else_clause) ; [44:7 - 46:5]
     (block) ; [44:12 - 46:5]
      (expression_statement) ; [45:9 - 21]
       (call_expression) ; [45:9 - 20]
        function: (identifier) ; [45:9 - 18]
        arguments: (arguments) ; [45:19 - 20]
```

### Example screenshot

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/128702040/095d7893-3a8c-4521-934d-23376d2245b6)

### Expected behavior

idk you do you fix it i guess 🤷

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v21.6.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `clang` executable found. Selected from { "clang" }
  Version: clang version 16.0.6
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.22621",
  sysname = "Windows_NT",
  version = "Windows 11 Pro"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - c_sharp             ✓ ✓ ✓ . ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                x ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR rust(highlights): ...\current\share\nvim\runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 4285 for language rust
  rust(highlights) is concatenated from the following files:
  | [ERROR]:"C:\Users\pcjla\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\rust\highlights.scm", failed to load: ...\current\share\nvim\runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 4285 for language rust
```

### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

### Additional context

broke after running :PackerUpdate, basically broke after updating the plugin

**Comment by clason** [comment] 2024-02-19 09:16
> idk you do you fix it i guess 🤷

yeah, that's not gonna fly. _you_ fix _your_ config.
Duplicate of #3092

**Closed by clason** 2024-02-19 09:16 UTC
Labels: highlights
