### ISSUE TITLE
`get_parser` in lua file causes `invalid field at position` error and breaks plugins

### ISSUE THREAD

**Issue by smjonas** [nvim-treesitter/nvim-treesitter#2295] opened 2022-01-18 21:49 UTC
### Describe the bug

This error occurs since the new lua parser was added in c80715f, it even occurs in `healthcheck` itself.
```
E5108: Error executing lua ...lsxC/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid
 field at position 18                                                                                     
stack traceback:                                                                                          
        [C]: in function '_ts_parse_query'                                                                
        ...lsxC/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: in function 'get_query'          
        ...r/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:37: in function 'new'                 
        ...nvim2ElsxC/usr/share/nvim/runtime/lua/vim/treesitter.lua:45: in function '_create_parser'      
        ...nvim2ElsxC/usr/share/nvim/runtime/lua/vim/treesitter.lua:93: in function 'get_parser'          
        [string ":lua"]:1: in main chunk   
```

### To Reproduce

- Open any lua file.
- run `:lua require("nvim-treesitter.parsers).get_parser()`

### Expected behavior

No error.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v14.17.3 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - erlang         . . . . . 
  - zig            ✓ . ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - fusion         ✓ ✓ ✓ ✓ . 
  - elm            ✓ . . . ✓ 
  - ledger         ✓ . ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - verilog        ✓ ✓ ✓ . ✓ 
  - perl           ✓ . . . . 
  - graphql        ✓ . . ✓ ✓ 
  - dot            ✓ . . . ✓ 
  - pascal         ✓ ✓ ✓ ✓ ✓ 
  - cuda           ✓ ✓ ✓ ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - r              ✓ ✓ . . . 
  - java           ✓ ✓ . ✓ ✓ 
  - surface        ✓ . ✓ ✓ ✓ 
  - heex           ✓ . ✓ ✓ ✓ 
  - ninja          ✓ . ✓ ✓ . 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - beancount      ✓ . ✓ . . 
  - http           ✓ . . . ✓ 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - norg           . . . . . 
  - scala          ✓ . ✓ . ✓ 
  - elixir         ✓ ✓ ✓ ✓ ✓ 
  - hack           ✓ . . . . 
  - foam           ✓ ✓ ✓ ✓ ✓ 
  - gomod          ✓ . . . ✓ 
  - tlaplus        ✓ . ✓ . ✓ 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - haskell        ✓ . . . ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - make           ✓ . . . ✓ 
  - kotlin         ✓ ✓ ✓ . ✓ 
  - vue            ✓ . ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - hocon          ✓ . . . ✓ 
  - glimmer        ✓ . . . . 
  - pioasm         ✓ . . . ✓ 
  - json5          ✓ . . . ✓ 
  - julia          ✓ ✓ ✓ ✓ ✓ 
  - rst            ✓ ✓ . . ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - markdown       ✓ . ✓ . ✓ 
  - vim            ✓ ✓ . . ✓ 
  - cmake          ✓ . ✓ . . 
  - yang           ✓ . ✓ . . 
  - bibtex         ✓ . ✓ ✓ . 
  - latex          ✓ . ✓ . ✓ 
  - svelte         ✓ . ✓ ✓ ✓ 
  - pug            ✓ . . . ✓ 
  - nix            ✓ ✓ ✓ . ✓ 
  - hcl            ✓ . ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - ocaml_interface✓ ✓ ✓ . ✓ 
  - comment        ✓ . . . . 
  - clojure        ✓ ✓ ✓ . ✓ 
  - regex          ✓ . . . . 
  - dockerfile     ✓ . . . ✓ 
  - lua            x x x x x 
  - ql             ✓ ✓ . ✓ ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - gowork         ✓ . . . ✓ 
  - hjson          ✓ ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - fennel         ✓ ✓ . . ✓ 
  - commonlisp     ✓ ✓ ✓ . . 
  - fortran        ✓ . ✓ ✓ . 
  - jsdoc          ✓ . . . . 
  - llvm           ✓ . . . . 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - prisma         ✓ . . . . 
  - dart           ✓ ✓ . ✓ ✓ 
  - glsl           ✓ ✓ ✓ ✓ ✓ 
  - rasi           ✓ ✓ ✓ ✓ . 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: lua(highlights): ...lsxC/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 503
  - ERROR: lua(locals): ...lsxC/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 15
  - ERROR: lua(folds): ...lsxC/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 92
  - ERROR: lua(indents): ...lsxC/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 29
  - ERROR: lua(injections): ...lsxC/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid field at position 18

```
```


### Output of `nvim --version`

```text
NVIM v0.7.0-dev+835-gf65b0d423                                                                            
Build type: RelWithDebInfo                                                                                
LuaJIT 2.1.0-beta3                                                                                        
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -O
g -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -W
missing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=a
lways -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM 
-DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/
home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/sr
c/nvim/auto -I/home/runner/work/neovim/neovim/build/include                                               
Compiled by runner@fv-az32-596                                                                            
                                                                                                          
Features: +acl +iconv +tui                                                                                
See ":help feature-compile"                                                                               
                                                                                                          
   system vimrc file: "$VIM/sysinit.vim"                                                                  
  fall-back for $VIM: "                                                                                   
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"                                         
                                                                                                          
Run :checkhealth for more info 
```

### Additional context

This breaks any plugin that uses the `get_parser()` function for me (e.g. `nvim_cmp`, `nvim-ts-context-commentstring`). I did run `:TSInstall lua`.

**Comment by theHamsta** [comment] 2022-01-18 21:54
Did restart after the plugin update? TSUpdate will fail since it still has the old repo URL loaded. It should work after a restart of Nvim.

**Comment by smjonas** [comment] 2022-01-18 21:55
Yes I restarted Neovim and also reinstalled several times.

**Comment by clason** [comment] 2022-01-18 21:56
If in doubt, remove the plugin directory and just let your package manager install it (and the parsers) again.

**Comment by theHamsta** [comment] 2022-01-18 21:58
I had the same problem and I found it by using `:TSEditQuery highlights` (and other query types). In my case a plugin had a `after` query that I could out-comment (a colorscheme I wasn't even using!?).

**Comment by ahmedelgabri** [comment] 2022-01-18 22:01
I have the same problem & I deleted my whole plugins folder & installed everything from scratch & I'm still getting the same errors still.

**Comment by gegoune** [comment] 2022-01-18 22:03
For me it's slightly different error:
```
[nvim-treesitter] [0/1] Downloading...
[nvim-treesitter] [0/1] Creating temporary directory
[nvim-treesitter] [0/1] Extracting...
[nvim-treesitter] [0/1] Compiling...
Failed to execute the following command:
{
  cmd = <function 1>
}
"...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 20"
```
on `TSInstall lua`. Did uninstall and tried reinstall the parser nvim restarted between tries. 

I understand that it might be a plugin - is there a way to tell which one is it without bisecting my configuration?

**Comment by theHamsta** [comment] 2022-01-18 22:09
As I said, I found my problem using `:TSEditQuery highlights`. It will list all files from which the query group is composed. So I would try `highlights`, `injections` and maybe `indent` in case it is loaded in your config at buffer attach.

**Comment by abzcoding** [comment] 2022-01-18 22:11
> For me it's slightly different error:
> 
> ```
> [nvim-treesitter] [0/1] Downloading...
> [nvim-treesitter] [0/1] Creating temporary directory
> [nvim-treesitter] [0/1] Extracting...
> [nvim-treesitter] [0/1] Compiling...
> Failed to execute the following command:
> {
>   cmd = <function 1>
> }
> "...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 20"
> ```
> 
> on `TSInstall lua`. Did uninstall and tried reinstall the parser nvim restarted between tries.
> 
> I understand that it might be a plugin - is there a way to tell which one is it without bisecting my configuration?

i had the same errors, but weirdly enough removing `vim-matchup` plugin fixed it 😢 not sure why though

**Comment by ahmedelgabri** [comment] 2022-01-18 22:12
Updating https://github.com/nvim-treesitter/nvim-treesitter-textobjects seems to have fixed the issue for me. This commit https://github.com/nvim-treesitter/nvim-treesitter-textobjects/commit/c81382328ad47c154261d1528d7c921acad5eae5

**Comment by smjonas** [comment] 2022-01-18 22:14
Thank you @ahmedelgabri, that seems to have fixed it for me as well!

**Comment by theHamsta** [comment] 2022-01-18 22:28
@ahmedelgabri  vim-matchup use tree-sitter queries for some languages on nvim. My comment mentioning that got deleted.

**Comment by cseickel** [comment] 2022-01-19 00:17
I'm having similar issues. I have enough of my own bugs to fix without dealing with other people's breaking changes, so I pinned my config to the commit before the breaking change:

```lua
use {
    'nvim-treesitter/nvim-treesitter',
    commit = '668de0951a36ef17016074f1120b6aacbe6c4515',
    ...
```

Then PackerSync, restart nvim, `TSInstall lua` to replace with the old parser.

**Comment by tdjordan** [comment] 2022-01-19 01:34
I have a similar issue.

```
ERROR: lua(highlights): ...im/0.6.1/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 2371
```

However, I tracked down to a query in the `eddyekofo94/gruvbox-flat.nvim` plugin

**Comment by ldelossa** [comment] 2022-01-19 03:13
Hello there, 

I blasted away my entire plugins directory and did a "PlugUpdate", then reinstalled all parsers. I can consistently produce 

```
Error detected while processing FileType Autocommands for "*":
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 20
stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: in function 'get_query'
        ...nvim/after/nvim-treesitter/lua/nvim-treesitter/query.lua:91: in function 'get_query'
        ...is/.config/nvim/after/nvim-gps/lua/nvim-gps/internal.lua:11: in function 'is_supported'
        ...im/after/nvim-treesitter/lua/nvim-treesitter/configs.lua:349: in function 'is_enabled'
        ...im/after/nvim-treesitter/lua/nvim-treesitter/configs.lua:456: in function 'attach_module'
        ...im/after/nvim-treesitter/lua/nvim-treesitter/configs.lua:481: in function 'reattach_module'
```

By performing a "filetype detect" command in the command window. This is not related to any plugin queries that I know of as its simply running the filetype detection. Any ideas to fix ?

**Comment by ldelossa** [comment] 2022-01-19 03:22
> I'm having similar issues. I have enough of my own bugs to fix without dealing with other people's breaking changes, so I pinned my config to the commit before the breaking change:
> 
> ```lua
> use {
>     'nvim-treesitter/nvim-treesitter',
>     commit = '668de0951a36ef17016074f1120b6aacbe6c4515',
>     ...
> ```
> 
> Then PackerSync, restart nvim, `TSInstall lua` to replace with the old parser.

This does not seem to work for me, as installing the new lua parser happens regardless I believe, at least, I still get the error.

**Comment by zenobht** [comment] 2022-01-19 07:25
Hello there,

I am getting this on Kotlin files

```
Error detected while processing BufReadPost Autocommands for "*":
E5108: Error executing lua vim/filetype.lua:0: Vim(lua):E5108: Error executing lua ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 84
stack traceback:
        [C]: in function '_ts_parse_query'
        ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: in function 'get_query'
        ...3/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:37: in function 'new'
        ...m/HEAD-de6f923/share/nvim/runtime/lua/vim/treesitter.lua:45: in function '_create_parser'
        ...m/HEAD-de6f923/share/nvim/runtime/lua/vim/treesitter.lua:93: in function 'get_parser'
        .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:107: in function 'attach'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:458: in function 'attach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:481: in function 'reattach_module'
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_buf_set_option'
        vim/filetype.lua: in function ''
        vim/filetype.lua: in function <vim/filetype.lua:0>
stack traceback:
        [C]: in function 'nvim_buf_set_option'
        vim/filetype.lua: in function ''
        vim/filetype.lua: in function <vim/filetype.lua:0>
Error detected while processing VimEnter Autocommands for "*":
E5108: Error executing lua ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...vim/site/pack/packer/opt/packer.
nvim/lua/packer/load.lua:155: Vim(call):E5108: Error executing lua vim/filetype.lua:0: Vim(lua):E5108: Error executing lua ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172:
query: invalid node type at position 84
stack traceback:
        [C]: in function 'cmd'
        ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: in function <...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:161>
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

checkhealth returns following errors
```
## The following errors have been detected:
  - ERROR: llvm(highlights): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 14
  - ERROR: cuda(highlights): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 3362
  - ERROR: cuda(locals): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 1938
  - ERROR: rust(highlights): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 4093
  - ERROR: java(highlights): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 2073
  - ERROR: java(indents): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 239
  - ERROR: java(injections): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 2
  - ERROR: cpp(highlights): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 3362
  - ERROR: cpp(locals): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 1938
  - ERROR: kotlin(highlights): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 18
  - ERROR: kotlin(locals): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 14
  - ERROR: kotlin(folds): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 4
  - ERROR: kotlin(injections): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 84
  - ERROR: lua(highlights): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 503
  - ERROR: lua(locals): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 15
  - ERROR: lua(folds): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 92
  - ERROR: lua(indents): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 29
  - ERROR: lua(injections): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid field at position 18
  - ERROR: verilog(highlights): ...6f923/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /Users/bharat.joshi/.local/share/nvim/site/parser/verilog.so: supported between 13 and 13, found 12
  - ERROR: verilog(locals): ...6f923/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /Users/bharat.joshi/.local/share/nvim/site/parser/verilog.so: supported between 13 and 13, found 12
  - ERROR: verilog(folds): ...6f923/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /Users/bharat.joshi/.local/share/nvim/site/parser/verilog.so: supported between 13 and 13, found 12
  - ERROR: verilog(injections): ...6f923/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /Users/bharat.joshi/.local/share/nvim/site/parser/verilog.so: supported between 13 and 13, found 12
  - ERROR: r(highlights): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 124
  - ERROR: latex(highlights): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 4574
  - ERROR: go(highlights): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 1040
  - ERROR: elixir(highlights): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 372
  - ERROR: elixir(locals): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 38
  - ERROR: elixir(injections): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 10
  - ERROR: query(highlights): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 249
  - ERROR: python(highlights): ...-de6f923/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 5614

```

**Comment by theHamsta** [comment] 2022-01-19 08:00
Can you check which parser file it loads? :h nvim_get_runtime. It's possible that it loads an old one from your data directory.

**Comment by zenobht** [comment] 2022-01-19 11:21
@theHamsta thanks. 

Previously I had deleted just the plugins and reinstalled. After deleting the parser and plugins and reinstalling everything, it is working without any errors now.

**Comment by a2n-s** [comment] 2022-01-19 11:21
In case you want more infos, I simply ran `:TSUpdate` as suggested in the `Treesitter` output of `:checkhealth` and it fixed the problems!

**Comment by horseinthesky** [comment] 2022-01-19 13:12
In my case, nothing (reinstalling parser, plugins, rebuilding NVIM) but removing the whole `~/.local/share/nvim` helped. But finally, it works again.

**Comment by mottram** [comment] 2022-01-19 14:28
> Can you check which parser file it loads? :h nvim_get_runtime searching for parser/lua.so.It's possible that it loads an old one from your data directory.

Thanks, this sorted everything out for me. Running `echo nvim_get_runtime_file('*/lua.so', v:true)` showed an old parser file at `~/.local/share/nvim/site/parser/lua.so`.

It looks like nvim-treesitter creates this parser directory and installs files there if it doesn't have write access to its own directory - see [utils.lua](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/utils.lua#L77) from line 77.

Outdated files stored in this directory have [caused problems before](https://github.com/nvim-treesitter/nvim-treesitter/issues/2014#issuecomment-970342040), so it might be a good idea to warn the user if parser files are installed in both locations?

**Comment by melsiir** [comment] 2022-01-19 14:42
Any fix for the issue ?

**Comment by clason** [comment] 2022-01-19 15:25
> It looks like nvim-treesitter creates this parser directory and installs files there if it doesn't have write access to the standard `nvim-treesitter/parser` directory - see [utils.lua](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/utils.lua#L77) from line 77.

Oh, good catch, I wasn't even aware we did that!

> Outdated files stored in this directory have [caused problems before](https://github.com/nvim-treesitter/nvim-treesitter/issues/2014#issuecomment-970342040), so it might be a good idea to warn the user if parser files are installed in both locations?

We should stop doing that, and/or add a list of found parsers to checkhealth. I'll open an issue about it.

**Comment by melsiir** [comment] 2022-01-19 16:30
For me treesitter doesn't have to installation directory here the result of echo nvim_get_runtime_file('*/lua.so', v:true):

['/data/data/com.termux/files/home/.local/share/nv
im/site/pack/packer/opt/nvim-treesitter/parser/lua
.so']

I deleted the whole nvim folder but the issue not solved yet 😔

**Comment by melsiir** [comment] 2022-01-19 17:51
> > I deleted the whole nvim folder but the issue not solved yet
> 
> @melsiir old parsers can be an issue (as noted above), but plugins might also be using (now) invalid queries. For instance [aerial.nvim](https://github.com/stevearc/aerial.nvim/issues/49) has some that will need to be updated. The error output _might_ have more information with regards to which plugin needs to be updated that would help you track down exactly where your issue lies.

...iles/usr/share/nvim/runtime/lua/vim/tre
esitter/query.lua:161: in function 'get_query'            ...sr/share/nvim/runtime/lua/vim/treesitte
r/highlighter.lua:98: in function 'new'
        ...sr/share/nvim/runtime/lua/vim/treesitte
r/highlighter.lua:223: in function 'get_query'
        ...m-matchup/lua/treesitter-matchup/third-
        ...m-matchup/lua/treesitter-matchup/third-
party/hl-info.lua:31: in function 'fn'
        ...r/share/nvim/runtime/lua/vim/treesitter
/languagetree.lua:194: in function 'for_each_tree'
        ...m-matchup/lua/treesitter-matchup/third-
party/hl-info.lua:22: in function 'get_treesitter_
hl'
        ...packer/opt/vim-matchup/lua/treesitter-m
atchup/syntax.lua:83: in function 'synID'
        [string "luaeval()"]:1: in main chunk

**Comment by clason** [comment] 2022-01-19 17:52
Yes, matchup uses incompatible queries -- you need to disable it (or downgrade and pin nvim-treesitter) until it is updated. (I believe that was mentioned in an earlier comment already.)

**Comment by melsiir** [comment] 2022-01-19 19:00
> Yes, matchup uses incompatible queries -- you need to disable it (or downgrade and pin nvim-treesitter) until it is updated. (I believe that was mentioned in an earlier comment already.)
> 
> **EDIT** ...which apparently already happened, please update.

I disabled vim-matchup one error gone but now I am getting this error  treesitter/highlighter:line: Error executing lua: ...iles/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 1 and the issue not fixed

**Comment by kdheepak** [comment] 2022-01-19 19:20
I'm still getting this error. I had to uninstall the lua treesitter parser to prevent any errors. I'm using the latest version of neovim, nvim-treesitter and nvim-treesitter-objects, and I'm not using vim-matchup.

**Comment by kishikaisei** [comment] 2022-01-19 19:22
Removing vim-matchup did not help from my side:
![image](https://user-images.githubusercontent.com/1894123/150199632-a9f29048-8372-4e76-baf9-e9f4c2e80a81.png)

**Comment by nikensss** [comment] 2022-01-19 21:30
In my case, I had issues opening rust files (TypeScript files worked fine). It said this: `treesitter/highlighter: Error executing lua` and it ended with this `treesitter/query.lua:161: query: invalid node type at position 4093`. Running `TSUpdate` fixed it.

**Comment by zenobht** [comment] 2022-01-19 23:51
I dont think there is an issue with vim-matchup. I have that plugin as well. It is the old parsers as @theHamsta suggested. Deleting all parsers solved the issue for me. 

I had old parsers in this location `~/.local/share/nvim/site/parser` but on deleting all of them and updating the plugins, the new parsers are at `~/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser`.

**Comment by metalelf0** [comment] 2022-01-20 07:57
Having a very similar issue, although the numbers seem a little different. My errors are with the lua parser.

Here's the `:checkhealth` output:

```text
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (e85a279cf29da1b08648e27214dda20a841e57c8) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.16.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.0.0 (clang-1300.0.29.30)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - lua            x ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: lua(highlights): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 2371
```

What I've tried:
- recompiling neovim from latest master (I'm on `v0.7.0-dev+906-gde6f9233e` now);
- updating all plugins to latest versions with `:PackerUpdate`;
- deleting all parsers and reinstalling them with `:TSInstall` / `:TSUpdate lua`;
- made sure I've no duplicate parsers lying around;
- removed the `nvim-treesitter-textobject` plugin;
- going back to the pinned commit as mentioned in https://github.com/nvim-treesitter/nvim-treesitter/issues/2295#issuecomment-1015952587, and reinstalled the lua parser (but this leads to another error: `Error executing lua /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 13`).

**Comment by mystilleef** [comment] 2022-01-20 12:17
Removing `nvim-treesitter-textobjects` fixed this issue for me.

**Comment by theHamsta** [comment] 2022-01-20 13:23
@mystilleef nvim-treesitter-textobjects was acutally updated for this change the same day.

**Comment by AckslD** [comment] 2022-01-20 22:30
Removing `~/.local/share/nvim/site/parser/lua.so` worked for me.

**Comment by hornyjailfish** [comment] 2022-01-21 00:42
`:TSEditQuery highlights` helps me too! One of the themes with TS support bork lua highlighing

**Comment by andozw** [comment] 2022-01-21 04:24
> Removing `~/.local/share/nvim/site/parser/lua.so` worked for me.

This worked for me as well.

**Comment by metalelf0** [comment] 2022-01-21 06:53
Edit: another `:TSInstall lua` this morning, after I had it uninstalled, got it back to working without any errors. I've no clue about why.

**Comment by theHamsta** [comment] 2022-01-21 07:02
@metalelf0 maybe your plugins did some fixes regarding Lua queries in the background...

**Comment by metalelf0** [comment] 2022-01-21 07:08
@theHamsta yeah, that's the only explanation!

**Comment by melsiir** [comment] 2022-01-21 08:06
Is there fix ?

**Comment by theHamsta** [comment] 2022-01-21 08:23
@melsiir there were various problems mostly related to plugin and user config dependencies. The Lua parser has changed so you must take care that
- no old Lua parser is on your system (in doubt delete `~/.local/share/nvim/site/parser/lua.so`)
- no query file for the old Lua parser on your system (in doubt check the following files `:lua print(vim.inspect(vim.api.nvim_get_runtime_file('queries/lua/*', true)))` with nvim-treesitter/playground)

There is no problem with this plugin itself

**Comment by melsiir** [comment] 2022-01-21 09:14
> 

I removed the whole treesitter folder and reinstalled it but just keep showing :
treesitter/highlighter: Error executing lua: ...iles/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161

Inlines

**Comment by clason** [comment] 2022-01-21 09:18
As theHamsta explained, you may have a Lua parser in a different directory. Also, other plugins may be causing this error if they haven't updated to the new queries yet. Please read his comment carefully and follow the advice.

**Comment by atomdmac** [comment] 2022-01-21 15:09
Reinstalling Neovim worked for me.

**Comment by braindev** [comment] 2022-01-21 23:24
FWIW, for me the problem appears to be resolved by removing an unused color scheme (https://git.sr.ht/~novakane/kosmikoa.nvim in my case).

**Comment by kishikaisei** [comment] 2022-01-22 00:35
Same, removing unused treesitter colorschemes solved that (one of which was indeed kosmikoa)

**Comment by phortonssf** [comment] 2022-01-22 00:53
> `:lua print(vim.inspect(vim.api.nvim_get_runtime_file('queries/lua/*', true))` So all the files from this output need to be removed?

**Comment by jatap** [comment] 2022-01-22 07:11
Removing custom queries for the theme the issue is gone.

```
after/queries/lua/highlights.scm

(nil) @boolean
(table ["{" "}"] @punctuation.bracket)
(field (identifier) @type)
```

**Comment by phortonssf** [comment] 2022-01-22 16:49
> Removing custom queries for the theme the issue is gone.
> 
> ```
> after/queries/lua/highlights.scm
> 
> (nil) @boolean
> (table ["{" "}"] @punctuation.bracket)
> (field (identifier) @type)
> ```

The error is gone, thank you however now I no longer have any highlights in lua files.  Any idea?

**Comment by hereGittyGitty** [comment] 2022-01-23 10:55
> I had the same problem and I found it by using `:TSEditQuery highlights` (and other query types). In my case a plugin had a `after` query that I could out-comment (a colorscheme I wasn't even using!?).

Yes that command was what helped me find the troubles. In my case it where the _colorschemes_:

- `kosmikoa.nvim`
- `zephyr-nvim`

Thx a lot everyone :)

**Comment by rvolosatovs** [comment] 2022-01-24 11:26
FYI, if you're using nix and encountered this - https://github.com/nvim-treesitter/nvim-treesitter/issues/2295 fixed it for me

**Comment by xiaolitongxue666** [comment] 2022-01-29 05:46
when i remove colorschemes all work well

**Closed** 2022-01-29 08:43 UTC
Labels: bug

**Comment by bryant-the-coder** [comment] 2022-01-29 13:08
I am still facing this issue. Can anyone help?

**Comment by runfalk** [comment] 2022-02-01 11:22
I needed to update treesitter, and then run `:TSUpdate` and restart. That fixed the problem for me.

**Comment by danbruegge** [comment] 2022-02-07 08:25
I removed the parser folders from `~/.local/share/nvim/site/pack`. Since then, I got no errors and `:checkhealth` looks also fine.
Was a bit tricky to find the parser's folder because I didn't find any documentation about where the parsers are installed.

**Comment by FinallyFinancialFreedom** [comment] 2022-03-02 09:28
> Edit: another `:TSInstall lua` this morning, after I had it uninstalled, got it back to working without any errors. I've no clue about why.

yes, it works for me

**Comment by eddyekofo94** [comment] 2022-05-24 08:44
> I have a similar issue.
> 
> ```
> ERROR: lua(highlights): ...im/0.6.1/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 2371
> ```
> 
> However, I tracked down to a query in the `eddyekofo94/gruvbox-flat.nvim` plugin

Ohh is it my plugin? just seeing this now

**Comment by jwnavarrete** [comment] 2022-06-24 04:40
> En mi caso, nada (reinstalación del analizador, complementos, reconstrucción de NVIM), pero la eliminación de todo `~/.local/share/nvim`ayudó. Finalmente, vuelve a funcionar.

Muchas gracias, funciono...

**Comment by benwoodward** [comment] 2022-07-04 02:19
> I needed to update treesitter, and then run `:TSUpdate` and restart. That fixed the problem for me.

This fixed it for me, thanks!

**Comment by nickbreid** [comment] 2022-08-09 12:51
> Updating https://github.com/nvim-treesitter/nvim-treesitter-textobjects seems to have fixed the issue for me. This commit [nvim-treesitter/nvim-treesitter-textobjects@c813823](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/commit/c81382328ad47c154261d1528d7c921acad5eae5)

plus-one to this... I wasn't using `nvim-treesitter-textobjects` and installing it fixed the issue. Thanks for the help!

**Comment by ExtremelySunnyYK** [comment] 2023-11-06 14:20
In my case, it was because i did not have the lua parser, which caused me opening the lua file to have this error

**Comment by clason** [comment] 2023-11-06 14:35
Then your Neovim installation is broken, since we bundle the Lua parser.
