### ISSUE TITLE
Failed to open .gitconfig

### ISSUE THREAD

**Issue by kneep** [nvim-treesitter/nvim-treesitter#6678] opened 2024-05-23 05:51 UTC
### Describe the bug

Open an empty ```.gitconfig```, getting this error msg:
```
Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 28:2. Invalid node type "escape_sequence":
(escape_sequence) @string.escape
 ^

stack traceback:
        [C]: in function '_ts_parse_query'
        ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
        ...ovim/0.10.0/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
        ...ovim/0.10.0/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
        ....0/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
        ....0/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:240: in function 'get_query'
        ....0/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:188: in function 'fn'
        ...0/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
        ....0/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:175: in function 'prepare_highlight_states'
        ....0/share/nvim/runtime/lua/
```
If I simply comment out ```require("tree-sitter")``` in ```init.lua```, everything is OK.

### To Reproduce

```
cd
touch .gitconfig
nvim .gitconfig
```

### Expected behavior

Open with no error.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.6 (parser generator, only needed for :TSInstallFromGrammar)
- WARNING `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.3.9.4)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.5.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - bitbake             x ✓ ✓ ✓ ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cmake               ✓ . ✓ ✓ .
  - comment             ✓ . . . .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - diff                x . . . .
  - dockerfile          x . . . x
  - git_config          x . ✓ . ✓
  - git_rebase          ✓ . . . ✓
  - gitattributes       ✓ ✓ . . ✓
  - gitcommit           x . . . ✓
  - gitignore           ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - kconfig             x ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              x . . . .
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - ninja               ✓ . ✓ ✓ .
  - proto               ✓ . ✓ . .
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              x . . . ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR bitbake(highlights): ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 221:2. Invalid node type "inherit_path":
  (inherit_path) @module
   ^
  
  bitbake(highlights) is concatenated from the following files:
  | [ERROR]:"/Users/alvin.cao/.local/share/nvim/lazy/nvim-treesitter/queries/bitbake/highlights.scm", failed to load: ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 221:2. Invalid node type "inherit_path":
  (inherit_path) @module
   ^
  
- ERROR diff(highlights): ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 17:4. Invalid node type "argument":
    (argument) @variable.parameter)
     ^
  
  diff(highlights) is concatenated from the following files:
  | [ERROR]:"/Users/alvin.cao/.local/share/nvim/lazy/nvim-treesitter/queries/diff/highlights.scm", failed to load: ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 17:4. Invalid node type "argument":
    (argument) @variable.parameter)
     ^
  
- ERROR dockerfile(highlights): ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 40:4. Invalid node type "heredoc_marker":
    (heredoc_marker)
     ^
  
  dockerfile(highlights) is concatenated from the following files:
  | [ERROR]:"/Users/alvin.cao/.local/share/nvim/lazy/nvim-treesitter/queries/dockerfile/highlights.scm", failed to load: ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 40:4. Invalid node type "heredoc_marker":
    (heredoc_marker)
     ^
  
- ERROR dockerfile(injections): ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 10:4. Invalid node type "heredoc_block":
    (heredoc_block) @injection.content)
     ^
  
  dockerfile(injections) is concatenated from the following files:
  | [ERROR]:"/Users/alvin.cao/.local/share/nvim/lazy/nvim-treesitter/queries/dockerfile/injections.scm", failed to load: ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 10:4. Invalid node type "heredoc_block":
    (heredoc_block) @injection.content)
     ^
  
- ERROR git_config(highlights): ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 28:2. Invalid node type "escape_sequence":
  (escape_sequence) @string.escape
   ^
  
  git_config(highlights) is concatenated from the following files:
  | [ERROR]:"/Users/alvin.cao/.local/share/nvim/lazy/nvim-treesitter/queries/git_config/highlights.scm", failed to load: ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 28:2. Invalid node type "escape_sequence":
  (escape_sequence) @string.escape
   ^
  
- ERROR gitcommit(highlights): ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 21:4. Invalid node type "subject_prefix":
    (subject_prefix) @function @nospell)
     ^
  
  gitcommit(highlights) is concatenated from the following files:
  | [ERROR]:"/Users/alvin.cao/.local/share/nvim/lazy/nvim-treesitter/queries/gitcommit/highlights.scm", failed to load: ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 21:4. Invalid node type "subject_prefix":
    (subject_prefix) @function @nospell)
     ^
  
- ERROR kconfig(highlights): ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 44:4. Invalid node type "":
    ":="
     ^
  
  kconfig(highlights) is concatenated from the following files:
  | [ERROR]:"/Users/alvin.cao/.local/share/nvim/lazy/nvim-treesitter/queries/kconfig/highlights.scm", failed to load: ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 44:4. Invalid node type "":
    ":="
     ^
  
- ERROR luadoc(highlights): ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 28:4. Invalid node type "":
    "@as"
     ^
  
  luadoc(highlights) is concatenated from the following files:
  | [ERROR]:"/Users/alvin.cao/.local/share/nvim/lazy/nvim-treesitter/queries/luadoc/highlights.scm", failed to load: ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 28:4. Invalid node type "":
    "@as"
     ^
  
- ERROR vimdoc(highlights): ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 58:2. Invalid node type "modeline":
  (modeline) @keyword.directive
   ^
  
  vimdoc(highlights) is concatenated from the following files:
  | [ERROR]:"/Users/alvin.cao/.local/share/nvim/lazy/nvim-treesitter/queries/vimdoc/highlights.scm", failed to load: ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 58:2. Invalid node type "modeline":
  (modeline) @keyword.directive
   ^
```

### Output of `nvim --version`

```text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202
```

### Additional context

macOS version: 14.5 (23F79)
nvim-treesitter branch: master

**Comment by clason** [comment] 2024-05-23 06:55
Duplicate of #3092

**Closed by clason** 2024-05-23 06:55 UTC
Labels: bug
