### ISSUE TITLE
How to disable Highlighting when  lua multiline string ?

### ISSUE THREAD

**Issue by sober-wang** [nvim-treesitter/nvim-treesitter#3118] opened 2022-07-05 02:06 UTC
### Describe the highlighting problem

When my cursor moves to the multiline string Times error is as follows.
this file is lua code file .
<img width="1571" alt="图片" src="https://user-images.githubusercontent.com/35804630/177233639-5972ed5a-d896-4c75-8a19-6595f6039a25.png">

### Example snippet that causes the problem

```lua
vim.api.nvim_exec(
[[
augroup·FormatAutogroup  
autocmd!
autocmd·BufWritePost·*.go,*.lua,*.py,*.vue,*.json,*.js·FormatWrite
augroup·END
]],
true
)
```

### Tree-sitter parsing result

I configure the `[nvim-treesitter/playground](https://github.com/nvim-treesitter/playground)` , my nvim not have the command  `:TSPlaygroundToggle`

### Example screenshot

I configure the `[nvim-treesitter/playground](https://github.com/nvim-treesitter/playground)` , my nvim not have the command  `:TSHighlightCapturesUnderCursor`

### Output of `:checkhealth nvim-treesitter`

```markdown
1
    2 nvim-treesitter:·require("nvim-treesitter.health").check()
    3 ========================================================================
    4 ##·Installation
    5 ··-·OK:·`tree-sitter`·found·0.20.4·(parser·generator,·only·needed·for·:TSInstallFromGrammar)
    6 ··-·OK:·`node`·found·v17.6.0·(only·needed·for·:TSInstallFromGrammar)
    7 ··-·OK:·`git`·executable·found.
    8 ··-·OK:·`cc`·executable·found.·Selected·from·{·vim.NIL,·"cc",·"gcc",·"clang",·"cl",·"zig"·}
    9 ····Version:·Apple·clang·version·13.1.6·(clang-1316.0.21.2.5)
   10 ··-·OK:·Neovim·was·compiled·with·tree-sitter·runtime·ABI·version·14·(required·>=13).·Parsers·must·be·compatible·with·runtime·ABI.
   11
   12 ##·Parser/Features·H·L·F·I·J
   13 ··-·html···········✓·✓·✓·✓·✓·
   14 ··-·css············✓·.·✓·✓·✓·
   15 ··-·javascript·····✓·✓·✓·✓·✓·
   16 ··-·json···········✓·✓·✓·✓·.·
   17 ··-·vim············x·✓·✓·.·✓·
   18 ··-·c··············✓·✓·✓·✓·✓·
   19 ··-·lua············✓·✓·✓·✓·✓·
   20 ··-·tsx············✓·✓·✓·✓·✓·
   21 ··-·bash···········✓·✓·✓·.·✓·
   22 ··-·yaml···········✓·✓·✓·✓·✓·
   23 ··-·vue············✓·.·✓·✓·✓·
   24 ··-·go·············✓·✓·✓·✓·✓·
   25 ··-·python·········✓·✓·✓·✓·✓·
   26 ··-·typescript·····✓·✓·✓·✓·✓·
   27
   28 ··Legend:·H[ighlight],·L[ocals],·F[olds],·I[ndents],·In[j]ections
   29 ·········+)·multiple·parsers·found,·only·one·will·be·used
   30 ·········x)·errors·found·in·the·query,·try·to·run·:TSUpdate·{lang}
   31
   32 ##·The·following·errors·have·been·detected:
   33 ··-·ERROR:·vim(highlights):·...im-macos/share/nvim/runtime/lua/vim/treesitter/query.lua:172:·query:·invalid·node·type·at·position·765
   34 ····vim(highlights)·is·concatenated·from·the·following·files:
   35 ····|·[ERROR]:"/Users/wangshen/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/vim/highlights.scm",·failed·to·load:·...im-macos/share/nvim/               runtime/lua/vim/treesitter/query.lua:172:·query:·invalid·node·type·at·position·765
   36
~
```
```


### Output of `nvim --version`

```text
lua ➤ nvim --version                                                                                                                                       git:master*
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@Mac-1656256708179.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment] 2022-07-05 06:14
Duplicate of #3092

**Closed by clason** 2022-07-05 06:14 UTC
Labels: highlights
