### ISSUE TITLE
lua parser error on each line 

### ISSUE THREAD

**Issue by marcelarie** [nvim-treesitter/nvim-treesitter#2435] opened 2022-02-02 15:53 UTC
### Describe the bug

If I have the lua highlighting enabled the error `treesitter/highlighter: Error executing lua: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172` appears on each line.

### To Reproduce

1. Enable lua highlight on treesitter config.

### Expected behavior

Highlight the code using the treesitter syntax.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.4 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.8.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - eex            ✓ . . . ✓ 
  - julia          ✓ ✓ ✓ ✓ ✓ 
  - bibtex         ✓ . ✓ ✓ . 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - gowork         ✓ . . . ✓ 
  - kotlin         ✓ ✓ ✓ . ✓ 
  - cmake          ✓ . ✓ . . 
  - gdscript       ✓ ✓ . ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - yang           ✓ . ✓ . . 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - nix            ✓ ✓ ✓ . ✓ 
  - dot            ✓ . . . ✓ 
  - llvm           ✓ . . . . 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - scala          ✓ . ✓ . ✓ 
  - rasi           ✓ ✓ ✓ ✓ . 
  - java           ✓ ✓ . ✓ ✓ 
  - foam           ✓ ✓ ✓ ✓ ✓ 
  - norg           ✓ . ✓ . ✓ 
  - dart           ✓ ✓ . ✓ ✓ 
  - ql             ✓ ✓ . ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - gomod          ✓ . . . ✓ 
  - cuda           ✓ ✓ ✓ ✓ ✓ 
  - pug            ✓ . . . ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - beancount      ✓ . ✓ . . 
  - css            ✓ . ✓ ✓ ✓ 
  - fennel         ✓ ✓ . . ✓ 
  - vala           ✓ . . . . 
  - hack           ✓ . . . . 
  - make           ✓ . . . ✓ 
  - prisma         ✓ . . . . 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - hjson          ✓ ✓ ✓ ✓ ✓ 
  - tlaplus        ✓ ✓ ✓ . ✓ 
  - json5          ✓ . . . ✓ 
  - hocon          ✓ . . . ✓ 
  - pioasm         ✓ . . . ✓ 
  - glimmer        ✓ . . . . 
  - http           ✓ . . . ✓ 
  - vim            ✓ ✓ . . ✓ 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - hcl            ✓ . ✓ ✓ ✓ 
  - dockerfile     ✓ . . . ✓ 
  - zig            ✓ . ✓ ✓ ✓ 
  - heex           ✓ ✓ ✓ ✓ ✓ 
  - r              ✓ ✓ . ✓ . 
  - svelte         ✓ . ✓ ✓ ✓ 
  - devicetree     ✓ ✓ ✓ ✓ ✓ 
  - clojure        ✓ ✓ ✓ . ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - ocamllex       ✓ . . . ✓ 
  - rst            ✓ ✓ . . ✓ 
  - ledger         ✓ . ✓ ✓ ✓ 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - jsdoc          ✓ . . . . 
  - comment        ✓ . . . . 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - ninja          ✓ . ✓ ✓ . 
  - pascal         ✓ ✓ ✓ ✓ ✓ 
  - verilog        ✓ ✓ ✓ . ✓ 
  - fusion         ✓ ✓ ✓ ✓ . 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - phpdoc         ✓ . . . . 
  - d              ✓ . ✓ ✓ ✓ 
  - perl           ✓ . . . . 
  - haskell        ✓ . . . ✓ 
  - surface        ✓ . ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - swift          ✓ ✓ . . . 
  - commonlisp     ✓ ✓ ✓ . . 
  - markdown       ✓ . ✓ . ✓ 
  - elixir         ✓ ✓ ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - lua            x ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - godot_resource ✓ ✓ ✓ . . 
  - erlang         . . . . . 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - vue            ✓ . ✓ ✓ ✓ 
  - teal           ✓ ✓ ✓ ✓ ✓ 
  - ocaml_interface✓ ✓ ✓ . ✓ 
  - regex          ✓ . . . . 
  - json           ✓ ✓ ✓ ✓ . 
  - fortran        ✓ . ✓ ✓ . 
  - elm            ✓ . . . ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - latex          ✓ . ✓ . ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - glsl           ✓ ✓ ✓ ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: lua(highlights): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 1
    lua(highlights) is concatenated from the following files:
    | [ERROR]:"/home/marcel/.local/share/nvim/site/pack/packer/start/gruvbox-flat.nvim/queries/lua/highlights.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 1
    |    [OK]:"/home/marcel/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/lua/highlights.scm"
```

### Output of `nvim --version`

```text
NVIM v0.7.0-dev+997-g21cdecc8e
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by root

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Additional context

![treesitter-lua](https://user-images.githubusercontent.com/62728887/152188276-8d5a6cbe-bec6-4947-ac87-d79ad15db047.gif)

**Comment by clason** [comment] 2022-02-02 15:56
Duplicate of https://github.com/nvim-treesitter/nvim-treesitter/issues/2338

(Update nvim-treesitter; uninstall the Lua parser; restart Neovim; install the parser again; restart Neovim. Make sure none of your plugins are using old, incompatible queries.)

**Closed by clason** 2022-02-02 15:56 UTC
Labels: bug

**Comment by clason** [comment] 2022-02-02 16:22
Yes, I don't understand why color schemes do that (silently, it seems). Nvim-treesitter is declared "experimental" for a reason.

**Comment by rodhash** [comment] 2022-05-07 13:13
It seems just updating the language parser seems to do the trick too
