### ISSUE TITLE
Opening any javascript file throws error

### ISSUE THREAD

**Issue by suvasanket** [nvim-treesitter/nvim-treesitter#5413] opened 2023-09-17 17:58 UTC
### Describe the bug

when opening any javascript file it throw this error

`23:24:00 msg_show Error executing lua callback: ...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:24: Error executing lua: ...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:25: BufReadPost Autocommands for "*"..FileType Autocommands for "*": Vim(append):Error executing lua callback: ...im/0.9.2/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 478 for language javascript
stack traceback:
	[C]: in function '_ts_parse_query'
	...im/0.9.2/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get_query'
	.../nvim/lazy/nvim-treesitter/lua/nvim-treesitter/query.lua:108: in function 'get_query'
	...t/.local/share/nvim/lazy/nvim-ts-rainbow/lua/rainbow.lua:8: in function 'is_supported'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:387: in function 'is_enabled'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:507: in function 'attach_module'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:132>
	[C]: in function 'nvim_cmd'
	...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:25: in function <...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:24>
	[C]: in function 'nvim_buf_call'
	...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:24: in function <...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:10>
stack traceback:
	[C]: in function 'nvim_cmd'
	...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:25: in function <...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:24>
	[C]: in function 'nvim_buf_call'
	...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:24: in function <...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:10>
stack traceback:
	[C]: in function 'nvim_buf_call'
	...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:24: in function <...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:10>
`
i've reinstalled treesitter ,reinstalled parsers

### To Reproduce

nvim anyfile.js

### Expected behavior

should not get any error

### Output of `:checkhealth nvim-treesitter`

```markdown
Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.6.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "22.5.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
```

### Output of `nvim --version`

```text
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.2/share/nvim"
```

### Additional context

i've asked this problem in nvim repo they said, its a treesitter issue

**Comment by clason** [comment] 2023-09-17 17:59
Duplicate of #3092

**Closed by clason** 2023-09-17 17:59 UTC
Labels: bug
