### ISSUE TITLE
TypeScript highlighting is partially broken (neovim v0.8+)

### ISSUE THREAD

**Issue by loqusion** [nvim-treesitter/nvim-treesitter#3569] opened 2022-10-01 15:38 UTC
### Describe the bug

It seems like the typescript-specific highlighting (`type`, `interface`, type annotations, etc.) isn't working even though javascript highlighting is functioning normally. (`"filetype"` is set to `typescript`)

![image](https://user-images.githubusercontent.com/38332081/193395626-40d342d5-a69d-4bd0-a62c-29fdde5b523d.png)

### To Reproduce

1. Install latest version of neovim (this bug also affects 0.8)
2. Open a `.ts` file with typescript-specific syntax

Treesitter config:

```
  {
    ensure_installed = 'all',
    ignore_install = { 'php', 'phpdoc' },
    additional_vim_regex_highlighting = false,
    highlight = {
      enable = true,
      disable = {
        'vim',
        'help',
      },
    },
    indent = {
      enable = true,
    },
    incremental_selection = {
      enable = false,
      keymaps = {
        init_selection = 'gnn',
        scope_incremental = 'gna',
        node_incremental = 'grn',
        node_decremental = 'grm',
      },
    },
    autotag = {
      enable = true,
      filetypes = { 'html', 'javascript', 'javascriptreact', 'typescriptreact', 'svelte', 'vue', 'markdown' },
    },
    context_commentstring = {
      -- https://github.com/JoosepAlviste/nvim-ts-context-commentstring#commentnvim
      enable = true,
      enable_autocmd = false,
    },
    endwise = { enable = true },
    matchup = { enable = true },
    query_linter = {
      enable = true,
      use_virtual_text = true,
      lint_events = { 'BufWrite', 'CursorHold' },
    },
    tree_setter = {
      enable = false,
    },
    textobjects = {
      select = {
        enable = true,
        -- Automatically jump forward to textobj, similar to targets.vim
        lookahead = true,
        keymaps = {
          ['af'] = '@function.outer',
          ['if'] = '@function.inner',
          ['il'] = '@loop.inner',
          ['al'] = '@loop.outer',
          -- ['icd'] = '@conditional.inner',
          -- ['acd'] = '@conditional.outer',
          -- ['acm'] = '@comment.outer',
          ['ast'] = '@statement.outer',
          ['isc'] = '@scopename.inner',
          ['iB'] = '@block.inner',
          ['aB'] = '@block.outer',
          ['ia'] = '@parameter.inner',
          ['aa'] = '@parameter.outer',
        },
      },
      move = {
        enable = true,
        set_jumps = true, -- whether to set jumps in the jumplist
        goto_next_start = {
          [']m'] = '@function.outer',
          [']im'] = '@function.inner',
          [')'] = '@parameter.inner',
          -- [']c'] = '@call.outer',
          -- [']ic'] = '@call.inner',
        },
        goto_next_end = {
          [']M'] = '@function.outer',
          [']iM'] = '@function.inner',
          ['g)'] = '@parameter.inner',
          -- [']C'] = '@call.outer',
          -- [']iC'] = '@call.inner',
        },
        goto_previous_start = {
          ['[m'] = '@function.outer',
          ['[im'] = '@function.inner',
          ['('] = '@parameter.inner',
          -- ['[c'] = '@call.outer',
          -- ['[ic'] = '@call.inner',
        },
        goto_previous_end = {
          ['[M'] = '@function.outer',
          ['[iM'] = '@function.inner',
          ['g('] = '@parameter.inner',
          -- ['[C'] = '@call.outer',
          -- ['[iC'] = '@call.inner',
        },
      },
    },
    textsubjects = {
      enable = true,
      keymaps = {
        ['.'] = 'textsubjects-smart',
      },
    },
  }
```

### Expected behavior

Note: I get this highlighting when I set `"ft"` to `typescriptreact`. However, after switching back to `typescript` and again to `typescriptreact` it reverts to the buggy highlighting.

![image](https://user-images.githubusercontent.com/38332081/193395651-ecc4ce48-fbcd-43bf-8553-856e7474a7a4.png)

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.6.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `/opt/homebrew/opt/llvm/bin/clang` executable found. Selected from { "/opt/homebrew/opt/llvm/bin/clang", "cc", "gcc", "clang", "cl", "zig" }
    Version: Homebrew clang version 15.0.1
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - embedded_template✓ . . . ✓
  - elvish         ✓ . . . ✓
  - rego           ✓ . . . ✓
  - cooklang       ✓ . . . .
  - latex          ✓ . ✓ . ✓
  - html           ✓ ✓ ✓ ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - scheme         ✓ . ✓ . ✓
  - racket         ✓ . ✓ . ✓
  - lalrpop        ✓ ✓ . . .
  - qmljs          ✓ . ✓ . .
  - meson          ✓ . ✓ . ✓
  - r              ✓ ✓ . ✓ ✓
  - agda           ✓ . ✓ . .
  - turtle         ✓ ✓ ✓ ✓ ✓
  - hack           ✓ . . . .
  - foam           ✓ ✓ ✓ ✓ ✓
  - godot_resource ✓ ✓ ✓ . .
  - rasi           ✓ ✓ ✓ ✓ .
  - gdscript       ✓ ✓ . ✓ ✓
  - sql            ✓ . . . ✓
  - prisma         ✓ . . . .
  - sparql         ✓ ✓ ✓ ✓ ✓
  - jsdoc          ✓ . . . .
  - c              ✓ ✓ ✓ ✓ ✓
  - teal           ✓ ✓ ✓ ✓ ✓
  - pascal         ✓ ✓ ✓ ✓ ✓
  - verilog        ✓ ✓ ✓ . ✓
  - ql             ✓ ✓ . ✓ ✓
  - rst            ✓ ✓ . . ✓
  - dart           ✓ ✓ . ✓ ✓
  - nix            ✓ ✓ ✓ . ✓
  - ninja          ✓ . ✓ ✓ .
  - yang           ✓ . ✓ ✓ .
  - yaml           ✓ ✓ ✓ ✓ ✓
  - elm            ✓ . . . ✓
  - jsonc          ✓ ✓ ✓ ✓ ✓
  - pug            ✓ . . . ✓
  - proto          ✓ . ✓ . .
  - glimmer        ✓ . . . .
  - kotlin         ✓ ✓ ✓ . ✓
  - toml           ✓ ✓ ✓ ✓ ✓
  - v              ✓ ✓ ✓ ✓ ✓
  - tlaplus        ✓ ✓ ✓ . ✓
  - markdown_inline✓ . . . ✓
  - hcl            ✓ . ✓ ✓ ✓
  - norg           . . . . .
  - typescript     ✓ ✓ ✓ ✓ ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - supercollider  ✓ ✓ ✓ ✓ ✓
  - bash           ✓ ✓ ✓ . ✓
  - scala          ✓ . ✓ . ✓
  - tsx            ✓ ✓ ✓ ✓ ✓
  - todotxt        ✓ . . . .
  - d              ✓ . ✓ ✓ ✓
  - c_sharp        ✓ ✓ ✓ . ✓
  - swift          ✓ ✓ . . .
  - org            . . . . .
  - menhir         ✓ . . . ✓
  - ocamllex       ✓ . . . ✓
  - ocaml_interface✓ ✓ ✓ . ✓
  - ocaml          ✓ ✓ ✓ . ✓
  - go             ✓ ✓ ✓ ✓ ✓
  - heex           ✓ ✓ ✓ ✓ ✓
  - eex            ✓ . . . ✓
  - surface        ✓ . ✓ ✓ ✓
  - gleam          ✓ ✓ ✓ ✓ ✓
  - llvm           ✓ . . . .
  - hocon          ✓ . . . ✓
  - fennel         ✓ ✓ . . ✓
  - clojure        ✓ ✓ ✓ . ✓
  - help           ✓ . . . .
  - query          ✓ ✓ ✓ ✓ ✓
  - markdown       ✓ . ✓ . ✓
  - erlang         ✓ . ✓ . .
  - scss           ✓ . . ✓ .
  - css            ✓ . ✓ ✓ ✓
  - jsonnet        ✓ . . . .
  - julia          ✓ ✓ ✓ ✓ ✓
  - java           ✓ ✓ . ✓ ✓
  - commonlisp     ✓ ✓ ✓ . .
  - vala           ✓ . ✓ . .
  - http           ✓ . . . ✓
  - bibtex         ✓ . ✓ ✓ .
  - gomod          ✓ . . . ✓
  - beancount      ✓ . ✓ . .
  - perl           ✓ . ✓ . .
  - php            ✓ ✓ ✓ ✓ ✓
  - ruby           ✓ ✓ ✓ ✓ ✓
  - glsl           ✓ ✓ ✓ ✓ ✓
  - hlsl           ✓ ✓ ✓ ✓ ✓
  - zig            ✓ . ✓ ✓ ✓
  - slint          ✓ . . ✓ .
  - gowork         ✓ . . . ✓
  - make           ✓ . ✓ . ✓
  - elixir         ✓ ✓ ✓ ✓ ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - blueprint      ✓ . . . .
  - haskell        ✓ . ✓ . ✓
  - json           ✓ ✓ ✓ ✓ .
  - gitattributes  ✓ . . . ✓
  - fish           ✓ ✓ ✓ ✓ ✓
  - cuda           ✓ ✓ ✓ ✓ ✓
  - gitignore      ✓ . . . .
  - ledger         ✓ . ✓ ✓ ✓
  - cpp            ✓ ✓ ✓ ✓ ✓
  - sxhkdrc        ✓ . ✓ . ✓
  - fusion         ✓ ✓ ✓ ✓ .
  - tiger          ✓ ✓ ✓ ✓ ✓
  - graphql        ✓ . . ✓ ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - dot            ✓ . . . ✓
  - hjson          ✓ ✓ ✓ ✓ ✓
  - dockerfile     ✓ . . . ✓
  - vue            ✓ . ✓ ✓ ✓
  - pioasm         ✓ . . . ✓
  - comment        ✓ . . . .
  - json5          ✓ . . . ✓
  - devicetree     ✓ ✓ ✓ ✓ ✓
  - svelte         ✓ . ✓ ✓ ✓
  - m68k           ✓ ✓ ✓ . ✓
  - vim            ✓ ✓ ✓ . ✓
  - wgsl           ✓ . ✓ ✓ .
  - rnoweb         ✓ . ✓ . ✓
  - cmake          ✓ . ✓ . .
  - regex          ✓ . . . .
  - fortran        ✓ . ✓ ✓ .
  - astro          ✓ ✓ ✓ ✓ ✓
  - solidity       ✓ . . . .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.9.0-dev-1215-g9353e2f7e-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by REDACTED

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-9353e2f_1/share/nvim"

Run :checkhealth for more info
```

**Comment by helderberto** [comment] 2022-10-03 11:27
I'm having issues with syntax highlight with nvim-treesitter + Alacritty since the last update.

I tested with Lua, JavaScript and TypeScript all with syntax issues.

**Comment by helderberto** [comment] 2022-10-04 09:21
After some search, I found the problem with my config you can [see more here](https://github.com/helderberto/dotfiles/commit/f6f6af1ec0a9f06f99b0f033f2036252d4c1a6dd).

I don't remember why I have the following config enabled:
```lua
-- Nvim recently introduced entirely-in-lua filetype detection to do away with
-- the slower `filetype.vim` which is the default.
-- https://neovim.discourse.group/t/introducing-filetype-lua-and-a-call-for-help/1806
vim.g.do_filetype_lua = 1
vim.g.did_load_filetypes = 0
```

But after removing it, everything worked fine.

**Comment by kirill-martynov** [comment] 2022-10-04 09:30
Same issue, Typescript highlighting broken

**Comment by kirill-martynov** [comment] 2022-10-04 11:13
On neovim 0.7.2 highlighting works perfectly

**Comment by loqusion** [comment] 2022-10-04 12:37
> After some search, I found the problem with my config you can [see more here](https://github.com/helderberto/dotfiles/commit/f6f6af1ec0a9f06f99b0f033f2036252d4c1a6dd).
> 
> I don't remember why I have the following config enabled:
> 
> ```lua
> -- Nvim recently introduced entirely-in-lua filetype detection to do away with
> -- the slower `filetype.vim` which is the default.
> -- https://neovim.discourse.group/t/introducing-filetype-lua-and-a-call-for-help/1806
> vim.g.do_filetype_lua = 1
> vim.g.did_load_filetypes = 0
> ```
> 
> But after removing it, everything worked fine.

Unfortunately this didn't work for me.

**Comment by loqusion** [comment] 2022-10-04 17:31
> maybe related to [neovim/neovim#20105](https://github.com/neovim/neovim/pull/20105)?
> 
> upd: fixed Elixir highlighting by adding `; extends` to the beggining of all files at `after/queries/elixir/*`

That fixes it for me! Incidentally, my lua highlighting was also broken (like #3538) and this fixed it.

**Comment by kirill-martynov** [comment] 2022-10-04 18:59
@loqusion can you please explain for a newbie what should I do exactly to fix this issue?

**Comment by loqusion** [comment] 2022-10-04 19:35
@kirill-martynov The `nvim-treesitter` plugin is probably located at `~/.local/share/nvim/site/pack/packer/start` for you (if you lazy load, it's `~/.local/share/nvim/site/pack/packer/opt`. Edit all the files in `nvim-treesitter/queries/typescript` and add the line `; extends` to the beginning of each file (I added it after the line with `; inherits`, but I don't think the order matters).

Note that this may cause issues when trying to update `nvim-treesitter` in the future; you can `git restore .` to fix that.

**Comment by kirill-martynov** [comment] 2022-10-05 08:31
@loqusion Thank you so much for help! It's worked

I hope it will be fixed also in package

**Comment by GopherJ** [comment] 2023-02-28 02:25
I also have broken highlights for months now, any idea on how to fix?

![image](https://user-images.githubusercontent.com/33961674/221737117-a8d4bad1-6ce0-46fe-9e71-83326d27eaa8.png)

**Comment by rostero1** [comment] 2023-03-13 18:54
I just updated and it wiped out the workaround.  I'm about to reapply the the hack, but any ideas why this is still needed?

**Comment by amaanq** [comment] 2023-03-13 19:04
> I'm about to reapply the the hack, but any ideas why this is still needed?

A reproducer would be nice, I'm not getting this bug

**Comment by rostero1** [comment] 2023-03-13 20:23
@amaanq even though I wasn't using the colorscheme, `Plug 'ful1e5/onedark.nvim'` was breaking some typescript highlighting.  Everything is highlighted as normal after I removed that plugin.

**Comment by amaanq** [comment] 2023-03-13 20:47
> @amaanq even though I wasn't using the colorscheme, `Plug 'ful1e5/onedark.nvim'` was breaking some typescript highlighting. Everything is highlighted as normal after I removed that plugin. The above workaround is only necessary when that plugin is enabled.

https://github.com/ful1e5/onedark.nvim/blob/main/queries/typescript/highlights.scm there's your issue

Either fix it yourself by adding ;extends at the top or moving it to *after/queries/*, or use a better colorscheme ;) 

I'll close this as this seems to be a colorscheme's issue with implementation

**Closed by amaanq** 2023-03-13 20:47 UTC
Labels: bug
