### ISSUE TITLE
Error parsing kotlin files

### ISSUE THREAD

**Issue by andresmartinezstay** [nvim-treesitter/nvim-treesitter#7129] opened 2024-09-09 15:09 UTC
### Describe the bug

Any kotlin file I open outputs this error:

```
Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...m/0.10.1/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 76:2. Invalid node type "wildcard_import":
(wildcard_import) @character.special
 ^

stack traceback:
        [C]: in function '_ts_parse_query'
        ...m/0.10.1/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
        ...ovim/0.10.1/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
        ...ovim/0.10.1/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
        ....1/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
        ....1/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:243: in function 'get_query'
        ....1/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:191: in function 'fn'
        ...1/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
        ....1/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:178: in function 'prepare_highlight_states'
        ....1/share/nvim/runtime/
```

### To Reproduce

Create a kotlin file with this content and open it:

```{kt}
package expo.modules.module

import android.content.Context
import expo.modules.core.interfaces.ApplicationLifecycleListener
import expo.modules.core.interfaces.Package as ExpoPackage
import expo.modules.core.interfaces.ReactActivityLifecycleListener

class Package : ExpoPackage {
  override fun createApplicationLifecycleListeners(context: Context?): List<ApplicationLifecycleListener> {
    return listOf(LibApplicationLifecycleListener())
  }
}
```

### Expected behavior

It should parse the file correctly

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.6 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.18.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.3.9.4)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.4.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.4.0: Fri Mar 15 00:19:22 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8112"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 x ✓ ✓ ✓ ✓
  - diff                x . ✓ . x
  - gitattributes       ✓ ✓ . . ✓
  - gitignore           ✓ . . . ✓
  - groovy              x ✓ ✓ ✓ ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - kotlin              x ✓ ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - matlab              ✓ ✓ ✓ ✓ ✓
  - objc                ✓ ✓ ✓ ✓ ✓
  - properties          ✓ ✓ . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - swift               ✓ ✓ . ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR cpp(highlights): ...m/0.10.1/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 565:4. Invalid node type "virtual":
    "virtual"
     ^
  
  cpp(highlights) is concatenated from the following files:
  |    [OK]:"/Users/andresmartinez/.local/share/nvim/lazy/nvim-treesitter/queries/c/highlights.scm"
  | [ERROR]:"/Users/andresmartinez/.local/share/nvim/lazy/nvim-treesitter/queries/cpp/highlights.scm", failed to load: ...m/0.10.1/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 233:4. Invalid node type "virtual":
    "virtual"
     ^
  
- ERROR diff(highlights): ...m/0.10.1/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 1:2. Invalid node type "comment":
  (comment) @comment @spell
   ^
  
  diff(highlights) is concatenated from the following files:
  | [ERROR]:"/Users/andresmartinez/.local/share/nvim/lazy/nvim-treesitter/queries/diff/highlights.scm", failed to load: ...m/0.10.1/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 1:2. Invalid node type "comment":
  (comment) @comment @spell
   ^
  
- ERROR diff(injections): ...m/0.10.1/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 1:3. Invalid node type "comment":
  ((comment) @injection.content
    ^
  
  diff(injections) is concatenated from the following files:
  | [ERROR]:"/Users/andresmartinez/.local/share/nvim/lazy/nvim-treesitter/queries/diff/injections.scm", failed to load: ...m/0.10.1/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 1:3. Invalid node type "comment":
  ((comment) @injection.content
    ^
  
- ERROR groovy(highlights): ...m/0.10.1/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 151:2. Invalid node type "wildcard_import":
  (wildcard_import) @character.special
   ^
  
  groovy(highlights) is concatenated from the following files:
  | [ERROR]:"/Users/andresmartinez/.local/share/nvim/lazy/nvim-treesitter/queries/groovy/highlights.scm", failed to load: ...m/0.10.1/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 151:2. Invalid node type "wildcard_import":
  (wildcard_import) @character.special
   ^
  
- ERROR kotlin(highlights): ...m/0.10.1/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 76:2. Invalid node type "wildcard_import":
  (wildcard_import) @character.special
   ^
  
  kotlin(highlights) is concatenated from the following files:
  | [ERROR]:"/Users/andresmartinez/.local/share/nvim/lazy/nvim-treesitter/queries/kotlin/highlights.scm", failed to load: ...m/0.10.1/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 76:2. Invalid node type "wildcard_import":
  (wildcard_import) @character.special
   ^
```

### Output of `nvim --version`

```text
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1725453128
```

**Comment by clason** [comment] 2024-09-09 15:10
Duplicate of #3092

**Closed by clason** 2024-09-09 15:10 UTC
Labels: bug
