### ISSUE TITLE
Conflicting parser paths

### ISSUE THREAD

**Issue by ksk0** [nvim-treesitter/nvim-treesitter#3970] opened 2022-12-14 07:58 UTC
Latest **Neovim Release Build** pre built **debian** package, from github, contains `/usr/lib/nvim/parser` directory with some parser (namely *c*, *lua*, *vim* and *help*), which are obviously not compatible with latest **nvim-treesitter**, generating errors like: `query error: invalid node type at position`.

Suggested solution for this problem is to have only one "parser" directory (the one used by **nvim-treesitter**), but that can be only solved if `/usr/lib/nvim/parser` is renamed, since it is detected by **nvim** on startup. Problem with this approach is that any update, or reinstall of package, will restore named directory, thus solving problem only temporarily. 

I would assume that in the future, other packages would have similar problem.

I would suggest extra option in **nvim-treesitter** config, which would allow to explicitly define parser path.

**Comment by clason** [comment] 2022-12-14 08:09
This needs more detail. Both the parser and query paths are set up so that nvim-treesitter ones take precedence over Neovim's bundled ones (and config ones over that). If that is not the case _for you_, something is not working as intended (as it does for, e.g., me). Try to create a minimal repo and add your effective `runtimepath` to the issue.

**Comment by clason** [comment] 2022-12-14 08:32
No, when you just dump queries into `~/.config/nvim/queries`.

> I didn't have installed parser for vim and help (where i noticed the problem).

Ah, yes, that would indeed lead to issues. The problem is that nvim-treesitter always puts all queries into runtimepath, even if the parser is not installed. We are discussing how to change this.

**Comment by ksk0** [comment] 2022-12-14 08:47
Thank you for quick answer. I have solved the my problem, thus i would close the issue. My only comment on this situation would, be that adding some extra text into **"README"** file, could prove helpful for someone else :)

Chaning this: 
 - Make sure you don't have more than one parser runtime directory. You can execute this command `:echo nvim_get_runtime_file('parser', v:true)` to find all runtime directories. If you get more than one path, remove the ones that are outside this plugin (`nvim-treesitter` directory), so the correct version of the parser is used.

Into:
 - Check if you have more than one  parser runtime directory by executing `:echo nvim_get_runtime_file('parser', v:true)`. If you get more than one path you have two solutions:
     - Install conflicting parser into `nvim-treesitter` directory (if they are not already), since `nvim-treesitter` takes precedence over any other runtime path(s).
     - remove the ones that are outside this plugin (`nvim-treesitter` directory), so the correct version of the parser is used (remove them, by deleting or renaming given directory).

Kind regards, and thank you again.

**Comment by clason** [comment] 2022-12-14 08:49
Thanks, but this should "just work", so it would be better to fix this issue ;) (The paragraph needs updating in any case since more than one parser directory now explicitly needs to be supported, but that will be the next step.)

**Comment by ksk0** [comment] 2022-12-14 08:58
I understand "just work" thing, thus "removing" directories would be unnecessary. But, if parser is installed with bundle, user will not be able to update that parser (until upgrade of bundle), and only control of the situation would be if he "override" it with those coming with `nvim-treesitter`.

If I understand correctly, this problem will persist regardless how  multiple query paths will be handled. If parser is not found in highest priority one it will be taken from lower one, and if broken, it will cause the problems.

Any way, I'm talking to much :). Have a nice day.

**Comment by anoojpatel** [comment] 2022-12-15 23:17
I've ran into this issue as well when working with preconfigured nvim distros (such as Astro and NvChad) on macOS. For folks who have neovim install from brew, they should delete the nvim parser to resolve this issue. `:echo nvim_get_runtime_file('parser', v:true)` returns both nvim-treesitter and the `neovim/0.x.x/lib/parser` directories. Not sure what the direct consequences are in this case but things be fixed 🤞 .

**Comment by miguno** [comment] 2022-12-22 23:58
+1 to https://github.com/nvim-treesitter/nvim-treesitter/issues/3970#issuecomment-1353836834

Using neovim 0.8.1 on macOS 13.1 Ventura via `brew install neovim`.

Running `:checkhealth nvim-treesitter` returns:

```
## The following errors have been detected:
  - ERROR: help(highlights): ...im/0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 100     for language help
    help(highlights) is concatenated from the following files:
    | [ERROR]:"/Users/foo/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/help/highlights.scm", failed to load: ...im/    0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 100 for language help
  - ERROR: help(injections): ...im/0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 14      for language help
    help(injections) is concatenated from the following files:
    | [ERROR]:"/Users/foo/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/help/injections.scm", failed to load: ...im/    0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 14 for language help
```

**Comment by Guzzii** [comment] 2022-12-29 09:13
Confirm [this](https://github.com/nvim-treesitter/nvim-treesitter/issues/3970#issuecomment-1353836834) fix the issue for me

**Comment by matu3ba** [comment] 2023-01-10 11:28
I ran into this recently, probably due to lazy installing nvim-treesitter parser (only C and C++ parsers so far?):
```
:echo nvim_get_runtime_file('parser', v:true)
['/home/user/.local/share/nvim/lazy/nvim-treesitter/parser', '/home/user/.local/nvim/lib/nvim/parser']
```
or are those two runtime files for parsers to be expected?

On opening a new file ie .h or .cpp I get
```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: /home/user/.local/nvim/share/nvim/runtime/filetype.lua:21: Error executing lua: /home/user/.local/nvim/share/nvim/runtime/f
iletype.lua:22: Vim(append):Error executing lua callback: ...cal/nvim/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at posi
tion 74 for language cpp
stack traceback:
        [C]: in function '_ts_parse_query'
        ...cal/nvim/share/nvim/runtime/lua/vim/treesitter/query.lua:219: in function 'get_query'
        ...m/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:52: in function 'new'
        ...er/.local/nvim/share/nvim/runtime/lua/vim/treesitter.lua:45: in function '_create_parser'
        ...er/.local/nvim/share/nvim/runtime/lua/vim/treesitter.lua:96: in function 'get_parser'
        ...er/.local/nvim/share/nvim/runtime/lua/vim/treesitter.lua:330: in function 'start'
        ...m/lazy/nvim-treesitter/lua/nvim-treesitter/highlight.lua:19: in function 'attach'
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:505: in function 'attach_module'
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:528: in function 'reattach_module'
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:131: in function <...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:130>
        [C]: in function 'nvim_cmd'
        /home/user/.local/nvim/share/nvim/runtime/filetype.lua:22: in function </home/user/.local/nvim/share/nvim/runtime/filetype.lua:21>
        [C]: in function 'nvim_buf_call'
        /home/user/.local/nvim/share/nvim/runtime/filetype.lua:21: in function </home/user/.local/nvim/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_cmd'
        /home/user/.local/nvim/share/nvim/runtime/filetype.lua:22: in function </home/user/.local/nvim/share/nvim/runtime/filetype.lua:21>
        [C]: in function 'nvim_buf_call'
        /home/user/.local/nvim/share/nvim/runtime/filetype.lua:21: in function </home/user/.local/nvim/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /home/user/.local/nvim/share/nvim/runtime/filetype.lua:21: in function </home/user/.local/nvim/share/nvim/runtime/filetype.lua:10>
```

**Comment by matu3ba** [comment] 2023-01-10 11:28
This is very annoying, because it also breaks .editorconfig indenting.

**Comment by clason** [comment] 2023-01-10 11:38
> or are those two runtime files for parsers to be expected?

Yes, they are expected. Neovim now bundles the four listed parsers (c, Lua, Vim, and help), but you can (and probably want to) also be able to install them via nvim-treesitter to, e.g., get faster updates.

So the current situation is **intentional** -- and things are set up so that nvim-treesitter parsers _and_ queries take precedence over the bundled ones, so there shouldn't be (and aren't in "normal" situations) any errors. The **recommended** way is to make sure you install all four parsers via nvim-treesitter if you're using nvim-treesitter at all.

If there are issues in "not normal" situations -- which definitely includes "Neovim distros" -- then people need to make sure themselves that the same precedence is respected. (To be clear, we _cannot_ support distros, we can only target stock Neovim.)

**Comment by matu3ba** [comment] 2023-01-10 11:38
To my knowledge, the workaround would be to explain users
1. to not to use `ensure_installed = { "c", "vim", "lua" },` in the README, because that clashes with the shipped ones by neovim and
2. to tell them to delete the neovim ones if they want to use upstream parser updates otherwise (finding the paths via `:echo nvim_get_runtime_file('parser', v:true)`).
3. It would be nicer, if nvim-treesitter would know have a priority setting: prioritize own parsers vs prioritize other ones.

**Comment by clason** [comment] 2023-01-10 11:40
No, these are definitely **not** the right workaround -- just the opposite:

1. you _should_ install **all** these parsers,
2. you should **not** touch Neovim's install directories,
3. because `nvim-treesitter` parsers and queries **do** have higher priority **by default** -- if a distro messes with runtimepath in some way that breaks this, this is up to them to fix. Go complain there.

**Comment by matu3ba** [comment] 2023-01-10 11:42
Agreed. Just a nit: `ensure_installed = { "c", "lua", "rust" },` does not contain `help`.

**Comment by clason** [comment] 2023-01-10 12:12
You mean in the README example? Just changed that, so I'll close this issue as completed. (We'll continue discussing possibly more robust handling in the meantime.)

**Closed by clason** 2023-01-10 12:12 UTC
Labels: bug, needs information

**Comment by miguno** [comment] 2023-01-10 12:21
Thanks for the follow-up, everyone.

**Comment by searleser97** [comment] 2023-08-29 00:17
Having this issue as well, are there any new thoughts around a new better solution ?

**Comment by searleser97** [comment] 2023-08-29 04:21
Also, is there another way around apart from deleting the folder ? any way to use lua or vim command to let neovim know we just want to use treesitter parsers ?

**Comment by vodrazka** [comment] 2023-11-06 20:30
So the solution is to do `:TSInstall X` where `X` is the parser in conflict?

**Comment by olevski** [comment] 2024-05-10 22:31
> Thank you for quick answer. I have solved the my problem, thus i would close the issue. My only comment on this situation would, be that adding some extra text into **"README"** file, could prove helpful for someone else :)
> 
> Chaning this:
> 
>     * Make sure you don't have more than one parser runtime directory. You can execute this command `:echo nvim_get_runtime_file('parser', v:true)` to find all runtime directories. If you get more than one path, remove the ones that are outside this plugin (`nvim-treesitter` directory), so the correct version of the parser is used.
> 
> 
> Into:
> 
>     * Check if you have more than one  parser runtime directory by executing `:echo nvim_get_runtime_file('parser', v:true)`. If you get more than one path you have two solutions:
>       
>       * Install conflicting parser into `nvim-treesitter` directory (if they are not already), since `nvim-treesitter` takes precedence over any other runtime path(s).
>       * remove the ones that are outside this plugin (`nvim-treesitter` directory), so the correct version of the parser is used (remove them, by deleting or renaming given directory).
> 
> 
> Kind regards, and thank you again.

I have to say the suggestion above from @ksk0 is what made me realize what I have to do to fix this. The existing instructions are really cryptic and before I read the proposal to reword this and some of the other comments here it was not clear to me at all what I am supposed to do.

**Comment by hejops** [comment] 2024-11-08 13:14
> Also, is there another way around apart from deleting the folder ? any way to use lua or vim command to let neovim know we just want to use treesitter parsers ?
> 
> When installing neovim through snap is not posible to delete or rename the parser folder

Removing and reinstalling `nvim` worked for me:

```bash
sudo snap remove nvim
sudo snap install --classic nvim
```
