### ISSUE TITLE
nvim hangs when particular file is opened

### ISSUE THREAD

**Issue by dhananjaylatkar** [nvim-treesitter/nvim-treesitter#5227] opened 2023-08-11 05:39 UTC
### Describe the bug

When I try to open `linux-6.2.6/tools/include/uapi/linux/bpf.h` nvim stops responding.

File size is 265k which should not be a problem since I'm able to open files of size 500k+ with little to no delay.

### To Reproduce

Open this file from linux source code in nvim.
```
➜ nvim tools/include/uapi/linux/bpf.h
```

### Expected behavior

nvim should open the file.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation
- OK tree-sitter found 0.20.4 (714bfd47a744ab44b904375c177a24c0614ef49c) (parser generator, only needed for :TSInstallFromGrammar)
- OK node found v8.10.0 (only needed for :TSInstallFromGrammar)
- OK git executable found.
- OK cc executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.4.0-136-generic",
  sysname = "Linux",
  version = "#153~18.04.1-Ubuntu SMP Wed Nov 30 15:47:57 UTC 2022"
}

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - perl                ✓ . ✓ . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
➜ nvim --version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by lucario387** [comment] 2023-08-11 05:43
I'm able to open `bpf.h` file without any issue, I suppose the problem is the `comment` parser?

**Comment by dhananjaylatkar** [comment] 2023-08-11 05:49
Is `comment` parser installed with `c` parser? I haven't installed it explicitly.

**Comment by lucario387** [comment] 2023-08-11 05:52
No, definitely not installed with `c` parser. But from my end, I can see that some areas does lead to more lagging than others, but I can open the whole file normally

**Comment by lucario387** [comment] 2023-08-11 05:53
Ah okay, The problem is with `cpp` parser actually, because `.h` files are actually cpp files. I now experience some more latency while moving around with its filetype not set to `c`

**Comment by dhananjaylatkar** [comment] 2023-08-11 05:57
Yep. After uninstalling `cpp` parser, file opens properly.

**Comment by lucario387** [comment] 2023-08-11 05:59
But still, I did not reach the `hangs` state for nvim, only `takes about 300ms more to open file` for nvim

**Comment by dhananjaylatkar** [comment] 2023-08-11 06:02
Weird. It hangs indefinitely for me.
I'm on nvim stable, let me try nighlty

**Comment by dhananjaylatkar** [comment] 2023-08-11 06:05
Same issue with nvim nightly :(

**Comment by waynecw** [comment] 2023-08-11 22:26
I can open the `bpf.h` but the highlighter was broken with the error message
```
treesitter/highlighter: Error executing lua: ...2809/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node
```

**Comment by lucario387** [comment] 2023-08-12 15:57
Does it get any better today on nightly @dhananjaylatkar ? Neovim just has a better injection handler PR merged today, can you try to see if the editing experience is any less miserable?

**Comment by dhananjaylatkar** [comment] 2023-08-16 04:22
Hey @lucario387 
Yes, I'm able to open this file on latest nvim nightly. 
Thanks a lot!

**Comment by lucario387** [comment] 2023-08-16 04:25
I am in no position to be credited for that 
All goes to @lewis6991

**Closed by lucario387** 2023-08-16 04:25 UTC
Labels: bug
