### ISSUE TITLE
Unresponsive nvim when typing quotes with new lua module

### ISSUE THREAD

**Issue by natecraddock** [nvim-treesitter/nvim-treesitter#2305] opened 2022-01-20 02:42 UTC
### Describe the bug

Typing specific sequences of characters causes nvim to freeze with the latest lua parser merged in c80715f883b8c7963782973b23297c5dec7924be. Specifically when I enter a `"` nvim becomes unresponsive and I am required to kill the process.

### To Reproduce

Type one of the following (there may be more):

```lua
a(b, "
a = b("", "
a.b(c, "
```

Note the freeze occurs when typing the `"` character. Also a string like `(b, "")` is fine.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.2 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.3.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - zig            ✓ . ✓ ✓ ✓ 
  - svelte         ✓ . ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - markdown       ✓ . ✓ . ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.7.0-dev+906-gde6f9233e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az32-122

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

I discovered this on 0.6.1, and downloaded the latest appimage to test on master. I have only enabled highlights from treesitter.

Reverting to 668de09 removes the issue.

Disabling buffer highlights also prevents the issue.

**Comment by theHamsta** [comment] 2022-01-20 07:21
@MunifTanjim

**Comment by clason** [comment] 2022-01-20 08:00
Can't reproduce; please always test with (and share!) a minimal config.

**Comment by MunifTanjim** [comment] 2022-01-20 09:29
With `a.b(c, "` at the end of file, tree-sitter is stuck in infinite loop for error recovery 🤕

```
recover_with_missing symbol:string_end, state:28
process version:0, version_count:6, state:0, row:1, col:8
lex_external state:1, row:1, column:8
  consume character:' '
lex_internal state:0, row:1, column:8
  skip character:' '
  skip character:10
lexed_lookahead sym:end, size:2
recover_to_previous state:55, depth:3
process version:1, version_count:7, state:230, row:1, col:8
no_lookahead_after_non_terminal_extra
reduce sym:comment, child_count:1
lex_external state:4, row:1, column:8
  consume character:' '
lex_internal state:0, row:1, column:8
  skip character:' '
  skip character:10
lexed_lookahead sym:end, size:2
detect_error
process version:2, version_count:7, state:28, row:1, col:8
lex_external state:2, row:1, column:8
lex_internal state:0, row:1, column:8
  skip character:' '
  skip character:10
lexed_lookahead sym:end, size:2
reduce sym:string, child_count:2
detect_error
process version:3, version_count:7, state:30, row:1, col:8
reduce sym:expression, child_count:1
detect_error
process version:4, version_count:7, state:57, row:1, col:8
reduce sym:_expression_list_repeat1, child_count:2
detect_error
process version:5, version_count:7, state:143, row:1, col:8
reduce sym:_expression_list, child_count:2
detect_error
process version:6, version_count:7, state:55, row:1, col:8
reduce sym:_expression_list, child_count:1
detect_error
resume version:0
recover_with_missing symbol:string_end, state:28
process version:0, version_count:6, state:0, row:1, col:8
lex_external state:1, row:1, column:8
  consume character:' '
lex_internal state:0, row:1, column:8
  skip character:' '
  skip character:10
lexed_lookahead sym:end, size:2
recover_to_previous state:55, depth:3
process version:1, version_count:7, state:230, row:1, col:8
no_lookahead_after_non_terminal_extra
reduce sym:comment, child_count:1
lex_external state:4, row:1, column:8
  consume character:' '
lex_internal state:0, row:1, column:8
  skip character:' '
  skip character:10
lexed_lookahead sym:end, size:2
detect_error
process version:2, version_count:7, state:28, row:1, col:8
lex_external state:2, row:1, column:8
lex_internal state:0, row:1, column:8
  skip character:' '
  skip character:10
lexed_lookahead sym:end, size:2
reduce sym:string, child_count:2
detect_error
process version:3, version_count:7, state:30, row:1, col:8
reduce sym:expression, child_count:1
detect_error
process version:4, version_count:7, state:57, row:1, col:8
reduce sym:_expression_list_repeat1, child_count:2
detect_error
process version:5, version_count:7, state:143, row:1, col:8
reduce sym:_expression_list, child_count:2
detect_error
process version:6, version_count:7, state:55, row:1, col:8
reduce sym:_expression_list, child_count:1
detect_error
resume version:0
recover_with_missing symbol:string_end, state:28
process version:0, version_count:6, state:0, row:1, col:8
lex_external state:1, row:1, column:8
  consume character:' '
lex_internal state:0, row:1, column:8
  skip character:' '
  skip character:10
lexed_lookahead sym:end, size:2
recover_to_previous state:55, depth:3
process version:1, version_count:7, state:230, row:1, col:8
no_lookahead_after_non_terminal_extra
reduce sym:comment, child_count:1
lex_external state:4, row:1, column:8
  consume character:' '
lex_internal state:0, row:1, column:8
  skip character:' '
  skip character:10
lexed_lookahead sym:end, size:2
detect_error
process version:2, version_count:7, state:28, row:1, col:8
lex_external state:2, row:1, column:8
lex_internal state:0, row:1, column:8
  skip character:' '
  skip character:10
lexed_lookahead sym:end, size:2
reduce sym:string, child_count:2
detect_error
process version:3, version_count:7, state:30, row:1, col:8
reduce sym:expression, child_count:1
detect_error
process version:4, version_count:7, state:57, row:1, col:8
reduce sym:_expression_list_repeat1, child_count:2
detect_error
process version:5, version_count:7, state:143, row:1, col:8
reduce sym:_expression_list, child_count:2
detect_error
process version:6, version_count:7, state:55, row:1, col:8
reduce sym:_expression_list, child_count:1
detect_error
resume version:0
recover_with_missing symbol:string_end, state:28
process version:0, version_count:6, state:0, row:1, col:8
lex_external state:1, row:1, column:8
  consume character:' '
lex_internal state:0, row:1, column:8
  skip character:' '
  skip character:10
lexed_lookahead sym:end, size:2
recover_to_previous state:55, depth:3
process version:1, version_count:7, state:230, row:1, col:8
no_lookahead_after_non_terminal_extra
reduce sym:comment, child_count:1
lex_external state:4, row:1, column:8
  consume character:' '
lex_internal state:0, row:1, column:8
  skip character:' '
  skip character:10
lexed_lookahead sym:end, size:2
detect_error
process version:2, version_count:7, state:28, row:1, col:8
lex_external state:2, row:1, column:8
lex_internal state:0, row:1, column:8
  skip character:' '
  skip character:10
lexed_lookahead sym:end, size:2
reduce sym:string, child_count:2
detect_error
process version:3, version_count:7, state:30, row:1, col:8
reduce sym:expression, child_count:1
detect_error
process version:4, version_count:7, state:57, row:1, col:8
reduce sym:_expression_list_repeat1, child_count:2
detect_error
process version:5, version_count:7, state:143, row:1, col:8
reduce sym:_expression_list, child_count:2
detect_error
process version:6, version_count:7, state:55, row:1, col:8
reduce sym:_expression_list, child_count:1
detect_error
resume version:0
recover_with_missing symbol:string_end, state:28
process version:0, version_count:6, state:0, row:1, col:8
lex_external state:1, row:1, column:8
  consume character:' '
lex_internal state:0, row:1, column:8
  skip character:' '
  skip character:10
lexed_lookahead sym:end, size:2
recover_to_previous state:55, depth:3
process version:1, version_count:7, state:230, row:1, col:8
no_lookahead_after_non_terminal_extra
reduce sym:comment, child_count:1
lex_external state:4, row:1, column:8
  consume character:' '
lex_internal state:0, row:1, column:8
  skip character:' '
  skip character:10
lexed_lookahead sym:end, size:2
detect_error
process version:2, version_count:7, state:28, row:1, col:8
lex_external state:2, row:1, column:8
lex_internal state:0, row:1, column:8
  skip character:' '
  skip character:10
lexed_lookahead sym:end, size:2
reduce sym:string, child_count:2
detect_error
process version:3, version_count:7, state:30, row:1, col:8
reduce sym:expression, child_count:1
detect_error
process version:4, version_count:7, state:57, row:1, col:8
reduce sym:_expression_list_repeat1, child_count:2
detect_error
process version:5, version_count:7, state:143, row:1, col:8
reduce sym:_expression_list, child_count:2
detect_error
process version:6, version_count:7, state:55, row:1, col:8
reduce sym:_expression_list, child_count:1
```

**Comment by clason** [comment] 2022-01-20 09:30
Ah, it has to be the _end_ of the file.

**Comment by clason** [comment] 2022-01-20 09:32
Yeah, the old parser (rather, scanner) explicitly checked for end of file: https://github.com/nvim-treesitter/tree-sitter-lua/blob/6f5d40190ec8a0aa8c8410699353d820f4f7d7a6/src/scanner.cc#L106

**Comment by MunifTanjim** [comment] 2022-01-20 09:54
Found the fix. Although, not sure why the fix works 🤷🏼‍♂️ One of those tree-sitter weirdness, I guess.

Anyway, here's the fix: https://github.com/MunifTanjim/tree-sitter-lua/pull/2

**Comment by MunifTanjim** [comment] 2022-01-20 10:20
Fixed in https://github.com/MunifTanjim/tree-sitter-lua/commit/470817132d7bb7532de34de06e70f3978f245397

**Closed** 2022-01-20 18:21 UTC
Labels: bug

**Comment by natecraddock** [comment] 2022-01-20 18:31
Thanks for the fast fix and the great plugin, y'all are the best!
