### ISSUE TITLE
highlight bug

### ISSUE THREAD

**Issue by Leviathans** [nvim-treesitter/nvim-treesitter#3965] opened 2022-12-12 23:41 UTC
### Describe the bug

when I edit file ,display some errors and I have run :TSUpdate but still not work

### To Reproduce

install nvim-treesitter/nvim-treesitter

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v19.2.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 14.0.0 (clang-1400.0.29.202)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "arm64",
  release = "22.1.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000"
}

## Parser/Features H L F I J
  - vim            x ✓ ✓ . ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - toml           ✓ ✓ ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - help           x . . . x

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: vim(highlights): ...im/0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
    vim(highlights) is concatenated from the following files:
    | [ERROR]:"/Users/jj/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/vim/highlights.scm", failed to load: ...im/0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
  - ERROR: help(highlights): ...im/0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 100 for language help
    help(highlights) is concatenated from the following files:
    | [ERROR]:"/Users/jj/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/help/highlights.scm", failed to load: ...im/0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 100 for language help
  - ERROR: help(injections): ...im/0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 14 for language help
    help(injections) is concatenated from the following files:
    | [ERROR]:"/Users/jj/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/help/injections.scm", failed to load: ...im/0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 14 for language help
```

### Output of `nvim --version`

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.1/share/nvim"

Run :checkhealth for more info
```

**Comment by BBboy01** [comment] 2022-12-13 01:44
same problem

**Comment by LegendaryPredz** [comment] 2022-12-13 03:02
I got the same error as well

**Comment by Ivan-Sanchez-Diaz** [comment] 2022-12-13 03:53
same here!

**Comment by clason** [comment] 2022-12-13 05:12
Duplicate of #3092

**Closed by clason** 2022-12-13 05:12 UTC
Labels: bug
