### ISSUE TITLE
Bug: Invalid node type "heredoc_end"

### ISSUE THREAD

**Issue by ad-chaos** [nvim-treesitter/nvim-treesitter#5346] opened 2023-09-03 13:28 UTC
### Describe the bug

nvim-treesitter errors when opening `builtin.txt` with the vimdoc parser with `highlight.enable = true` with the following error

```
Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...t/neovim/share/nvim/runtime/lua/vim/treesitter/query.lua:273: Query error at 9:4. Invalid node type "heredoc_end":
  (heredoc_end) @injection.language)
   ^

stack traceback:
        [C]: in function '_ts_parse_query'
        ...t/neovim/share/nvim/runtime/lua/vim/treesitter/query.lua:273: in function 'parse'
        ...t/neovim/share/nvim/runtime/lua/vim/treesitter/query.lua:232: in function 'get'
        ...m/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:131: in function 'new'
        ...m/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:495: in function 'add_child'
        ...m/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:383: in function '_add_injections'
        ...m/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:435: in function 'parse'
        ...im/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:325: in function <...im/share/nvim/runtime/lua/vim/treesitter/highlighter.l
ua:320>
```

### To Reproduce

```lua
-- minimal.lua
for name, url in pairs{
  nvim_treesitter = 'https://github.com/nvim-treesitter/nvim-treesitter'
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require('nvim-treesitter.configs').setup({
   highlight = { enable = true }
})
```

```bash
nvim --clean -u minimal.lua +'h builtin.txt
```

### Expected behavior

No error

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.5.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "22.5.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . x
  - c                   ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR bash(injections): ...t/neovim/share/nvim/runtime/lua/vim/treesitter/query.lua:273: Query error at 9:4. Invalid node type "heredoc_end":
    (heredoc_end) @injection.language)
     ^
  
  bash(injections) is concatenated from the following files:
  | [ERROR]:"/private/tmp/nvim_issue/nvim_treesitter/queries/bash/injections.scm", failed to load: ...t/neovim/share/nvim/runtime/lua/vim/treesitter/query.lua:273: Query error at 9:4. Invalid node type "heredoc_end":
    (heredoc_end) @injection.language)
     ^
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-1030+ge7ab9f379
Build type: Release
LuaJIT 2.1.1693350652
```

### Additional context

Though the checkhealth output suggests I need to run `TSUpdate vimdoc`, the error remains even after doing that

**Comment by clason** [comment] 2023-09-03 13:30
Duplicate of #3092

**Comment by clason** [comment] 2023-09-03 13:30
Bash is the culprit, as the check health indicates.

**Closed by clason** 2023-09-03 13:30 UTC
Labels: bug

**Comment by ad-chaos** [comment] 2023-09-03 13:34
Ah, it never occured to me to install the bash parser 🤦‍♂️ . `TSInstall bash` fixes it.

**Comment by debdutdeb** [comment] 2024-01-02 04:51
> Ah, it never occured to me to install the bash parser 🤦‍♂️ . `TSInstall bash` fixes it.

Still happening for me, I already had bash installed

**Comment by anoduck** [comment] 2025-05-10 23:32
#3092 Fixed it for me. Removed `/usr/local/lib/nvim/parser` and `/usr/local/share/nvim/runtime/queries`. 

These directories existed due to compiling nvim from source. After, their removal, everything works as it should.
