### ISSUE TITLE
treesitter/highlighter invalid node type as position 4348 for language c_sharp

### ISSUE THREAD

**Issue by mezdelex** [nvim-treesitter/nvim-treesitter#4039] opened 2022-12-26 13:28 UTC
### Describe the bug

Ran PackerSync, Mason omnisharp update and TSUpdateSync.

After doing that, every other language that I've tried (lua, ts, vue, rust) are ok but with csharp this happens.

![image](https://user-images.githubusercontent.com/59997405/209553122-4cf2939c-685a-4258-a447-d740aab2d557.png)

### To Reproduce

1. Update lsp for csharp, update treesitter parser for csharp, update Packer.
2. Open any .cs file
3. Highlighting throws described error.

### Expected behavior

To be highlighted properly as before.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.19.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: gcc (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders) 12.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "10.0.22000",
  sysname = "Windows_NT",
  version = "Windows 10 Pro"
}

## Parser/Features         H L F I J
  - yaml                ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - c_sharp             x ✓ ✓ . ✓
  - gitignore           ✓ . . . .
  - help                ✓ . . . ✓
  - json5               ✓ . . . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . . . .
  - markdown            ✓ . ✓ . ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - vim                 ✓ ✓ ✓ . ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - dockerfile          ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - c                   ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - vue                 ✓ . ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - jsonc               ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: c_sharp(highlights): ...\current\share\nvim\runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 4348 for language c_sharp
    c_sharp(highlights) is concatenated from the following files:
    | [ERROR]:"C:\Users\Mezdelex\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\c_sharp\highlights.scm", failed to load: ...\current\share\nvim\runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 4348 for language c_sharp
```

### Output of `nvim --version`

```text
NVIM v0.8.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az30-11

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment] 2022-12-26 13:29
Duplicate of #3092

**Closed by clason** 2022-12-26 13:29 UTC
Labels: bug
