### ISSUE TITLE
`treesitter/highlighter: Error executing lua: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua`

### ISSUE THREAD

**Issue by nicowilliams** [nvim-treesitter/nvim-treesitter#4054] opened 2022-12-29 05:05 UTC
### Describe the bug

Using `init.lua` from https://github.com/nvim-lua/kickstart.nvim with nvim 0.8.1 (stable) I get this:
![image](https://user-images.githubusercontent.com/604851/209904548-236980bb-c30b-45d2-bfec-3427467616b4.png)

I have:

- not updated neovim to latest master -- is that really necessary?
- the plugin was installed by kickstart.nvim
- I have run `:TSUpdate`
- I have read the troubleshooting section
- I have checked that `/usr/share/nvim/runtime/lua/vim/treesitter/query.lua` exists

I'm a VIM user with much experience, but totally new to neovim.  Maybe I shouldn't have tried kickstarter?

### To Reproduce

1. Install nvim stable from PPA or .deb for Ubuntu 21.04, which means I get 0.8.1.
2. `mkdir -p .config/nvim && curl -Lo .config/nvim/init.lua https://raw.githubusercontent.com/nvim-lua/kickstart.nvim/master/init.lua`
3. `nvim ~/.config/nvim/init.lua`
4. Immediately observe the error as shown in the screenshot.

### Expected behavior

No error to be displayed, or some way to get the details of the error (so that I might fix it), or some way to make the error go away.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
  ========================================================================
  ## Installation
    - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)     - WARNING: `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
    - OK: `git` executable found.
    - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }                                                  Version: cc (Ubuntu 11.2.0-7ubuntu2) 11.2.0
    - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.
                                                                                                                                           ## OS Info:
  {
    machine = "x86_64",
    release = "5.13.0-52-generic",
    sysname = "Linux",
    version = "#59-Ubuntu SMP Wed Jun 15 20:17:13 UTC 2022"
  }

  ## Parser/Features         H L F I J
    - vim                 x ✓ ✓ . ✓
    - go                  ✓ ✓ ✓ ✓ ✓
    - lua                 ✓ ✓ ✓ ✓ ✓
    - c                   ✓ ✓ ✓ ✓ ✓
    - cpp                 ✓ ✓ ✓ ✓ ✓
    - typescript          ✓ ✓ ✓ ✓ ✓
    - help                ✓ . . . ✓
    - python              ✓ ✓ ✓ ✓ ✓
    - rust                ✓ ✓ ✓ ✓ ✓

    Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
           +) multiple parsers found, only one will be used
           x) errors found in the query, try to run :TSUpdate {lang}

  ## The following errors have been detected:
    - ERROR: vim(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for        language vim
      vim(highlights) is concatenated from the following files:
      | [ERROR]:"/home/nico/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/vim/highlights.scm", failed to load: /usr/        share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
```

Aha, finally some detail.  In `query.lua` at `219` we see:

```
212 function M.parse_query(lang, query)
213   language.require_language(lang)
214   local cached = query_cache[lang][query]
215   if cached then
216     return cached
217   else
218     local self = setmetatable({}, Query)
219     self.query = vim._ts_parse_query(lang, query)
220     self.info = self.query:inspect()
221     self.captures = self.info.captures
222     query_cache[lang][query] = self
223     return self
224   end
225 end
```

though idk why that would be an error.
```


### Output of `nvim --version`

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az178-366

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```
```


### Additional context

Total newbie to neovim, but long long time vim user trying out neovim.

**Comment by juangpc** [comment] 2022-12-29 06:40
Same here. 
After uninstalling ```help``` and ```vim``` parsers, it seems to churn.

**Comment by Guzzii** [comment] 2022-12-29 09:07
Same issue. I don't even have the help and vim parser installed in the first place

**Comment by clason** [comment] 2022-12-29 10:09
Duplicate of #3092

**Closed by clason** 2022-12-29 10:09 UTC
Labels: bug

**Comment by syeo66** [comment] 2022-12-29 13:12
Sorry, I am not okay with this just being closed since I feel this is a different issue and there are probably many more people having this issue despite (or maybe because) having everything updated (as I do). I already did everything mentioned in #3092 without resolution. I think this needs some closer look.

**Comment by clason** [comment] 2022-12-29 13:17
It's really not a different issue: `:checkhealth` clearly shows that the `vim` queries are not compatible with the parser that is used. This can have different causes, depending on how exactly your config is set up, which is impossible to diagnose from here. Hence the linked issue gives you the tools to figure this out.

In a nutshell, you need to make sure that you are either
* using parsers **and** queries shipped with nvim-treesitter 
* using parsers **and** queries bundled with Neovim.

If you mix and match, you get exactly the error reported here.

**Comment by clason** [comment] 2022-12-29 13:18
And if this happens with `kickstart.nvim` out of the box, that means it's not setting things up correctly, and the problem should be reported there.

**Comment by nicowilliams** [comment] 2022-12-29 18:07
Thank you all!
