### ISSUE TITLE
indent (php) dont correct indent php embedded in html code #neovim#nvim

### ISSUE THREAD

**Issue by truongtd94** [nvim-treesitter/nvim-treesitter#4652] opened 2023-04-14 05:54 UTC
### Describe the bug

when I put php opening tag in html code it automatically jumps to the beginning of the line, i want the php code to be at the same level as the html code.
Broblem Images:
https://github.com/truongtd94/errors/blob/master/2023-04-14_12-38.png
https://github.com/truongtd94/errors/blob/master/2023-04-14_12-39.png

### To Reproduce

1. Write php embedded in html tag
2. It automatically jumps to the beginning of the line
3. Finally, Format it with phpcsfixer, wrong indentation.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.14.2 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Debian 10.2.1-6) 10.2.1 20210110
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "5.10.0-21-amd64",
  sysname = "Linux",
  version = "#1 SMP Debian 5.10.162-1 (2023-01-21)"
}

## Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - comment             ✓ . . . .
  - css                 ✓ . ✓ ✓ ✓
  - dart                ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ . ✓
  - markdown_inline     ✓ . . . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - phpdoc              ✓ . . . .
  - query               ✓ ✓ ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ .
  - sql                 ✓ . . . ✓
  - vim                 ✓ ✓ ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
v8.1
```

**Comment by lucario387** [comment] 2023-04-14 06:36
Can you show `:InspectTree` of that code section?
And the second image attached to this issue does not have any relations to nvim-treesitter

**Comment by lucario387** [comment] 2023-04-14 06:39
![image](https://user-images.githubusercontent.com/29790821/231962859-f63160d4-fd1f-4344-b1ef-d785efbb74b2.png)

From `:InspectTree`, this shows that php does not get recognized at all in html files, as can be seen by the `(ERROR)` node. So I don't think it's possible to be supported

**Comment by lucario387** [comment] 2023-04-14 06:48
Please disable other php plugins for nvim-treesitter issues, as this isn't a problem with treesitter, but rather other plugins' faults

**Comment by truongtd94** [comment] 2023-04-14 07:10
I already restore to defaults, but wrong indentation
https://github.com/truongtd94/errors/blob/master/2023-04-14_14-08.png

**Comment by lucario387** [comment] 2023-04-14 07:12
Just from that picture i don't see where it's wrong at tbf

**Comment by truongtd94** [comment] 2023-04-14 07:13
https://github.com/truongtd94/errors/blob/master/2023-04-14_14-12.png

**Comment by lucario387** [comment] 2023-04-14 07:14
Also, from your picture, there's highlighting for php codeblocks inside `.html` files, even though in nvim-treesitter's code, there's no injections for it?
https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/html_tags/injections.scm

So this is really not this repo's/plugin's fault whatsoever

**Comment by lucario387** [comment] 2023-04-14 07:33
The image just means there's error elsewhere in your code (Where exactly I cannot know) that leads to that issue
Please post the whole code as well, it's hard to reproduce this issue.
And I don't see why `php-cs-fixer` is related to this? If it's the problem with php-cs-fixer indenting improperly, then it's not related here

**Comment by truongtd94** [comment] 2023-04-14 07:38
error occurred while embedding html code in php file
https://github.com/truongtd94/errors/blob/master/2023-04-14_14-35.png

**Comment by lucario387** [comment] 2023-04-14 07:44
so is the problem with php code in html files, or the other way around (for this issue only)

**Comment by lucario387** [comment] 2023-04-14 07:46
Duplicate of #2565

**Closed** 2023-04-14 07:46 UTC
Labels: bug, duplicate
