### ISSUE TITLE
Text in HTML file becomes white when scrolling through them

### ISSUE THREAD

**Issue by SleepyCatOnTheBed** [nvim-treesitter/nvim-treesitter#1702] opened 2021-08-16 04:42 UTC
https://user-images.githubusercontent.com/71932200/129512238-d7ad1d60-5662-4e52-95ff-a918c4396a13.mp4

The text become white after i scroll through them, i know whether this is a treesitter bug or not. But it only happens when i installed the tree sitter html parser.

**Comment by vigoux** [comment] 2021-08-16 07:28
This seems to be a tree-sitter issue, we will try to debug that.

Could you provide a file to reproduce the issue ?

**Comment by stsewd** [comment] 2021-08-16 14:44
This look like a duplicate of https://github.com/nvim-treesitter/nvim-treesitter/issues/1506, there is a patch on neovim to fix this.

**Comment by SleepyCatOnTheBed** [comment] 2021-08-17 02:31
Sorry for such a late reply, i tried to reinstalled treesitter and my colorscheme. Everything is working fine now.
The colorscheme i used when getting this bug was gruvbox-material.

In case, you need the files for debugging:
[HTML_files.zip](https://github.com/nvim-treesitter/nvim-treesitter/files/6996604/HTML_files.zip)

Thank you for your helps.

**Closed** 2021-08-20 17:16 UTC

**Comment by biggiesmallsAG** [comment] 2021-08-23 00:20
@stsewd hey mate, i tried your fix-skipping-matches patch, still have exactly the same issue as Sleepycat, its literally ONLY html files that this happens on... i do a lot of dev in angular, here is a prime example of it not working..

```
<div class="clr-row clr-justify-content-center">
  <form class="clr-form clr-form-compact">
    <div class="clr-col-1" *ngIf="clientId$ | async as routedClient">
      <clr-select-container>
        <label>Client</label>
        <select
          clrSelect
          name="clientid"
          [ngModel]="routedClient"
          (ngModelChange)="clientid($event)"
        >
          <option
            *ngFor="let client of clients$ | async"
            [ngValue]="client.id"
            [selected]="routedClient === client.id"
          >
            {{ client.client_name }}
          </option>
        </select>
      </clr-select-container>
    </div>
    <div class="clr-col-1" *ngIf="clientsProjects$ | async as projects">
      <clr-select-container>
        <label>Project</label>
        <select
          clrSelect
          name="projectid"
          [ngModel]="projectId$ | async"
          (ngModelChange)="projectid($event)"
        >
          <option [selected]="true"></option>
          <option *ngFor="let project of projects" [ngValue]="project.id">
            {{ project.project_name }}
          </option>
        </select>
      </clr-select-container>
    </div>
  </form>
</div>

```

**Comment by biggiesmallsAG** [comment] 2021-08-23 00:25
@stsewd with playground - https://imgur.com/a/87po5wz
