### ISSUE TITLE
Enable javascript highlighting for .vue files

### ISSUE THREAD

**Issue by ChristianChiarulli** [nvim-treesitter/nvim-treesitter#650] opened 2020-11-14 03:43 UTC
Could you enable javascript highlighting for .vue files?

It seems to look fine for now.

![image](https://user-images.githubusercontent.com/29136904/99138808-6bc7a180-2601-11eb-9c1f-d502720e9896.png)

If not is there an easy way to override .vue files to use js that I'm ignorant of?

**Comment by theHamsta** [comment] 2020-11-15 10:44
Could you try to add `used_by` to the js/typescript server (in parser.lua). Like "c++" is used_by "cuda".

**Comment by ChristianChiarulli** [comment] 2020-11-16 04:23
That works, with one small issue that it picks up the bottom script tag as TSStringRegex. 

![image](https://user-images.githubusercontent.com/29136904/99212284-b29bcf80-2798-11eb-9f2c-e7a660e8f59e.png)

Should I put a PR in for this? I think it's certainly a good start for people using Vue.

**Comment by kyazdani42** [comment] 2020-11-16 06:29
a bigger issue is that i think it takes the vue html part as react components. I'm not sure how it's been handled for angular which has a similar syntax.
 @steelsojka what do you think ? im not that familiar with vue and these kinds of frontend frameworks.

**Comment by Steadyx** [comment] 2020-11-16 09:29
How would it handle different templates and css preprocessors? I believe you can change the style tag from regular css to sass as well as scss. The script tag can be changed to typescript by using the attribute lang="ts". The template can be changed to pug as well. I've been playing around with the language injection in vue files but so far there is only a parser for css, not sure how I would be able to switch from javascript to typescript depending not the lang attribute.

**Comment by kyazdani42** [comment] 2020-11-16 15:11
maybe vue would need it's own parser. And it could inject stuff like javascript or typescript

**Comment by vigoux** [comment] 2021-01-04 07:48
So that we move on here : there is a vue parser -> https://github.com/ikatyang/tree-sitter-vue

**Comment by 3nuc** [comment] 2021-01-09 07:32
I can't get highlighting to work in the <script> tag with tree-sitter-vue. Anybody have the same problem?
![image](https://user-images.githubusercontent.com/5359825/104086108-25836d00-5255-11eb-8738-5237c2197cc0.png)

**Comment by Steadyx** [comment] 2021-01-11 11:20
@3nuc I did something a little hacky but if you know where your package is installed you can check this with the command ':set runtimepath' in vim, it should print out locations to all your plugins. Find where treesitter is installed. Your going to want to create a vue folder in queries and then inside the vue folder create a file called injections.scm. Add the following code to that file: 

`(script_element 
  (raw_text) @javascript)
`

Next you're going to want to go and create another file in the vue folder called highlights.scm. In there just create some queries for highlighting. You can find all the info to do that in the contributing.md, you'll have to see how the parser represents the vue file which you can do with treesitter-playground. Hope this helps!!

**Comment by antaxiom** [comment] 2021-01-25 14:53
What about .svelte support? Svelte purely has javascript in the `script` tag, with the rest being html except for some small stuff like what's implemented in vim-svelte (eg. #if, /if, #each and /each, on:click).

**Comment by steelsojka** [comment] 2021-01-25 15:10
@antaxiom You would have to have a specific parser to handle the svelte templating and use injections for the javascript portion. Vue is pretty easy because it's just three sections of html with injections, and might be able to just use the existing html parser. Svelte would require it's own syntax parser.

**Comment by antaxiom** [comment] 2021-01-25 15:14
How bad would that be to write? I could consider doing it myself, although
I don't write vim plugins.

**Comment by steelsojka** [comment] 2021-01-25 16:17
You wouldn't have to write a vim plugin. You just need to write the parser grammer. I would go off of this https://tree-sitter.github.io/tree-sitter/creating-parsers#writing-the-grammar

**Comment by kyazdani42** [comment] 2021-01-25 16:21
you could fork the html parser and add svelte templating to it, am i right @steelsojka ?

**Comment by antaxiom** [comment] 2021-01-25 17:13
This seems pretty useful but I don't fully understand it well. I'd need
someone I could ask to help me out with that.

**Comment by vigoux** [comment] 2021-01-26 12:47
@antaxiom I would suggest reaching out to Zulip, so that we can discuss more interactively and guide you through your work.

**Comment by antaxiom** [comment] 2021-01-26 21:26
Great, I'll work on it when I can. If I don't report anything in a week
(not unlikely) feel free to post on here again to remind me.

**Comment by ht55ght55** [comment] 2021-02-19 15:45
I'm also interested in working on the Svelte parser if I can get some guidance.  @antaxiom, have you made any headway in the past few weeks?  Maybe we can work together?

**Comment by antaxiom** [comment] 2021-02-19 15:54
I have made 0 headway in the psat weeks, I totally expected for this to
happen, but I'm still impressed. I would like to work together. What would
be the best contact method for this (without exposing it on this gh issue)?
I have no experience in making a parser, but I think I can figure it out
with help.

**Comment by dagadbm** [comment] 2021-04-08 17:05
im confused. https://github.com/ikatyang/tree-sitter-vue isnt this what  you are looking for? its also linked in  the  README.

I  do notice that  the  colors  are a bit weird (but  im also not usinng  a treesitter specific  color  scheme. im  using onedark)

So I  always thought that was the  issue

**Comment by cloggier** [comment] 2021-04-08 17:07
I believe this was before tree-sitter-vue was integrated. Shouldn't that issue be closed now?

**Comment by 3nuc** [comment] 2021-04-08 17:18
Yeah this should be closed.

I wrote my earlier comment when tree-sitter-vue was already a thing.
For the future: At that time I didn't have highlighting because tree-sitter-vue expects you to have all the sub-parsers TSInstalled. So you can't just `:TSInstall vue` and expect things to work. You have to `:TSInstall vue javascript typescript html css`

**Comment by cloggier** [comment] 2021-04-08 17:26
There isn't one just yet, pretty soon it might change thanks to @elianiva in #1109.

**Comment by vigoux** [comment] 2021-04-14 14:11
I think this issue can be closed now ?, Could you confirm by closing if that's the case ?

**Comment by dagadbm** [comment] 2021-04-14 14:33
For me what doesnt work is the comments on the scss files and vue
components. SO im guessing its a bug on the  scss parser?

**Comment by vigoux** [comment] 2021-04-14 14:37
What do you mean by that, are they now highlighted ?

**Comment by dagadbm** [comment] 2021-04-15 08:03
They are not highlighted as comments but as normal text (its white) really
destroys the whole color scheme but I'm assuming this is related to scss
tree sitter and not really vue related

**Comment by elianiva** [comment] 2021-04-15 09:49
Could you give the code snippet? Seems like the parser failed to parse the code.

**Comment by dagadbm** [comment] 2021-04-15 10:10
[image: image.png]
for example
this is the top of the  file .scss extension

**Comment by 3nuc** [comment] 2021-04-15 12:44
@elianiva 
![image](https://user-images.githubusercontent.com/5359825/114870916-00c10780-9df9-11eb-9544-6fb0135d225e.png)

Seems like it gets lost when you type "or". If you change the var name ot $colar-something: red; it's fine.

**Comment by cloggier** [comment] 2021-04-15 13:11
that seems like it's using css parser rather than scss. Did you install scss one?

**Comment by elianiva** [comment] 2021-04-15 13:19
I'm guessing [this is the culprit](https://github.com/elianiva/tree-sitter-scss/blob/b2407613f3804d0db15ae6f9f49cf2e759f06dba/grammar.js#L296)

**Comment by 3nuc** [comment] 2021-04-15 20:51
I had some stale `scss.so` files in ~/.treesitter/bin. `rm -rf ~/.treesitter` did the trick. Thank you for your help and making scss highlighting happen.

<details>
<summary>more verbose info in case someone comes across this in 3 years</summary>
I had some stale scss.so file in `~/.treesitter/bin`. I noticed the highlighting worked fine if I had a fresh clone of tree-sitter-scss repo that I ran `tree-sitter generate in`. That clone needs to be in a folder specified in `~/.treesitter/config.json`. The tree-sitter-scss had to be in a folder from ~/.treesitter/config.json.
</details>

**Comment by 3nuc** [comment] 2021-04-15 22:05
Edited my previous comment with playground now that @cloggier confirmed that it also happens on his side.

I feel like we should open a separate issue and I can report it properly, but do I open it in this repo or @elianiva could allow opening issues in his fork?

**Comment by elianiva** [comment] 2021-04-15 22:15
you should open it upstream (the original ts-scss repo), mine is just a fork with 0.19 regenerated version

**Comment by 3nuc** [comment] 2021-04-17 10:09
Opened the issue in tree-sitter-vue as it's more of a vue/tree-sitter specific issue.

For now, just :TSUninstall css (and make sure you don't have css parser in ensure_installed in your init.vim/init.lua)

**Comment by cloggier** [comment] 2021-04-17 10:11
But then there will be no css tree sitter functionalities, or is scss order capable of parsing css too?

**Comment by elianiva** [comment] 2021-04-17 10:16
it's capable of parsing css, too

**Comment by cloggier** [comment] 2021-04-17 10:31
Awesome, so there really isn't a need to keep both installed, is that correct?

**Comment by elianiva** [comment] 2021-04-17 10:52
same reason with JS/TS, you'd want both of them installed if you want "the correct" highlighting, i.e you'd get error node if you use TS syntax in JS file, same goes with valid SCSS syntax in CSS file.

If you're OK with this, then yes, you can just install SCSS parser and use it for both CSS and SCSS

**Closed** 2023-02-13 16:53 UTC
Labels: enhancement
