### ISSUE TITLE
java query error with vim.lsp.buf.signature_help()

### ISSUE THREAD

**Issue by wenjinnn** [nvim-treesitter/nvim-treesitter#6649] opened 2024-05-17 08:42 UTC
### Describe the bug

treesitter parse error when runing `:lua vim.lsp.buf.signature_help()`
error message:
```
Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...1390/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 17:2. Invalid node type "condition":
(condition
 ^

stack traceback:
        [C]: in function '_ts_parse_query'
        ...1390/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
        ...1471390/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
        ...1471390/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get_query'
        ...y/rainbow-delimiters.nvim/lua/rainbow-delimiters/lib.lua:78: in function 'get_query'
        ...limiters.nvim/lua/rainbow-delimiters/strategy/global.lua:191: in function 'thunk'
        .../rainbow-delimiters.nvim/lua/rainbow-delimiters/util.lua:33: in function 'for_each_child'
        ...limiters.nvim/lua/rainbow-delimiters/strategy/global.lua:187: in function 'setup_parser'
        ...limiters.nvim/lua/rainbow-delimiters/strategy/global.lua:266: in function 'cb'
        ...r/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:8
```

### To Reproduce

1. setup with java jdtls LSP, in my case, I use the plugin `nvim-jdtls`.
2. open nvim with a java file, wait for jdtls finish the startup process.
3. write or point cursor at some function, run `:lua vim.lsp.buf.signature_help()`, and you'll see this issue.
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/30885216/9d54362a-a4d2-4b65-ac36-9c077d92784d)

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.19.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: gcc (GCC) 12.3.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.15.133.1-microsoft-standard-WSL2",
  sysname = "Linux",
  version = "#1 SMP Thu Oct 5 21:02:42 UTC 2023"
} ~

Parser/Features         H L F I J
  - astro               ✓ ✓ ✓ ✓ ✓
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - git_rebase          ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . .
  - glimmer             ✓ ✓ ✓ ✓ .
  - html                ✓ ✓ ✓ ✓ ✓
  - http                ✓ . . . ✓
  - hurl                ✓ . ✓ ✓ ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - nix                 ✓ ✓ ✓ . ✓
  - org                 ✓ . ✓ . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . ✓ ✓
  - ssh_config          ✓ ✓ ✓ ✓ ✓
  - svelte              ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - vue                 ✓ . ✓ ✓ ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

**Comment by clason** [comment] 2024-05-17 08:47
Duplicate of #

**Closed by clason** 2024-05-17 08:47 UTC
Labels: bug
