### ISSUE TITLE
the latex parser is not properly registered for the tex filetype

### ISSUE THREAD

**Issue by mathjiajia** [nvim-treesitter/nvim-treesitter#4630] opened 2023-04-09 13:20 UTC
### Describe the bug

Error executing vim.schedule lua callback: ...local/share/nvim/runtime/lua/vim/treesitter/language.lua:94: no parser for 'tex' language, see :help treesitter-parsers
stack traceback:
	[C]: in function 'error'
	...local/share/nvim/runtime/lua/vim/treesitter/language.lua:94: in function 'add'
	...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:88: in function 'new'
	/usr/local/share/nvim/runtime/lua/vim/treesitter.lua:61: in function '_create_parser'
	/usr/local/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser'
	/usr/local/share/nvim/runtime/lua/vim/treesitter/_fold.lua:106: in function 'get_folds_levels'
	/usr/local/share/nvim/runtime/lua/vim/treesitter/_fold.lua:196: in function </usr/local/share/nvim/runtime/lua/vim/treesitter/_fold.lua:193>

### To Reproduce

1, save the minimal config below as repro.lua
2, nvim -u repro.lua xxx.tex (to open any latex file)
3, key 'gcc' to comment one line

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	-- add any other plugins here
	{ "numToStr/Comment.nvim", config = true },

	{
		"nvim-treesitter/nvim-treesitter",
		config = function()
			vim.opt.foldmethod = "expr"
			vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"
			vim.opt.foldenable = false

			require("nvim-treesitter.configs").setup({
				ensure_installed = { "latex" },
				highlight = { enable = true },
			})
		end,
	},
}

require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v19.8.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "22.4.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - bibtex              ✓ . ✓ ✓ .
  - c                   ✓ ✓ ✓ ✓ ✓
  - comment             ✓ . . . .
  - diff                ✓ . . . .
  - fish                ✓ ✓ ✓ ✓ ✓
  - git_rebase          ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . .
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - luap                ✓ . . . .
  - markdown            ✓ . ✓ . ✓
  - markdown_inline     ✓ . . . ✓
  - matlab              ✓ . ✓ . ✓
  - norg                . . . . .
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - swift               ✓ ✓ . . .
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-339011f59
```

### Additional context

See also https://github.com/neovim/neovim/issues/22974

**Comment by clason** [comment] 2023-04-09 13:22
Please try to reproduce this without lazy.nvim.

What does `:=vim.treesitter.language.get_filetypes('latex')` say?

**Comment by theHamsta** [comment] 2023-04-09 15:14
Wasn't there a vim option whether `.tex`should be treated as`.txt` or latex?

**Comment by clason** [comment] 2023-04-09 15:16
That's only the legacy syntax file; not relevant here. I suspect a race condition where the `filetype` key is not applied yet.

**Comment by mathjiajia** [comment] 2023-04-09 22:51
Start nvim with `nvim --clean` and `:=vim.treesitter.language.get_filetypes('latex')` gives `{}`

**Comment by clason** [comment] 2023-04-09 23:19
Well, obviously you still have to install the nvim-treesitter plugin. you just shouldn't use lazy to do i.

**Comment by mathjiajia** [comment] 2023-04-10 12:39
The output is `{ "latex", "cls", "sty", "tex" }`

**Comment by mathjiajia** [comment] 2023-04-10 12:42
Yes, the same error

**Comment by clason** [comment] 2023-04-10 12:45
Do you have a minimal init.lua I can reproduce this with? Because I only get the error when `tex` is _not_ registered.

**Comment by clason** [comment] 2023-04-10 13:10
yes, and please check the output of `:=vim.treesitter.language.get_filetypes('latex')` before _and_ after the error

**Comment by mathjiajia** [comment] 2023-04-10 13:36
before: `{ "latex", "cls", "sty", "tex" }`
after" `{ "latex", "cls", "sty" }`

**Comment by clason** [comment] 2023-04-10 13:37
Ok, that should not happen. Sorry for giving you the run-around, but could you open this issue at comment.nvim too?

**Comment by mathjiajia** [comment] 2023-04-10 13:38
No problem

**Comment by tbung** [comment] 2023-04-11 10:57
This seems to also be happening with `bash`/`sh`.

`init.lua`
```lua
local ensure_packer = function()
  local fn = vim.fn
  local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
  if fn.empty(fn.glob(install_path)) > 0 then
    fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
    vim.cmd [[packadd packer.nvim]]
    return true
  end
  return false
end

local packer_bootstrap = ensure_packer()

return require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'

	use {
		"numToStr/Comment.nvim",
		config = function()
			require('Comment').setup()
		end,
		}
    use {
			'nvim-treesitter/nvim-treesitter',
      run = ':TSUpdate',
			config = function()
				-- Folding
				vim.opt.foldmethod = "expr"
				vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"
				vim.opt.foldenable = false

				require("nvim-treesitter.configs").setup({
					ensure_installed = { "bash" },
					highlight = { enable = true },
				})
			end,
    }

		if packer_bootstrap then
			require('packer').sync()
		end
end)
```

`test.sh`
```bash
#!/bin/bash

function foo() {
    printf "test"
}
```

When opening the file, `:=vim.treesitter.language.get_filetypes('bash')` gives
```
{ "bash", "sh", "PKGBUILD" }
```
and `:=vim.treesitter.language.get_filetypes('sh')` gives `{}`.

After triggering the error with comment.nvim, `:=vim.treesitter.language.get_filetypes('bash')` gives
```
{ "bash", "PKGBUILD" }
```
and `:=vim.treesitter.language.get_filetypes('sh')` gives `{ "sh" }`.

**Comment by tbung** [comment] 2023-04-11 11:26
Ok, so I investigated a bit more and the issue arises if `vim.treesitter.get_parser` is called with a filetype that is not the same as its language, as this resets the registered language for a filetype:

Before:
```
:=vim.treesitter.language.get_filetypes('bash')
```
```
{ "bash", "sh", "PKGBUILD" }
```

```
:=vim.treesitter.language.get_filetypes('sh')
```
```
{}
```
After calling
```lua
vim.treesitter.get_parser(0, "sh")
```
```
:=vim.treesitter.language.get_filetypes('bash')
```
```
{ "bash", "PKGBUILD" }
```

```
:=vim.treesitter.language.get_filetypes('sh')
```
```
{ "sh" }
```

`Comment.nvim` should probably call `vim.treesitter.language.get_lang` before calling `get_parser`, but I am guessing `get_parser` should not de-register a filetype from a language.

**Comment by clason** [comment] 2023-04-11 13:09
Fixed in comment.nvim. Thanks for investigating this!

**Closed by clason** 2023-04-11 13:09 UTC
Labels: bug
