### ISSUE TITLE
Treesitter complains of invalid nodetype whilst loading Rust highlights

### ISSUE THREAD

**Issue by FrankTaylorLieder** [nvim-treesitter/nvim-treesitter#5687] opened 2023-11-17 15:51 UTC
### Describe the bug

After a :PackerSync today my Rust windows are peppered with: "treesitter/highlighter: Error executing lua: ..."

:checkhealth shows:

The following errors have been detected: ~
- ERROR rust(highlights): ...im/0.9.4/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 617 for language rust
  rust(highlights) is concatenated from the following files:
  | [ERROR]:"/Users/fst/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/rust/highlights.scm", failed to load: ...im/0.9.4/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 617 for language rust

Looks like commit https://github.com/nvim-treesitter/nvim-treesitter/commit/557561fbc17269cdd4e9e88ef0ca1a9ff0bbf7e6 has caused it.

### To Reproduce

1. Open a Rust file.
2. See "treesitter/highlighter errors..." on many lines.
3. Run :checkhealth and see errors reported for treesitter and rust highlighting.

### Expected behavior

No errors.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v21.1.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.0.40.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.0.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - csv                 ✓ . . . .
  - diff                ✓ . . . .
  - gitignore           ✓ . . . .
  - javascript          ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                x ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR rust(highlights): ...im/0.9.4/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 617 for language rust
  rust(highlights) is concatenated from the following files:
  | [ERROR]:"/Users/fst/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/rust/highlights.scm", failed to load: ...im/0.9.4/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 617 for language rust
```

### Output of `nvim --version`

```text
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1699524327

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.4/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment] 2023-11-17 15:53
Duplicate of #3092

**Closed by clason** 2023-11-17 15:53 UTC
Labels: bug

**Comment by FrankTaylorLieder** [comment] 2023-11-17 16:15
Thanks... I did a ":TSUpdate rust" as suggested. Without a restart of nvim this did not solve it. After restarting it looks like its resolved now. If the restart is needed, it would be useful to note it in the checkhealth suggestion.

This is day 3 of neovim for me, so all this is new.

**Comment by clason** [comment] 2023-11-17 16:20
Restarts are _always_ needed in (Neo)vim if you update plugins.

**Comment by Pagliacii** [comment] 2023-11-18 06:36
`:TSUpdate rust` and restart neovim wasn't work for me. I should did `:TSInstall! rust` and restart neovim.

**Comment by dramborleg** [comment] 2023-12-23 01:21
> `:TSUpdate rust` and restart neovim wasn't work for me. I should did `:TSInstall! rust` and restart neovim.

Thanks for mentioning this, saved me a lot of time. Got a similar invalid node type error while reading neovim help (vimdoc parser) and this solved it where a TSUpdate didn't.
