### ISSUE TITLE
query.lua:248: Query error at 58:2. Invalid node type "modeline":

### ISSUE THREAD

**Issue by qZhang88** [nvim-treesitter/nvim-treesitter#6419] opened 2024-04-09 03:35 UTC
### Describe the bug

using neovim, check help for conceal, with `:h conceal`, following error popped up.
```
Error in decoration provider treesitter/highlighter.line:                                                                                                                                                                  
Error executing lua: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:248: Query error at 58:2. Invalid node type "modeline":
(modeline) @keyword.directive
 ^

stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:248: in function 'fn'
        /usr/local/share/nvim/runtime/lua/vim/func/_memoize.lua:54: in function 'fn'
        /usr/local/share/nvim/runtime/lua/vim/func/_memoize.lua:54: in function 'get'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:53: in function 'new'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:206: in function 'get_query'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:231: in function 'fn'
        ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:483: in function 'for_each_tree'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:217: in function 'on_line_impl'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:
```

### To Reproduce

open nvim
:h conceal

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v16.19.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.3) 9.4.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.15.0-91-generic",
  sysname = "Linux",
  version = "#101~20.04.1-Ubuntu SMP Thu Nov 16 14:22:28 UTC 2023"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . . . .
  - go                  ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - nix                 ✓ ✓ ✓ . ✓
  - norg                ✓ . ✓ . ✓
  - norg_meta           ✓ . . ✓ .
  - org                 . . . . .
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rst                 ✓ ✓ . . ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - scala               ✓ ✓ ✓ . ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              x . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR vimdoc(highlights): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:248: Query error at 58:2. Invalid node type "modeline":
  (modeline) @keyword.directive
   ^
  
  vimdoc(highlights) is concatenated from the following files:
  | [ERROR]:"/home/q/.local/share/nvim/lazy/nvim-treesitter/queries/vimdoc/highlights.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:248: Query error at 58:2. Invalid node type "modeline":
  (modeline) @keyword.directive
   ^
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-0ff13a6
Build type: Release
LuaJIT 2.1.1695653777
Run "nvim -V1 -v" for more info
```

**Comment by lucario387** [comment] 2024-04-09 03:37
Duplicate of #3092

**Closed** 2024-04-09 03:37 UTC
Labels: bug
