### ISSUE TITLE
The folding result is incorrect after undo text deletion by `c{move}`, where `{move}` can be `j`,`k`, etc.

### ISSUE THREAD

**Issue by nyngwang** [nvim-treesitter/nvim-treesitter#2439] opened 2022-02-02 23:24 UTC
### Describe the bug

The folding result is incorrect after undo text deletion by `c{motion}`, where `{move}` can be `j`,`k`, etc.

#### before `cc` at line 24

<img src="https://user-images.githubusercontent.com/24765272/152254764-02e9726c-db59-490a-bec1-75e8d38087a7.png" width="300"><img src="https://user-images.githubusercontent.com/24765272/152254794-cb56fe77-5ecd-4420-8b3b-eb223faba6fe.png" width="300">

#### after `cc` at line 24

<img src="https://user-images.githubusercontent.com/24765272/152254967-f4f6d800-593b-4de8-9836-6b0cc58aa115.png" width="300"><img src="https://user-images.githubusercontent.com/24765272/152254992-a3a4f7e8-138a-4544-b2fe-96b73f89acfd.png" width="300">

### To Reproduce

1. Go to any line that can fold
2. Run normal mode `zc` and `zO` and remember the result
3. Execute `cc` at the same line, then use `u` to undo.
4. Run `zc` again and compare the result with that of step 2.

### Expected behavior

After undo, should see the same result when calling `zc` on the same line.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.8.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.0.0 (clang-1300.0.29.30)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - yang           ✓ . ✓ . . 
  - make           ✓ . . . ✓ 
  - scss           ✓ . . ✓ . 
  - ql             ✓ ✓ . ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - vim            ✓ ✓ . . ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - dockerfile     ✓ . . . ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - svelte         ✓ . ✓ ✓ ✓ 
  - perl           ✓ . . . . 
  - surface        ✓ . ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - gomod          ✓ . . . ✓ 
  - scala          ✓ . ✓ . ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - pascal         ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - gdscript       ✓ ✓ . ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - clojure        ✓ ✓ ✓ . ✓ 
  - fusion         ✓ ✓ ✓ ✓ . 
  - graphql        ✓ . . ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - comment        ✓ . . . . 
  - rst            ✓ ✓ . . ✓ 
  - jsdoc          ✓ . . . . 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - vue            ✓ . ✓ ✓ ✓ 
  - gowork         ✓ . . . ✓ 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - ocaml_interface✓ ✓ ✓ . ✓ 
  - hjson          ✓ ✓ ✓ ✓ ✓ 
  - heex           ✓ ✓ ✓ ✓ ✓ 
  - dot            ✓ . . . ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - beancount      ✓ . ✓ . . 
  - bibtex         ✓ . ✓ ✓ . 
  - fennel         ✓ ✓ . . ✓ 
  - vala           ✓ . . . . 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - norg           . . . . . 
  - hcl            ✓ . ✓ ✓ ✓ 
  - ledger         ✓ . ✓ ✓ ✓ 
  - r              ✓ ✓ . ✓ . 
  - rasi           ✓ ✓ ✓ ✓ . 
  - pioasm         ✓ . . . ✓ 
  - tlaplus        ✓ ✓ ✓ . ✓ 
  - prisma         ✓ . . . . 
  - hocon          ✓ . . . ✓ 
  - glimmer        ✓ . . . . 
  - erlang         . . . . . 
  - llvm           ✓ . . . . 
  - pug            ✓ . . . ✓ 
  - http           ✓ . . . ✓ 
  - json5          ✓ . . . ✓ 
  - zig            ✓ . ✓ ✓ ✓ 
  - cmake          ✓ . ✓ . . 
  - eex            ✓ . . . ✓ 
  - kotlin         ✓ ✓ ✓ . ✓ 
  - julia          ✓ ✓ ✓ ✓ ✓ 
  - regex          ✓ . . . . 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - dart           ✓ ✓ . ✓ ✓ 
  - nix            ✓ ✓ ✓ . ✓ 
  - ninja          ✓ . ✓ ✓ . 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - glsl           ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - cuda           ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - latex          ✓ . ✓ . ✓ 
  - elixir         ✓ ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - commonlisp     ✓ ✓ ✓ . . 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.7.0-dev+997-g21cdecc8e
Build type: Release
LuaJIT 2.1.0-beta3
```

#### before `cc` at line 24

<img src="https://user-images.githubusercontent.com/24765272/152254764-02e9726c-db59-490a-bec1-75e8d38087a7.png" width="300"><img src="https://user-images.githubusercontent.com/24765272/152254794-cb56fe77-5ecd-4420-8b3b-eb223faba6fe.png" width="300">

#### after `cc` at line 24

<img src="https://user-images.githubusercontent.com/24765272/152254967-f4f6d800-593b-4de8-9836-6b0cc58aa115.png" width="300"><img src="https://user-images.githubusercontent.com/24765272/152254992-a3a4f7e8-138a-4544-b2fe-96b73f89acfd.png" width="300">

**Comment by theHamsta** [comment] 2022-02-03 00:18
I also found that folding results are not accurate at all after editing. It would be worth to look into the logic and back it up with actual tests. I personally don't have any experience with the folding logic until now.

**Comment by nyngwang** [comment] 2022-02-03 00:27
@theHamsta I consider this a hard problem(long-term/time-consuming, at least). I just found a workaround, which should save people from this issue (and similar ones) for now. I'm going to create a plugin for this.

**Comment by stsewd** [comment] 2022-02-03 03:07
This is an upstream issue https://github.com/neovim/neovim/issues/14977

**Comment by stsewd** [comment] 2022-02-03 03:09
Duplicate of https://github.com/nvim-treesitter/nvim-treesitter/issues/1424

**Closed by stsewd** 2022-02-03 03:09 UTC
Labels: bug
