### ISSUE TITLE
Maximum Results for Query?

### ISSUE THREAD

**Issue by tjdevries** [nvim-treesitter/nvim-treesitter#963] opened 2021-02-20 05:20 UTC
Hey @vigoux 

I got a bug here: https://github.com/tjdevries/tree-sitter-lua/issues/5

It seems that we are limited in the number of nodes that we return? I'm not sure if it's something on the nvim-treesitter side or neovim core side. Figured I'd just ping here. thanks :)

**Comment by vigoux** [comment] 2021-02-22 06:13
This is reaaaaaally weird.

**Comment by tjdevries** [comment] 2021-02-22 16:13
@vigoux any recommendations on how to fix / investigate / do based on conni's excellent debug info there?

**Comment by vigoux** [comment] 2021-02-22 20:37
I'd try looking at what tree-sitter playground and our playground give, just to see if that's a deeper bug.

**Comment by Conni2461** [comment] 2021-02-22 20:51
![2021-02-22_21-46](https://user-images.githubusercontent.com/15233006/108768068-82ae5600-7557-11eb-959b-df5325dbddbf.png)

My screenshot shows the parser that is provided by this repo. Not tjs.

"our playground" gives me the same. I don't know how to check the `tree-sitter playground` because it has no lua parser available but i can test another language tomorrow. 

It also only happens when `#eq` is set. If not it captures all nodes. Also the playground shows all nodes as well. Its only the capturing that is missing the beginning if we pass some threshold.

**Comment by steelsojka** [comment] 2021-02-23 13:09
Does this only happen with the lua parser? I'll try it out with the javascript parser and see if I get the same results.

**Comment by steelsojka** [comment] 2021-02-23 13:26
I reproduced this and even removing the `eq?` predicate still causes it to only match a subset. Removing the return_statement node from the query will make it match all the queries. I can reproduce the same thing in JS as well.

![Screen Shot 2021-02-23 at 7 25 52 AM](https://user-images.githubusercontent.com/2062154/108849973-68e92f00-75a8-11eb-935c-23dc060f4e48.png)

**Comment by steelsojka** [comment] 2021-02-23 13:29
I tried this in the playground and it has the same weird experience. The functions are highlighted until you start scrolling and then once you reach that 15 or so limit they stop matching. I think this is a bug in treesitter.

**Comment by tjdevries** [comment] 2021-02-23 18:40
FIX IT FOR ME @vigoux !!!! HAVE IT ON MY DESK BY MONDAY MORNINGN!N!N!N!N!N!N!?!?!?!N!?!?!?!?!?! :wink: 

I'm glad me and @Conni2461 aren't crazy at least :laughing:

**Comment by tjdevries** [comment] 2021-03-02 03:52
So this is fixed in upstream tree sitter now I think. It is breaking change though. We will need to update nvim version of tree sitter.

**Comment by tjdevries** [comment] 2021-04-13 14:15
@vigoux :)

**Comment by vigoux** [comment] 2021-04-13 14:40
Hmmm I can't seem to reproduce...

**Comment by vigoux** [comment] 2021-04-13 15:11
I am doing some inverstigations, and it seems that the  query is actually running twice (which is already weird):
- Once during the call to  `parser:parse()`
- And during the actual `iter_matches` call

**Comment by vigoux** [comment] 2021-04-14 12:11
Great news, this is actually an upstream issue, reproducible using tree-sitter only, I am going to open an issue right now.

**Comment by vigoux** [comment] 2021-04-16 14:59
Update: this is actually a limitation of tree-sitter, dropping some matches sometimes, so this should be fixed following the upstream issue.

**Comment by vigoux** [comment] 2021-06-11 14:37
After testing, on very latest master (includes an update of the runtime), it seems to be gone (actually, I am sure it's gone). I am closing this then.

**Closed by vigoux** 2021-06-11 14:37 UTC
Labels: bug, upstream
