### ISSUE TITLE
Err when opening .py files

### ISSUE THREAD

**Issue by PouriDev** [nvim-treesitter/nvim-treesitter#660] opened 2020-11-17 16:42 UTC
When I open a Python file I get this error
![err](https://user-images.githubusercontent.com/61497342/99418473-4e038080-2910-11eb-88eb-be41334be11c.png)
Recently I've setup this liens in my init.vim
```vim
lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained",
  highlight = {
    enable = true,             
    disable = {},  
  },
}
require"nvim-treesitter.highlight"
local hlmap = vim.treesitter.highlighter.hl_map
hlmap.error = nil
hlmap["punctuation.delimiter"] = "Delimiter"
hlmap["punctuation.bracket"] = nil
EOF
```
I use a plugin called rainbow which colorize the brackets, I've disabled bracket colorizing for treesitter, and it just works! it works as expected for everyfiles except python files.
And these lines are in my highlighter.lua file:
```lua
function TSHighlighter.new(parser, query)
  local self = setmetatable({}, TSHighlighter)

  self.parser = parser
  parser:register_cbs {
    on_changedtree = function(...) self:on_changedtree(...) end
  }

  self:set_query(query)
  self.edit_count = 0
  self.redraw_count = 0
  self.line_count = {}
  self.root = self.parser:parse():root() -- <-- this line is 71
  a.nvim_buf_set_option(self.buf, "syntax", "")

  -- TODO(bfredl): can has multiple highlighters per buffer????
  if not TSHighlighter.active[parser.bufnr] then
    TSHighlighter.active[parser.bufnr] = {}
  end

  TSHighlighter.active[parser.bufnr][parser.lang] = self

  -- Tricky: if syntax hasn't been enabled, we need to reload color scheme
  -- but use synload.vim rather than syntax.vim to not enable
  -- syntax FileType autocmds. Later on we should integrate with the
  -- `:syntax` and `set syntax=...` machinery properly.
  if vim.g.syntax_on ~= 1 then
    vim.api.nvim_command("runtime! syntax/synload.vim")
  end
  return self
end
```

**Comment by theHamsta** [comment] 2020-11-17 16:45
Duplicate of https://github.com/nvim-treesitter/nvim-treesitter/issues/649 ? For newest Python parser you need a Neovim nighltly newer than Nov 3rd.

**Comment by PouriDev** [comment] 2020-11-18 05:29
Done! it works , thanks!

**Comment by PouriDev** [comment] 2020-11-18 06:09
The issue appears again after restarting (reopening) terminal , after I built neovim, it worked in the current terminal , but it's still here, If I restart them

**Closed** 2020-11-21 05:41 UTC
Labels: bug
