### ISSUE TITLE
Weird italicized underlining in some files like LaTeX/HTML

### ISSUE THREAD

**Issue by paniash** [nvim-treesitter/nvim-treesitter#1506] opened 2021-07-05 20:36 UTC
**Describe the bug**

At times, in certain sections of text, I notice italicized underlining when moving the cursor in one direction. Reversing the direction reverts the text back to normal.

**To Reproduce**

1. Open a .tex file and type the following:

```tex
\hypersetup{
bookmarksopen=true,
citecolor=red,
urlcolor=blue,
}
```

2. Move the cursor across this section of text from bottom to top. One notices this section to become italicized and underlined.

3. Move the cursor in reverse i.e. top to bottom, reverts the text back to normal.

**Expected behavior**

There should be no such visual modification of text without user intervention.

**Output of `:checkhealth nvim_treesitter`**

```

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - WARNING: `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - c_sharp        ✓ . ✓ . ✓ 
  - bibtex         ✓ . ✓ ✓ . 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - r              ✓ ✓ . . . 
  - comment        ✓ . . . . 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - ql             ✓ ✓ . ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - jsdoc          ✓ . . . . 
  - ledger         ✓ . ✓ ✓ ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - clojure        ✓ ✓ ✓ . ✓ 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - fennel         ✓ ✓ . . ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - vue            ✓ . ✓ . ✓ 
  - latex          ✓ . ✓ . ✓ 
  - rst            ✓ ✓ . . ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - glimmer        ✓ . . . . 
  - erlang         . . . . . 
  - regex          ✓ . . . . 
  - svelte         ✓ . ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - teal           ✓ ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - gomod          ✓ . . . . 
  - dart           ✓ ✓ . ✓ ✓ 
  - verilog        ✓ ✓ ✓ . ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - julia          ✓ ✓ ✓ . ✓ 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - zig            ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - commonlisp     ✓ ✓ ✓ . . 
  - ocaml_interface✓ ✓ ✓ . ✓ 
  - beancount      ✓ . ✓ . . 
  - kotlin         ✓ . . . ✓ 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - dockerfile     ✓ . . . ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - nix            ✓ ✓ ✓ . ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - sparql         ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

```

**Output of `nvim --version`**

```
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.0/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

## Screenshots

**When running the cursor from bottom to top**

![pic-selected-210706-0158-09](https://user-images.githubusercontent.com/59497618/124516123-a3889100-ddfe-11eb-86a7-00a2f870b5ec.png)

**When moving the cursor across in reverse**
![pic-selected-210706-0157-57](https://user-images.githubusercontent.com/59497618/124516138-a71c1800-ddfe-11eb-882e-985ded0519be.png)

**Comment by theHamsta** [comment] 2021-07-05 20:41
![image](https://user-images.githubusercontent.com/7189118/124516417-df612d80-dde1-11eb-9112-c1ecdc8426dd.png)
 Really weird surprisingly similar to https://github.com/nvim-treesitter/nvim-treesitter/issues/1371

**Comment by paniash** [comment] 2021-07-05 20:57
@theHamsta I've noticed this same effect in html files as well!

**Comment by theHamsta** [comment] 2021-07-05 20:59
It seems that all queries with `@_foo` match now automatically.

```
;((environment
  ;(begin
   ;name: (word) @_frame)
   ;(brace_group
        ;child: (text) @text.title))
 ;(#eq? @_frame "frame"))

;((generic_command
  ;name:(generic_command_name) @_name
  ;arg: (brace_group
          ;(text) @text.title))
 ;(#eq? @_name "\\frametitle"))

;; Formatting

;((generic_command
  ;name:(generic_command_name) @_name
  ;arg: (_) @text.emphasis)
 ;(#eq? @_name "\\emph"))

;((generic_command
  ;name:(generic_command_name) @_name
  ;arg: (_) @text.emphasis)
 ;(#match? @_name "^(\\\\textit|\\\\mathit)$"))

;((generic_command
  ;name:(generic_command_name) @_name
  ;arg: (_) @text.strong)
 ;(#match? @_name "^(\\\\textbf|\\\\mathbf)$"))

;((generic_command
  ;name:(generic_command_name) @_name
  ;.
  ;arg: (_) @text.uri)
 ;(#match? @_name "^(\\\\url|\\\\href)$"))

```

**Comment by paniash** [comment] 2021-07-05 21:02
> This solves the problem. Maybe related to an update in tree-sitter?

Hmm... I did notice this bug since I started using treesitter (about 10 days back) so maybe an update before this time?

**Comment by theHamsta** [comment] 2021-07-05 21:04
Is the same issue as for html. I posted the culprit queries for htmls.

**Comment by paniash** [comment] 2021-07-06 15:25
Apologies if I'm misunderstanding but is there a fix available for this issue?

**Comment by stsewd** [comment] 2021-07-06 15:39
@paniash no yet, looks like we still need to research when this started happening or why those queries are being omitted

**Comment by paniash** [comment] 2021-07-06 17:03
> @theHamsta I've noticed this same effect in html files as well!

Example screenshot for when handling html files.

![pic-selected-210706-2232-25](https://user-images.githubusercontent.com/59497618/124639750-29ade180-deaa-11eb-9ed3-df92d87612eb.png)

**Comment by vigoux** [comment] 2021-07-06 17:24
@theHamsta, that's really weird that the queries ignore `@_foo`, does that also happens in the playground ?

**Comment by ChristianChiarulli** [comment] 2021-07-07 02:34
Same here:

![image](https://user-images.githubusercontent.com/29136904/124691735-4ea25480-deaa-11eb-9c7d-fc9e70694e9d.png)

**Comment by abenz1267** [comment] 2021-07-09 00:29
It's even worse with tagged literals.

![Screenshot_20210709_022814](https://user-images.githubusercontent.com/7055955/125006030-72f26280-e05d-11eb-8087-962cc428d9be.png)

**Comment by stsewd** [comment] 2021-07-11 04:42
Looks like the error comes from `iter_captures` when the range is changed

test file:

```latex
\hypersetup{
citecolor=red,
urlcolor=blue,
}
```

lua code:

```lua
local parsers = require "nvim-treesitter.parsers"
local query = require "vim.treesitter.query"

local function print(str)
  vim.api.nvim_out_write(vim.inspect(str) .. "\n")
end

local lang = "latex"

local parser = parsers.get_parser(0, lang)
local tree = parser:parse()[1]
local node = tree:root()
local q = query.get_query(lang, "highlights")
for id, n, metadata in q:iter_captures(node, 0, 0, 3) do
  print("Capture: " .. id .. " / " .. q.captures[id])
  print("Node: " .. n:type())
end
```

getting the captures for the whole doc gets the correct results, but change it to `iter_captures(node, 0, 1, 3)` and it returns invalid captures.

**Comment by stsewd** [comment] 2021-07-12 04:16
So, digging a little more into this bug, what I found is that it looks like the predicates are being ignored when the range is changed in `iter_captures`. If you remove the predicates (match, eq, etc) from the `(generic_command)` queries, you get the result you see when moving the cursor. Well, that's a hint if someone wants to dig into the neovim code :D

**Comment by charbelnicolas** [comment] 2021-07-14 17:44
Here is a svelte file for testing as requested by @stsewd

[SVELTE FILE](https://charbelnicolas.com/files/Player.svelte)

This one is quite decorated with many lines!

![20210714_124402](https://user-images.githubusercontent.com/14960414/125668116-0bce61cd-3a0d-4d90-866c-1cef42c5c96e.png)

**Comment by vaga** [comment] 2021-07-16 13:40
Same here in vue file:
![Screenshot 2021-07-16 at 15 38 20](https://user-images.githubusercontent.com/1078179/125957000-e37b65a0-95db-4c56-931a-f8cda5490f9b.png)

**Comment by stsewd** [comment] 2021-07-18 16:44
Found a fix for this problem, but don't know why neovim was doing that before. PR at https://github.com/neovim/neovim/pull/15126

**Comment by charbelnicolas** [comment] 2021-11-02 05:14
https://user-images.githubusercontent.com/14960414/139790259-01124e40-fc1a-4ddc-8eba-daa38bca76b7.mp4

**Comment by charbelnicolas** [comment] 2021-11-05 19:38
> @charbelnicolas I'm not able to reproduce, I think your neovim wasn't compiled with the proper treesitter version. Try building neovim from source and see if you can reproduce this.

I opened the same svelte file today and the issue is back. :(

**Comment by stsewd** [comment] 2021-11-05 23:41
I can't reproduce this. And it hasn't been any changes about treesitter on neovim. If you see some parts white, then that's https://github.com/nvim-treesitter/nvim-treesitter/issues/1788.

**Comment by vigoux** [comment] 2022-05-03 06:50
Reopening since part of this issues are still reproducible on both neovim master and nvim-treesitter master.

**Comment by shellRaining** [comment] 2023-11-23 02:13
Is there a solution to this problem? I still encountered this bug when writing Vue code.

<img width="440" alt="image" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/111564053/d513f638-b1f9-4edb-a769-93955a60bc41">

the version of `neovim` is `0.9.4`, and `nvim-treesitter` is the latest version.

**Comment by lucario387** [comment] 2023-11-23 02:30
We don't provide any highlighting, only capture groups. Ask your theme maintainer on why that's the case

**Comment by shellRaining** [comment] 2023-11-23 02:42
without using any theme, the underline still appear in the line 4,5,6, and when use `TSDisable highlight`, the under is disappeared

**Comment by lucario387** [comment] 2023-11-23 02:49
If you put your cursor under such underline areas and do `:Inspect`, what are the listed hlgroups? Whatever it is, remove italic from that group

**Comment by XVilka** [comment] 2024-06-03 16:52
I tried to reproduce the original report with no luck. No underlining appears in my NeoVim 0.10.0 in iTerm2 3.5.0

**Comment by clason** [comment] 2024-06-03 16:54
Yeah, that is (now) an upstream bug, if any.

**Closed by clason** 2024-06-03 16:54 UTC
Labels: bug, upstream Neovim
