### ISSUE TITLE
HTML injection in Rust inconsistent

### ISSUE THREAD

**Issue by Xandaros** [nvim-treesitter/nvim-treesitter#3379] opened 2022-08-27 01:55 UTC
### Describe the bug

The HTML injection in Rust is inconsistent. Sometimes the injected part will be highlighted as HTML, sometimes it will be highlighted as Rust. Restarting the editor can toggle it with no changes to the document.

### To Reproduce

Run `TSInstall` for both html and rust.
Create a file `test.rs` with this content:
```rust
fn main() {
    html! {
        <body>
            <h1>Asdf</h1>
        </body>
    }
}
```
Open the file in neovim with treesitter highlighting enabled. Restart the editor a bunch of times and notice the highlighting change.

### Expected behavior

The way the document is highlight should not change between restarts - the contents of the `html` macro should always be highlighted as HTML.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.7.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - rust           ✓ ✓ ✓ ✓ ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - query          ✓ ✓ ✓ ✓ ✓
  - html           ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

The problem appears to be that the `injections.scm` file defines two matching queries for different language injections. One injects rust, the other html.

```scheme
(macro_invocation
  (token_tree) @rust)

; [...]

(
  (macro_invocation
    macro: ((identifier) @_html_def)
    (token_tree) @html)

    (#eq? @_html_def "html")
)
```

I don't know why the first rule is necessary. In my testing, removing it completely solves the issue, but I do not know what consequences this has.
If it cannot be outright removed, some kind of exclusion for the html macro should probably be added. That said, this rule will also interfere with people's custom injections, so maybe a more general solution should be found.

**Comment by sigmaSd** [comment] 2022-08-28 14:16
It seems like its not needed because inside a macro invocation the host parser will continue to be used by default, so even without that lines the inside of a macro will still be considered rust.

Same for
 ```rust
(macro_definition
  (macro_rule
    left: (token_tree_pattern) @rust
    right: (token_tree) @rust))
```
It should be not needed as far as I can tell.

The commit was made 2 years ago 
![image](https://user-images.githubusercontent.com/22427111/187078394-bd0bae65-b4bb-45b8-a9af-1f9c3551da71.png)

Maybe things were different back then.

**Comment by theHamsta** [comment] 2022-08-29 22:09
Closing as duplicate of #3110

**Closed by theHamsta** 2022-08-29 22:09 UTC
Labels: bug
