### ISSUE TITLE
highlighter for vim not working on lattest

### ISSUE THREAD

**Issue by allancomar** [nvim-treesitter/nvim-treesitter#4014] opened 2022-12-22 14:12 UTC
### Describe the bug

Installed the latest package for treesitter and I got a parse error when opening my plugins file:
treesitter/highlighter: error executing lua: /user/local/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
![Screen Shot 2022-12-22 at 9 08 57 AM](https://user-images.githubusercontent.com/13906250/209152263-a55e7eb3-b6e0-4c20-9d03-633562a3cc5e.png)

### To Reproduce

use the snippet to auto install packer on a lua file:
local ensure_packer = function()
    local fn = vim.fn
    local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
    if fn.empty(fn.glob(install_path)) > 0 then
        fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
        vim.cmd [[packadd packer.nvim]]
        return true
    end
    return false
end

that should trigger the defect.

### Expected behavior

no errors on the highlighter.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.12.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.0.0 (clang-1300.0.29.30)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "20.6.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 20.6.0: Thu Sep 29 20:15:11 PDT 2022; root:xnu-7195.141.42~1/RELEASE_X86_64"
}

## Parser/Features         H L F I J
  - rust                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - help                ✓ . . . ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - vim                 x ✓ ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: vim(highlights): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
    vim(highlights) is concatenated from the following files:
    | [ERROR]:"/Users/acomar/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/vim/highlights.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
```

### Output of `nvim --version`

```text
NVIM v0.8.2-dev-13+gca4a600e4
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by acomar@C02FQ2YMMD6R.corp.proofpoint.com

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment] 2022-12-22 14:13
Duplicate of #3092

**Closed by clason** 2022-12-22 14:13 UTC
Labels: bug

**Comment by allancomar** [comment] 2022-12-22 15:06
Thanks. reinstalling the vim package parser did the trick.

**Comment by jsc57x** [comment] 2022-12-28 09:08
For future generations: You might have to use the latest development version of nvim (I used the latest stalbe which caused the error)
