### ISSUE TITLE
c_sharp: Invalid node type "for_each_statement"

### ISSUE THREAD

**Issue by ar1a** [nvim-treesitter/nvim-treesitter#7186] opened 2024-09-27 10:58 UTC
### Describe the bug

When loading a c# file in this empty godot project I just started, I get this error pop up. I've found that the error *won't* pop up if i open nvim in the directory, and then open the file, but if i run `nvim <file>` the error will pop up. In this case, I opened the directory and then the file. I instead procced this error by trying to comment a line.

```
E5108: Error executing lua ...s/Neovim/share/nvim/runtime/lua/vim/filetype/options.lua:82: FileType Autocommands for "*": Vim(append):Error executing lua callback: ...s/Neovim/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 17:2. Invalid node type "for_each_statement":
(for_each_statement
 ^

stack traceback:
	[C]: in function '_ts_parse_query'
	...s/Neovim/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
	...iles/Neovim/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
	...iles/Neovim/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get_query'
	...l/nvim-data/lazy/nvim-ts-rainbow2/lua/ts-rainbow/lib.lua:70: in function 'get_query'
	...vim-data/lazy/nvim-ts-rainbow2/lua/ts-rainbow/module.lua:30: in function 'is_supported'
	...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:387: in function 'is_enabled'
	...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:507: in function 'attach_module'
	...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
	...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:132>
	[C]: in function 'nvim_get_option_value'
	...s/Neovim/share/nvim/runtime/lua/vim/filetype/options.lua:82: in function '_get_option'
	...-data/lazy/ts-comments.nvim/lua/ts-comments/comments.lua:86: in function 'resolve'
	...-data/lazy/ts-comments.nvim/lua/ts-comments/comments.lua:98: in function 'get_option'
	...ram Files/Neovim/share/nvim/runtime/lua/vim/_comment.lua:38: in function 'traverse'
	...ram Files/Neovim/share/nvim/runtime/lua/vim/_comment.lua:48: in function 'get_commentstring'
	...ram Files/Neovim/share/nvim/runtime/lua/vim/_comment.lua:57: in function 'get_comment_parts'
	...ram Files/Neovim/share/nvim/runtime/lua/vim/_comment.lua:183: in function 'toggle_lines'
	...ram Files/Neovim/share/nvim/runtime/lua/vim/_comment.lua:228: in function <...ram Files/Neovim/share/nvim/runtime/lua/vim/_comment.lua:207>
stack traceback:
	[C]: in function 'nvim_get_option_value'
	...s/Neovim/share/nvim/runtime/lua/vim/filetype/options.lua:82: in function '_get_option'
	...-data/lazy/ts-comments.nvim/lua/ts-comments/comments.lua:86: in function 'resolve'
	...-data/lazy/ts-comments.nvim/lua/ts-comments/comments.lua:98: in function 'get_option'
	...ram Files/Neovim/share/nvim/runtime/lua/vim/_comment.lua:38: in function 'traverse'
	...ram Files/Neovim/share/nvim/runtime/lua/vim/_comment.lua:48: in function 'get_commentstring'
	...ram Files/Neovim/share/nvim/runtime/lua/vim/_comment.lua:57: in function 'get_comment_parts'
	...ram Files/Neovim/share/nvim/runtime/lua/vim/_comment.lua:183: in function 'toggle_lines'
	...ram Files/Neovim/share/nvim/runtime/lua/vim/_comment.lua:228: in function <...ram Files/Neovim/share/nvim/runtime/lua/vim/_comment.lua:207>
```

### To Reproduce

1. Open c sharp file via `nvim <file>`
2. Observe error, 

### Output of `:checkhealth nvim-treesitter`

```markdown
Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v18.12.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: gcc (MinGW-W64 x86_64-msvcrt-posix-seh, built by Brecht Sanders) 13.1.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.22631",
  sysname = "Windows_NT",
  version = "Windows 11 Pro"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - c_sharp             ✓ ✓ ✓ . ✓
  - diff                ✓ . ✓ . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - luap                ✓ . . . .
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - printf              ✓ . . . .
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```
```


### Output of `nvim --version`

```text
NVIM v0.11.0-dev-842+ga9287dd88
Build type: RelWithDebInfo
LuaJIT 2.1.1724512491
Run "nvim -V1 -v" for more info```
```

### Additional context

Interestingly enough, when trying to comment a line, half of nvim stops rendering. Probably out of the scope of nvim-treesitter:

![image](https://github.com/user-attachments/assets/7efae55d-bb1a-410b-825c-fb1a154a24af)

**Comment by lucario387** [comment] 2024-09-27 11:53
Duplicate of #3092

**Closed by lucario387** 2024-09-27 11:53 UTC
Labels: bug

**Comment by ar1a** [comment] 2024-09-27 12:03
aha! `:echo nvim_get_runtime_file('queries/c_sharp/*.scm', v:true)` revealed I had https://github.com/HiPhish/nvim-ts-rainbow2 `nvim-ts-rainbow2` installed, which is deprecated.
