### ISSUE TITLE
Neovim crashes when highlighting an SQL heredoc inside a PHP file

### ISSUE THREAD

**Issue by loganswartz** [nvim-treesitter/nvim-treesitter#6589] opened 2024-05-06 17:11 UTC
### Describe the bug

Neovim crashes when highlighting an SQL heredoc inside a PHP file. This seems to have been introduced in [this](https://github.com/nvim-treesitter/nvim-treesitter/commit/4e21361e15b1d4147830c5fe571556eb1b14e6f9) commit, since checking out to [the previous commit](https://github.com/nvim-treesitter/nvim-treesitter/commit/c579d186bec0a4af9d0741b235cfa0627ffd9f15) and opening the same file does not crash for me.

### To Reproduce

1. Create `crash.php` with these contents:

```php
<?php

$var = <<<SQL
SELECT * FROM table
SQL;
```

2. `nvim crash.php`, with Neovim >= `v0.10.0-dev-2791+g99b3a068d` (that's the earliest version I had installed), and treesitter highlighting enabled.

3. It should crash.

### Expected behavior

Neovim should not crash.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.4 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v21.7.3 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20240316 (Red Hat 13.2.1-7)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.8.8-200.fc39.x86_64",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Sat Apr 27 17:42:13 UTC 2024"
} ~

Parser/Features         H L F I J
  - asm                 ✓ . . . ✓
  - awk                 ✓ . . . ✓
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - c_sharp             ✓ ✓ ✓ . ✓
  - cmake               ✓ . ✓ ✓ .
  - comment             ✓ . . . .
  - commonlisp          ✓ ✓ ✓ . .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - csv                 ✓ . . . .
  - dockerfile          ✓ . . . ✓
  - git_config          ✓ . ✓ . ✓
  - git_rebase          ✓ . . . ✓
  - gitattributes       ✓ ✓ . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . .
  - go                  ✓ ✓ ✓ ✓ ✓
  - graphql             ✓ . . ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - htmldjango          ✓ . ✓ ✓ ✓
  - ini                 ✓ . ✓ . .
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - json5               ✓ . . . ✓
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - julia               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - luap                ✓ . . . .
  - luau                ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - perl                ✓ . ✓ . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - phpdoc              ✓ . . . .
  - python              ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - rst                 ✓ ✓ . . ✓
  - ruby                ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ .
  - sql                 ✓ . . ✓ ✓
  - ssh_config          ✓ ✓ ✓ ✓ ✓
  - svelte              ✓ ✓ ✓ ✓ ✓
  - tmux                ✓ . . . ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev+3085-gb024643ca
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634
Run "nvim -V1 -v" for more info
```

### Additional context

Here's my lazy.nvim config for treesitter, just for completeness:

```lua
local M = {
    'nvim-treesitter/nvim-treesitter',
    version = false,
    build = ":TSUpdate",
    event = { "BufReadPost", "BufNewFile" },
    cmd = { "TSUpdateSync" },
    main = 'nvim-treesitter.configs',
    opts = {
        ensure_installed = {
            'asm', 'awk', 'bash', 'c', 'c_sharp',
            'cmake', 'comment', 'commonlisp', 'cpp', 'css',
            'csv', 'dockerfile', 'git_config', 'git_rebase',
            'gitattributes', 'gitcommit', 'gitignore', 'go',
            'graphql', 'html', 'htmldjango', 'ini',
            'javascript', 'jsdoc', 'json', 'json5',
            'jsonc', 'julia', 'lua', 'luadoc', 'luap',
            'luau', 'make', 'markdown', 'perl', 'php',
            'phpdoc', 'python', 'regex', 'rst', 'ruby',
            'rust', 'scss', 'ssh_config', 'sql', 'svelte',
            'toml', 'tmux', 'tsx', 'typescript', 'vim',
            'yaml', 'xml',
        },
        highlight = {
            enable = true,
        },
        indent = {
            enable = true
        },
        playground = {
            enable = false,
            disable = {},
            updatetime = 25,
            persist_queries = false,
            keybindings = {
                toggle_query_editor = 'o',
                toggle_hl_groups = 'i',
                toggle_injected_languages = 't',
                toggle_anonymous_nodes = 'a',
                toggle_language_display = 'I',
                focus_language = 'f',
                unfocus_language = 'F',
                update = 'R',
                goto_node = '<cr>',
                show_help = '?',
            },
        },
        context_commentstring = {
            enable = true,
            enable_autocmd = false,
        },
        autotag = {
            enable = true,
        },
    },
}

return M
```

**Comment by clason** [comment] 2024-05-06 17:39
Duplicate of #6573 (and an upstream issue).

**Closed by clason** 2024-05-06 17:39 UTC
Labels: bug

**Comment by amaanq** [comment] 2024-05-14 04:00
Fixed in https://github.com/tree-sitter/tree-sitter-php/commit/27afeb02e49ff30acd17b67897b1c0114561a38c
