### ISSUE TITLE
Latest update can't install YAML treesitter

### ISSUE THREAD

**Issue by jacobrreed** [nvim-treesitter/nvim-treesitter#6302] opened 2024-03-15 15:49 UTC
### Describe the bug

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/25580051/3e4b65b2-0541-47d4-8fda-a1b817d6d330)

I have deleted ~/.local/share/nvim/tree-sitter-yaml and ran :TsUpdateSync yaml to no avail

### To Reproduce

1. Install `yaml` treesitter parser
2.  Fail from clang not finding src/scanner.cc

### Expected behavior

YAML treesitter parser should install

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.1 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v16.20.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.1.0.2.5)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.3.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - c_sharp             ✓ ✓ ✓ . ✓
  - css                 ✓ . ✓ ✓ ✓
  - diff                ✓ . . . .
  - dockerfile          ✓ . . . ✓
  - fish                ✓ ✓ ✓ ✓ ✓
  - git_config          ✓ . ✓ . ✓
  - git_rebase          ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . .
  - go                  ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - hyprlang            ✓ . ✓ ✓ .
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rasi                ✓ ✓ ✓ ✓ .
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ .
  - sql                 ✓ . . ✓ ✓
  - ssh_config          ✓ ✓ ✓ ✓ ✓
  - terraform           ✓ . ✓ ✓ ✓
  - tmux                ✓ . . . ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~


```
```


### Output of `nvim --version`

```text
NVIM v0.10.0-dev-2258+g1405e5c8c
Build type: RelWithDebInfo
LuaJIT 2.1.1706708390
Run "nvim -V1 -v" for more info
```
```


### Additional context

_No response_

**Comment by jacobrreed** [comment] 2024-03-15 15:54
I was able to fix this by manually running `cd ~/.local/share/nvim/tree-sitter-yaml %% cc -o parser.so -I./src src/parser.c src/scanner.c -Os -bundle -lstdc++ -fPIC` (notice that I changed parser.cc to parser.c

**Comment by lucario387** [comment] 2024-03-16 01:17
Duplicate of #3092 it seems

**Closed** 2024-03-16 01:17 UTC
Labels: bug
