### ISSUE TITLE
python always autoindent  after a string contains "[" 

### ISSUE THREAD

**Issue by ch4m1gn0n** [nvim-treesitter/nvim-treesitter#4149] opened 2023-01-12 07:50 UTC
### Describe the bug

always indent after "["

### To Reproduce

![treesitter](https://user-images.githubusercontent.com/51645204/212006532-48a3698a-ba04-4354-a991-a2cdf7c26b58.gif)
![treesitter2](https://user-images.githubusercontent.com/51645204/212006546-4355db60-7757-4247-9c0c-8e8b67185def.gif)

### Expected behavior

do not indent when "[" is a string.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v18.13.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Debian 12.2.0-9) 12.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.10.16.3-microsoft-standard-WSL2",
  sysname = "Linux",
  version = "#1 SMP Fri Apr 2 22:23:49 UTC 2021"
} ~

Parser/Features         H L F I J
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - help                ✓ . . . ✓
  - vim                 ✓ ✓ ✓ . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ . ✓ ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.0-dev-538+gf9c62ce34
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az449-598

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

### Additional context

treesitter config file
```
local status_ok, configs = pcall(require, "nvim-treesitter.configs")
if not status_ok then
  return
end

configs.setup {
  -- A list of parser names, or "all"
  ensure_installed = {"lua","cpp","python","java","php"}, --{ "c", "lua", "rust" },

  -- Install parsers synchronously (only applied to `ensure_installed`)
  sync_install = false,

  -- Automatically install missing parsers when entering buffer
  -- Recommendation: set to false if you don't have `tree-sitter` CLI installed locally
  auto_install = false,

  -- List of parsers to ignore installing (for "all")
  ignore_install = { "javascript" },

  ---- If you need to change the installation directory of the parsers (see -> Advanced Setup)
  -- parser_install_dir = "/some/path/to/store/parsers", -- Remember to run vim.opt.runtimepath:append("/some/path/to/store/parsers")!

  highlight = {
    -- `false` will disable the whole extension
    enable = true,

    -- NOTE: these are the names of the parsers and not the filetype. (for example if you want to
    -- disable highlighting for the `tex` filetype, you need to include `latex` in this list as this is
    -- the name of the parser)
    -- list of language that will be disabled
    --[[ disable = { "c", "rust" }, ]]
    --[[ -- Or use a function for more flexibility, e.g. to disable slow treesitter highlight for large files ]]
    --[[ disable = function(lang, buf) ]]
    --[[     local max_filesize = 100 * 1024 -- 100 KB ]]
    --[[     local ok, stats = pcall(vim.loop.fs_stat, vim.api.nvim_buf_get_name(buf)) ]]
    --[[     if ok and stats and stats.size > max_filesize then ]]
    --[[         return true ]]
    --[[     end ]]
    --[[ end, ]]

    -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
    -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
    -- Using this option may slow down your editor, and you may see some duplicate highlights.
    -- Instead of true it can also be a list of languages
    additional_vim_regex_highlighting = false,
  },
}
```

**Comment by amaanq** [comment] 2023-02-24 01:26
Interesting, something to note is that this isn't limited to python...see an example in C:
```c
int main(int argc, char *argv[])
{

  const char* a = "["
}
```

It requires the ; delimiter to be omitted to occur, so I think this isn't a python-specific error, but a nvim-treesitter general bug.

**Comment by amaanq** [comment] 2023-02-24 23:27
@theHamsta could you look into this a bit

**Comment by theHamsta** [comment] 2023-02-25 19:29
Hi! I can only reproduce with `idnent` module off for Python. The indentation will then be handled by the filetype plugin that might have some problems with syntax off

**Comment by theHamsta** [comment] 2023-02-25 19:37
Closing this as duplicate of #2499 #1136 (out Python indent module doesn't work well) and #3793 (tree-sitter breaks python indentation event if  indentation is turned off)

**Closed by theHamsta** 2023-02-25 19:37 UTC
Labels: bug
