### ISSUE TITLE
Commenting & undoing with (tcomment or vim-commentary) is really really slow & locks the editor.

### ISSUE THREAD

**Issue by ahmedelgabri** [nvim-treesitter/nvim-treesitter#1251] opened 2021-04-25 12:41 UTC
**Describe the bug**

Commenting or uncommenting with tcomment or vim-commentary are very slow.

**To Reproduce**

1. Install https://github.com/tomtom/tcomment_vim or https://github.com/tpope/vim-commentary
2. Visually select some text (the bigger the selection the slower it gets) 
3. Try to comment `gc`& `u` undo 
4. It should be very slow (especially the undo)
5. Uninstall treesitter & repeat steps 2-4 it should be nearly instantaneous 

These demos are using `tcomment_vim` but the same exact behaviour is happening with `vim-commentary` too

You can see at the bottom right how much it took after I typed `u` & the command hanging there locking the editor

https://user-images.githubusercontent.com/63876/115993537-9451bf80-a5d3-11eb-944f-ce1d818cee9c.mp4

This one is nearly instantaneous which how it used to work.

https://user-images.githubusercontent.com/63876/115993544-9b78cd80-a5d3-11eb-800a-9720a9ffc669.mp4

**Expected behavior**

Shouldn't be slow.

**Output of `:checkhealth nvim_treesitter`**

<details>
<pre><code>health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: 'tree-sitter' executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v14.16.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - ruby           ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . 
  - nix            ✓ ✓ ✓ . 
  - php            ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ 
  - regex          ✓ . . . 
  - json           ✓ ✓ ✓ ✓ 
  - kotlin         ✓ . . . 
  - beancount      ✓ . ✓ . 
  - yaml           ✓ ✓ ✓ ✓ 
  - graphql        ✓ . . ✓ 
  - html           ✓ ✓ ✓ ✓ 
  - latex          ✓ . ✓ . 
  - glimmer        ✓ . . . 
  - rust           ✓ ✓ ✓ ✓ 
  - bibtex         ✓ . ✓ ✓ 
  - clojure        ✓ ✓ . . 
  - c              ✓ ✓ ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . 
  - go             ✓ ✓ ✓ ✓ 
  - zig            ✓ ✓ ✓ ✓ 
  - r              ✓ ✓ . . 
  - ocaml_interface✓ ✓ ✓ . 
  - svelte         ✓ . ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ 
  - turtle         ✓ ✓ ✓ ✓ 
  - c_sharp        ✓ . . . 
  - rst            ✓ ✓ . . 
  - julia          ✓ ✓ . . 
  - css            ✓ . ✓ ✓ 
  - vue            ✓ . ✓ . 
  - teal           ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ 
  - dart           ✓ ✓ . ✓ 
  - verilog        ✓ ✓ ✓ . 
  - fennel         ✓ ✓ . . 
  - ql             ✓ ✓ . ✓ 
  - toml           ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . 
  - ledger         ✓ . ✓ ✓ 
  - jsdoc          ✓ . . . 
  - jsonc          ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ 
  - sparql         ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}</code></pre>
</details>

**Output of `nvim --version`**

<details>
<pre><code>NVIM v0.5.0-dev+nightly-172-gbb7d3790b
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210425-72946-p7j3of/build/config -I/tmp/neovim-20210425-72946-p7j3of/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210425-72946-p7j3of/build/src/nvim/auto -I/tmp/neovim-20210425-72946-p7j3of/build/include
Compiled by ahmed@pandoras-box

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-bb7d379_2/share/nvim"

Run :checkhealth for more info</code></pre>
</details>

**Additional context**

**Comment by stsewd** [comment] 2021-04-25 16:09
I was able to replicate this with a lua file, I think this is due that each line `--`  is a comment, so treesitter creates a tree for each line (for the comment parser). When uncomenting I think the slowness may be due to destroying each tree, not sure. Looks like using `@combined` helps a little.

**Comment by stsewd** [comment] 2021-04-25 16:18
Let us know if https://github.com/nvim-treesitter/nvim-treesitter/pull/1252 makes things more faster

**Comment by ahmedelgabri** [comment] 2021-04-25 16:47
@stsewd #1252 fixed the issue, yes. Thanks!

**Comment by stsewd** [comment] 2021-05-07 16:56
We had to revert this change as the plugin isn't ready to make use of `@combined` https://github.com/nvim-treesitter/nvim-treesitter/pull/1266. Re-opening.

**Comment by stsewd** [comment] 2021-06-26 19:47
I'm closing this in favor of https://github.com/nvim-treesitter/nvim-treesitter/issues/1267 since the root cause is the same.

**Closed by stsewd** 2021-06-26 19:47 UTC
Labels: bug
