### ISSUE TITLE
Error when editing new .cpp and .h files.

### ISSUE THREAD

**Issue by ErlanRG** [nvim-treesitter/nvim-treesitter#5304] opened 2023-08-23 04:38 UTC
### Describe the bug

I get the following error message when editing a `.cpp` or `.h` file.
I decided to start a program in C++ after a long time, so I can't remember if this happened to the `.h` files, but  I am completely sure this didn't  happen with the `.cpp` before.

```
Error detected while processing BufNewFile Autocommands for "*":
Error executing lua callback: /usr/local/share/nvim/runtime/filetype.lua:21: Error executing lua: /usr/local/share/nvim/runtime/filetype.lua:22: BufNewFile Autocommands for "*"..FileType Autocommands for "*": Vim(append):Error executing lua callback: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 338 for language cpp
stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get_query'
        .../share/nvim/lazy/nvim-ts-rainbow2/lua/ts-rainbow/lib.lua:70: in function 'get_query'
        ...are/nvim/lazy/nvim-ts-rainbow2/lua/ts-rainbow/module.lua:30: in function 'is_supported'
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:387: in function 'is_enabled'
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:507: in function 'attach_module'
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:132>
        [C]: in function 'nvim_cmd'
        /usr/local/share/nvim/runtime/filetype.lua:22: in function </usr/local/share/nvim/runtime/filetype.lua:21>
        [C]: in function 'nvim_buf_call'
        /usr/local/share/nvim/runtime/filetype.lua:21: in function </usr/local/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_cmd'
        /usr/local/share/nvim/runtime/filetype.lua:22: in function </usr/local/share/nvim/runtime/filetype.lua:21>
        [C]: in function 'nvim_buf_call'
        /usr/local/share/nvim/runtime/filetype.lua:21: in function </usr/local/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/local/share/nvim/runtime/filetype.lua:21: in function </usr/local/share/nvim/runtime/filetype.lua:10>

```

### To Reproduce

1. Create either a .cpp or a .h (or both) files
2. Edit the file.

### Expected behavior

Not having this error when editing any buffer with the extensions mentioned before.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v16.20.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.4.11-arch2-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Sat, 19 Aug 2023 15:38:34 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - norg                . . . . .
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.1692616192

    system vimrc file: "$VIM/sysinit.vim"
   fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

* I tested this on two different machines with different neovim versions and the same thing happens. Both have the latest nvim-treesitter version and `c` / `cpp` parsers.
On the other one, the `nvim --version` output is:

```
NVIM v0.10.0-dev-347+g6b19170d4
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DNVIM_LOG_DEBUG -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/home/rangeler/Repos/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/rangeler/Repos/neovim/.deps/usr/include -I/home/rangeler/Repos/neovim/build/src/nvim/auto -I/home/rangeler/Repos/neovim/build/include -I/home/rangeler/Repos/neovim/build/cmake.config -I/home/rangeler/Repos/neovim/src -I/usr/include -I/home/rangeler/Repos/neovim/.deps/usr/include -I/home/rangeler/Repos/neovim/.deps/usr/include -I/home/rangeler/Repos/neovim/.deps/usr/include -I/home/rangeler/Repos/neovim/.deps/usr/include -I/home/rangeler/Repos/neovim/.deps/usr/include -I/home/rangeler/Repos/neovim/.deps/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
Same `:checkhealth` output as well.

* `nvim-treesitter` working as expected on other languages.

**Comment by clason** [comment] 2023-08-23 04:40
Duplicate of #3092

**Comment by clason** [comment] 2023-08-23 04:41
Check nvim-tsrainbow2 for incompatible queries

**Closed by clason** 2023-08-23 04:40 UTC
Labels: bug

**Comment by ErlanRG** [comment] 2023-08-23 05:08
Thanks for the heads up. I will check this out.
