### ISSUE TITLE
Lua parser install error

### ISSUE THREAD

**Issue by aspeddro** [nvim-treesitter/nvim-treesitter#2309] opened 2022-01-20 14:06 UTC
### Describe the bug

`:TSInstall lua` 

![image](https://user-images.githubusercontent.com/16160544/150353218-4661a5cf-882e-48ce-a697-a4503d2696f6.png)

### To Reproduce

1. Use the following config:
  ```lua
  require 'nvim-treesitter.install'.prefer_git = true
  ```

2. Run `:TSInstall lua`

### Expected behavior

Lua parser should be installed with no error

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.2 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.3.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - python         ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - latex          ✓ . ✓ . ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - regex          ✓ . . . . 
  - rescript       ✓ . . . ✓ 
  - markdown       ✓ . ✓ . ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - vim            ✓ ✓ . . ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - bibtex         ✓ . ✓ ✓ . 
  - r              ✓ ✓ . . . 
  - julia          ✓ ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - haskell        ✓ . . . ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment] 2022-01-20 14:09
Cannot reproduce. What's your version? Did you _uninstall_ the parser before reinstalling?

**Comment by aspeddro** [comment] 2022-01-20 14:15
`TSUninstall lua` and `TSInstall lua` works. Reinstall with `TSInstall lua` raise a error.

Version: `d0158c053d01de1bcb618d7899bd8e38ce154430`

**Comment by theHamsta** [comment] 2022-01-20 14:17
This bug occurs when the parser installation was successful but loading the  queries fails (e.g. plugins, user queries)

**Comment by clason** [comment] 2022-01-20 17:45
Duplicate of https://github.com/nvim-treesitter/nvim-treesitter/issues/2295, then.

**Closed by clason** 2022-01-20 17:45 UTC
Labels: bug
