### ISSUE TITLE
Problems with Tsserver and HTML

### ISSUE THREAD

**Issue by leandrofmoraes** [nvim-treesitter/nvim-treesitter#6792] opened 2024-06-20 21:32 UTC
### Describe the bug

E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 13:4. Invalid node type "function":
  (function "function" @open.function)
   ^

stack traceback:
	[C]: in function '_ts_parse_query'
	/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
	/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
	/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get_query'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:55: in function 'get_query'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:142: in function 'prepare_query'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:339: in function 'iter_group_results'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:351: in function 'collect_group_results'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:23: in function 'update_cached_matches'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:31: in function 'get_matches'
	.../nvim/lazy/vim-matchup/lua/treesitter-matchup/syntax.lua:26: in function 'get_skips'
	.../nvim/lazy/vim-matchup/lua/treesitter-matchup/syntax.lua:60: in function 'lang_skip'
	[string "luaeval()"]:1: in main chunk
line    1:
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 13:4. Invalid node type "function":
  (function "function" @open.function)
   ^

stack traceback:
	[C]: in function '_ts_parse_query'
	/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
	/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
	/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get_query'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:55: in function 'get_query'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:142: in function 'prepare_query'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:339: in function 'iter_group_results'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:351: in function 'collect_group_results'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:23: in function 'update_cached_matches'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:31: in function 'get_matches'
	.../nvim/lazy/vim-matchup/lua/treesitter-matchup/syntax.lua:26: in function 'get_skips'
	.../nvim/lazy/vim-matchup/lua/treesitter-matchup/syntax.lua:60: in function 'lang_skip'
	[string "luaeval()"]:1: in main chunk
line    1:
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 13:4. Invalid node type "function":
  (function "function" @open.function)
   ^

stack traceback:
	[C]: in function '_ts_parse_query'
	/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
	/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
	/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get_query'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:55: in function 'get_query'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:142: in function 'prepare_query'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:339: in function 'iter_group_results'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:351: in function 'collect_group_results'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:23: in function 'update_cached_matches'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:31: in function 'get_matches'
	.../nvim/lazy/vim-matchup/lua/treesitter-matchup/syntax.lua:26: in function 'get_skips'
	.../nvim/lazy/vim-matchup/lua/treesitter-matchup/syntax.lua:60: in function 'lang_skip'
	[string "luaeval()"]:1: in main chunk
line    1:
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 13:4. Invalid node type "function":
  (function "function" @open.function)
   ^

stack traceback:
	[C]: in function '_ts_parse_query'
	/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
	/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
	/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get_query'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:55: in function 'get_query'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:142: in function 'prepare_query'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:339: in function 'iter_group_results'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:351: in function 'collect_group_results'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:23: in function 'update_cached_matches'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:31: in function 'get_matches'
	.../nvim/lazy/vim-matchup/lua/treesitter-matchup/syntax.lua:26: in function 'get_skips'
	.../nvim/lazy/vim-matchup/lua/treesitter-matchup/syntax.lua:60: in function 'lang_skip'
	[string "luaeval()"]:1: in main chunk
line    1:
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 13:4. Invalid node type "function":
  (function "function" @open.function)
   ^

stack traceback:
	[C]: in function '_ts_parse_query'
	/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
	/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
	/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get_query'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:55: in function 'get_query'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:142: in function 'prepare_query'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:339: in function 'iter_group_results'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:351: in function 'collect_group_results'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:23: in function 'update_cached_matches'
	...vim-matchup/lua/treesitter-matchup/third-party/query.lua:31: in function 'get_matches'
	.../nvim/lazy/vim-matchup/lua/treesitter-matchup/syntax.lua:26: in function 'get_skips'
	.../nvim/lazy/vim-matchup/lua/treesitter-matchup/syntax.lua:60: in function 'lang_skip'
	[string "luaeval()"]:1: in main chunk

Erro detectado ao processar WinEnter Autocommands for "*"..function 4[71]..matchup#delim#get_current[1]..<SNR>46_get_delim_multi[3]..<SNR>46_get_delim[165]..matchup#delim#skip[13]..matchup#ts_syntax#skip_expr[1]..matchup#ts_syntax#lang_skip[1]..<SNR>73_forward:

### To Reproduce

The error message appears when trying to edit any file using typescript-language-server. (Javascript or typescript files). If I try to use the latest release of nvim-treesitter, the error with javascript files disappears but I can't edit any html files. when trying to write something, neovim suddenly closes.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.15.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 14.1.1 20240522
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.8.12-3-MANJARO",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Mon Jun 10 09:44:22 UTC 2024"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - bp                  ✓ ✓ ✓ ✓ ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - diff                ✓ . . . .
  - dockerfile          x . . . x
  - git_config          ✓ . ✓ . ✓
  - git_rebase          ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - idl                 ✓ . . . ✓
  - inko                ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - koto                ✓ ✓ ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - luap                ✓ . . . .
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - ralph               ✓ . . . ✓
  - ssh_config          ✓ ✓ ✓ ✓ ✓
  - tact                ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - typespec            ✓ . . ✓ ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR dockerfile(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'dockerfile': uv_dlopen: no error
  dockerfile(highlights) is concatenated from the following files:
  | [ERROR]:"/home/leandro-f/.local/share/nvim/lazy/nvim-treesitter/queries/dockerfile/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'dockerfile': uv_dlopen: no error
- ERROR dockerfile(injections): /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'dockerfile': uv_dlopen: no error
  dockerfile(injections) is concatenated from the following files:
  | [ERROR]:"/home/leandro-f/.local/share/nvim/lazy/nvim-treesitter/queries/dockerfile/injections.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'dockerfile': uv_dlopen: no error
```

### Output of `nvim --version`

```text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478
```

### Additional context

This is my configuration file
```
return {
  -- nvim-treesitter
  {
    'nvim-treesitter/nvim-treesitter',
    -- commit = '9a7ad2f', --Temporary fix for treesitter issue
    -- commit = 'e5af2d7fdcdcbafd75e0bdb4e53d3be55c5761c4',
    commit = '7b04b398f868563cac37ae90baffd7c3dca513fe',
    build = ':TSUpdate',
    event = { 'BufReadPost', 'BufNewFile' },
    opts = {
      ensure_installed = {
        'lua',
        'luadoc',
        'luap',
        'cpp',
        'java',
        'markdown',
        'markdown_inline',
        'git_config',
        'git_rebase',
        'gitcommit',
        'gitignore',
        -- 'gitattributes',
        'diff',
        -- 'vim',
        'vimdoc',
        -- 'regex',
        'bash',
        'toml',
        'ssh_config',
      },
      -- highlight = { enable = true },
      highlight = {
        enable = true,
        use_languagetree = true,
        additional_vim_regex_highlighting = false,
      },
      context_commentstring = {
        enable = true,
        enable_autocmd = false,
        config = {
          -- Languages that have a single comment style
          typescript = "// %s",
          css = "/* %s */",
          scss = "/* %s */",
          html = "<!-- %s -->",
          svelte = "<!-- %s -->",
          vue = "<!-- %s -->",
          json = "",
        },
      },
      -- indent = { enable = true },
      indent = { enable = true, disable = { "yaml", "python" } },
      autotag = { enable = false },

      -- Automatically install missing parsers when entering buffer
      auto_install = true,
      -- vim-matchup config
      matchup = { enable = false, include_match_words = true, enable_quotes = true }, -- disabled to fix issue with javascript module

    },
    config = function(_, opts)
      require('nvim-treesitter.configs').setup(opts)
      -- Use the bash ts parser for zsh
      vim.treesitter.language.register('bash', 'zsh')
    end,
  },

  -- nvim-treesitter-context
  -- {
  --   'nvim-treesitter/nvim-treesitter-context',
  --   dependencies = 'nvim-treesitter/nvim-treesitter',
  --   event = { 'BufReadPost', 'BufNewFile' },
  --   config = true,
  -- },

  -- vim-matchup
  {
    'andymass/vim-matchup',
    dependencies = 'nvim-treesitter/nvim-treesitter',
    event = { 'BufReadPost', 'BufNewFile' },
    config = function()
      vim.g.matchup_matchparen_offscreen = {}
      vim.g.matchup_matchparen_deferred = 1
    end,
  },

  -- treesj
  {
    -- enabled = false,
    'Wansmer/treesj',
    dependencies = 'nvim-treesitter/nvim-treesitter',
    opts = { max_join_length = 500 },
    keys = {
      -- stylua: ignore start
      { 'g/m', function() return require('treesj').toggle() end, desc = 'Toggle' },
      { 'g/j', function() return require('treesj').join() end,   desc = 'Join' },
      { 'g/s', function() return require('treesj').split() end,  desc = 'Split' },
      -- stylua: ignore end
    },
  },

  -- rainbow-delimiters.nvim
  {
    --   'hiphish/rainbow-delimiters.nvim',
    'HiPhish/rainbow-delimiters.nvim',
    dependencies = 'nvim-treesitter/nvim-treesitter',
    event = { 'BufReadPost', 'BufNewFile' },
  },

  -- { "p00f/nvim-ts-rainbow" },

  -- indent-blankline.nvim
  {
    'lukas-reineke/indent-blankline.nvim',
    main = 'ibl',
    -- commit = "3d08501caef2329aba5121b753e903904088f7e6", -- release v3.5.4
    dependencies = 'nvim-treesitter/nvim-treesitter',
    event = { 'BufReadPost', 'BufNewFile' },
    opts = {
      indent = { char = '│', tab_char = '│' },
      scope = { enabled = false },
      exclude = { filetypes = { 'lazy', 'dashboard', 'mason' } },
    },
  },
}
```

**Comment by clason** [comment] 2024-06-20 21:50
Duplicate of #3092

**Closed by clason** 2024-06-20 21:50 UTC
Labels: bug
