### ISSUE TITLE
Input lag on large TypeScript file

### ISSUE THREAD

**Issue by chmln** [nvim-treesitter/nvim-treesitter#1275] opened 2021-05-05 01:50 UTC
**Describe the bug**

There is input lag on a large-ish file (3K lines).
I have removed plugins one by one, and tree-sitter happens to be the culprit

**To Reproduce**

1. Download https://raw.githubusercontent.com/flatpickr/flatpickr/master/src/index.ts
2. Set up high keyboard repeat rate if haven't already: `xset r rate 250 85`
3. Open the file and go to some line like 77
4. Press and hold 'a'

**Expected behavior**

No lag.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.4 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.1.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - c_sharp        ✓ . . . 
  - svelte         ✓ . ✓ ✓ 
  - beancount      ✓ . ✓ . 
  - c              ✓ ✓ ✓ ✓ 
  - fortran        ✓ . ✓ . 
  - teal           ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ 
  - python         ✓ ✓ ✓ ✓ 
  - sparql         ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . 
  - gomod          ✓ . . . 
  - dart           ✓ ✓ . ✓ 
  - lua            ✓ ✓ ✓ ✓ 
  - zig            ✓ ✓ ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . 
  - go             ✓ ✓ ✓ ✓ 
  - bibtex         ✓ . ✓ ✓ 
  - haskell        . . . . 
  - yaml           ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ 
  - jsdoc          ✓ . . . 
  - ledger         ✓ . ✓ ✓ 
  - php            ✓ ✓ ✓ ✓ 
  - julia          ✓ ✓ . . 
  - supercollider  ✓ ✓ ✓ ✓ 
  - latex          ✓ . ✓ . 
  - r              ✓ ✓ . . 
  - turtle         ✓ ✓ ✓ ✓ 
  - devicetree     ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ 
  - gdscript       ✓ ✓ . . 
  - nix            ✓ ✓ ✓ . 
  - jsonc          ✓ ✓ ✓ ✓ 
  - regex          ✓ . . . 
  - verilog        x x x . 
  - swift          . . . . 
  - ql             ✓ ✓ . ✓ 
  - fennel         ✓ ✓ . . 
  - rst            ✓ ✓ . . 
  - query          ✓ ✓ ✓ ✓ 
  - elm            . . . . 
  - cpp            ✓ ✓ ✓ ✓ 
  - graphql        ✓ . . ✓ 
  - kotlin         ✓ . . . 
  - ruby           ✓ ✓ ✓ ✓ 
  - vue            ✓ . ✓ . 
  - ocamllex       ✓ . . . 
  - scala          . . . . 
  - toml           ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ 
  - ocaml_interface✓ ✓ ✓ . 
  - bash           ✓ ✓ ✓ . 
  - javascript     ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ 
  - glimmer        ✓ . . . 
  - erlang         . . . . 
  - clojure        ✓ ✓ . . 
  - scss           ✓ . . ✓ 
  - tsx            ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

The following errors have been detected:
  - ERROR: verilog(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/greg/.local/share/nvim/site/parser/verilog.so: supported between 13 and 13, found 12
  - ERROR: verilog(locals): /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/greg/.local/share/nvim/site/parser/verilog.so: supported between 13 and 13, found 12
  - ERROR: verilog(folds): /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/greg/.local/share/nvim/site/parser/verilog.so: supported between 13 and 13, found 12

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+1295-g3fc71ea22
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/greg/.cache/yay/neovim-nightly-git/src/build/config -I/home/greg/.cache/yay/neovim-nightly-git/src/neovim-nightly-git/src -I/usr/include -I/home/greg/.cache/yay/neovim-nightly-git/src/build/src/nvim/auto -I/home/greg/.cache/yay/neovim-nightly-git/src/build/include
Compiled by greg@laptop

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

My TS config:

```lua
packer.use {"nvim-treesitter/nvim-treesitter", run = ":TSUpdate"}

require "nvim-treesitter.configs".setup {
  ensure_installed = "all",
  highlight = {
    enable = true
  },
  indent = {
    enable = true
  },
}
```

**Comment by theHamsta** [comment] 2021-05-05 03:38
We're having performance problems with the jsdoc and the comment parser. Can you try to remove the two with TSUninstall?

**Comment by chmln** [comment] 2021-05-05 20:48
@theHamsta thanks for the quick response!
I uninstalled both and added them to the ignored parsers list, but the problem still persists.

Let me know if there's anything I could help with. 
Everything has been working perfectly until recently.

**Comment by stsewd** [comment] 2021-05-06 00:46
@chmln can you try https://github.com/nvim-treesitter/nvim-treesitter/pull/1266?

**Comment by chmln** [comment] 2021-05-06 01:14
@stsewd Yes that's a slight improvement. But sadly the stutter is still there

**Comment by chmln** [comment] 2021-05-06 22:14
Also here's a video illustration of the problem.

https://user-images.githubusercontent.com/11352152/117371907-b03c4780-ae96-11eb-83f3-64fe927f91da.mp4

**Comment by stsewd** [comment] 2021-05-07 01:48
That looks fast for me :laughing:, I guess that's just slowness from treesitter in general or the queries, since the tree is updated on each change.

**Comment by CaptainKO** [comment] 2021-07-26 08:16
https://user-images.githubusercontent.com/32269291/126956146-4486edf2-2535-4795-a5e9-26f601b3356e.mp4

Hi @stsewd, please check this out. I think there must be something wrong with backtick functions.

**Comment by kyazdani42** [comment] 2021-08-07 22:44
this looks like its related to the typescript parser itself.

**Comment by i3d** [comment] 2021-08-24 05:36
I've noticed this in go files (6000+) and rust files (3000+). Disable highlight made dramatic difference.

**Comment by echovl** [comment] 2022-06-24 20:28
same problem here, the only solution is to disable highlight in big files

**Comment by rodhash** [comment] 2022-07-23 19:57
JS files with huge lines are so slow, is this related to this issue too?

ie:

Running "npm run build" in a React app, which makes a JS file with huuuge line. My nvim goes from a blazingly fast tool to something around 10s to load the file + 17s to move from one line to another.


Disabling the syntax highlighting (as said above) also works around my issue.

So was wondering .. Is this the same issue? Or related?

**Comment by kyazdani42** [comment] 2022-07-25 11:45
This is expected. parsing the files is not yet asynchronous or partial, so that will be slow.

**Comment by lewis6991** [comment] 2023-02-24 10:41
Any update here? Does https://github.com/neovim/neovim/pull/22309 help with performance?

**Comment by ramonbakker** [comment] 2023-08-18 09:10
I experience input lag even when a file is not so large, but makes use of the @angular/localize package (see https://angular.io/api/localize#angularlocalize). When I use an alias for the $localize import or when I disable the highlight module with `:TSBufDisable highlight`, the input lag is gone.

Relevant issue: https://github.com/tree-sitter/tree-sitter-typescript/issues/179

**Comment by lewis6991** [comment] 2023-08-18 09:49
Are you able to retry with Neovim nightly? https://github.com/neovim/neovim/pull/24647 make injection handling much more efficient.

**Comment by lewis6991** [comment] 2023-08-18 10:12
I just downloaded https://raw.githubusercontent.com/flatpickr/flatpickr/master/src/index.ts and made lots of text edits.

Seems fine.

**Comment by lewis6991** [comment] 2023-08-18 10:13
I'm going to close this since I can't reproduce and the issue is old.

If this is still a problem please open a new issue with precise reproduction steps.

**Closed by lewis6991** 2023-08-18 10:13 UTC
Labels: bug, performance

**Comment by ramonbakker** [comment] 2023-08-21 06:09
I downgraded Neovim to version 0.9.1, in which the issue does not occur.
