### ISSUE TITLE
No parser available for typescriptreact

### ISSUE THREAD

**Issue by ic-768** [nvim-treesitter/nvim-treesitter#7201] opened 2024-09-30 14:04 UTC
### Describe the bug

After updating, I suddenly don't get syntax highlighting in .tsx files, and I get the error `No parser available for typescriptreact`. Reverting to a previous version fixes this.

### To Reproduce

Tree sitter configuration:

```
return {
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		opts = {
			highlight = { enable = true },
		},
		config = function()
			local configs = require("nvim-treesitter.configs")

			configs.setup({
				ensure_installed = { "typescript", "tsx", "javascript", "html", "lua" },
				sync_install = false,
				highlight = { enable = true },
				indent = { enable = true },
			})
		end,
	},
	"nvim-treesitter/nvim-treesitter-context",
}
```

Open any .tsx file the error pops up

### Output of `:checkhealth nvim-treesitter`

```markdown
nstallation
    5 - WARNING tree-sitter executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
    6 - OK node found v18.18.0 (only needed for :TSInstallFromGrammar)
    7 - OK git executable found.
    8 - OK cc executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    9   Version: cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
   10 - OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.
   11
   12 OS Info:
   13 {
   14   machine = "x86_64",
   15   release = "6.8.0-45-generic",
   16   sysname = "Linux",
   17   version = "#45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Sep 11 15:25:05 UTC 2"
   18 }
   19
   20 Parser/Features         H L F I J
   21   - c                   ✓ ✓ ✓ ✓ ✓
   22   - html                ✓ ✓ ✓ ✓ ✓
   23   - javascript          ✓ ✓ ✓ ✓ ✓
   24   - lua                 ✓ ✓ ✓ ✓ ✓
   25   - markdown            ✓ . ✓ ✓ ✓
   26   - markdown_inline     ✓ . . . ✓
   27   - python              ✓ ✓ ✓ ✓ ✓
   28   - query               ✓ ✓ ✓ ✓ ✓
   29   - tsx                 ✓ ✓ ✓ ✓ ✓
   30   - typescript          ✓ ✓ ✓ ✓ ✓
   31   - vim                 ✓ ✓ ✓ . ✓
   32   - vimdoc              ✓ . . . ✓
   33
   34   Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
   35          +) multiple parsers found, only one will be used
   36          x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.11.0-dev-475+g5fc25ecc7
Build type: RelWithDebInfo
LuaJIT 2.1.1720049189
Run "nvim -V1 -v" for more info
```

**Comment by seblj** [comment] 2024-09-30 16:52
You need to update your neovim nightly: 

https://github.com/nvim-treesitter/nvim-treesitter/commit/140f534ce9c02189921b80f5c8a68ab9e3f92ce8
https://github.com/neovim/neovim/commit/041d98fe8d892a81ed659c32be5360d4f80e7d18

**Comment by ribru17** [comment] 2024-09-30 16:55
This will fix the error, but I believe we made a mistake because even updating nightly provides no highlighting for such files (and all files with parsername != filetypename)...

**Comment by clason** [comment] 2024-09-30 20:11
No, my bad. Closed by #7202

**Comment by GitMurf** [comment] 2024-09-30 23:53
@clason I can certainly open a new GH Issue, but this seems very similar. I am getting this error for powershell files when typing. Based off the call stack it seems like it may be initiating from nvim-cmp completion and maybe the markdown from the popup window?

```
.../treesitter/languagetree.lua:111: No parser for language "ps1"
```

If you do not think this is related, I will open a new GH Issue. Thanks!

![image](https://github.com/user-attachments/assets/431d35ad-ba1f-4337-abe3-11fbd307bc98)

**Comment by GitMurf** [comment] 2024-10-01 00:01
cc @folke as it seems when I remove the Noice lsp override for `vim.lsp.util.stylize_markdown` that this error goes away.

**Comment by ribru17** [comment] 2024-10-01 00:07
@GitMurf would you mind updating this plugin and retrying?

**Closed** 2024-10-01 00:06 UTC
Labels: bug

**Comment by GitMurf** [comment] 2024-10-01 00:21
> @GitMurf would you mind updating this plugin and retrying?

@ribru17 I can confirm that BOTH the original post tsx error and my new powershell / ps1 error are fixed with the merged update!! I was also experiencing the tsx issue and now no more errors, so can confirm both are fixed with this :-)

Thanks for getting on this so quickly!
