### ISSUE TITLE
Wrong indentation after JavaScript multiline function arguments

### ISSUE THREAD

**Issue by frangio** [nvim-treesitter/nvim-treesitter#1448] opened 2021-06-28 23:51 UTC
When function arguments are placed on separate lines, the first line of the function body is not properly indented.

```javascript
function foo(
  a,
) {
| <- inferred indent level
```

**Output of `nvim --version`**

<details>
<code>
NVIM v0.5.0-dev+1420-gc78816eb6
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/frangio/.cache/yay/neovim-git/src/build/config -I/home/frangio/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/frangio/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/frangio/.cache/yay/neovim-git/src/build/include
Compiled by frangio@godard

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
</code>
</details>

**Comment by jinh0** [comment] 2021-06-29 12:09
Can confirm this is happening to me as well on the latest version of `nvim-treesitter` and up-to-date parsers!

**Comment by yujinyuz** [comment] 2021-06-30 00:12
Might be related to #1370 as well

**Comment by LeviOP** [comment] 2024-02-02 15:31
fixed in https://github.com/nvim-treesitter/nvim-treesitter/commit/3b8c2ea492917fcb3c0e88ad6682dbd355cc0644. cannot reproduce

**Closed** 2024-02-02 15:33 UTC
Labels: bug, indent
