### ISSUE TITLE
"Error executing vim.schedule lua callback, invalid node type at position 196 for language bash" when file is Makefile

### ISSUE THREAD

**Issue by vincer2040** [nvim-treesitter/nvim-treesitter#6536] opened 2024-04-29 15:31 UTC
### Describe the bug

When I open a Makefile, I get error 
`Error executing lua: /usr/local/share/nvim/runtime/filetype.lua:22:
 function <SNR>38_NetrwBrowseChgDir[197]..BufReadPost Autocommands for "*"..FileType Autocommands for "*": Vim(append):Error executing lua callb
ack: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 196 for language bash`

### To Reproduce

create makefile 

```Makefile
.PHONY: test
test:
	go test ./...
```

view the error

### Output of `:checkhealth nvim-treesitter`

```markdown
Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.9.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.8.7-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000"
} ~

Parser/Features         H L F I J
  - bash                x ✓ ✓ . x
  - c                   ✓ ✓ ✓ ✓ ✓
  - cmake               ✓ . ✓ ✓ .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . . . .
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . .
  - go                  ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - ocaml               ✓ ✓ ✓ ✓ ✓
  - python              x ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR bash(highlights): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 280 for language bash
  bash(highlights) is concatenated from the following files:
  | [ERROR]:"/home/vince/.local/share/nvim/lazy/nvim-treesitter/queries/bash/highlights.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 280 for language bash
- ERROR bash(injections): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 196 for language bash
  bash(injections) is concatenated from the following files:
  | [ERROR]:"/home/vince/.local/share/nvim/lazy/nvim-treesitter/queries/bash/injections.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 196 for language bash
- ERROR python(highlights): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 648 for language python
  python(highlights) is concatenated from the following files:
  | [ERROR]:"/home/vince/.local/share/nvim/lazy/nvim-treesitter/queries/python/highlights.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 648 for language python
```

### Output of `nvim --version`

```text
NVIM v0.9.2
Build type: Debug
LuaJIT 2.1.1692716794
Compilation: /usr/lib/clang/ccc-analyzer -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DNVIM_LOG_DEBUG -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/vince/apps/packages/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/vince/apps/packages/neovim/.deps/usr/include -I/home/vince/apps/packages/neovim/build/src/nvim/auto -I/home/vince/apps/packages/neovim/build/include -I/home/vince/apps/packages/neovim/build/cmake.config -I/home/vince/apps/packages/neovim/src -I/usr/include -I/home/vince/apps/packages/neovim/.deps/usr/include -I/home/vince/apps/packages/neovim/.deps/usr/include -I/home/vince/apps/packages/neovim/.deps/usr/include -I/home/vince/apps/packages/neovim/.deps/usr/include -I/home/vince/apps/packages/neovim/.deps/usr/include -I/home/vince/apps/packages/neovim/.deps/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment] 2024-04-29 16:21
Duplicate of #3092

**Closed by clason** 2024-04-29 16:21 UTC
Labels: bug
