### ISSUE TITLE
Error executing lua .../lua/vim/treesitter/query.lua:119: query: error at position

### ISSUE THREAD

**Issue by RonanMacF** [nvim-treesitter/nvim-treesitter#759] opened 2020-12-11 13:16 UTC
**Describe the bug**
Running treesitter on any treesitter supported language provides an error immediately upon open and movement.

```
Error detected while processing FileType Autocommands for "*":                                                                                                                                     
E5108: Error executing lua ...y-master/share/nvim/runtime/lua/vim/treesitter/query.lua:119: query: error at position 3371
```
**To Reproduce**
1. use following init.vim
```
lua <<EOF  
require'nvim-treesitter.configs'.setup {
  ensure_installed = "all",
  highlight = {
    enable = true,              -- false will disable the whole extension
  },
}
EOF
```
2. nvim -u vimfile pythonFile.py
3. see errors

**Expected behavior**
tree sitter to work
**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## ruby parser healthcheck
  - OK: ruby parser found.
  - ERROR: Error in `highlights.scm` query found for ruby
    ...y-master/share/nvim/runtime/lua/vim/treesitter/query.lua:119: query: error at position 708
    - ADVICE:
      - Try `:TSUpdate ruby` (queries might have been adapted for a upstream parser change)
      - Try to find the syntax error/invalid node type in above file.
  - ERROR: Error in `locals.scm` query found for ruby
    ...y-master/share/nvim/runtime/lua/vim/treesitter/query.lua:119: query: error at position 1796
    - ADVICE:
      - Try `:TSUpdate ruby` (queries might have been adapted for a upstream parser change)
      - Try to find the syntax error/invalid node type in above file.
  - WARNING: No `folds.scm` query found for ruby
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for ruby
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## typescript parser healthcheck
  - OK: typescript parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for typescript
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## bash parser healthcheck
  - OK: bash parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `folds.scm` query found for bash
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for bash
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## tsx parser healthcheck
  - OK: tsx parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for tsx
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## scala parser healthcheck
  - OK: scala parser found.
  - WARNING: No `highlights.scm
</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: 
Compiled by nixbld1

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/k2yk51rh0ydz5l1mh018cq29lji4fizx-neovim-nightly-master/share/nvim"

Run :checkhealth for more info
```

**Additional context**
treesitter version: `76486942e79973095795e8699f95bb509e063d0d`

**Comment by vigoux** [comment] 2020-12-11 15:22
Hi, can you run `TSUpdate` and tell us if the error persist ?

**Comment by alemuller** [comment] 2020-12-11 15:22
This is caused when the query file contains a rule a rule not present in the parser.

Try running  `:TSUpdate`.

If you want to check what exactly is the issue, you can open the `query/lang/highlights.scm` and `:go 3371`

**Comment by RonanMacF** [comment] 2020-12-11 16:01
> Hi, can you run TSUpdate and tell us if the error persist ?

Sorry forgot to mention I ran that as per the instructions on the template.

> If you want to check what exactly is the issue, you can open the query/lang/highlights.scm and :go 3371

apparently it is on 
```
(lambda_parameters
  (tuple_pattern
    (identifier) @parameter))
```
although this is me testing it on a very simple python file with no lambda funcs. I have ensured the python file is well-formed also.

**Comment by alemuller** [comment] 2020-12-11 16:34
Does this error happens when you open an empty python file?

Are you editing a custom `grammar.js`? If not, try running `:TSInstallSync python`.

If this still don't work, could if the checksum of the parser and highlight are similar to mine (just to make sure we are in the same page):

```
$ md5sum  $YOUR_NVIM_PLUGIN_PATH/nvim-treesitter/parser/python.so
0d8d5a3f997bfda832a6b4f0e4af1a3a  nvim-treesitter/parser/python.so
$ md5sum $YOUR_NVIM_PLUGIN_PATH/nvim-treesitter/queries/python/highlights.scm
d293dd765f9503780aac9efb888d3619  nvim-treesitter/queries/python/highlights.scm
```

**Comment by RonanMacF** [comment] 2020-12-11 17:59
> Does this error happens when you open an empty python file?

interestingly yes

>Are you editing a custom grammar.js? If not, try running :TSInstallSync python.

nope all out of the box, ran that which reinstalled it but no change.

our md5 values are different. 
`MD5 (start/nvim-treesitter/queries/python/highlights.scm) = 564a314b83d9c0f426a405b2b183ff9b`

**Comment by alemuller** [comment] 2020-12-11 19:02
> >   Does this error happens when you open an empty python file?
>
> interestingly yes

That was the expected behavior. Just wanted to make sure it wasn't something else causing the error.

It seems the parser and highlight scheme are out of sync. Updating nvim-tressiter should solve your issue. I don't know enough of nvim-tree-sitter architecture to know if this post ia a feature request or a bug.

**Comment by vigoux** [comment] 2020-12-15 18:39
It is really weird that this issue occurs, following your `:checkhealth`, it seems that the parsers are you correctly installed, could you try running `TSInstall` ?

**Comment by RonanMacF** [comment] 2020-12-15 18:55
`TSInstall` seems to be acting up with a `string required` error now also. I tried `all` and it does nothing, `python` asks for confirmation and then gives error. I made an [asciicinema](https://asciinema.org/a/oZBLEXSJOjLFTSKAKcvKkJQAe)

I have had an issue before with Treesitter and it was because I was using nix so _potentially_ there might be something there. I'll push an update nvim-treesitter to nixpkgs and update here when I have it checked out.

**Comment by theHamsta** [comment] 2020-12-15 19:17
There is a PR on nvim-treesitter/playground that will display potential errors in the query files

**Comment by Stupremee** [comment] 2020-12-25 21:11
> `TSInstall` seems to be acting up with a `string required` error now also. I tried `all` and it does nothing, `python` asks for confirmation and then gives error. I made an [asciicinema](https://asciinema.org/a/oZBLEXSJOjLFTSKAKcvKkJQAe)
> 
> I have had an issue before with Treesitter and it was because I was using nix so _potentially_ there might be something there. I'll push an update nvim-treesitter to nixpkgs and update here when I have it checked out.

I have the same issue and I'm using Nix too (with home-manager). So it may be caused by Home-Manager

Everytime I open my vim and my lua config gets loaded, I get the following error, which will be fixed if I remove the nvim-treesitter setup call.

```
E5108: Error executing lua Vim:E928: String required
```

**Comment by theHamsta** [comment] 2020-12-25 21:45
> I tried all and it does nothing, python asks for confirmation and then gives error.

if python asks for confirmation, it's already installed. If all other languages are also installed, `TSInstall all` will do nothing.

There is a code path that is only used for nix (it uses nvim's site directory to install parsers in case the plugin directory is read-only).

**Comment by ngmoviedo** [comment] 2022-03-04 11:37
I'm experiencing a similar issue, if not the same, although it happens with Lua files.
When opening neovim, the following error is produced:
```
Error detected while processing FileType Autocommands for "*":
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid field at position 18
stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: in function 'get_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:37: in function 'new'
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:46: in function '_create_parser'
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:94: in function 'get_parser'
        .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:124: in function 'start'
        .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:130: in function 'attach'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:459: in function 'attach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:482: in function 'reattach_module'
        [string ":lua"]:1: in main chunk
```
I'm using the following init.vim

```vim
lua << EOF
require'nvim-treesitter.configs'.setup {
    ensure_installed = {
        "bash", "fish", "regex", "lua", "latex", "bibtex", "python", "html",
        "css", "typescript", "yaml", "java", "javascript"
    },
    highlight = {
        enable = true,
        disable = {"latex"} -- no highlighting for latex
    },
    indent = {enable = true},
    -- rainbow = {enable = true}
}
EOF
```
The error occurs inmediately when opening any lua file. Even an empty one. Neovim seems to work properly after that, although I only use treesitter for syntax highlighting, so some functions may not be working too.

### Output of `:checkhealth nvim_treesitter`:
```
nvim_treesitter: health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.6.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - css            ✓ . ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - bibtex         ✓ . ✓ ✓ . 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - latex          ✓ . ✓ . ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - regex          ✓ . . . . 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - lua            x x x x x 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: lua(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 503
    lua(highlights) is concatenated from the following files:
    | [ERROR]:"/home/nicolas/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/lua/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 503
  - ERROR: lua(locals): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 15
    lua(locals) is concatenated from the following files:
    | [ERROR]:"/home/nicolas/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/lua/locals.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 15
  - ERROR: lua(folds): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 92
    lua(folds) is concatenated from the following files:
    | [ERROR]:"/home/nicolas/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/lua/folds.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 92
  - ERROR: lua(indents): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 29
    lua(indents) is concatenated from the following files:
    | [ERROR]:"/home/nicolas/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/lua/indents.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 29
  - ERROR: lua(injections): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid field at position 18
    lua(injections) is concatenated from the following files:
    | [ERROR]:"/home/nicolas/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/lua/injections.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid field at position 18
```
### Output of `nvim --version`:

```
NVIM v0.7.0-dev+1182-ge23af71d3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az87-587

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"
```

**Comment by cseickel** [comment] 2022-04-11 14:59
I have the same problem:

```
:version
NVIM v0.7.0-dev+1434-gf89ca7194
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
```

```
nvim_treesitter: health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.19.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - lua            x x x x x 
  - comment        ✓ . . . . 
  - bash           ✓ ✓ ✓ . ✓ 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - json5          ✓ . . . ✓ 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - json           ✓ ✓ ✓ ✓ . 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - regex          ✓ . . . . 
  - dockerfile     ✓ . . . ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - r              ✓ ✓ . ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - vim            ✓ ✓ . . ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: lua(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 361
    lua(highlights) is concatenated from the following files:
    | [ERROR]:"/home/cseickel/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/lua/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 361
  - ERROR: lua(locals): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 15
    lua(locals) is concatenated from the following files:
    | [ERROR]:"/home/cseickel/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/lua/locals.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 15
  - ERROR: lua(folds): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 92
    lua(folds) is concatenated from the following files:
    | [ERROR]:"/home/cseickel/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/lua/folds.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 92
  - ERROR: lua(indents): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 29
    lua(indents) is concatenated from the following files:
    | [ERROR]:"/home/cseickel/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/lua/indents.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 29
  - ERROR: lua(injections): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid field at position 18
    lua(injections) is concatenated from the following files:
    | [ERROR]:"/home/cseickel/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/lua/injections.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid field at position 18
```

The interesting thing here is that I am running this in a docker container, and I use that same docker container with the same dotfiles (synced via git) on another computer without any issues. The only difference is the contents of my home directory, which is mounted into each one. Is there some kind of cache I can clear out that can be affecting the builds?

**Comment by clason** [comment] 2022-04-11 16:37
I strongly suspect that your lua parser is outdated. (Queries are tied to a specific parser version, and if you install parsers -- or queries _not_ by updating  `nvim-treesitter` through a package manager, you run a high risk of having an inconsistent state.

**Comment by cseickel** [comment] 2022-04-11 17:40
I checked and I am on the latest commit of `nvim-treesitter`. I do remember that there was a breaking change for the lua parser that I had issues with on one of my computers. I trued to uninstall and reinstall but it had no effect. Is there a manual way of making sure it is clean and I am on the latest for lua?

**Comment by clason** [comment] 2022-04-11 17:48
Same way as last time: just removing all traces of nvim-treesitter (and the parsers) and reinstalling from scratch. You can check if there are outdated parsers somewhere else via `:echo nvim_get_runtime_file('*/lua.so', v:true)`.

**Comment by cseickel** [comment] 2022-04-11 17:57
> You can check if there are outdated parsers somewhere else via `:echo nvim_get_runtime_file('*/lua.so', v:true)`.

Thank you! That command let me know that the `lua.so` file was still hanging around even after I uninstalled it. After I found and manually deleted that file, on the next startup it automtically installed the latest lua and everything works now.

**Closed** 2022-04-11 18:00 UTC
Labels: bug
