### ISSUE TITLE
invalid node type at position 4781 for language sql

### ISSUE THREAD

**Issue by qrockz** [nvim-treesitter/nvim-treesitter#5692] opened 2023-11-19 00:38 UTC
### Describe the bug

running `:checkhealth` get's me an ERROR regarding **sql** language

### To Reproduce

`:checkhealth`

### Expected behavior

nooooo errors

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (d4c1bf7ce78051b7f4a381d1508d68928512ed5f) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.6.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.15.0-86-generic",
  sysname = "Linux",
  version = "#96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - ini                 ✓ . ✓ . .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - sql                 x . . ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR sql(highlights): ...t/.local/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 4781 for language sql
  sql(highlights) is concatenated from the following files:
  | [ERROR]:"/home/t/.local/share/nvim/lazy/nvim-treesitter/queries/sql/highlights.scm", failed to load: ...t/.local/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 4781 for language sql
```

### Output of `nvim --version`

```text
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

```
:echo nvim_get_runtime_file('parser', v:true)
['/home/t/.local/share/nvim/lazy/nvim-treesitter/parser']
```

I've also done `:TSUpdate` but still get an error message after running `:checkhealth`

**Comment by amaanq** [comment] 2023-11-19 00:39
Duplicate of #3092

**Closed by amaanq** 2023-11-19 00:39 UTC
Labels: bug
