### ISSUE TITLE
query.lua:167 invalid start

### ISSUE THREAD

**Issue by pushqrdx** [nvim-treesitter/nvim-treesitter#528] opened 2020-09-25 20:02 UTC
**Describe the bug**
In c++ randomly highlighting breaks displaying `Error executinglua: ...query.lua:167: invalid start` sometimes it's invalid end instead

**To Reproduce**
1. Edit cpp files
2. ?
![image](https://user-images.githubusercontent.com/25884937/94311857-39dc7c00-ff7c-11ea-9681-4717dd4ebc24.png)

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>
## cpp parser healthcheck
  - OK: cpp parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - OK: `folds.scm` found.
</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-4a996bc43
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200925-73387-1i80kl9/build/config -I/tmp/neovim-20200925-73387-1i80kl9/src -I/usr/local/include -I/tmp/neovim-20200925-73387-1i80kl9/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200925-73387-1i80kl9/build/src/nvim/auto -I/tmp/neovim-20200925-73387-1i80kl9/build/include
Compiled by pushqrdx@Ahmeds-iMac.local

Features: +acl +iconv +tui
```

**Comment by vigoux** [comment] 2020-09-26 08:23
Hi ! Thanks for reporting !

This problem is actually the indication of the syntax tree and the buffer content getting out of sync. The problem is having the repro steps.

Furthermore, we (at nvim-treesitter) can't do that much about it in this repo, but in upstream neovim we can. Could you open an issue there ?

**Comment by akinsho** [comment] 2020-09-26 19:36
I've seen this issue quite a bit as well, the main way I've noticed that it happens is when the underlying buffer changes through a shell command specifically in my case when switching git branch, if the buffer's content is different on another branch then this error occurs.

**Comment by pushqrdx** [comment] 2020-09-27 14:13
@akinsho @vigoux my repro is pretty minimal i just open a c++ file then insert some text and undo/redo after a couple of times the issue happens. I tried to trace it and it seems like vim.regex is receiving an invalid index, hence the `invalid start` or `invalid end` so i wonder if that's on `nvim-treesitter`

**Comment by vigoux** [comment] 2020-09-27 16:57
`undo` and `luahl` (which is used to highlight things using tree-sitter), is pretty broken but will be fixed soon.
I think it it worth pinging @bfredl here, because this seems undo related.

**Comment by pushqrdx** [comment] 2020-09-27 19:39
@vigoux i think i have the undo (history) tree that is causing the issue saved, will that be helpful?

**Comment by vigoux** [comment] 2020-11-19 09:27
This issue is a duplicate of https://github.com/nvim-treesitter/nvim-treesitter/issues/651, please continue discussion there.

**Closed by vigoux** 2020-11-19 09:27 UTC
Labels: bug
