### ISSUE TITLE
Haskell TS module is taking all my memory and is crashing VIM

### ISSUE THREAD

**Issue by guibou** [nvim-treesitter/nvim-treesitter#1207] opened 2021-04-19 20:37 UTC
**Describe the bug**

Tree sitter on Haskell file just eat all my memory (15 GiB + 16 GiB of swap on SSD) in 5s and crashs vim.

**To Reproduce**

With the following `.vimrc` in `altvimrc`:

```vim
source ~/.vim/autoload/plug.vim
call plug#begin('~/.vim/plugged')

Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
call plug#end()

set foldmethod=expr
set foldexpr=nvim_treesitter#foldexpr()
```

(`plug.vim` from https://github.com/junegunn/vim-plug)

Note: I'm using `foldmethod` in order to trigger the failure at file opening, that's the smallest repro I can write.

The following `TestTS.hs` file:

```haskell
main = print "hello"
```

In an environment containing `gcc`, `tree-sitter` and `nodejs`. I used the following nix command: `nix-shell -p gcc -p tree-sitter -p nodejs` and then:

- `vim -u altvimrc`
- `:PlugInstall` (optional, restart vim if you do that for the first time)
- `:TSInstall haskell` ("press" `y` to reinstall if asked for)
- `:e TestTS.hs`

Vim will crash soon after eating all your RAM.

**Expected behavior**

Well, I'd like vim to not eat all my RAM (and optionally, use TreeSitter with haskell ;)

**Output of `:checkhealth nvim_treesitter`**
<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.3 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.16.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `gcc` executable found. Selected from { "gcc", "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - nix            ✓ ✓ ✓ . 
  - python         ✓ ✓ ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ 
  - haskell        . . . . 
  - c              ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
</code>
</details>

**Output of `nvim --version`**

<details>
<code>
NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: 
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/xc0pbpn511g1nyj12shgnm54aplyzj3q-neovim-unwrapped-master/share/nvim
"

Run :checkhealth for more info
</code>
</details>

**Additional context**

**Comment by theHamsta** [comment] 2021-04-19 20:41
But this should be an issue for tree-sitter-haskell. Before the complete rewrite it could not even parse the simplest programs. Don't know what is the current status.

**Comment by theHamsta** [comment] 2021-04-19 20:50
Wow, just experienced it myself. Can you reproduce it with the tree-sitter CLI (especially `tree-sitter query <highlight.scm> <main.hs>` (or with swapped files.))

**Comment by theHamsta** [comment] 2021-04-19 20:51
@tek any ideas where this is coming from?

**Comment by theHamsta** [comment] 2021-04-19 21:15
@tek it also happens with tree-sitter-cli

Just `tree-sitter parser` with above file.

**Comment by tek** [comment] 2021-04-19 21:21
no crash here with 0.19.4, I'll try upgrading

**Comment by theHamsta** [comment] 2021-04-19 21:29
Can confirm that this fixes the problem.

**Comment by theHamsta** [comment] 2021-04-19 21:36
Yes, with 0.19.0 it will stop until it consumes all your RAM

**Comment by tek** [comment] 2021-04-19 21:37
ah yes. I'll put that in the readme

**Comment by theHamsta** [comment] 2021-04-19 21:39
Can't you regenerate the grammar in the repo. We're compiling the source files from the repo directly.

**Comment by theHamsta** [comment] 2021-04-19 21:47
Yes, because when you have `.node_module/bin` in PATH it will use the version from package.json. To fix the problem I changed the version in package.json and run `npm i` and `tree-sitter generate`. This will modify the current parser.c

![image](https://user-images.githubusercontent.com/7189118/115307465-86caae80-a169-11eb-978a-a0b3c366931d.png)

**Comment by theHamsta** [comment] 2021-04-19 21:51
It also works when you regenerate with 0.19.0. The parser.c seems to be outdated.

**Comment by tek** [comment] 2021-04-19 21:53
:thinking:  I think I might have committed a corrupt `parser.c` some time ago. I regenerated and pushed now

**Closed** 2021-04-19 22:17 UTC
Labels: bug

**Comment by guibou** [comment] 2021-04-20 07:48
Hey, thank you! (Hello @tek, told you I'll open a bug report, took me 3 weeks... sorry ;)

**Comment by guibou** [comment] 2021-04-20 07:53
Haha, it works, it works! Thank you!

**Comment by tek** [comment] 2021-04-20 09:59
oh my god @guibou I did not realize it was you :joy:
