### ISSUE TITLE
HTML file causes neovim segv

### ISSUE THREAD

**Issue by TarunDaCoder** [nvim-treesitter/nvim-treesitter#6730] opened 2024-06-05 11:19 UTC
### Describe the bug

Whenever I edit an html file, when I indent lines with `Ctrl->` it crashes neovim without saying anything, no errors, no warnings, nothing. I have uploaded a video demonstrating what happens. 
This has happened only in html files so far. When I disable my treesitter config, the error stops occuring, this is why I think this is a treesitter issue. It appears to only happen to HTML tags, it doesn't segfault when I indent regular text.

I am on a windows machine using wsl2 with "Ubuntu 22.04.3 LTS"

https://github.com/nvim-treesitter/nvim-treesitter/assets/77536695/55a2f0c7-c3e5-43b6-8cd0-82d50b3714c3

### To Reproduce

1. Open an HTML file
2. Add any HTML tag
3. Try to indent it by selecting the line in visual select mode and pressing `Ctrl->`
4. If it doesn't happen try indenting it back using `Ctrl-<`

### Expected behavior

The line gets indented.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.6 (b40f342067a89cd6331bf4c27407588320f3c263) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v22.2.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.15.146.1-microsoft-standard-WSL2",
  sysname = "Linux",
  version = "#1 SMP Thu Jan 11 04:09:03 UTC 2024"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - cmake               ✓ . ✓ ✓ .
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - norg                ✓ . ✓ . ✓
  - norg_meta           ✓ . . ✓ .
  - rust                ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

### Additional Info
Sometimes when I type something in the HTML file, it gives an IOT error.

**Comment by clason** [comment] 2024-06-05 11:25
Duplicate of #6707

**Closed by clason** 2024-06-05 11:25 UTC
Labels: bug

**Comment by clason** [comment] 2024-06-05 11:26
Sorry, not quite -- this sounds more like an issue with the `html-tags` parser than the `html` one. Nevertheless, the answer is the same: please report this to the parser repo; we can't do anything about it.

**Comment by TarunDaCoder** [comment] 2024-06-05 11:32
> Sorry, not quite -- this sounds more like an issue with the `html-tags` parser than the `html` one. Nevertheless, the answer is the same: please report this to the parser repo; we can't do anything about it.

Sure, thanks for the response.

**Comment by TarunDaCoder** [comment] 2024-06-05 16:32
@clason turns out that building the html parser from source fixes the segv, I think the version that is installed when doing `:TSInstall html` is an older version, so if someone could update that, it could be helpful to others also.

**Comment by clason** [comment] 2024-06-05 16:51
No, that is the latest version. You just had an outdated version lying around -- either of your parser or of the nvim-treesitter plugin.

**Comment by TarunDaCoder** [comment] 2024-06-06 03:12
> No, that is the latest version. You just had an outdated version lying around -- either of your parser or of the nvim-treesitter plugin.

Oh ok. Thanks.

**Comment by muriware** [comment] 2024-06-18 11:20
For anyone encountering this issue, it could be caused by corrupted Neovim cache files.

My solution was to delete the entire Neovim cache directory, reinstall all plugins, and allow Neovim to recreate any necessary cache files when it runs.
