### ISSUE TITLE
Error in decoration provider treesitter/highlighter.line

### ISSUE THREAD

**Issue by SFS-RAID** [nvim-treesitter/nvim-treesitter#7242] opened 2024-10-14 10:51 UTC
### Describe the bug

Error in decoration provider treesitter/highlighter.line:
Error executing lua: ...nvim-treesitter/lua/nvim-treesitter/query_predicates.lua:80: attempt to
call method 'parent' (a nil value)
stack traceback:
        ...nvim-treesitter/lua/nvim-treesitter/query_predicates.lua:80: in function 'handler'
        /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:757: in function 'fn'
        /usr/local/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'match_preds'
        /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:873: in function 'iter'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:313: in function 'fn'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:213: in function 'for_each_h
ighlight_state'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:294: in function 'on_line_im
pl'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:370: in function <...al/shar
e/nvim/runtime/lua/vim/treesitter/highlighter.lua:364>

### To Reproduce

Open any file with c++ code

### Output of `:checkhealth nvim-treesitter`

```
  nvim-treesitter:                     require("nvim-treesitter.health").check()

  Installation
  - OK tree-sitter found 0.24.2 (0b167b0782a74e3702fb77cbef1486c6c01c24c8) (parser generator, only needed for :TSInstallFromGrammar)
  - OK node found v22.9.0 (only needed for :TSInstallFromGrammar)
  - OK git executable found.
  - OK cc executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 14.1.1 20240507
  - OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

  OS Info:
  {
    machine = "aarch64",
    release = "6.2.1-PRoot-Distro",
    sysname = "Linux",
    version = "#1 SMP PREEMPT Tue May 21 18:51:45 KST 2024"
  }

  Parser/Features         H L F I J
    - bash                ✓ ✓ ✓ . ✓
    - c                   ✓ ✓ ✓ ✓ ✓
    - comment             ✓ . . . .
    - cpp                 ✓ ✓ ✓ ✓ ✓
    - latex               ✓ . ✓ . ✓
    - lua                 ✓ ✓ ✓ ✓ ✓
    - markdown            ✓ . ✓ ✓ ✓
    - markdown_inline     ✓ . . . ✓
    - python              ✓ ✓ ✓ ✓ ✓
    - query               ✓ ✓ ✓ ✓ ✓
    - regex               ✓ . . . .
    - vim                 ✓ ✓ ✓ . ✓
    - vimdoc              ✓ . . . ✓

    Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
           +) multiple parsers found, only one will be used
           x) errors found in the query, try to run :TSUpdate {lang}

~
```

### Output of `nvim --version`

NVIM v0.11.0-dev-967+g36890824c
Build type: RelWithDebInfo
LuaJIT 2.1.1727870382

### Additional context

This error is the exact same as #7115 
It happens on the latest version of Nvim and TreeSitter
I already ran :TSUpdate
![Image](https://github.com/user-attachments/assets/884092c6-1e35-4620-9e5a-db09648ddce5)

**Comment by clason** [comment] 2024-10-14 10:55
Duplicate of #7115 

(Your line numbers don't match up with current `master`, which indicates your nvim-treesitter plugin is not updated.)

**Closed by clason** 2024-10-14 10:55 UTC
Labels: bug
