### ISSUE TITLE
performance: cost a lot of time (60 secs longer) to open C file with large header file

### ISSUE THREAD

**Issue by colorsu** [nvim-treesitter/nvim-treesitter#5603] opened 2023-11-01 08:08 UTC
### Describe the bug

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/33319375/86b8ec8b-2f0a-4c99-a7ad-0d829b856d51)
Recently I opened a C file include the NEON_2_SSE.h in linux platform, which took me a long time to wait for it.

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/33319375/e208b798-80ab-4def-9b67-d239078d9f87)
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/33319375/a8696200-c34a-4751-a7e9-2fcfd50ea3da)

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/33319375/69c1f11c-23bf-410b-9eb8-6935657b941c)

I have no way to find out which plugin running so long. 
And then I found that I can open whithin 1 second when I close the plugin treesitter.

here is my treesitter config:
`-- import nvim-treesitter plugin safely
local status, treesitter = pcall(require, "nvim-treesitter.configs")
if not status then
  return
end

-- configure treesitter
treesitter.setup({
  -- enable syntax highlighting
  highlight = {
    enable = true,
  },
  install = {
    prefer_git = true,
  },
  rainbow = {
    enable = true,
    extended_mode = true,
    max_file_lines = nil,
  },
  -- enable indentation
  indent = {
    enable = true,
    ignore_scopes = {"string", "comment"},
  },
  -- enable autotagging (w/ nvim-ts-autotag plugin)
  autotag = { enable = true },
  -- ensure these language parsers are installed
  ensure_installed = {
    "bash",
    "lua",
    "c",
    "cpp",
    "rust",
    "toml",
    "python",
  },
  -- auto install above language parsers
  auto_install = true,
})
`

### To Reproduce

1. open the file which included NEON_2_SSE.h
2. then will need to wait for about 5 mins.

### Expected behavior

open a C file as fast as possible, within 1 second.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
diffview: require("diffview.health").check()

Checking plugin dependencies ~
- OK nvim-web-devicons installed.

Checking VCS tools ~
- The plugin requires at least one of the supported VCS tools to be valid.
- OK Git found.
- OK Git is up-to-date. (2.34.1)
- WARNING Configured `hg_cmd` is not executable: 'hg'

==============================================================================
lspsaga: require("lspsaga.health").check()

Lspsaga.nvim report ~
- WARNING `tree-sitter` executable not found 
- ERROR tree-sitter `markdown` parser not found
- ERROR tree-sitter `markdown_inline` parser not found

==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- WARNING mason.nvim version v1.8.1
  - ADVICE:
    - The latest version of mason.nvim is: v1.8.2
- OK PATH: prepend
- OK Providers: 
  mason.providers.registry-api
  mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2023-10-31-amused-suede` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.`
- OK wget: `GNU Wget 1.21.2 built on linux-gnu.`
- OK curl: `curl 8.2.1 (x86_64-conda-linux-gnu) libcurl/8.2.1 OpenSSL/3.0.10 zlib/1.2.13 libssh2/1.10.0 nghttp2/1.52.0`
- OK gzip: `gzip 1.10`
- OK tar: `tar (GNU tar) 1.34`
- OK bash: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- WARNING Go: not available
  - ADVICE:
    - spawn: go failed with exit code - and signal -. go is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- WARNING cargo: not available
  - ADVICE:
    - spawn: cargo failed with exit code - and signal -. cargo is not executable
- WARNING luarocks: not available
  - ADVICE:
    - spawn: luarocks failed with exit code - and signal -. luarocks is not executable
- WARNING javac: not available
  - ADVICE:
    - spawn: javac failed with exit code - and signal -. javac is not executable
- WARNING java: not available
  - ADVICE:
    - spawn: java failed with exit code - and signal -. java is not executable
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- WARNING Ruby: not available
  - ADVICE:
    - spawn: ruby failed with exit code - and signal -. ruby is not executable
- WARNING RubyGem: not available
  - ADVICE:
    - spawn: gem failed with exit code - and signal -. gem is not executable
- OK node: `v20.9.0`
- OK python: `Python 3.11.5`
- OK npm: `10.1.0`
- OK pip: `pip 23.2.1 from /home/ruihong/anaconda3/lib/python3.11/site-packages/pip (python 3.11)`
- OK python venv: `Ok`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 1. Remaining: 59. Limit: 60. Reset: 2023年11月01日 星期三 16时27分37秒.
  Install and authenticate via gh-cli to increase rate limit.

==============================================================================
null-ls: require("null-ls.health").check()

- no sources registered

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: /home/ruihong/mytools/nvim-linux64/share/nvim/runtime

Performance ~
- OK Build type: Release

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=\177`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $TERM_PROGRAM="tmux"
- $SSH_TTY="/dev/pts/0"

tmux ~
- OK escape-time: 280
- WARNING `focus-events` is not enabled. |'autoread'| may not work.
  - ADVICE:
    - (tmux 1.9+ only) Set `focus-events` in ~/.tmux.conf:
      set-option -g focus-events on
- $TERM: tmux-256color
- WARNING Neither Tc nor RGB capability set. True colors are disabled. |'termguicolors'| won't work properly.
  - ADVICE:
    - Put this in your ~/.tmux.conf and replace XXX by your $TERM outside of tmux:
      set-option -sa terminal-features ',XXX:RGB'
    - For older tmux versions use this instead:
      set-option -ga terminal-overrides ',XXX:Tc'

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.9.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.2.0-36-generic",
  sysname = "Linux",
  version = "#37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cmake               ✓ . ✓ ✓ .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

==============================================================================
provider: health#provider#check

Clipboard (optional) ~
- OK Clipboard tool found: tmux

Python 3 provider (optional) ~
- WARNING No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
- WARNING Could not load Python 3:
  /home/ruihong/anaconda3/bin/python3 does not have the "neovim" module.
  /usr/bin/python3.10 does not have the "neovim" module.
  python3.9 not found in search path or not executable.
  python3.8 not found in search path or not executable.
  python3.7 not found in search path or not executable.
  /home/ruihong/anaconda3/bin/python does not have the "neovim" module.
  - ADVICE:
    - See :help |provider-python| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_python3_provider = 0` to your init.vim
- Executable: Not found

Python virtualenv ~
- OK no $VIRTUAL_ENV

Ruby provider (optional) ~
- WARNING `ruby` and `gem` must be in $PATH.
  - ADVICE:
    - Install Ruby and verify that `ruby` and `gem` commands work.

Node.js provider (optional) ~
- Node.js: v20.9.0
- WARNING Missing "neovim" npm (or yarn, pnpm) package.
  - ADVICE:
    - Run in shell: npm install -g neovim
    - Run in shell (if you use yarn): yarn global add neovim
    - Run in shell (if you use pnpm): pnpm install -g neovim
    - You may disable this provider (and warning) by adding `let g:loaded_node_provider = 0` to your init.vim

Perl provider (optional) ~
- WARNING "Neovim::Ext" cpan module is not installed
  - ADVICE:
    - See :help |provider-perl| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.1

===== Installed extensions ===== ~

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `live_grep_args` ~
- No healthcheck provided

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: /home/ruihong/.local/state/nvim/lsp.log
- Log size: 123 KB

vim.lsp: Active Clients ~
- No active clients

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: bash       ABI: 14, path: /home/ruihong/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/bash.so
- OK Parser: c          ABI: 14, path: /home/ruihong/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/c.so
- OK Parser: cmake      ABI: 14, path: /home/ruihong/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/cmake.so
- OK Parser: cpp        ABI: 14, path: /home/ruihong/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/cpp.so
- OK Parser: lua        ABI: 14, path: /home/ruihong/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/lua.so
- OK Parser: python     ABI: 14, path: /home/ruihong/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/python.so
- OK Parser: rust       ABI: 14, path: /home/ruihong/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/rust.so
- OK Parser: toml       ABI: 13, path: /home/ruihong/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/toml.so
- OK Parser: c          ABI: 14, path: /home/ruihong/mytools/nvim-linux64/lib/nvim/parser/c.so
- OK Parser: lua        ABI: 14, path: /home/ruihong/mytools/nvim-linux64/lib/nvim/parser/lua.so
- OK Parser: query      ABI: 14, path: /home/ruihong/mytools/nvim-linux64/lib/nvim/parser/query.so
- OK Parser: vim        ABI: 14, path: /home/ruihong/mytools/nvim-linux64/lib/nvim/parser/vim.so
- OK Parser: vimdoc     ABI: 14, path: /home/ruihong/mytools/nvim-linux64/lib/nvim/parser/vimdoc.so
```

### Output of `nvim --version`

```text
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by lucario387** [comment] 2023-11-01 08:28
It's gonna be another `#define` issue, I suspect

**Comment by lucario387** [comment] 2023-11-01 08:34
Does the issue happen if you use neovim nightly?

**Comment by andis-sprinkis** [comment] 2023-11-01 20:23
Not sure if the same issue, but I noticed that key input and UI refresh slowed to crawl after opening and scrolling down the attached `sysexits.h`.
[sysexits.h.txt](https://github.com/nvim-treesitter/nvim-treesitter/files/13231414/sysexits.h.txt)

Disabling the treesitter highlight mitigates the issue and the input performance is normal again.

```
local M = {
  'nvim-treesitter/nvim-treesitter',
  config = function()
    require 'nvim-treesitter.configs'.setup {
      ensure_installed = "all",
      -- highlight = {
      --   enable = true,
      -- },
      indent = {
        enable = true,
      },
      context_commentstring = {
        enable = true,
        enable_autocmd = false,
      },
    }

    local o = vim.opt
    o.foldmethod = 'expr'
    o.foldenable = false
    o.foldexpr = 'nvim_treesitter#foldexpr()'
  end,
  build = ':TSUpdate'
}

return M
```

(Sorry for no proper report, bit in a hurry now.)

**Comment by colorsu** [comment] 2023-11-07 08:48
> Not sure if the same issue, but I noticed that key input and UI refresh slowed to crawl after opening and scrolling down the attached `sysexits.h`. [sysexits.h.txt](https://github.com/nvim-treesitter/nvim-treesitter/files/13231414/sysexits.h.txt) (Rename back to `sysexits.h`.)
> 
> Disabling the treesitter highlight mitigates the issue and the input performance is normal again.
> 
> ```
> local M = {
>   'nvim-treesitter/nvim-treesitter',
>   config = function()
>     require 'nvim-treesitter.configs'.setup {
>       ensure_installed = "all",
>       -- highlight = {
>       --   enable = true,
>       -- },
>       indent = {
>         enable = true,
>       },
>       context_commentstring = {
>         enable = true,
>         enable_autocmd = false,
>       },
>     }
> 
>     local o = vim.opt
>     o.foldmethod = 'expr'
>     o.foldenable = false
>     o.foldexpr = 'nvim_treesitter#foldexpr()'
>   end,
>   build = ':TSUpdate'
> }
> 
> return M
> ```
> 
> NVIM 0.9.2
> 
> (Sorry for no proper report, bit in a hurry now.)

Thanks for your comment.
It's not the same issue. The whole window was frozed and the mouse and key input has no response at all.

**Comment by colorsu** [comment] 2023-11-07 08:49
> Does the issue happen if you use neovim nightly?

To be honest, my neovim version was pretty new, so I didn't try the nightly one.
thanks

**Comment by Avimitin** [comment] 2023-11-08 08:02
I get the same issue when editing large cpp file in LLVM repository as well. It takes too long to open a file, and even after loaded, the cursor movement are laggy. I am using neovim v0.9.4, with nvim-treesitter rev `f3fb301b267e85e4cbc725561da4a82b1c3089c8`.

**Comment by andis-sprinkis** [comment] 2023-11-09 08:46
The performance issue in comment I posted above with `sysexists.h` example is not affected by removing `vim-illuminate` or by changing it's settings, so mine is then confirmed a separate issue.

**Comment by amaanq** [comment] 2023-11-09 09:00
That's not solid evidence - you need to make sure nvim-treesitter is the *only* plugin installed in a *minimal config* when experiencing slowness

**Comment by colorsu** [comment] 2023-11-25 08:29
I use ccls as my LSP server, and today I used cmake to generate the compile_command.json for my project, and reenable the treesitter plugin again. It seems that the issue has gone.
Now I can enable nvim-treesitter again.

Maybe the reason it's ok  just because not including the NEON_2_SSE.h, after using the compile_command.json, it will use the correct compiler which will include <arm_neon.h>, and not the gcc in x86 which may include the NEON_2_SSE.h. 
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/33319375/471550b8-b559-4c69-8a00-52ede19047e1)

So I will close this issue since the nvim-treesitter can work fluently again.
thank you guys.

**Comment by colorsu** [comment] 2023-12-13 07:04
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/33319375/e6e75195-52cf-4955-9df3-11e66090a077)
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/33319375/f790f5d7-184d-4773-a9d6-23cc77ad8190)
Recently I started to use lazyVim and reopen the project which will use the neon header file. and the problem still occur.
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/33319375/011d4118-ad90-4fe2-a11f-a606a5cb66e0)
:checkhealth nvim-treesitter

**Comment by theHamsta** [comment] 2023-12-13 07:37
> ![image](https://private-user-images.githubusercontent.com/33319375/290101016-e6e75195-52cf-4955-9df3-11e66090a077.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTI4ODIsIm5iZiI6MTcwMjQ1MjU4MiwicGF0aCI6Ii8zMzMxOTM3NS8yOTAxMDEwMTYtZTZlNzUxOTUtNTJjZi00OTU1LTlkZjMtMTFlNjYwOTBhMDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA3Mjk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZjZmMjhkOWVjM2FkMjRkYzc0ZjQ3ZGMyMjYxNzE5YTA2MjZhOWM0ZDVhYTE5MGEwYmQ5MWMzOTkzYmU0ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.72p1qw2v94O2_QyPnEZJS8e_Gxe7f_TieJ4iZ4QcqgE) ![image](https://private-user-images.githubusercontent.com/33319375/290101770-f790f5d7-184d-4773-a9d6-23cc77ad8190.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTI4ODIsIm5iZiI6MTcwMjQ1MjU4MiwicGF0aCI6Ii8zMzMxOTM3NS8yOTAxMDE3NzAtZjc5MGY1ZDctMTg0ZC00NzczLWE5ZDYtMjNjYzc3YWQ4MTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA3Mjk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkY2Q3ZTE4OGEwMzdkNDAxOTMzM2FjZWZiMDU1OWMwZDBjN2M4MDJmODQzMjI1MDA5YTU0NmM2ZmQ1M2IxNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AEFlOC0aEVvqREx7k45B8S_R9Lq2iHgLmQpquX8TfDI) Recently I started to use lazyVim and reopen the project which will use the neon header file. and the problem still occur. ![image](https://private-user-images.githubusercontent.com/33319375/290102764-011d4118-ad90-4fe2-a11f-a606a5cb66e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTI4ODIsIm5iZiI6MTcwMjQ1MjU4MiwicGF0aCI6Ii8zMzMxOTM3NS8yOTAxMDI3NjQtMDExZDQxMTgtYWQ5MC00ZmUyLWExMWYtYTYwNmE1Y2I2NmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA3Mjk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NGQxYzQ4MGM1YzEyNTZjZjU4Mzg3ZDZlYzY0OWU5ODk0MGZiYzNmYzdiMDAwN2E5M2NmNDE1MzY3MTcxY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MwNqh6XbNKeS8XNM7E4aKG9HO8vhyzTPeJWujG0A-Jg) :checkhealth nvim-treesitter

But this isn't the healthcheck right? If this happens in your file you some how trigger an infinite injection probably self-injection through this query. Can you try whether removing the query resolves the problem? 
https://github.com/nvim-treesitter/nvim-treesitter/blob/a6c655629cad421e432aa84af32cbfe35375113a/queries/c/injections.scm#L1-L2 or https://github.com/nvim-treesitter/nvim-treesitter/blob/a6c655629cad421e432aa84af32cbfe35375113a/queries/cpp/injections.scm#L1-L2 if filetype is c++

**Comment by colorsu** [comment] 2023-12-13 07:43
You mean I need to delete this code in ~/.local/share/nvim/lazy/nvim-treesitter/queries/c/injections.scm ?
[nvim-treesitter/queries/c/injections.scm](https://github.com/nvim-treesitter/nvim-treesitter/blob/a6c655629cad421e432aa84af32cbfe35375113a/queries/c/injections.scm#L1-L2)

Lines 1 to 2 in [a6c6556](https://github.com/nvim-treesitter/nvim-treesitter/commit/a6c655629cad421e432aa84af32cbfe35375113a)

 ((preproc_arg) @injection.content 
  (#set! injection.language "c"))
  
After I delete the 2 line you given, the problem was resolves.

**Comment by lucario387** [comment] 2023-12-13 08:12
@amaanq What should we do here (for master branch only :thinking: )

**Comment by lucario387** [comment] 2023-12-13 08:16
Can you share the file for reproduction, your neovim version, and the minimal config for the issue @colorsu ? I suspect this may be a bigger problem here, considering it's calling repeated `for_each_child` like that

**Comment by colorsu** [comment] 2023-12-13 09:38
> Can you share the file for reproduction, your neovim version, and the minimal config for the issue @colorsu ? I suspect this may be a bigger problem here, considering it's calling repeated `for_each_child` like that

[NEON_2_SSE.h](https://github.com/intel/ARM_NEON_2_x86_SSE/blob/master/NEON_2_SSE.h)
This issue could be easily reproduce by open this header file. `nvim NEON_2_SSE.h`

the neovim version: 
> nvim --version
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.1692716794
   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

You can use Lazyvim with lang.clangd enabled to reproduce this issue, cause I am not very familiar with the configuration of nvim.
Here is [my lazyvim config](https://github.com/colorsu/lazyvim_config) just for fun

**Comment by clason** [comment] 2023-12-13 09:47
> You can use Lazyvim with lang.clangd enabled to reproduce this issue, cause I am not very familiar with the configuration of nvim.

That's completely unrelated to nvim-treesitter, though. If you cannot reproduce the issue with a minimal config (just nvim-treesitter, without lazy and language servers and...), then it's out of scope here.

If you can, please open a new issue (using the latest Nvim release, 0.9.4, and testing current `master` as well).

**Closed by clason** 2023-12-13 09:47 UTC
Labels: bug
