### ISSUE TITLE
Error in Treesitter Decoration Provider When Running `:help` in Neovim

### ISSUE THREAD

**Issue by Robin0315** [nvim-treesitter/nvim-treesitter#6788] opened 2024-06-19 12:25 UTC
### Describe the bug

I encountered an error with the Treesitter highlighter when running the `:help` command in Neovim. The error message indicates an invalid node type `delimiter` in the Treesitter query file.
![screenshot (1)](https://github.com/nvim-treesitter/nvim-treesitter/assets/13429428/9884f7b5-b09f-443c-a9ad-990aca6ec143)

### To Reproduce

1. Open Neovim.
2. Run the command `:help`.

### Expected behavior

The help documentation should open without any errors.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.6 (b40f342067a89cd6331bf4c27407588320f3c263) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v22.3.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: gcc (x86_64-posix-seh-rev1, Built by MinGW-Builds project) 13.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.22631",
  sysname = "Windows_NT",
  version = "Windows 11 Home China"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
Run ":verbose version" for more info
```

**Comment by clason** [comment] 2024-06-19 12:28
Duplicate of #3092

**Closed by clason** 2024-06-19 12:28 UTC
Labels: bug
