### ISSUE TITLE
tar: Error opening archive: Unrecognized archive format

### ISSUE THREAD

**Issue by tutu-stack** [nvim-treesitter/nvim-treesitter#2847] opened 2022-04-21 06:13 UTC
### Describe the bug

`TSInstall tsx`
When I installed the tsx module, I had the following problem
<img width="664" alt="image" src="https://user-images.githubusercontent.com/69944746/164385585-42ac413c-ed01-46c4-a8d3-c65afbda56e5.png">

### To Reproduce

1. Type `TSInstall tsx` and hit enter
2. Wait a few moments and you'll see that question

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.1 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.18.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 12.0.5 (clang-1205.0.22.9)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - fusion         ✓ ✓ ✓ ✓ . 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
编译者 brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/usr/local/Cellar/neovim/0.6.0/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment] 2022-04-21 06:20
We've had similar reports that I can never reproduce. I suspect that something goes wrong when downloading the parser, probably due to your network settings (or a transient Github problem, in which case just try again after waiting a bit).

Without the necessary information you omitted (platform, environment, any special network settings, a **full but minimal config** someone can run with `nvim --clean -u minimal.lua`), there's nothing we can do, so I'm closing this (and similar issues) until it is provided.

(Also, nvim-treesitter requires Neovim 0.7.0 now; 0.6.0 is no longer supported.)

**Closed by clason** 2022-04-21 06:20 UTC
Labels: bug

**Comment by theHamsta** [comment] 2022-04-21 06:41
TSX and typescript are downloading the same file it's possible that races for the downloaded files happen. They are then moved to a different location but during download they can overwrite each other.

**Comment by tutu-stack** [comment] 2022-04-21 07:10
> checkhealth nvim-treesitter

The same problem occurs when I execute `TSInstall lua`

**Comment by tutu-stack** [comment] 2022-04-21 07:10
The same problem occurs when I execute `TSInstall lua`

**Comment by theHamsta** [comment] 2022-04-21 07:44
Same with `require'nvim-treesitter.install'.prefer_git = true`?

**Comment by tutu-stack** [comment] 2022-04-21 07:59
When I added `require'nvim-treesitter.install'.prefer_git = true`, the problem was solved

**Comment by tutu-stack** [comment] 2022-04-21 09:35
> Same with `require'nvim-treesitter.install'.prefer_git = true`?



> Same with `require'nvim-treesitter.install'.prefer_git = true`?

appreciate it
