### ISSUE TITLE
Slow performance in large tsx file when GraphQL comment query enabled

### ISSUE THREAD

**Issue by dwoznicki** [nvim-treesitter/nvim-treesitter#3581] opened 2022-10-04 02:30 UTC
### Describe the bug

I noticed some lag while editing large tsx files (~2000 lines). The lag manifests as slow repaints; i.e. after making changes, the terminal is slow to show the updates.

I found that commenting out the following lines in `queries/ecma/injections.scm` appears to solve most if not all of the lag issue.

```scm
((comment) @_gql_comment
  (#eq? @_gql_comment "/* GraphQL */")
  (template_string) @graphql)
```

Here's a video with a demonstration. The lag isn't terrible here, but it is noticeable.

[screencast_20221003.webm](https://user-images.githubusercontent.com/13933454/193720851-df5e3ae1-f9e3-4016-aeee-ee5a54d5eadb.webm)

### To Reproduce

Open a large tsx file and make changes.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not           required for :TSInstall)
  - OK: `node` found v16.17.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Debian 10.2.1-6) 10.2.1 20210110
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with    runtime ABI.

## Parser/Features H L F I J
  - cuda           ✓ ✓ ✓ ✓ ✓
  - todotxt        ✓ . . . .
  - zig            ✓ . ✓ ✓ ✓
  - glsl           ✓ ✓ ✓ ✓ ✓
  - fortran        ✓ . ✓ ✓ .
  - hlsl           ✓ ✓ ✓ ✓ ✓
  - cmake          ✓ . ✓ . .
  - dockerfile     ✓ . . . ✓
  - slint          ✓ . . ✓ .
  - json5          ✓ . . . ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - fusion         ✓ ✓ ✓ ✓ .
  - hjson          ✓ ✓ ✓ ✓ ✓
  - ledger         ✓ . ✓ ✓ ✓
  - hocon          ✓ . . . ✓
  - markdown_inline✓ . . . ✓
  - tlaplus        ✓ ✓ ✓ . ✓
  - gomod          ✓ . . . ✓
  - prisma         ✓ . . . .
  - gowork         ✓ . . . ✓
  - toml           ✓ ✓ ✓ ✓ ✓
  - graphql        ✓ . . ✓ ✓
  - ruby           ✓ ✓ ✓ ✓ ✓
  - pug            ✓ . . . ✓
  - hack           ✓ . . . .
  - perl           ✓ . ✓ . .
  - norg           . . . . .
  - jsonc          ✓ ✓ ✓ ✓ ✓
  - elm            ✓ . . . ✓
  - vala           ✓ . ✓ . .
  - yang           ✓ . ✓ ✓ .
  - lalrpop        ✓ ✓ . . .
  - ninja          ✓ . ✓ ✓ .
  - solidity       ✓ . . . .
  - nix            ✓ ✓ ✓ . ✓
  - dart           ✓ ✓ . ✓ ✓
  - elvish         ✓ . . . ✓
  - fennel         ✓ ✓ . . ✓
  - astro          ✓ ✓ ✓ ✓ ✓
  - wgsl           ✓ . ✓ ✓ .
  - ql             ✓ ✓ . ✓ ✓
  - m68k           ✓ ✓ ✓ . ✓
  - pascal         ✓ ✓ ✓ ✓ ✓
  - tiger          ✓ ✓ ✓ ✓ ✓
  - jsdoc          ✓ . . . .
  - sxhkdrc        ✓ . ✓ . ✓
  - query          ✓ ✓ ✓ ✓ ✓
  - sparql         ✓ ✓ ✓ ✓ ✓
  - gitattributes  ✓ . . . ✓
  - sql            ✓ . . . ✓
  - blueprint      ✓ . . . .
  - gdscript       ✓ ✓ . ✓ ✓
  - proto          ✓ . ✓ . .
  - turtle         ✓ ✓ ✓ ✓ ✓
  - svelte         ✓ . ✓ ✓ ✓
  - beancount      ✓ . ✓ . .
  - regex          ✓ . . . .
  - rnoweb         ✓ . ✓ . ✓
  - bibtex         ✓ . ✓ ✓ .
  - r              ✓ ✓ . ✓ ✓
  - make           ✓ . ✓ . ✓
  - json           ✓ ✓ ✓ ✓ .
  - vim            ✓ ✓ ✓ . ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - bash           ✓ ✓ ✓ . ✓
  - html           ✓ ✓ ✓ ✓ ✓
  - tsx            ✓ ✓ ✓ ✓ ✓
  - hcl            ✓ . ✓ ✓ ✓
  - glimmer        ✓ . . . .
  - twig           ✓ . . . ✓
  - verilog        ✓ ✓ ✓ . ✓
  - haskell        ✓ . ✓ . ✓
  - latex          ✓ . ✓ . ✓
  - dot            ✓ . . . ✓
  - org            . . . . .
  - foam           ✓ ✓ ✓ ✓ ✓
  - java           ✓ ✓ . ✓ ✓
  - vue            ✓ . ✓ ✓ ✓
  - c_sharp        ✓ ✓ ✓ . ✓
  - kotlin         ✓ ✓ ✓ . ✓
  - cpp            ✓ ✓ ✓ ✓ ✓
  - scala          ✓ . ✓ . ✓
  - supercollider  ✓ ✓ ✓ ✓ ✓
  - julia          ✓ ✓ ✓ ✓ ✓
  - pioasm         ✓ . . . ✓
  - help           ✓ . . . .
  - c              ✓ ✓ ✓ ✓ ✓
  - jsonnet        ✓ . . . .
  - agda           ✓ . ✓ . .
  - go             ✓ ✓ ✓ ✓ ✓
  - rst            ✓ ✓ . . ✓
  - scss           ✓ . . ✓ .
  - elixir         ✓ ✓ ✓ ✓ ✓
  - surface        ✓ . ✓ ✓ ✓
  - erlang         ✓ . ✓ . .
  - yaml           ✓ ✓ ✓ ✓ ✓
  - rasi           ✓ ✓ ✓ ✓ .
  - meson          ✓ . ✓ . ✓
  - fish           ✓ ✓ ✓ ✓ ✓
  - qmljs          ✓ . ✓ . .
  - menhir         ✓ . . . ✓
  - gleam          ✓ ✓ ✓ ✓ ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - racket         ✓ . ✓ . ✓
  - php            ✓ ✓ ✓ ✓ ✓
  - css            ✓ . ✓ ✓ ✓
  - eex            ✓ . . . ✓
  - scheme         ✓ . ✓ . ✓
  - heex           ✓ ✓ ✓ ✓ ✓
  - typescript     ✓ ✓ ✓ ✓ ✓
  - ocaml          ✓ ✓ ✓ . ✓
  - rego           ✓ . . . ✓
  - markdown       ✓ . ✓ . ✓
  - comment        ✓ . . . .
  - ocaml_interface✓ ✓ ✓ . ✓
  - embedded_template✓ . . . ✓
  - llvm           ✓ . . . .
  - clojure        ✓ ✓ ✓ . ✓
  - http           ✓ . . . ✓
  - v              ✓ ✓ ✓ ✓ ✓
  - commonlisp     ✓ ✓ ✓ . .
  - cooklang       ✓ . . . .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az164-457

Features: +acl +iconv +tui
```

**Comment by chearon** [comment] 2022-11-21 17:41
I've also been experiencing serious lag on JS files starting around 2-3k lines. After 4-5k it's almost impossible to use Neovim.

I can confirm that deleting that exact query makes it snappy again. Thank you for posting this @dwoznicki

**Comment by Rayk0** [comment] 2022-11-23 10:10
I've just started using nvim and treesitter. I was quite disappointed seing this kind of lag on big files (using vue), but commenting that exact query fixed the lag for me. Thanks for posting @dwoznicki

**Comment by OlegGulevskyy** [comment] 2022-11-25 12:00
Amazing, thank you for the workaround, it was unbearable opening 1.3k of lines!
Hoping this can can be fixed by the team soon :)

**Comment by OlegGulevskyy** [comment] 2023-01-25 10:21
This workaround is not working on MacOS M1
File with 1.3k is very slow to process, and the `gql` thing is commented out.
I have another file that is also 1.3k and it's working ok there, the difference between files is that one file contains a lot of JSdoc and a lot of comments and it's by far slower than another file without comments.
It seems like `jsdoc` is commented out from the `injections` file. What else can be done?

**Comment by bain3** [comment] 2023-02-07 22:31
Hi! I'd just like to bump this a little. Commenting out those 3 lines fixed it for me. Editing large JS files (6k lines) was completely impossible.

**Comment by bekirisgor** [comment] 2023-02-08 18:13
Hi, I have same issue here. Input lag can be so annoying 2k+ lines. Currently i disabled treesitter to keep use neovim.

**Comment by lewis6991** [comment] 2023-02-24 10:17
Should be fixed with https://github.com/neovim/neovim/pull/22309

**Closed by lewis6991** 2023-02-24 10:17 UTC
Labels: bug, performance

**Comment by jackfranklin** [comment] 2023-04-12 10:09
@lewis6991 I just hit upon this performance issue and have tracked it down to the same injection mentioned in the opening post.

I am running NeoVim nightly (literally just did an install now from the master branch), and have updated all my plugins including Treesitter to the latest version.

With that injection enabled, typing in a 3000 line TS file is almost impossible and so laggy. But commenting out those three lines changes everything to be very snappy.

If I can provide any further info to aid debugging this, please let me know. Thanks!

**Comment by OlegGulevskyy** [comment] 2023-04-12 10:11
> Should be fixed with [neovim/neovim#22309](https://github.com/neovim/neovim/pull/22309)

It doesn't seem to be fixed, or at least I am not sure how to verify this change. Which neovim version this is expected to be fixed in?

**Comment by amaanq** [comment] 2023-04-12 12:28
> @lewis6991 I just hit upon this performance issue and have tracked it down to the same injection mentioned in the opening post.
> 
> I am running NeoVim nightly (literally just did an install now from the master branch), and have updated all my plugins including Treesitter to the latest version.
> 
> With that injection enabled, typing in a 3000 line TS file is almost impossible and so laggy. But commenting out those three lines changes everything to be very snappy.
> 
> If I can provide any further info to aid debugging this, please let me know. Thanks!

I have noticed this as well, I'm not against removing this bit.

**Comment by lewis6991** [comment] 2023-04-12 12:34
I'll be working on TS performance for 0.10. I'm aware of most bottlenecks in our implementation

**Comment by erlonbie** [comment] 2023-04-21 18:36
I've been having this issue for a long time, no only for tsx files, but for rust, cpp, python, java and other languages that I tried.

Just following the logic for commenting the "comment" part of any injection.scm regards to each file type, the lag goes away. I tested for tsx, cpp, rust, python and java.

**Comment by jyc** [comment] 2024-09-04 03:41
I experience this if I use the following injection to highlight GitHub-style Markdown `math` fenced blocks:

```scheme
; extends
; Use :Inspect, :InspectTree, and :EditQuery

; Treat math fenced blocks as LaTeX.
; Note that you can use ```latex instead; it seems to be faster.
(fenced_code_block
  (info_string (language) @_lang)
  (code_fence_content) @injection.content
  (#eq? @_lang "math")
  (#set! injection.language "latex"))
```
