### ISSUE TITLE
Lua: too much spellchecking if empty comment lines exist

### ISSUE THREAD

**Issue by HiPhish** [nvim-treesitter/nvim-treesitter#5291] opened 2023-08-20 15:52 UTC
### Describe the bug

If a Lua buffer contains an empty comment line everything will be spell-checked, not just comments and strings. In the following screenshot spelling errors are curly underlined in purple.

![Screenshot_20230820_174431](https://github.com/nvim-treesitter/nvim-treesitter/assets/4954650/077cded8-44a4-422d-a202-b7df4a48d7b2)

### To Reproduce

1. Create a new Lua buffer
2. Add the following contents:

```lua
-- Lol
--
-- rofl

print 'lol'

local function derp()
    print 'derp'
end
```

### Expected behavior

Only comments (and maybe string?) should be spell-checked.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v18.16.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 12.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.3.13_1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Tue Jul 25 00:19:40 UTC 2023"
} ~

Parser/Features         H L F I J
  - astro               ✓ ✓ ✓ ✓ ✓
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - c_sharp             ✓ ✓ ✓ . ✓
  - clojure             ✓ ✓ ✓ . ✓
  - comment             ✓ . . . .
  - commonlisp          ✓ ✓ ✓ . .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - cuda                ✓ ✓ ✓ ✓ ✓
  - dart                ✓ ✓ ✓ ✓ ✓
  - elixir              ✓ ✓ ✓ ✓ ✓
  - erlang              ✓ . ✓ . .
  - fennel              ✓ ✓ ✓ . ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - haskell             ✓ . ✓ . ✓
  - hcl                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - json5               ✓ . . . ✓
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - jsonnet             ✓ . . . .
  - julia               ✓ ✓ ✓ ✓ ✓
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - nix                 ✓ ✓ ✓ . ✓
  - org                 . . . . .
  - perl                ✓ . ✓ . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - r                   ✓ ✓ . ✓ ✓
  - racket              ✓ . ✓ . ✓
  - rasi                ✓ ✓ ✓ ✓ .
  - regex               ✓ . . . .
  - rst                 ✓ ✓ . . ✓
  - ruby                ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - scheme              ✓ . ✓ . ✓
  - scss                ✓ . ✓ ✓ .
  - sql                 ✓ . . ✓ ✓
  - terraform           ✓ . ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - v                   ✓ ✓ ✓ ✓ ✓
  - verilog             ✓ ✓ ✓ . ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vue                 ✓ . ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓
  - zig                 ✓ . ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.1
Build type: None
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/ccache/bin/cc  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-2.1 -I/usr/include -I/usr/include -I/builddir/neovim-0.9.1/build/src/nvim/auto -I/builddir/neovim-0.9.1/build/include -I/builddir/neovim-0.9.1/build/cmake.config -I/builddir/neovim-0.9.1/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

This does not happen in other languages like Python.

**Comment by lucario387** [comment] 2023-08-21 04:28
The problem is with injected tree without range that lead to its range being interpreted as the whole tree.

The root cause is fixed on nightly neovim and the upcoming 0.9.2 release, so how should I be handling this for this repo?

**Comment by lucario387** [comment] 2023-08-22 00:54
I've reverted the PR that leads to this issue for now, will re apply such PR once 0.9.2 is stable

**Closed by lucario387** 2023-08-22 00:54 UTC
Labels: bug

**Comment by HiPhish** [comment] 2023-08-22 07:49
That sounds good, thank you. It will bite those who are on stable distributions though where it takes a long time until they get a Neovim update. On the other hand, anyone who uses Tree-sitter on such a distribution probably uses some other more recent build anyway.
