### ISSUE TITLE
Variables in format strings are not highlighted anymore

### ISSUE THREAD

**Issue by nawordar** [nvim-treesitter/nvim-treesitter#3634] opened 2022-10-13 07:27 UTC
### Describe the highlighting problem

After some update the interpolated variables in strings are not highlighted anymore. This applies to Bash and Python grammar and probably more.

### Example snippet that causes the problem

Python file:
```python
test_string = f"{test}"
```

Bash file:
```bash
test_string="$test"
```

### Tree-sitter parsing result

```
expression_statement [0, 0] - [0, 23] python
  assignment [0, 0] - [0, 23] python
    left: identifier [0, 0] - [0, 11] python
    "=" [0, 12] - [0, 13] python
    right: string [0, 14] - [0, 23] python
      """ [0, 14] - [0, 16] python
      interpolation [0, 16] - [0, 22] python
        "{" [0, 16] - [0, 17] python
        identifier [0, 17] - [0, 21] python
        "}" [0, 21] - [0, 22] python
      """ [0, 22] - [0, 23] python
```

```
variable_assignment [0, 0] - [0, 19] bash
  name: variable_name [0, 0] - [0, 11] bash
  "=" [0, 11] - [0, 12] bash
  value: string [0, 12] - [0, 19] bash
    """ [0, 12] - [0, 13] bash
    simple_expansion [0, 13] - [0, 18] bash
      "$" [0, 13] - [0, 14] bash
      variable_name [0, 14] - [0, 18] bash
    """ [0, 18] - [0, 19] bash
"\n" [0, 19] - [1, 0] bash
```

### Example screenshot

Python file:
![Screenshot of a Python file with broken highlighting](https://user-images.githubusercontent.com/26769700/195528576-b218cf84-4408-477e-b4f9-e9e204b0f5e6.png)

Bash file:
![Screenshot of a Bash file with broken highlighting](https://user-images.githubusercontent.com/26769700/195528459-5b7f093b-a564-4170-b837-ace5fcf2dfcc.png)

### Expected behavior

Variable inside the string should be highlighted in a different color.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim: health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: /home/cezdro/.config/nvim/init.vim
    - ADVICE:
      - :help init.vim

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'
```

### Output of `nvim --version`

```text
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

I have created the following files to reproduce the problem:

<details>
<summary><code>init.lua</code></summary>

```lua
-- Based on this comment:
-- https://www.reddit.com/r/neovim/comments/tyxp8s/whats_the_easiest_way_to_create_a_minimal_test/i3w00kb/

-- Find directories
local script_info = debug.getinfo(1, 'S')
local script_dir = script_info.source:sub(2):match '(.*/)'
local site_dir = script_dir .. '/site'
local packer_dir = site_dir .. '/pack/packer/start/packer.nvim'

-- Ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.stdpath 'config')
vim.opt.packpath:remove(vim.fn.stdpath 'data' .. '/site')

-- Add test config
vim.opt.runtimepath:append(script_dir)
vim.opt.packpath:append(site_dir)

-- Install Packer
if vim.fn.empty(vim.fn.glob(packer_dir)) > 0 then
  vim.fn.system {
    'git',
    'clone',
    '--depth',
    '1',
    'https://github.com/wbthomason/packer.nvim',
    packer_dir,
  }

  vim.cmd 'packadd packer.nvim'
end

local packer = require 'packer'

packer.init {
  package_root = site_dir .. '/pack',
  compile_path = script_dir .. '/plugin/packer_compiled.lua',
}

packer.startup(function(use)
  use 'wbthomason/packer.nvim'

  use {
    'nvim-treesitter/nvim-treesitter',
    run = ':TSUpdate',
    config = function()
      require('nvim-treesitter.configs').setup {
        ensure_installed = { 'bash', 'python' },
        highlight = { enable = true },
      }
    end,
  }

  use {
    'nvim-treesitter/playground',
    requires = 'nvim-treesitter',
    config = function()
      require('nvim-treesitter.configs').setup {
        playground = { enable = true },
      }
    end,
  }
end)
```
</details>

<details>
<summary><code>test.py</code></summary>

```python
test_string = f"{test}"
```
</details>

<details>
<summary><code>test.sh</code></summary>

```bash
test_string="$test"
```
</details>

Then I ran Neovim with `nvim -u init.lua`, ran `:PackerSync` and restarted Neovim using `nvim -u init.lua test.py` and `nvim -u init.lua test.sh`.

**EDIT:** I tried downgrading nvim-treesitter and updating Neovim to 0.8.0, but it didn't change anything. It seems that the problem is elsewhere, but I don't know where to search anymore.

**Comment by kbc8894** [comment] 2022-10-31 12:50
Me too

**Comment by clason** [comment] 2022-10-31 12:59
I can't reproduce this; `test` is highlighted exactly like `test_string` for me. You need to install Neovim 0.8, though, since nvim-treesitter no longer supports 0.7.2.

**Comment by nawordar** [comment] 2022-10-31 13:37
> I can't reproduce this; `test` is highlighted exactly like `test_string` for me.

What color scheme are you using? Maybe the issue is actually with the theme I'm using, not nvim-treesitter. I might report it there.

> You need to install Neovim 0.8, though, since nvim-treesitter no longer supports 0.7.2.

I already did, and it didn't help, unfortunately

**Comment by clason** [comment] 2022-10-31 13:41
I tested with `default` color scheme.

**Comment by amaanq** [comment] 2023-02-28 05:44
This is a bug with your theme, NOT nvim-treesitter. Closing

(FWIW I'm aware tokyonight has this bug)

**Closed by amaanq** 2023-02-28 05:44 UTC
Labels: highlights
