### ISSUE TITLE
HTML paragraph is highlighted with all highlight groups

### ISSUE THREAD

**Issue by ten3roberts** [nvim-treesitter/nvim-treesitter#1812] opened 2021-09-14 11:09 UTC
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

When moving inside an paragraph tag inside a div in a valid HTML, the lines which have been navigated are highlighted with both TSStrike, TSUnderline, TSURI, TSBold and TSItalic, which is all possible text styles and makes the text look very weird when moving through it. This occurs when using normal jk, and stays until you move out from the paragraph.

![image](https://user-images.githubusercontent.com/25723553/133246630-ca76af04-bd18-47f7-aeed-7552e7a4402c.png)

### To Reproduce

Create an html page with an <html><body><div><p></p></div></html>

Add text inside inside the paragraph

When moving through the paragraph text, it is highlighted as all possible types of text.

### Expected behavior

The paragraph retains the TSNonde highlight and does not change when moving

### Output of `:checkhealth nvim_treesitter`

```markdown
health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v14.17.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - clojure        ✓ ✓ ✓ . ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - cuda           ✓ ✓ ✓ ✓ ✓ 
  - dockerfile     ✓ . . . ✓ 
  - svelte         ✓ . ✓ ✓ ✓ 
  - dot            ✓ . . . ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - beancount      ✓ . ✓ . . 
  - ledger         ✓ . ✓ ✓ ✓ 
  - vim            ✓ ✓ . . ✓ 
  - latex          ✓ . ✓ . ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - bibtex         ✓ . ✓ ✓ . 
  - gomod          ✓ . . . . 
  - zig            ✓ . ✓ ✓ ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - cmake          ✓ . ✓ . . 
  - bash           ✓ ✓ ✓ . ✓ 
  - json5          ✓ . . . ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - pioasm         ✓ . . . ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - kotlin         ✓ . . . ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - julia          ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - css            ✓ . ✓ ✓ ✓ 
  - tlaplus        ✓ . ✓ . ✓ 
  - surface        ✓ . ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - heex           ✓ . ✓ ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - vue            ✓ . ✓ . ✓ 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - nix            ✓ ✓ ✓ . ✓ 
  - dart           ✓ ✓ . ✓ ✓ 
  - rst            ✓ ✓ . . ✓ 
  - fennel         ✓ ✓ . . ✓ 
  - ql             ✓ ✓ . ✓ ✓ 
  - r              ✓ ✓ . . . 
  - yang           ✓ . ✓ . . 
  - verilog        ✓ ✓ ✓ . ✓ 
  - glimmer        ✓ . . . . 
  - erlang         . . . . . 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . . 
  - regex          ✓ . . . . 
  - jsdoc          ✓ . . . . 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - hcl            ✓ . ✓ ✓ ✓ 
  - ocaml_interface✓ ✓ ✓ . ✓ 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - commonlisp     ✓ ✓ ✓ . . 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.0-dev+223-g384a43fe7
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/tej/src/neovim/build/config -I/home/tej/src/neovim/src -I/home/tej/src/neovim/.deps/usr/include -I/usr/include -I/home/tej/src/neovim/build/src/nvim/auto -I/home/tej/src/neovim/build/include
Compiled by tej@probook

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Additional context

The issue has persisted ever since I started with html, which means it most likely has been ocurring before the 0.5 point release.

**Comment by stsewd** [comment] 2021-09-14 15:15
Hi, this is a duplicate of https://github.com/nvim-treesitter/nvim-treesitter/issues/1506

**Closed by stsewd** 2021-09-14 15:15 UTC
Labels: bug
