### ISSUE TITLE
"Plugin runtime path not found" error

### ISSUE THREAD

**Issue by errx** [nvim-treesitter/nvim-treesitter#363] opened 2020-08-30 20:26 UTC
**Describe the bug**
"Plugin runtime path not found" when trying to install parser

**To Reproduce**
TSInstall go

**Expected behavior**
parser should be installed

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

  health#nvim_treesitter#check
  ========================================================================
  ## Installation
    - OK: `git` executable found.
    - OK: `cc` executable found.
  
</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-91109ffda
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200828-46044-19k8zbb/build/config -I/tmp/neovim-20200828-46044-19k8zbb/src -I/usr/local/include -I/tmp/neovim-20200828-46044-19k8zbb/deps-build/include -I/usr/local/Cellar/unibilium/2.0.0/include -I/usr/local/Cellar/libtermkey/0.22/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200828-46044-19k8zbb/build/src/nvim/auto -I/tmp/neovim-20200828-46044-19k8zbb/build/include
Compiled by o.matrohin@matrohin.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-91109ff/share/nvim"

Run :checkhealth for more info
```

**Additional context**
Regression was introduced in this commit: https://github.com/nvim-treesitter/nvim-treesitter/commit/ce7efd34c688ae8d548cf384b215975ef3e6fd98

because runtime paths is ended with /
/Users/usernname/.config/nvim/plugged/nvim-treesitter/

**Comment by vigoux** [comment] 2020-08-30 20:29
Hi ! Thanks for reporting, that looks like a duplicate of #172, did you tried the fix there ?

**Comment by vigoux** [comment] 2020-08-30 20:29
> because runtime paths is ended with /
> /Users/usernname/.config/nvim/plugged/nvim-treesitter/

What do you mean by that ?

**Comment by errx** [comment] 2020-08-30 20:34
No this is different


I guess error is here
https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/utils.lua#L22

```
echo fnamemodify("foo/bar/", ":t") is not working
echo fnamemodify("fo/bar/", ":h:t")    will print bar (correct)
```

**Comment by errx** [comment] 2020-08-30 20:37
also all my runtime paths:
```
  runtimepath=~/.config/nvim,~/.config/nvim/plugged/lightline.vim/,~/.config/nvim/plugged/vim-highlightedyank/,~/.config/nvim/plugged/rainbow/,~/.config/nvim/plugged/vim-fugitive/,~/.config/nvim/pl
ugged/vim-commentary/,~/.config/nvim/plugged/vim-sensible/,~/.config/nvim/plugged/vim-wordmotion/,~/.config/nvim/plugged/vim-rooter/,~/.config/nvim/plugged/vim-css-color/,~/.config/nvim/plugged/bas
e16-vim/,~/.config/nvim/plugged/gruvbox/,~/.config/nvim/plugged/ultisnips/,~/.config/nvim/plugged/vim-snippets/,~/.config/nvim/plugged/rust.vim/,~/.fzf/,~/.config/nvim/plugged/fzf.vim/,~/.config/nv
im/plugged/coc.nvim/,~/.config/nvim/plugged/nvim-treesitter/,/etc/xdg/nvim,~/.local/share/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr/local/Cellar/neovim/HEAD-91109ff/share/nvim/
runtime,/usr/local/Cellar/neovim/HEAD-91109ff/share/nvim/runtime/pack/dist/opt/matchit,/usr/local/Cellar/neovim/HEAD-91109ff/lib/nvim,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,~/.
local/share/nvim/site/after,/etc/xdg/nvim/after,~/.c```

note the trailing slash in some cases

**Comment by errx** [comment] 2020-08-30 20:40
I don't know maybe this behavior is specific to plug.vim

**Comment by theHamsta** [comment] 2020-08-30 20:52
I was waiting for this to come. Using those weird vim functions on the first try couldn't go right. Though I tested most combination that I thought could be possible.

**Comment by errx** [comment] 2020-08-30 20:53
https://github.com/nvim-treesitter/nvim-treesitter/pull/364 maybe this will fix it?

**Comment by theHamsta** [comment] 2020-08-30 21:00
For me this all witch craft. We should have stayed with the regex solution which is understandable for mere mortals.

I tried your fix it seems to be working but only for `penultimate_segement` shouldn't it be just `:t` for the last segment

**Closed** 2020-08-30 21:48 UTC
Labels: bug

**Comment by toupeira** [comment] 2020-09-04 15:13
I ran into this error with Pathogen (which just uses `runtimepath` without any other magic), in my case the problem was that I cloned the repo as `treesitter` instead of `nvim-treesitter`, so the check at https://github.com/nvim-treesitter/nvim-treesitter/blob/fcdb3eb35d849fe29eb682e4e082f4ffa0c5d38f/lua/nvim-treesitter/utils.lua#L23 failed.

It looks like in Lua we could use `debug.getinfo()` to get the path to the current source file, and resolve the package path from there. This seems to work:

```lua
function M.get_package_path()
  -- Path to this source file, removing the leading '@'
  local source = string.sub(debug.getinfo(1, 'S').source, 2)

  -- Path to the package root
  return fn.fnamemodify(source, ":p:h:h:h")
end
```

@vigoux what do you think?

**Comment by vigoux** [comment] 2020-09-04 15:15
Sounds like a good idea, and a more robust way of handling this problem.

**Comment by toupeira** [comment] 2020-09-10 12:21
@vigoux great, I submitted a PR at https://github.com/nvim-treesitter/nvim-treesitter/pull/432! :+1:
