### ISSUE TITLE
Tracking Issue: Tree-sitter-based Concealing

### ISSUE THREAD

**Issue by theHamsta** [nvim-treesitter/nvim-treesitter#2663] opened 2022-03-21 12:10 UTC
As https://github.com/nvim-treesitter/nvim-treesitter/issues/2660 mentioned it is now possible to use the conceal feature for tree-sitter highlights using https://github.com/neovim/neovim/pull/17776. This issues is for tracking and discussing for which languages conceal would make sense and how we would structure the queries for that. Please post here when you would like to have some conceal features for a certain language.

The following languages already have PRs:

 - [ ] markdown #2662
 - [ ] JSON (https://github.com/nvim-treesitter/nvim-treesitter/pull/2664, see #645)

TODOs:

- [ ] RST
- [ ] LaTeX (needs discussion because of huge number of single-character replacements)

**Comment by gegoune** [comment] 2022-03-21 12:15
Would be nice to be able to conceal `"`s in `json` files. Related https://github.com/nvim-treesitter/nvim-treesitter/issues/645.

**Comment by clason** [comment] 2022-03-21 12:18
Also, a fundamental question: Do we want to put these into the `highlights.scm` queries (following the legacy syntax precedent), or create a new `conceal.scm` query type so people who don't want conceal can just ignore them?

**Comment by theHamsta** [comment] 2022-03-21 12:28
@clason I also had this question. We could logically merge `conceal.scm` into `highlight.scm` but keep them logically separated on filesystem. If we assume that most queries are as small as for markdown it would be tolerable to have them in the highlights.scm.

**Comment by clason** [comment] 2022-03-21 12:31
I don't know what the best option is, either. For Markdown I agree, but I was mostly thinking of LaTeX.

We could also think of handling LaTeX as a special case? I agree that we should not needlessly increase the number of modules and options.

**Comment by theHamsta** [comment] 2022-03-21 12:33
For LaTeX, we probably need a check on the conceallevel for more fancy conceals. Could be handled by predicates. Are there other reasons why LaTeX is special? I think most of the needed tokens (e.g. `$` for math mode are already in the token tree.

**Comment by clason** [comment] 2022-03-21 12:37
No, just the fancy conceals (meaning, you have a replacement instead of just hiding a capture). But there are [a lot of them](https://github.com/nvim-treesitter/nvim-treesitter/issues/645)...

**Comment by megalithic** [comment] 2022-04-18 20:51
I think this is what i'm most excited about.. `- [ ]` rendering as `- ` and `- [x]` as `- ` basically a checkbox that is checked, or any number of options for that (as also seen in the various org-mode plugins).

**Comment by j-hui** [comment] 2022-05-18 00:32
Just checking in on support for Latex: what are the issues blocking support for Latex symbol conceal? This is something I'm really looking forward to!

**Comment by clason** [comment] 2022-05-18 06:14
Still the same as I mentioned above: a principled way to opting into levels of conceals (and someone who cares actually implementing all of them).

**Comment by ziontee113** [comment] 2022-06-18 06:48
Hi guys, I'm planning to maybe make a plugin with the purpose of shortening CSS classes (useful for React, Vue, Svelte, HTML,....) especially when the user uses CSS libraries like Bootstrap or Tailwind.

Put in the work is not the issue for me. It's just that I don't know the ins and outs of the current state of Neovim's Conceal & Treesitter.

**Comment by sisrfeng** [comment] 2022-07-25 03:19
For conceal in python:
I think this can be merged (after some modification, e.g., adding options of using conceal or not)
https://gist.github.com/graelo/2d1f5bc6775432a5c8eb6d6c8b624011

**Comment by dlvhdr** [comment] 2022-08-26 14:50
I like concealment for markdown, but I would like to disable it specifically for code blocks.
How can I do that?
Is there an opposite of `#set! conceal`?

**Comment by ahmedelgabri** [comment] 2022-10-09 16:34
I have a question regarding concealing fenced code blocks https://github.com/nvim-treesitter/nvim-treesitter/pull/2662. I'd like to conceal the tripple ticks/tildas but keep the language visible. Right now, seems like `language` is a child of `info_string`, so is it possible to do something like this?

**Comment by vishalbalaji** [comment] 2022-10-12 13:51
I have a question regarding how conceal selects which capture group to conceal. If there are multiple capture groups in a query, then `#set! conceal` targets the first capture group in the chain by default. 

According to the (neovim treesitter docs)[https://neovim.io/doc/user/treesitter.html#treesitter-directives], you should be able to specify the capture group in the `#set!` directive. However, when a capture group is passed to `#set! conceal`, the entire query is just ignored.

Is this the intended behaviour? Is there a way to get around this? This is in relation to discussion #3613.

**Comment by ryleelyman** [comment] 2022-12-01 01:57
I didn't manage to get even all the default regex-based latex conceals (mainly properly concealing something like `\'etale` as `étale` would require a bigger tree-sitter parser change than I feel like attempting), but a good amount of them are implemented [in latex.nvim](https://github.com/ryleelyman/latex.nvim). The plugin allows for a certain amount of granularity along the lines of the `g:tex_conceal='abdmgs'` kind of configuration.

I discovered that implementing each conceal as its own query was 1) extremely slow and 2) quickly ran over the maximum number of queries treesitter would accept, so I added a `#set-pairs!` directive, as well as a somewhat hacky `#has-grandparent?` to get around the conceal directive's kind of bizarre behavior mentioned by @vishalbalaji above.

**Comment by ColinKennedy** [comment] 2023-10-21 20:50
A use case for this ticket: objdump files contain both objdump specific text as well as assembly code. It'd be a great help if I could use a quick conceal to toggle the display of the non-assembly bits on and off.

To get an idea of what I mean, this is a regular objdump

```
0000000000400d60 <stuff>:
  129:	48 8d 3d 00 00 00 00                                  	lea    rdi,[rip+0x0]        # 130 <void std::vector<engine::entity::Entity, std::allocator<engine::entity::Entity> >::_M_realloc_insert<engine::entity::Entity const&>(__gnu_cxx::__normal_iterator<engine::entity::Entity*, std::vector<engine::entity::Entity, std::allocator<engine::entity::Entity> > >, engine::entity::Entity const&)+0x130> (File Offset: 0x40c)
```

And ideally a conceal to temporarily remove the non-assembly, which would then look like

```
lea    rdi,[rip+0x0]
```

objdump files are commonly hundreds to thousands of lines so the ability to remove the display if you don't need it would be huge. And on the note of "should it be in highlight.scm or a separate conceal.scm", as long as the conceal can be opted in or out at any time, either works IMO. From an organizational standpoint I think it'd be good to use a separate conceal.scm so it's clear which languages support conceals at a glance would be helpful. But it's probably fine even as a combined, single file.

**Comment by clason** [comment] 2023-10-21 21:03
Sorry, forgot to close this. Nvim-treesitter only allows marking captures for concealing (no request necessary, just make a PR). Everything else is a (non-trivial) Neovim issue and out of scope here.

**Closed by clason** 2023-10-21 21:03 UTC
