### ISSUE TITLE
Support for Solidity

### ISSUE THREAD

**Issue by stevennevins** [nvim-treesitter/nvim-treesitter#2607] opened 2022-03-07 13:14 UTC
What would the steps be to add solidity support through nvim-tree sitter?  I was able to install from grammar this repository, but when I tried moving the highlights.scm into treesitter it started throwing parsing errors

This is the repo that I tried installing from grammer file https://github.com/JoranHonig/tree-sitter-solidity

**Comment by clason** [comment] 2022-03-07 13:20
Duplicate of #2282, which also explains more how to proceed. (Questions should be asked on Matrix instead of as an issue.)

**Closed by clason** 2022-03-07 13:20 UTC
Labels: enhancement, good first issue, help wanted
