### ISSUE TITLE
Error in php files

### ISSUE THREAD

**Issue by Nobody9512** [nvim-treesitter/nvim-treesitter#7059] opened 2024-08-19 09:47 UTC
### Describe the bug

Error in opening php files:

```
Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...2823/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 224:5. Invalid field name "alias":
    alias: (name) @type.definition
    ^

stack traceback:
	[C]: in function '_ts_parse_query'
	...2823/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
	...im/2823/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
	...im/2823/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
	...sr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
	...sr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:240: in function 'get_query'
	...sr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:188: in function 'fn'
	...r/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
	...sr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:175: in function 'prepare_highlight_states'
	...sr/share/nvim/runtime/lua/vim
```

### To Reproduce

1. Opening php file

### Output of `:checkhealth nvim-treesitter`

```markdown
Installation ~
- OK `tree-sitter` found 0.22.2 (fc15f621334a262039ffaded5937e2844f88da61) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.19.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.5.0-1027-oem",
  sysname = "Linux",
  version = "#28-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 25 13:32:46 UTC 2024"
} ~

...
  - perl                ✓ . ✓ . ✓
  - php                 x x ✓ x ✓
  - php_only            x x ✓ x ✓
  - phpdoc              ✓ . . . .
  - pioasm              ✓ . . . ✓
```

### Output of `nvim --version`

```text
NVIM v0.10.0
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

**Comment by clason** [comment] 2024-08-19 11:35
Duplicate of #3092

**Closed by clason** 2024-08-19 11:35 UTC
Labels: bug
