### ISSUE TITLE
Treesitter is not working with c headers files

### ISSUE THREAD

**Issue by RayenMnif** [nvim-treesitter/nvim-treesitter#7156] opened 2024-09-17 17:08 UTC
### Describe the highlighting problem

Treesitter is not working with c headers files 

### Example snippet that causes the problem

```
Error in decoration provider treesitter/highlighter.win:
Error executing lua: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 565:4. Invalid node type "virtual":
  "virtual"
   ^

stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:243: in function 'get_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:191: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:178: in function 'prepare_highlight_states'
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:405: in function </usr/share/nvim/
```

### Tree-sitter parsing result

![Screenshot from 2024-09-17 18-04-26](https://github.com/user-attachments/assets/681aa684-9e5d-4b39-9eea-66c20d3306ee)

### Example screenshot

stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:243: in function 'get_query'
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:286: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:273: in function 'get_captures_at_pos'
        /usr/share/nvim/runtime/lua/vim/_inspector.lua:79: in function 'inspect_pos'
        /usr/share/nvim/runtime/lua/vim/_inspector.lua:153: in function 'show_pos'
        vim/_defaults.lua: in function <vim/_defaults.lua:0>

### Output of `:checkhealth nvim-treesitter`

```markdown
stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:243: in function 'get_query'
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:286: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:273: in function 'get_captures_at_pos'
        /usr/share/nvim/runtime/lua/vim/_inspector.lua:79: in function 'inspect_pos'
        /usr/share/nvim/runtime/lua/vim/_inspector.lua:153: in function 'show_pos'
        vim/_defaults.lua: in function <vim/_defaults.lua:0>
```

### Output of `nvim --version`

```text
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1725453128
```

**Comment by clason** [comment] 2024-09-17 17:09
Duplicate of #3092

**Closed by clason** 2024-09-17 17:09 UTC
Labels: highlights
