### ISSUE TITLE
module 'vim.treesitter.query' not found

### ISSUE THREAD

**Issue by nymann** [nvim-treesitter/nvim-treesitter#340] opened 2020-08-25 08:48 UTC
**Describe the bug**
When I open up neovim I get the following error message:
```
Error detected while processing /home/knj/code/github.com/nymann/dotfiles/dots/nvim/plugged/nvim-treesitter/plugin/nvim-treesitter.vim:
line   23:
E5108: Error executing lua ...vim-treesitter//lua/nvim-treesitter/query_predicates.lua:1: module 'vim.treesitter.query' not found:
        no field package.preload['vim.treesitter.query']
        no file '/home/knj/.config/nvim/lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/nvim-lsp//lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/nvim-lsp//lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/completion-nvim//lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/completion-nvim//lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/diagnostic-nvim//lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/diagnostic-nvim//lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/lsp-status.nvim//lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/lsp-status.nvim//lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/nvim-treesitter//lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/nvim-treesitter//lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/nerdcommenter//lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/nerdcommenter//lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/vim-autoformat//lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/vim-autoformat//lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/vim-gitbranch//lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/vim-gitbranch//lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/vim-fugitive//lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/vim-fugitive//lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/vim-rhubarb//lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/vim-rhubarb//lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/vim-signify//lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/vim-signify//lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/indentLine//lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/indentLine//lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/fzf//lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/fzf//lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/fzf.vim//lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/fzf.vim//lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/vim-easy-align//lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/vim-easy-align//lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/quick-scope//lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/quick-scope//lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/nvim-colorizer.lua//lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/nvim-colorizer.lua//lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/markdown-preview.nvim//lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/markdown-preview.nvim//lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/vim-grammarous//lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/vim-grammarous//lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/onedark.vim//lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/onedark.vim//lua/vim/treesitter/query/init.lua'
        no file '/etc/xdg/nvim/lua/vim/treesitter/query.lua'
        no file '/etc/xdg/nvim/lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.local/share/nvim/site/lua/vim/treesitter/query.lua'
        no file '/home/knj/.local/share/nvim/site/lua/vim/treesitter/query/init.lua'
        no file '/usr/local/share/nvim/site/lua/vim/treesitter/query.lua'
        no file '/usr/local/share/nvim/site/lua/vim/treesitter/query/init.lua'
        no file '/usr/share/nvim/site/lua/vim/treesitter/query.lua'
        no file '/usr/share/nvim/site/lua/vim/treesitter/query/init.lua'
        no file '/usr/share/nvim/runtime/lua/vim/treesitter/query.lua'
        no file '/usr/share/nvim/runtime/lua/vim/treesitter/query/init.lua'
        no file '/usr/lib/nvim/lua/vim/treesitter/query.lua'
        no file '/usr/lib/nvim/lua/vim/treesitter/query/init.lua'
        no file '/usr/share/nvim/site/after/lua/vim/treesitter/query.lua'
        no file '/usr/share/nvim/site/after/lua/vim/treesitter/query/init.lua'
        no file '/usr/local/share/nvim/site/after/lua/vim/treesitter/query.lua'
        no file '/usr/local/share/nvim/site/after/lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.local/share/nvim/site/after/lua/vim/treesitter/query.lua'
        no file '/home/knj/.local/share/nvim/site/after/lua/vim/treesitter/query/init.lua'
        no file '/etc/xdg/nvim/after/lua/vim/treesitter/query.lua'
        no file '/etc/xdg/nvim/after/lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/after/lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/after/lua/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/plugged/indentLine/after/lua/vim/treesitter/query.lua'
        no file '/home/knj/.config/nvim/plugged/indentLine/after/lua/vim/treesitter/query/init.lua'
        no file '/usr/share/vim/vimfiles/lua/vim/treesitter/query.lua'
        no file '/usr/share/vim/vimfiles/lua/vim/treesitter/query/init.lua'
        no file './vim/treesitter/query.lua'
        no file '/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/share/luajit-2.1.0-beta3/vim/treesitter/query.lua'
        no file '/usr/local/share/lua/5.1/vim/treesitter/query.lua'
        no file '/usr/local/share/lua/5.1/vim/treesitter/query/init.lua'
        no file '/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/share/lua/5.1/vim/treesitter/query.lua'
        no file '/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/share/lua/5.1/vim/treesitter/query/init.lua'
        no file '/home/knj/.config/nvim/lua/vim/treesitter/query.so'
        no file '/home/knj/.config/nvim/plugged/nvim-lsp//lua/vim/treesitter/query.so'
        no file '/home/knj/.config/nvim/plugged/completion-nvim//lua/vim/treesitter/query.so'
        no file '/home/knj/.config/nvim/plugged/diagnostic-nvim//lua/vim/treesitter/query.so'
        no file '/home/knj/.config/nvim/plugged/lsp-status.nvim//lua/vim/treesitter/query.so'
        no file '/home/knj/.config/nvim/plugged/nvim-treesitter//lua/vim/treesitter/query.so'
        no file '/home/knj/.config/nvim/plugged/nerdcommenter//lua/vim/treesitter/query.so'
        no file '/home/knj/.config/nvim/plugged/vim-autoformat//lua/vim/treesitter/query.so'
        no file '/home/knj/.config/nvim/plugged/vim-gitbranch//lua/vim/treesitter/query.so'
        no file '/home/knj/.config/nvim/plugged/vim-fugitive//lua/vim/treesitter/query.so'
        no file '/home/knj/.config/nvim/plugged/vim-rhubarb//lua/vim/treesitter/query.so'
        no file '/home/knj/.config/nvim/plugged/vim-signify//lua/vim/treesitter/query.so'
        no file '/home/knj/.config/nvim/plugged/indentLine//lua/vim/treesitter/query.so'
        no file '/home/knj/.config/nvim/plugged/fzf//lua/vim/treesitter/query.so'
        no file '/home/knj/.config/nvim/plugged/fzf.vim//lua/vim/treesitter/query.so'
        no file '/home/knj/.config/nvim/plugged/vim-easy-align//lua/vim/treesitter/query.so'
        no file '/home/knj/.config/nvim/plugged/quick-scope//lua/vim/treesitter/query.so'
        no file '/home/knj/.config/nvim/plugged/nvim-colorizer.lua//lua/vim/treesitter/query.so'
        no file '/home/knj/.config/nvim/plugged/markdown-preview.nvim//lua/vim/treesitter/query.so'
        no file '/home/knj/.config/nvim/plugged/vim-grammarous//lua/vim/treesitter/query.so'
        no file '/home/knj/.config/nvim/plugged/onedark.vim//lua/vim/treesitter/query.so'
        no file '/etc/xdg/nvim/lua/vim/treesitter/query.so'
        no file '/home/knj/.local/share/nvim/site/lua/vim/treesitter/query.so'
        no file '/usr/local/share/nvim/site/lua/vim/treesitter/query.so'
        no file '/usr/share/nvim/site/lua/vim/treesitter/query.so'
        no file '/usr/share/nvim/runtime/lua/vim/t
Press ENTER or type command to continue
```

**To Reproduce**
1. Open neovim

**Expected behavior**
No errors are shown

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## Missing parsers
  - WARNING: Some parsers are not installed:
    elm
    c
    java
    python
    dart
    lua
    ocaml
    go
    nix
    yaml
    json
    jsdoc
    markdown
    julia
    html
    typescript
    fennel
    swift
    query
    cpp
    ruby
    vue
    scala
    tsx
    rust
    bash
    c_sharp
    rst
    css
    php
    javascript
    haskell
    toml
    regex
    - ADVICE:
      - Install them using `:TSInstall language

health#nvim#check

</code>
</details>

**Output of `nvim --version`**
```
 $ nvim --version                                                                                                                            130 ↵
NVIM v0.5.0-622-gf26df8bb6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-b60d7f7a-2dc5-4a6d-bb2a-adaae1420daa

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Additional context**
I don't have the command `:TSInstall` or any other `:TS` commands.

**Comment by theHamsta** [comment] 2020-08-25 08:52
Duplicate of #322 . You need a nvim- version from August 13 or newer

We should maybe keep these issue open as long as people still have problems.

**Comment by nymann** [comment] 2020-08-25 09:09
Thanks @theHamsta the newest version currently on the AUR is the one I have, so I guess a lot of people will face this issue. :-)

**Comment by theHamsta** [comment] 2020-08-25 09:28
We try to submit core thing of this plugin to upstream. So when something from here is moved to upstream people need to upgrade their nvim version.

**Comment by norcalli** [comment] 2020-09-01 19:08
It seems like it would be kinder to do a version check at the start of the plugin's init which aborts initialization if the required version isn't met (or by checking for the existence of required features), and then printing the required minimum commit/date.

**Comment by theHamsta** [comment] 2020-09-01 21:42
How can I pin this issue?

**Closed** 2020-09-18 22:59 UTC
Labels: bug

**Comment by RobyCigar** [comment] 2022-05-11 03:23
In my case, ubuntu package manager(apt) only have version v0.4.0 so you need to update to latest version using manual installation

**Comment by githorse** [comment] 2023-01-28 00:08
Still seeing this error with Neovim v0.9.0-dev (nightly build) ... what am I missing here?

```
:version                                                                                                                                                                                                                            
NVIM v0.9.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-kPj90v/neovim-0.9.0~ubuntu1+git202301261605-a0a112515-333b5866f=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g  -Og
 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fno-common -fdiagno
stics-color=auto -fstack-protector-strong -DNVIM_UNIBI_HAS_VAR_FROM -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DMIN_LOG_LEVEL=3 -I/usr/include/luaji
t-2.1 -I/usr/include -I/build/neovim-kPj90v/neovim-0.9.0~ubuntu1+git202301261605-a0a112515-333b5866f/.deps/usr/include -I/build/neovim-kPj90v/neovim-0.9.0~ubuntu1+git202301261605-a0a112515-333b5866f/build/src/nvim/auto -I/build/neovim-kPj
90v/neovim-0.9.0~ubuntu1+git202301261605-a0a112515-333b5866f/build/include -I/build/neovim-kPj90v/neovim-0.9.0~ubuntu1+git202301261605-a0a112515-333b5866f/build/cmake.config -I/build/neovim-kPj90v/neovim-0.9.0~ubuntu1+git202301261605-a0a1
12515-333b5866f/src
Compiled by buildd@lcy02-amd64-002

Features: +acl +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by theHamsta** [comment] 2023-01-28 00:16
> Still seeing this error with Neovim v0.9.0-dev (nightly build) ... what am I missing here?
> 
> ```
> :version                                                                                                                                                                                                                            
> NVIM v0.9.0-dev
> Build type: RelWithDebInfo
> LuaJIT 2.1.0-beta3
> Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-kPj90v/neovim-0.9.0~ubuntu1+git202301261605-a0a112515-333b5866f=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g  -Og
>  -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fno-common -fdiagno
> stics-color=auto -fstack-protector-strong -DNVIM_UNIBI_HAS_VAR_FROM -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DMIN_LOG_LEVEL=3 -I/usr/include/luaji
> t-2.1 -I/usr/include -I/build/neovim-kPj90v/neovim-0.9.0~ubuntu1+git202301261605-a0a112515-333b5866f/.deps/usr/include -I/build/neovim-kPj90v/neovim-0.9.0~ubuntu1+git202301261605-a0a112515-333b5866f/build/src/nvim/auto -I/build/neovim-kPj
> 90v/neovim-0.9.0~ubuntu1+git202301261605-a0a112515-333b5866f/build/include -I/build/neovim-kPj90v/neovim-0.9.0~ubuntu1+git202301261605-a0a112515-333b5866f/build/cmake.config -I/build/neovim-kPj90v/neovim-0.9.0~ubuntu1+git202301261605-a0a1
> 12515-333b5866f/src
> Compiled by buildd@lcy02-amd64-002
> 
> Features: +acl +tui
> See ":help feature-compile"
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/usr/share/nvim"
> 
> Run :checkhealth for more info
> ```

Do you have a (older) Neovim installation from your distro? So that it would use the binary of your self-compiled version but the runtime files from the old Neovim?

**Comment by andyl** [comment] 2023-04-21 18:21
Also see this error with 0.9.0 - only when running under tmux, only on a newly configured machine (Xubuntu 22.04)

**Comment by armandfavrot** [comment] 2023-12-03 10:06
Same error. I just upgraded neovim from v0.6.1 to v0.9.4.
