### ISSUE TITLE
[Golang] Indentation issue with generics + type aliases

### ISSUE THREAD

**Issue by geefuoco** [nvim-treesitter/nvim-treesitter#3508] opened 2022-09-16 00:38 UTC
### Describe the bug

The cursor indentation is incorrect when calling a function with generics if a type alias is present

```go
package util

type Node[T any] struct {
  Val T
  Next *Node[T]
  Prev *Node[T]
}

func New[T any](v T) *Node[T] {
  return &Node{Val: v, Next: nil, Prev: nil}
}

====================================
package tests

import "util"

type Node = util.Node[uint]

func test() {
  t := util.New[uint](uint(0))
<-- cursor is here
}
```

Strangely, if a semicolon is placed after the type alias, it works correctly

```go
package tests

import "util"

type Node = util.Node[uint]; //semicolon added here

func test() {
  t := util.New[uint](uint(0))
  <-- cursor is here
}
```

### To Reproduce

1. Create a generic type and constructor in another package
2. Create a type alias for the generic type in current package and don't put a semicolon at the end
3. Call the constructor inside a function

### Expected behavior

```go
package util

type Node[T any] struct {
  Val T
  Next *Node[T]
  Prev *Node[T]
}

func New[T any](v T) *Node[T] {
  return &Node{Val: v, Next: nil, Prev: nil}
}
============================

import "util"

type Node = util.Node[uint]

func test() {
  t := util.New[uint](uint(0))
  <-- cursor should be here
}
```

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.13.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - bibtex         ✓ . ✓ ✓ .
  - scheme         ✓ . ✓ . ✓
  - gitattributes  ✓ . . . ✓
  - zig            ✓ . ✓ ✓ ✓
  - rego           ✓ . . . ✓
  - todotxt        ✓ . . . .
  - sxhkdrc        ✓ . ✓ . ✓
  - cmake          ✓ . ✓ . .
  - typescript     ✓ ✓ ✓ ✓ ✓
  - v              ✓ ✓ ✓ ✓ ✓
  - tiger          ✓ ✓ ✓ ✓ ✓
  - scala          ✓ . ✓ . ✓
  - proto          ✓ . ✓ . .
  - json5          ✓ . . . ✓
  - supercollider  ✓ ✓ ✓ ✓ ✓
  - m68k           ✓ ✓ ✓ . ✓
  - pioasm         ✓ . . . ✓
  - slint          ✓ . . ✓ .
  - hjson          ✓ ✓ ✓ ✓ ✓
  - racket         ✓ . ✓ . ✓
  - haskell        ✓ . ✓ . ✓
  - hocon          ✓ . . . ✓
  - astro          ✓ ✓ ✓ ✓ ✓
  - llvm           ✓ . . . .
  - svelte         ✓ . ✓ ✓ ✓
  - json           ✓ ✓ ✓ ✓ .
  - vim            ✓ ✓ ✓ . ✓
  - solidity       ✓ . . . .
  - prisma         ✓ . . . .
  - beancount      ✓ . ✓ . .
  - vala           ✓ . ✓ . .
  - tlaplus        ✓ ✓ ✓ . ✓
  - query          ✓ ✓ ✓ ✓ ✓
  - make           ✓ . . . ✓
  - hack           ✓ . . . .
  - foam           ✓ ✓ ✓ ✓ ✓
  - toml           ✓ ✓ ✓ ✓ ✓
  - rasi           ✓ ✓ ✓ ✓ .
  - norg           . . . . .
  - http           ✓ . . . ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - help           ✓ . . . .
  - pug            ✓ . . . ✓
  - fortran        ✓ . ✓ ✓ .
  - latex          ✓ . ✓ . ✓
  - vue            ✓ . ✓ ✓ ✓
  - go             ✓ ✓ ✓ ✓ ✓
  - jsonc          ✓ ✓ ✓ ✓ ✓
  - clojure        ✓ ✓ ✓ . ✓
  - lalrpop        ✓ ✓ . . .
  - elm            ✓ . . . ✓
  - commonlisp     ✓ ✓ ✓ . .
  - yaml           ✓ ✓ ✓ ✓ ✓
  - r              ✓ ✓ . ✓ ✓
  - yang           ✓ . ✓ ✓ .
  - cuda           ✓ ✓ ✓ ✓ ✓
  - cooklang       ✓ . . . .
  - ninja          ✓ . ✓ ✓ .
  - elvish         ✓ . . . ✓
  - glsl           ✓ ✓ ✓ ✓ ✓
  - hlsl           ✓ ✓ ✓ ✓ ✓
  - dart           ✓ ✓ . ✓ ✓
  - dockerfile     ✓ . . . ✓
  - wgsl           ✓ . ✓ . .
  - rst            ✓ ✓ . . ✓
  - dot            ✓ . . . ✓
  - fennel         ✓ ✓ . . ✓
  - bash           ✓ ✓ ✓ . ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - nix            ✓ ✓ ✓ . ✓
  - fusion         ✓ ✓ ✓ ✓ .
  - ql             ✓ ✓ . ✓ ✓
  - jsdoc          ✓ . . . .
  - cpp            ✓ ✓ ✓ ✓ ✓
  - comment        ✓ . . . .
  - javascript     ✓ ✓ ✓ ✓ ✓
  - pascal         ✓ ✓ ✓ ✓ ✓
  - regex          ✓ . . . .
  - c              ✓ ✓ ✓ ✓ ✓
  - glimmer        ✓ . . . .
  - html           ✓ ✓ ✓ ✓ ✓
  - gomod          ✓ . . . ✓
  - tsx            ✓ ✓ ✓ ✓ ✓
  - gowork         ✓ . . . ✓
  - hcl            ✓ . ✓ ✓ ✓
  - graphql        ✓ . . ✓ ✓
  - sparql         ✓ ✓ ✓ ✓ ✓
  - verilog        ✓ ✓ ✓ . ✓
  - ruby           ✓ ✓ ✓ ✓ ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - perl           ✓ . ✓ . .
  - gdscript       ✓ ✓ . ✓ ✓
  - java           ✓ ✓ . ✓ ✓
  - elixir         ✓ ✓ ✓ ✓ ✓
  - fish           ✓ ✓ ✓ ✓ ✓
  - c_sharp        ✓ ✓ ✓ . ✓
  - ledger         ✓ . ✓ ✓ ✓
  - php            ✓ ✓ ✓ ✓ ✓
  - surface        ✓ . ✓ ✓ ✓
  - turtle         ✓ ✓ ✓ ✓ ✓
  - agda           ✓ . ✓ . .
  - eex            ✓ . . . ✓
  - css            ✓ . ✓ ✓ ✓
  - heex           ✓ ✓ ✓ ✓ ✓
  - scss           ✓ . . ✓ .
  - ocaml          ✓ ✓ ✓ . ✓
  - erlang         ✓ . ✓ . .
  - gleam          ✓ ✓ ✓ ✓ ✓
  - embedded_template✓ . . . ✓
  - ocaml_interface✓ ✓ ✓ . ✓
  - meson          ✓ . ✓ . ✓
  - julia          ✓ ✓ ✓ ✓ ✓
  - kotlin         ✓ ✓ ✓ . ✓
  - menhir         ✓ . . . ✓
  - markdown       ✓ . ✓ . ✓
  - org            . . . . .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az164-457

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

### Additional context

- Only seems to occur when a generic function is called from a different package
- A semicolon after the type alias fixes the indentation

**Comment by amaanq** [comment] 2023-05-08 22:13
Seems fixed now, can't reproduce

**Closed by amaanq** 2023-05-08 22:13 UTC
Labels: bug
