### ISSUE TITLE
vim-prettier causes `end_col` errors.

### ISSUE THREAD

**Issue by itmecho** [nvim-treesitter/nvim-treesitter#1376] opened 2021-06-10 10:09 UTC
**Describe the bug**
I have a `BufWritePre` autocommand on typescript files to run the `Prettier` command. When the formatter makes changes, the highlighting breaks from the point of the first change with the following error message: 
```
treesitter/highlighter: Error executing lua: ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:259: end_col value outside range
```

Reopening the file with `:edit` then fixes the highlighting. This only seems to be happening with `Prettier` and typescript, I don't see this issue with go and `gofmt`.

This has broken since I ran `PackerSync` but I'm unsure of how to find which version I was using before the update.

**To Reproduce**

1. `yarn create next-app --typescript example && cd example`
2. `yarn add -D prettier`
2. Install nvim-treesitter and enable highlighting
3. Install `prettier/vim-prettier`
3. `:TSInstall tsx` and `:TSInstall typescript`
4. Open `pages/index.tsx`
5. `:autocmd BufWritePre * Prettier`
6. `:w` - This should run prettier and format the file. This is the point where I get the error

**Expected behavior**

Highlighting should continue to work as expected

**Output of `:checkhealth nvim_treesitter`**

<details>
<pre>
health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v12.22.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
</pre>
</details>

**Output of `nvim --version`**

<details>
<pre>
NVIM v0.5.0-dev+1385-g93f15db5d
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/iain/src/neovim/build/config -I/home/iain/src/neovim/src -I/home/iain/src/neovim/.deps/usr/include -I/usr/include -I/home/iain/src/neovim/build/src/nvim/auto -I/home/iain/src/neovim/build/include
Compiled by iain@orion

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/iain/.local/share/nvim"

Run :checkhealth for more info
</pre>
</details>

**Additional context**
Before:
![image](https://user-images.githubusercontent.com/8384983/121505069-65a07480-c9da-11eb-8b21-5bd91be33cb2.png)

After:
![image](https://user-images.githubusercontent.com/8384983/121505122-7650ea80-c9da-11eb-86c2-9a651cfb9d61.png)

**Comment by dakahn** [comment] 2021-06-10 18:59
This is also happening to me on my non-typescript javascript files when running Prettier. Closing and reopening fixes the broken highlighting for me as well
![image](https://user-images.githubusercontent.com/40970507/121581903-00f21380-c9f4-11eb-8491-907402ff6b3b.png)

**Comment by vigoux** [comment] 2021-06-11 06:36
Hi, and thanks for reporting.

This issue was actually already reported, and comes from upstream.
FYI we think that the issue arrises in the vim-prettier plugin, and we are going to investigate in this direction.

I'll then mark that as duplicate and upstream (maybe even close it).

Please refer to neovim/neovim#12861 and especiallye [this comment](https://github.com/neovim/neovim/issues/12861#issuecomment-857624004) for more information.

**Comment by chentau** [comment] 2021-06-11 07:36
@vigoux I'm pretty sure this is another issue with `curbuf->deleted_bytes2` not being correctly zeroed out; it's causing `extmark_adjust` to send incorrect buffer updates. I haven't had time to work on extmark stuff recently, but I can submit a quick patch this weekend.

**Comment by vigoux** [comment] 2021-06-11 08:24
Pretty sure it is not to be honest (see https://github.com/neovim/neovim/issues/14772).
But in any case, we should stop relying on `deleted_bytes`.

**Comment by chentau** [comment] 2021-06-11 08:37
`lockmarks` with `append()` does probably cause the bulk of invalid updates, but the `:delete` ex command is also causing some of them, too. For example, substituting/joining a line and then running `:%delete` will send invalid buffer updates.

**Comment by AstroLuluGit** [comment] 2021-06-22 13:17
Anything new on this bug? I am getting this error as well, while formatting TSX files with vim-prettier.

**Comment by stsewd** [comment] 2021-06-26 18:48
This is a duplicate of https://github.com/nvim-treesitter/nvim-treesitter/issues/1201 indeed, I'll link to this issue from the other one in case this case isn't mentioned there already.

**Closed by stsewd** 2021-06-26 18:48 UTC
Labels: bug, duplicate, upstream
