### ISSUE TITLE
lua: parser error for multiple situations

### ISSUE THREAD

**Issue by boltlessengineer** [nvim-treesitter/nvim-treesitter#3183] opened 2022-07-15 15:22 UTC
### Describe the bug

Tree-sitter parsing brokes when I save the file with change.
But it gets fine only when I restart the neovim(`:edit` doesn't fix the problem).

This doesn't occurs every time, but it occurs when I make certain specific changes to a file.

### To Reproduce

1. Make a file `test.lua` like below
    ```lua
    vim.keymap.set('t', '<M-Tab>', ':echo "hi"<CR>')
    ```
2. open file with neovim

    <img width="498" alt="image" src="https://user-images.githubusercontent.com/60088301/179253919-57d7a507-3fe5-4940-94ea-04f99127fdec.png">

3. Delete word x with `fxdw`, undo with `u`, and save with `:w`.
4. Once I save the file, the parser breaks (can be found on TSPlayground)

    <img width="493" alt="image" src="https://user-images.githubusercontent.com/60088301/179253859-d0bf97ab-0233-4e8c-89cf-7221a33cb90b.png">

### Expected behavior

Cause the file content isn't changed, the parser result should be same.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.5.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - pug            ✓ . . . ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - vim            ✓ ✓ ✓ . ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - solidity       ✓ . . . . 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - markdown       ✓ . ✓ . ✓ 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - swift          ✓ ✓ . . . 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - svelte         ✓ . ✓ ✓ ✓ 
  - vue            ✓ . ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - comment        ✓ . . . . 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - markdown_inline✓ . . . ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - dart           ✓ ✓ . ✓ ✓ 
  - dockerfile     ✓ . . . ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - gomod          ✓ . . . ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.0-dev-
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_
FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Wall 
-Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-prom
otion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fst
ack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPAC
K_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/boltless/Projects/neovim/build/cmake.co
nfig -I/Users/boltless/Projects/neovim/src -I/Users/boltless/Projects/neovim/.deps/usr/include -I/Applicat
ions/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include -I/o
pt/homebrew/opt/gettext/include -I/Users/boltless/Projects/neovim/build/src/nvim/auto -I/Users/boltless/Pr
ojects/neovim/build/include
Compiled by root@MacBook-Pro-3.local

Features: +acl +iconv +tui
See ":help feature-compile"

        시스템 vimrc 파일: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Additional context

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/60088301/179254090-3004971d-53f3-4714-9e6a-99420ace580e.png">

The `TSPlaygroundToggle`'s output in step 4 is like this.

I encountered this issue often for a while, but I'm creating this issue now because I had not time to stop editing my code and create an issue for past few months.
This doesn't occurs with every changes I make, but it can be reproduced with similar changes when the problem occurs.

**Comment by kyazdani42** [comment] 2022-07-15 16:20
Could not reproduce exactly with your steps, but i've also noticed a lot of breakage using the lua parser today.
although i can produce errors with this lua snippet (just copy paste it into any.lua)
```lua
it('', function()
  local function print()
    return "":gsub():gsync()
  end
end)
```

**Comment by kyazdani42** [comment] 2022-07-16 09:03
@MunifTanjim if you can take a look at this please :)

**Comment by MunifTanjim** [comment] 2022-07-16 09:16
@kyazdani42 are you sure `return "":gsub()` is a valid lua thing to do? 🤔 What happens when you run that function?

**Comment by MunifTanjim** [comment] 2022-07-16 09:32
@boltlessengineer by any chance, do you have any formatter installed for Lua?

**Comment by kyazdani42** [comment] 2022-07-16 09:35
Indeed it's not valid at all ^^'
I must say the parser was breaking quite a bit during long lua sessions yesterday, more specifically on test files. If i can reproduce consistently i'll link a file.

**Comment by kyazdani42** [comment] 2022-07-16 09:42
okay i've found a way to reproduce easily.
Using `efm-langserver` and `stylua` as a formatter.
given:
```lua
local mock = require "luassert.mock"

local FS = require "FS"
local L = require "L"
local R = require "R"

describe("1", function()
  local some_var
  before_each(function()
    uv = mock(vim.loop, true)
  end)

  after_each(function()
    mock.revert(uv)
  end)
end)
```
- go after the parens in describe
- insert mode
- hit enter 2/3 times
- save
- run formatter
-> highlight is completely borked

My config for the format command is:
```lua
lua = {{ formatCommand = "stylua -", formatStdin = true }}
```

**Comment by kyazdani42** [comment] 2022-07-16 09:43
This might be an issue with neovim not updating the given bytes to the parser correctly for lsp format command.

**Comment by MunifTanjim** [comment] 2022-07-16 09:45
Found another one:

```
|vim.keymap.set("y", "<leader>e", ':echo "x"<CR>')
```

`fxhx` (delete the opening double quote from `"x"`)
 
```
vim.keymap.set("y", "<leader>e", ':echo |x"<CR>')
```

`Fycs"'` (change `"y"` to `'y'`)

```
vim.keymap.set('|y', "<leader>e", ':echo |x"<CR>')
```

at this point the ts tree is broken:

```
dot_index_expression [0, 0] - [0, 14]
  table: dot_index_expression [0, 0] - [0, 10]
    table: identifier [0, 0] - [0, 3]
    "." [0, 3] - [0, 4]
    field: identifier [0, 4] - [0, 10]
  "." [0, 10] - [0, 11]
  field: identifier [0, 11] - [0, 14]
"(" [0, 14] - [0, 15]
ERROR [0, 15] - [0, 16]
  "string_end" [0, 15] - [0, 16]
method_index_expression [0, 16] - [0, 39]
  table: function_call [0, 16] - [0, 34]
    name: identifier [0, 16] - [0, 17]
    arguments: arguments [0, 17] - [0, 34]
      string [0, 17] - [0, 34]
        start: "string_start" [0, 17] - [0, 18]
        content: "string_content" [0, 18] - [0, 33]
        end: "string_end" [0, 33] - [0, 34]
  ":" [0, 34] - [0, 35]
  method: identifier [0, 35] - [0, 39]
ERROR [0, 40] - [0, 41]
  identifier [0, 40] - [0, 41]
"string_start" [0, 41] - [0, 42]
"string_content" [0, 42] - [0, 48]
```

**Comment by MunifTanjim** [comment] 2022-07-16 09:46
I'm not sure what to do here 🤔 Seems like the incremental sync is broken somehow?

**Comment by kyazdani42** [comment] 2022-07-16 09:52
dunno, haven't observed this for other languages yet.

**Comment by MunifTanjim** [comment] 2022-07-16 10:26
I'm working on a fix. I'll open a PR shortly.

**Comment by MunifTanjim** [comment] 2022-07-16 11:12
Should be fixed in `v0.0.12`: https://github.com/MunifTanjim/tree-sitter-lua/tree/v0.0.12

**Comment by kyazdani42** [comment] 2022-07-16 12:15
yep fixed for me, the revision was updated ! Closing. @boltlessengineer you need to update the parser after updating nvim-treesitter :)

**Closed by kyazdani42** 2022-07-16 12:15 UTC
Labels: bug

**Comment by boltlessengineer** [comment] 2022-07-17 03:49
Thank you all for BLAZINGLY fast fix!
