### ISSUE TITLE
`Failed to execute the following command` when `TSUpdate`

### ISSUE THREAD

**Issue by Daydreamer-riri** [nvim-treesitter/nvim-treesitter#7259] opened 2024-10-18 06:48 UTC
### Describe the bug

This error is always reported when running `:TSUpdate`:

![Image](https://github.com/user-attachments/assets/ba1813da-4ded-4fe7-9167-d28d8b996dc2)

'D:\\Users\\ding.zhao\\AppData\\Local\\nvim-data\\lazy\\nvim-treesitter\\parser\\\\typescript.so' is an obvious path error at the end. The last path separator was repeated.

### To Reproduce

1. On Windows, run ':TSUpdate' when you need to update a language.

### Output of `:checkhealth nvim-treesitter`

==============================================================================
nvim-treesitter:                     require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.11.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cl` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.41.34120 版
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.22631",
  sysname = "Windows_NT",
  version = "Windows 11 Pro"
} ~

Parser/Features         H L F I J
  - astro               ✓ ✓ ✓ ✓ ✓
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - diff                ✓ . ✓ . ✓
  - git_config          ✓ . ✓ . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - json5               ✓ . . . ✓
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - luap                ✓ . . . .
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - nu                  ✓ . . ✓ ✓
  - printf              ✓ . . . .
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - ron                 ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

### Output of `nvim --version`

NVIM v0.11.0-dev-946+g25665b365
Build type: RelWithDebInfo
LuaJIT 2.1.1727870382
Run "nvim -V1 -v" for more info

**Comment by clason** [comment] 2024-10-19 09:41
Please test the latest Neovim release (0.10.2).

**Comment by psynyde** [comment] 2024-10-20 19:24
> Please test the latest Neovim release (0.10.2).

I'm on v0.10.2 in windows 11 & I'm also encountering the same issue while installing `typst`
![Image](https://github.com/user-attachments/assets/9b18fb1d-a1ee-4d9d-bbb9-e596820e28c6)

**NOTE**: I'm running powershell with admin privilege but it's the same none the less.

**Comment by TheLeoP** [comment] 2024-10-28 21:10
This is happening because Windows can't move/delete/rename files/executables while they are opened. Probably you all were using these parsers while you executed the `:TSUpdate` command, hence the error.

I guess a check could be added in the nvim-treesitter side to show a better error message (?)

**Comment by marovira** [comment] 2024-10-28 22:07
Yeah I can confirm this is the case. Ensuring that no other processes are running leads to a successful `:TSUpdate`. If the error message could be changed to say that the files/executables are opened by another process that would be great!

**Comment by clason** [comment] 2024-10-28 22:20
This is already fixed on `main`, which is what will be nvim-treesitter 1.0

**Closed by clason** 2024-10-28 22:20 UTC
Labels: bug, platform Windows

**Comment by JohnWilliston** [comment] 2025-02-02 23:36
I'm seeing this exact issue again on Windows 11.
