### ISSUE TITLE
 loop or previous error loading module 'nvim-treesitter'

### ISSUE THREAD

**Issue by omezro** [nvim-treesitter/nvim-treesitter#3553] opened 2022-09-27 08:44 UTC
### Describe the bug

Error detected while processing /Users/jiangyao/.local/share/nvim/site/pack/packer/start/nvim-treesitter/plugin/nvim-treesitter.lua:
E5113: Error while calling lua chunk: .../packer/start/nvim-treesitter/plugin/nvim-treesitter.lua:9: loop or previous error loading module 'nvim-treesitter'
stack traceback:
        [C]: in function 'require'
        .../packer/start/nvim-treesitter/plugin/nvim-treesitter.lua:9: in main chunk

### To Reproduce

1 my os: mac
2 my nvim version: 0.7.2
3 use nvim packer to build 

### Output of `:checkhealth nvim-treesitter`

```markdown
- ERROR: Failed to run healthcheck for "nvim-treesitter" plugin. Exception:
    function health#check, line 20
    Vim(eval):E5108: Error executing lua [string "luaeval()"]:1: loop or previous error loading module 'nvim-treesitter.health'
    stack traceback:
    [C]: in function 'require'
    [string "luaeval()"]:1: in main chunk
```

### Output of `nvim --version`

```text
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.2_1/share/nvim"

Run :checkhealth for more info
```

**Comment by JakeStanger** [comment] 2022-10-02 10:39
Can confirm I am also experiencing the same problem when opening nvim on Arch Linux. Plugin is installed as part of [AstroNvim](https://astronvim.github.io/), which also uses packer.

Interestingly though it looks like my checkhealth succeeded?

```
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.13.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - lua            ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

Version info:
```
λ nvim --version 
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by pixendrit** [comment] 2022-10-03 22:52
Having the exact same issue on Arch Linux

**Comment by theHamsta** [comment] 2022-10-04 00:42
Do you have a file called `nvim-treesitter.lua` in your config? `plugin/nvim-treesitter.lua` is not from nvim-treesitter but require will load this file instead of `nvim-treesitter/lua/nvim-treesitter.lua`

**Comment by pixendrit** [comment] 2022-10-04 12:31
Deleted the local share folder nvim, reinstalled all the packages with Packer and everything seems to be working fine

**Comment by ztreble** [comment] 2022-10-05 11:08
I have the same problem

**Comment by clason** [comment] 2022-11-20 13:47
Closing since there are no reliable (minimal!) reproduction steps. If someone has the same problem and can provide such steps, please open a new issue.

**Closed by clason** 2022-11-20 13:47 UTC
Labels: bug

**Comment by iFrostizz** [comment] 2023-01-23 19:30
Same issue. Did what pixendrift said but it didn't resolved it.
