### ISSUE TITLE
LaTeX and spell checking

### ISSUE THREAD

**Issue by ngmoviedo** [nvim-treesitter/nvim-treesitter#1278] opened 2021-05-05 10:16 UTC
Syntax highlighting is great on LaTeX when using nvim-treesitter and the corresponding module, but there's one little caveat: it makes no difference between text and code. Thus, the built-in (neo)vim spell checker highlights also most commands, especially for languages other than English.
On the other hand, using the syntax highlighting included in vimtex the commands are (for the most part) not spell checked.
A comparison can be seen in the images.

- Without Treesitter (just Vimtex):
![no_treesitter](https://user-images.githubusercontent.com/61010998/117126368-f2805e80-ad9a-11eb-8778-c2fa14d72c25.jpg)

- With Treesitter:
![treesitter](https://user-images.githubusercontent.com/61010998/117126451-0cba3c80-ad9b-11eb-8885-fb42900d4c1a.jpg)

Given the main purpose of this language, being able to discern between text and code would be really useful.

**Comment by theHamsta** [comment] 2021-05-05 10:27
@ngmoviedo This is an interesting problem. I'll have a look onto it the next days to see whether it can be solved within our plugin or whether we need to do some changes in nvim.

If you don't mind having both tree-sitter and regular highlighting you might activate `:set syntax=1` as a workaround for the moment

**Comment by ngmoviedo** [comment] 2021-05-05 15:08
Thanks!
I'm not sure I understand what `:set syntax=1` does. In fact, it appears to have no effect. Anyway, the recommendation has lead me to try `:set syntax=tex`, which gives the desired result. It's even compatible with concealment that way, which is a plus.
I can't find where to add the option in the config files, though. Tried inside `ftplugin/tex.vim`, but it gets unset for some reason. Even when the other option I have inside that file work perfectly. I suppose it might have something to do with the loading order.

**Comment by ngmoviedo** [comment] 2021-05-05 15:44
I've just seen that this is not really a new issue. I guess it's related with PR #1042.
Also, when having both types of highlighting at the same time, treesitter starts throwing crash errors when using a UltiSnips snippet #1184.

**Comment by theHamsta** [comment] 2021-05-05 16:17
It's because all these features depend on Vim's regex highlighting and are not aware of tree-sitter. We need a replacements for all of these if we want to highlight with tree-sitter.

**Comment by vigoux** [comment] 2021-05-07 07:58
This is a duplicate of #698 btw. So I think we'll concentrate the discussion here.
And the mentionned workaround in mentionned there, so I'll be closing in favor of the former.

**Closed by vigoux** 2021-05-07 07:58 UTC
Labels: duplicate, enhancement

**Comment by theHamsta** [comment] 2021-05-07 08:28
Maybe we could add a API function to add clusters like `@Spell`/`@NoSpell` without syntax. Don't know how easy this is.

**Comment by vigoux** [comment] 2021-05-07 14:46
I think it'll be feasible using the decoration API, but this should be discussed in the aforementionned issue.
