### ISSUE TITLE
golang: wrong indentation on new lines in certain conditions

### ISSUE THREAD

**Issue by primalmotion** [nvim-treesitter/nvim-treesitter#2369] opened 2022-01-25 20:28 UTC
### Describe the bug

When inserting a new line, depending on what seems to be the way to write outer function parameters (single line or multine), indentation is off.

### To Reproduce

go.mod:
```go
module test
```

main.go:

```go
package main

import "fmt"

func goodIndent(param string) {
	fmt.Println("typing o here works as expected")
}

func badIndent(
	param string, // this is the difference
) {
	fmt.Println("typing o here triggers bad indent")
}
```
If you open this file as part of a project (with `vim .`) and you add a line in the second function with `o`, indentation is off. It seems to depend on the way to write the parameters of the outer function.
disabling `indent=true` in treesitter config fixes the problem.

### Expected behavior

Indentation should be correct.

This is what is expected:
![image](https://user-images.githubusercontent.com/208711/151053997-8756886d-cacf-4fcb-8667-91276a0b1774.png)

But this is what's happening:
![image](https://user-images.githubusercontent.com/208711/151054059-edc0a4eb-1e95-4cdc-a244-f0db44849d83.png)

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.4 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.3.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - ocaml_interface✓ ✓ ✓ . ✓ 
  - beancount      ✓ . ✓ . . 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . . 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - ninja          ✓ . ✓ ✓ . 
  - nix            ✓ ✓ ✓ . ✓ 
  - glsl           ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - pug            ✓ . . . ✓ 
  - ledger         ✓ . ✓ ✓ ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - clojure        ✓ ✓ ✓ . ✓ 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - heex           ✓ ✓ ✓ ✓ ✓ 
  - godot_resource ✓ ✓ ✓ . . 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - fennel         ✓ ✓ . . ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - vue            ✓ . ✓ ✓ ✓ 
  - latex          ✓ . ✓ . ✓ 
  - make           ✓ . . . ✓ 
  - rst            ✓ ✓ . . ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - glimmer        ✓ . . . . 
  - erlang         . . . . . 
  - gowork         ✓ . . . ✓ 
  - regex          ✓ . . . . 
  - norg           . . . . . 
  - scss           ✓ . . ✓ . 
  - svelte         ✓ . ✓ ✓ ✓ 
  - prisma         ✓ . . . . 
  - http           ✓ . . . ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - teal           ✓ ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - llvm           ✓ . . . . 
  - hjson          ✓ ✓ ✓ ✓ ✓ 
  - gomod          ✓ . . . ✓ 
  - dart           ✓ ✓ . ✓ ✓ 
  - verilog        ✓ ✓ ✓ . ✓ 
  - pioasm         ✓ . . . ✓ 
  - json5          ✓ . . . ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - vim            ✓ ✓ . . ✓ 
  - cmake          ✓ . ✓ . . 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - zig            ✓ . ✓ ✓ ✓ 
  - bibtex         ✓ . ✓ ✓ . 
  - r              ✓ ✓ . . . 
  - devicetree     ✓ ✓ ✓ ✓ ✓ 
  - julia          ✓ ✓ ✓ ✓ ✓ 
  - pascal         ✓ ✓ ✓ ✓ ✓ 
  - gdscript       ✓ ✓ . ✓ ✓ 
  - jsdoc          ✓ . . . . 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - ql             ✓ ✓ . ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - fusion         ✓ ✓ ✓ ✓ . 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - yang           ✓ . ✓ . . 
  - hocon          ✓ . . . ✓ 
  - surface        ✓ . ✓ ✓ ✓ 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - dot            ✓ . . . ✓ 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - elixir         ✓ ✓ ✓ ✓ ✓ 
  - cuda           ✓ ✓ ✓ ✓ ✓ 
  - commonlisp     ✓ ✓ ✓ . . 
  - eex            ✓ . . . ✓ 
  - kotlin         ✓ ✓ ✓ . ✓ 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - ocamllex       ✓ . . . ✓ 
  - scala          ✓ . ✓ . ✓ 
  - dockerfile     ✓ . . . ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - perl           ✓ . . . . 
  - tlaplus        ✓ . ✓ . ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - rasi           ✓ ✓ ✓ ✓ . 
  - hcl            ✓ . ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by theHamsta** [comment] 2022-01-25 20:40
I'll have a look. It's probably a similar problem as in [#php](https://github.com/nvim-treesitter/nvim-treesitter/issues/2357). Thanks for providing the example!

**Comment by theHamsta** [comment] 2022-01-25 21:21
The problem is that `function_declaration` and `block` increase the indent. The indent is strangely not increased when both start at the same line. You can simply remove `function_declaration` from `queries/go/indents.scm` as the function indent is already covered by `block`. I will add more Go fixes in #2333

**Comment by indeedhat** [comment] 2022-02-09 11:10
This appears to only be partially fixed, functions with multi levels indentation are still behaving oddly.

Expected:
![image](https://user-images.githubusercontent.com/2787027/153186138-3aab35fb-3d70-4ebb-9c64-2bfcc5f806e0.png)

Actual:
![image](https://user-images.githubusercontent.com/2787027/153186190-cea5bd14-17a5-49fa-808f-156c5f3f4f8c.png)

I have also found indentation issues at the top level:

Expected:
![image](https://user-images.githubusercontent.com/2787027/153186501-265d467f-a737-45e6-980e-fbe87339fca9.png)
 
Actual:
![image](https://user-images.githubusercontent.com/2787027/153186684-3aa41412-f128-46e4-9f5c-c2b602039a71.png)

**Comment by theHamsta** [comment] 2022-02-09 21:55
I think this is all the same bug https://github.com/nvim-treesitter/nvim-treesitter/issues/2497 https://github.com/nvim-treesitter/nvim-treesitter/issues/2499 https://github.com/nvim-treesitter/nvim-treesitter/pull/2505 fixel where I removed ")" from `@branch` but did not add it to `@indent_end`

**Comment by primalmotion** [comment] 2022-02-10 00:39
I confirm that I tried to re-enable indent for go, and the bug is back

**Comment by g2boojum** [comment] 2022-03-17 20:37
Yep, I'm definitely seeing what @indeedhat  described.

**Comment by kyazdani42** [comment] 2022-07-02 10:29
looks like this is fixed. Closing.

**Closed by kyazdani42** 2022-07-02 10:29 UTC
Labels: bug, indent
