### ISSUE TITLE
Failed to load parser for language 'vue': uv_dlopen: The specified procedure could not be found.

### ISSUE THREAD

**Issue by KaranJayakumar** [nvim-treesitter/nvim-treesitter#5748] opened 2023-12-01 01:55 UTC
### Describe the bug

I'm new to neovim and attempting to use the vue parser to parse a vue file. I'm having trouble since whenever i open a file with the .vue extension, neovim gives me the error message given below. I believe I've updated both neovim and treesitter since i just installed about 2 days ago. I did read a similar issue wherein someone had not installed a C compiler however I don't believe that this is my issue since I have MinGW installed and other languages seem to work fine. For context, I am using neovim on windows 11 and do not have wsl or any other linux subsystem installed

### To Reproduce

1. Create a new file in netRW called *.vue
2. Open the file

### Expected behavior

I expected there to be no error and for it to allow me to continue coding within the file.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.10.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `gcc` executable found. Selected from { "gcc" }
  Version: gcc (x86_64-posix-seh-rev0, Built by MinGW-Builds project) 13.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.22631",
  sysname = "Windows_NT",
  version = "Windows 11 Home"
} ~

Parser/Features         H L F I J
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - vimdoc              ✓ . . . ✓
  - vue                 x . x x x

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR vue(highlights): Failed to load parser for language 'vue': uv_dlopen: The specified procedure could not be found.
  
  vue(highlights) is concatenated from the following files:
  | [ERROR]:"C:\Users\Karan\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html_tags\highlights.scm", failed to load: Failed to load parser for language 'vue': uv_dlopen: The specified procedure could not be found.
  
  | [ERROR]:"C:\Users\Karan\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\vue\highlights.scm", failed to load: Failed to load parser for language 'vue': uv_dlopen: The specified procedure could not be found.
- ERROR vue(folds): Failed to load parser for language 'vue': uv_dlopen: The specified procedure could not be found.
  
  vue(folds) is concatenated from the following files:
  | [ERROR]:"C:\Users\Karan\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\vue\folds.scm", failed to load: Failed to load parser for language 'vue': uv_dlopen: The specified procedure could not be found.
- ERROR vue(indents): Failed to load parser for language 'vue': uv_dlopen: The specified procedure could not be found.
  
  vue(indents) is concatenated from the following files:
  | [ERROR]:"C:\Users\Karan\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html_tags\indents.scm", failed to load: Failed to load parser for language 'vue': uv_dlopen: The specified procedure could not be found.
  
  | [ERROR]:"C:\Users\Karan\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\vue\indents.scm", failed to load: Failed to load parser for language 'vue': uv_dlopen: The specified procedure could not be found.
- ERROR vue(injections): Failed to load parser for language 'vue': uv_dlopen: The specified procedure could not be found.
  
  vue(injections) is concatenated from the following files:
  | [ERROR]:"C:\Users\Karan\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html_tags\injections.scm", failed to load: Failed to load parser for language 'vue': uv_dlopen: The specified procedure could not be found.
  
  | [ERROR]:"C:\Users\Karan\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\vue\injections.scm", failed to load: Failed to load parser for language 'vue': uv_dlopen: The specified procedure could not be found.
```

### Output of `nvim --version`

```text
:version
NVIM v0.9.2
Build type: RelWithDebInfo
LuaJIT 2.1.1694082368
```

### Additional context

Error Message : 
Error detected while processing function <SNR>44_NetrwOpenFile[35]..BufNewFile Autocommands for "*":
Error executing lua callback: C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:24: Error executing lua: C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:25: function <SNR>44_NetrwOpenFile[35]..BufNewFile Autocommands for "*"..FileType Autocommands for "*": Vim(append):Error executing lua callback: Failed to load parser for language 'vue': uv_dlopen: The specified procedure could not be found.

stack traceback:
        [C]: in function '_ts_add_language'
        ...eovim\share\nvim\runtime/lua/vim/treesitter/language.lua:99: in function 'add'
        ...m\share\nvim\runtime/lua/vim/treesitter/languagetree.lua:98: in function 'new'
        ...m Files\Neovim\share\nvim\runtime/lua/vim/treesitter.lua:61: in function '_create_parser'
        ...m Files\Neovim\share\nvim\runtime/lua/vim/treesitter.lua:131: in function 'get_parser'
        ...m Files\Neovim\share\nvim\runtime/lua/vim/treesitter.lua:459: in function 'start'
        ...\start\nvim-treesitter/lua/nvim-treesitter/highlight.lua:20: in function 'attach'
        ...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
        ...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
        ...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:132>
        [C]: in function 'nvim_cmd'
        C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:25: in function <C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:24>
        [C]: in function 'nvim_buf_call'
        C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:24: in function <C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_cmd'
        C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:25: in function <C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:24>

My config : 
Packer.lua ; -- This file can be loaded by calling `lua require('plugins')` from your init.vim
-- Only required if you have packer configured as `opt`
vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function(use)
	-- Packer can manage itself
	use 'wbthomason/packer.nvim'
	use {
		'nvim-telescope/telescope.nvim', tag = '0.1.4',
		-- or                            , branch = '0.1.x',
		requires = { {'nvim-lua/plenary.nvim'} }
	} 
	use { "catppuccin/nvim", as = "catppuccin", 
		config = function()
		vim.cmd('colorscheme catppuccin')
	end
}
use ('mbbill/undotree')
use ('tpope/vim-fugitive')
use {
	'nvim-treesitter/nvim-treesitter',
	run = ':TSUpdate'
}
use {
  'VonHeikemen/lsp-zero.nvim',
  branch = 'v3.x',
  requires = {
    --- Uncomment these if you want to manage LSP servers from neovim
    {'williamboman/mason.nvim'},
    {'williamboman/mason-lspconfig.nvim'},

    -- LSP Support
    {'neovim/nvim-lspconfig'},
    -- Autocompletion
    {'hrsh7th/nvim-cmp'},
    {'hrsh7th/cmp-nvim-lsp'},
    {'L3MON4D3/LuaSnip'},
  }
}
end)
treesitter.lua : 
require'nvim-treesitter.configs'.setup {
  -- A list of parser names, or "all" (the five listed parsers should always be installed)
  ensure_installed = {'vimdoc', 'java', 'html', 'css', 'vue', 'lua'}, 

  -- Install parsers synchronously (only applied to `ensure_installed`)
  sync_install = false,

  -- Automatically install missing parsers when entering buffer
  -- Recommendation: set to false if you don't have `tree-sitter` CLI installed locally
  auto_install = true,

  ---- If you need to change the installation directory of the parsers (see -> Advanced Setup)
  -- parser_install_dir = "/some/path/to/store/parsers", -- Remember to run vim.opt.runtimepath:append("/some/path/to/store/parsers")!

  highlight = {
    enable = true,
    -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
    -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
    -- Using this option may slow down your editor, and you may see some duplicate highlights.
    -- Instead of true it can also be a list of languages
    additional_vim_regex_highlighting = false,
  },
}

**Comment by lucario387** [comment] 2023-12-01 02:21
Duplicate of #4719. Please follow the issue aforementioned for solutions as well

**Closed by lucario387** 2023-12-01 02:21 UTC
Labels: bug
