### ISSUE TITLE
Markdown code block start and end line is concealed

### ISSUE THREAD

**Issue by pteroctopus** [nvim-treesitter/nvim-treesitter#3723] opened 2022-10-27 06:13 UTC
### Describe the highlighting problem

Markdown code block start and end line is concealed.

so:
```
```language # not visible has @conceal highlight group
# visible
``` # not visible
```

Features like this should be opt-in not opt-out.

"Feature" was added here: https://github.com/nvim-treesitter/nvim-treesitter/issues/2663

Markdown file is a text file. To edit it we must see the text.
If somebody wants to see it rendered there are other ways of doing it.

For me it is a problem to edit lines I can't even see. I don't see the point of hiding that text :-)

Please make it opt-in. This doesn't make any sense.

Also first I thought it was a bug so I updated everything to the latest version and I spent a few hours to finally find out what the problem was.
I also wrongly reported the bug first to: https://github.com/MDeiml/tree-sitter-markdown/issues/68 and then to: https://github.com/tree-sitter/tree-sitter/issues/1933.

@MDeiml was nice and pointed me to the right repo (twice) to report the issue.

My guess is that I will not be the only one that is confused by the (in my opinion) wrongly used conceal feature. And will unnecessarily cause people to spend time trying to fix a problem and in the end just disable treesitter markdown and use the default syntax highlighting. 

Please consider reverting the commit and make a rule that concealing like that should be opt-in so that in the future no such "features" are implemented.

Also please look at the discussion on reddit: https://www.reddit.com/r/neovim/comments/ye3f0p/treesitter_conceals_by_default_what_do_you_think/
There are not a lot of comments but people don't seem happy about the feature.

Thank you.

![Alas, I cannot see](https://user-images.githubusercontent.com/16186848/198032199-8792204b-089b-491b-a301-615444028200.png)

### Example snippet that causes the problem

```
```language # not visible has @conceal highlight group
# visible
``` # not visible
```

### Tree-sitter parsing result

```
section [0, 0] - [9, 0]
  atx_heading [0, 0] - [1, 0]
    atx_h1_marker [0, 0] - [0, 1]
    heading_content: inline [0, 1] - [0, 28]
  fenced_code_block [2, 0] - [6, 0]
    fenced_code_block_delimiter [2, 0] - [2, 3]
    info_string [2, 3] - [2, 5]
      language [2, 3] - [2, 5]
    block_continuation [3, 0] - [3, 0]
    code_fence_content [3, 0] - [5, 0]
      block_continuation [4, 0] - [4, 0]
      block_continuation [5, 0] - [5, 0]
    fenced_code_block_delimiter [5, 0] - [5, 3]
  paragraph [7, 0] - [8, 0]
    inline [7, 0] - [7, 25]
```

### Example screenshot

![Alas, I cannot see](https://user-images.githubusercontent.com/16186848/198032199-8792204b-089b-491b-a301-615444028200.png)

### Expected behavior

I would like to see the text when I am editing in neovim text editor. Even the code block start and end in markdown. But, alas I can not see them.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - WARNING: `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - diff           ✓ . . . .
  - ocaml_interface✓ ✓ ✓ . ✓
  - tiger          ✓ ✓ ✓ ✓ ✓
  - markdown_inline✓ . . . ✓
  - sparql         ✓ ✓ ✓ ✓ ✓
  - comment        ✓ . . . .
  - elvish         ✓ . . . ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - ocaml          ✓ ✓ ✓ . ✓
  - m68k           ✓ ✓ ✓ . ✓
  - vala           ✓ . ✓ . .
  - glsl           ✓ ✓ ✓ ✓ ✓
  - fusion         ✓ ✓ ✓ ✓ .
  - jsdoc          ✓ . . . .
  - ledger         ✓ . ✓ ✓ ✓
  - markdown       ✓ . ✓ . ✓
  - supercollider  ✓ ✓ ✓ ✓ ✓
  - typescript     ✓ ✓ ✓ ✓ ✓
  - help           ✓ . . . .
  - v              ✓ ✓ ✓ ✓ ✓
  - cpp            ✓ ✓ ✓ ✓ ✓
  - slint          ✓ . . ✓ .
  - wgsl           ✓ . ✓ ✓ .
  - zig            ✓ . ✓ ✓ ✓
  - svelte         ✓ . ✓ ✓ ✓
  - solidity       ✓ . . . .
  - java           ✓ ✓ . ✓ ✓
  - http           ✓ . . . ✓
  - dart           ✓ ✓ . ✓ ✓
  - cmake          ✓ . ✓ . .
  - org            . . . . .
  - yaml           ✓ ✓ ✓ ✓ ✓
  - rnoweb         ✓ . ✓ . ✓
  - toml           ✓ ✓ ✓ ✓ ✓
  - sxhkdrc        ✓ . ✓ . ✓
  - yang           ✓ . ✓ ✓ .
  - hocon          ✓ . . . ✓
  - surface        ✓ . ✓ ✓ ✓
  - cuda           ✓ ✓ ✓ ✓ ✓
  - sql            ✓ . . . ✓
  - scala          ✓ . ✓ . ✓
  - dockerfile     ✓ . . . ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - cooklang       ✓ . . . .
  - prisma         ✓ . . . .
  - rasi           ✓ ✓ ✓ ✓ .
  - racket         ✓ . ✓ . ✓
  - gdscript       ✓ ✓ . ✓ ✓
  - beancount      ✓ . ✓ . .
  - phpdoc         ✓ . . . .
  - python         ✓ ✓ ✓ ✓ ✓
  - go             ✓ ✓ ✓ ✓ ✓
  - scss           ✓ . . ✓ .
  - pug            ✓ . . . ✓
  - php            ✓ ✓ ✓ ✓ ✓
  - clojure        ✓ ✓ ✓ . ✓
  - hack           ✓ . . . .
  - heex           ✓ ✓ ✓ ✓ ✓
  - menhir         ✓ . . . ✓
  - fennel         ✓ ✓ . . ✓
  - embedded_template✓ . . . ✓
  - meson          ✓ . ✓ . ✓
  - query          ✓ ✓ ✓ ✓ ✓
  - jsonnet        ✓ . . . .
  - qmljs          ✓ . ✓ . .
  - vue            ✓ . ✓ ✓ ✓
  - latex          ✓ . ✓ . ✓
  - make           ✓ . ✓ . ✓
  - rst            ✓ ✓ . . ✓
  - css            ✓ . ✓ ✓ ✓
  - glimmer        ✓ . . . .
  - erlang         ✓ . ✓ . .
  - hlsl           ✓ ✓ ✓ ✓ ✓
  - lalrpop        ✓ ✓ . . .
  - regex          ✓ . . . .
  - fortran        ✓ . ✓ ✓ .
  - hjson          ✓ ✓ ✓ ✓ ✓
  - gomod          ✓ . . . ✓
  - gleam          ✓ ✓ ✓ ✓ ✓
  - twig           ✓ . . . ✓
  - blueprint      ✓ . . . .
  - gitattributes  ✓ . . . ✓
  - bash           ✓ ✓ ✓ . ✓
  - llvm           ✓ . . . .
  - hcl            ✓ . ✓ ✓ ✓
  - norg           . . . . .
  - graphql        ✓ . . ✓ ✓
  - astro          ✓ ✓ ✓ ✓ ✓
  - c_sharp        ✓ ✓ ✓ . ✓
  - tlaplus        ✓ ✓ ✓ . ✓
  - vim            ✓ ✓ ✓ . ✓
  - perl           ✓ . ✓ . .
  - javascript     ✓ ✓ ✓ ✓ ✓
  - turtle         ✓ ✓ ✓ ✓ ✓
  - todotxt        ✓ . . . .
  - rego           ✓ . . . ✓
  - verilog        ✓ ✓ ✓ . ✓
  - r              ✓ ✓ . ✓ ✓
  - commonlisp     ✓ ✓ ✓ . .
  - ninja          ✓ . ✓ ✓ .
  - json           ✓ ✓ ✓ ✓ .
  - elm            ✓ . . . ✓
  - gowork         ✓ . . . ✓
  - html           ✓ ✓ ✓ ✓ ✓
  - scheme         ✓ . ✓ . ✓
  - dot            ✓ . . . ✓
  - elixir         ✓ ✓ ✓ ✓ ✓
  - julia          ✓ ✓ ✓ ✓ ✓
  - nix            ✓ ✓ ✓ . ✓
  - pascal         ✓ ✓ ✓ ✓ ✓
  - kotlin         ✓ ✓ ✓ . ✓
  - ruby           ✓ ✓ ✓ ✓ ✓
  - fish           ✓ ✓ ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - bibtex         ✓ . ✓ ✓ .
  - ql             ✓ ✓ . ✓ ✓
  - proto          ✓ . ✓ . .
  - pioasm         ✓ . . . ✓
  - nickel         ✓ . . . .
  - agda           ✓ . ✓ . .
  - haskell        ✓ . ✓ . ✓
  - eex            ✓ . . . ✓
  - json5          ✓ . . . ✓
  - foam           ✓ ✓ ✓ ✓ ✓
  - jsonc          ✓ ✓ ✓ ✓ ✓
  - tsx            ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
❯ nvim --version
NVIM v0.9.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-UwvQcg/neovim-0.9.0~ubuntu1+git202210251433-40791f8e8-333b5866f=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FOR
TIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing
-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HA
S_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-UwvQcg/neovim-0.9.0~ubuntu1+git202210251433-40791f8e8-333b5866f/build/cmake.config -I/build/neovim-UwvQcg/neovim-0.9.0~ubuntu1+git202210251433-
40791f8e8-333b5866f/src -I/build/neovim-UwvQcg/neovim-0.9.0~ubuntu1+git202210251433-40791f8e8-333b5866f/.deps/usr/include -I/usr/include -I/build/neovim-UwvQcg/neovim-0.9.0~ubuntu1+git202210251433-40791f8e8-333b58
66f/build/src/nvim/auto -I/build/neovim-UwvQcg/neovim-0.9.0~ubuntu1+git202210251433-40791f8e8-333b5866f/build/include
Compiled by buildd@lcy02-amd64-008

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

The problem was the same with the stable version 0.7.x. I don't remember witch one exactly because I updated to latest version to see if the "bug" will dissapear.

**Comment by clason** [comment] 2022-10-27 06:23
Duplicate of #2825

**Comment by clason** [comment] 2022-10-27 06:23
> Markdown file is a text file. To edit it we must see the text.
If somebody wants to see it rendered there are other ways of doing it.

Exactly. So just set `conceallevel=0`.

**Closed by clason** 2022-10-27 06:23 UTC
Labels: highlights

**Comment by pteroctopus** [comment] 2022-10-27 06:30
Thank you for the info, but: set conceallevel=0 should be the default to that user are not confused.

And the bug:
[#2825](https://github.com/nvim-treesitter/nvim-treesitter/issues/2825)

Was reported 4 months ago and was not solved. Please don't close this issue until the problem is fixed.

**Comment by clason** [comment] 2022-10-27 06:47
> Thank you for the info, but: set conceallevel=0 should be the default to that user are not confused. Also set conceallevel=0 doesn't work if set in .vimrc. It works only if set through command mode manually.

That _is_ the default. Check your config (or plugins) via `:verbose set conceallevel`?

> Was reported 4 months ago and was not solved. Please don't close this issue until the problem is fixed.

Yes, because it's not trivial. And only one issue is needed to track it.

**Comment by pteroctopus** [comment] 2022-10-27 06:55
https://github.com/Yggdroot/indentLine plugin sets the conceallevel to 2.

disabled plugin for markdown with this:

let g:indentLine_fileTypeExclude = ['markdown']

**Comment by pteroctopus** [comment] 2022-10-27 07:48
@clason @theHamsta why don't you just remove concealing text in markdown and json files until you solve non-trivial problem mentioned by @clason ?

It seems like it caused problems for people for a feature that is not that useful.

https://github.com/Yggdroot/indentLine/issues/349
https://vi.stackexchange.com/questions/7258/how-do-i-prevent-vim-from-hiding-symbols-in-markdown-and-json
https://www.reddit.com/r/neovim/comments/nu8e0t/help_needed_with_markdown_syntax_conceal_and/
etc.

**Comment by clason** [comment] 2022-10-27 07:50
Because other people requested it.

**Comment by pteroctopus** [comment] 2022-10-27 08:01
@clason  This will be my last comment, I don't want to annoy you further :-) But I suggest that for this feature and others like it that could cause problems for people (users and plugin devs) you make a poll (and post it on various channels like reddit, mailing lists etc.) and ask the people what they think. Maybe the most of them will vote against it and maybe not.

**Comment by clason** [comment] 2022-10-27 08:14
Sorry, that's not how this works. Queries are community contributed and maintained. If you want to change something, open a PR and ping the corresponding maintainer listed in the README.

And you can always override the queries in your own config.

**Comment by clason** [comment] 2022-11-02 15:10
By the way, if you don't like conceal, you should use an indentline plugin that does not rely on it, like https://github.com/lukas-reineke/indent-blankline.nvim.

**Comment by pteroctopus** [comment] 2022-11-02 16:03
Thank you, works like a charm.
