### ISSUE TITLE
Error detected while processing FileType Autocommands for "zsh" and "sh"

### ISSUE THREAD

**Issue by bangedorrunt** [nvim-treesitter/nvim-treesitter#387] opened 2020-09-05 03:42 UTC
**Describe the bug**

**To Reproduce**
1. Open `.zshrc`
2. Error message

```
Error detected while processing FileType Autocommands for "zsh":
E5108: Error executing lua ...76/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:121: Expected lua string
```

**Expected behavior**
No error raised

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.
## bash parser healthcheck
  - OK: bash parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for bash
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `fold.scm` query found for bash
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
## javascript parser healthcheck
  - OK: javascript parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - OK: `fold.scm` found.

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-nightly-4-g3853276
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200905-5954-4321sw/build/config -I/tmp/neovim-20200905-5954-4321sw/src -I/usr/local/include -I/tmp/neovim-20200905-5954-4321sw/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200905-5954-4321sw/build/src/nvim/auto -I/tmp/neovim-20200905-5954-4321sw/build/include
Compiled by babygau@babygau.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-3853276/share/nvim"
```

**Comment by babygau** [comment] 2020-09-06 16:29
it's not fixed yet :( 
```
Error detected while processing FileType Autocommands for "zsh":
E5108: Error executing lua ...46/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:121: Expected lua string
```

**Comment by kyazdani42** [comment] 2020-09-06 16:29
did you update to master ?
if you did, could you give me the content of you zsh file ?

**Comment by babygau** [comment] 2020-09-06 16:35
yes, i updated and the issue still there

<details>
<summary>zsh content</summary>
```
#!/bin/zsh
#
# if you come from bash you might have to change your $PATH.
export PATH=/usr/local/bin:/usr/local/sbin:$HOME/bin:$PATH

# enable powerlevel10k instant prompt. should stay close to the top of ~/.zshrc.
# initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# homebrew config
# ######################
# this load brew wrapper
if [ -f $(brew --prefix)/etc/brew-wrap ];then
  source $(brew --prefix)/etc/brew-wrap
fi

if type brew &>/dev/null; then
  HOMEBREW_PREFIX=$(brew --prefix)
  # gnubin; gnuman
  for d in ${HOMEBREW_PREFIX}/opt/*/libexec/gnubin; do export PATH=$d:$PATH; done
  # i actually like that man grep gives the bsd grep man page
  # for d in ${HOMEBREW_PREFIX}/opt/*/libexec/gnuman; do export MANPATH=$d:$MANPATH; done
fi

# fzf config
# ######################

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh # this loads fzf
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS' --color=fg:#eeeeed,bg:#282c34,hl:#5f87af --color=fg+:#eeeeed,bg+:#282c34,hl+:#5fd7ff --color=info:#afaf87,prompt:#d7005f,pointer:#af5fff --color=marker:#87ff00,spinner:#af5fff,header:#87afaf'
# export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_DEFAULT_COMMAND="rg --files --hidden --follow --glob '!*/{.git,node_modules}/**'"
export FZF_CTRL_T_COMMAND="rg --files --hidden --follow --glob '!*/{.git,node_modules}/**'"
export FZF_ALT_C_COMMAND="fd --type d --no-ignore-vcs --exclude node_modules --exclude .git"

# nvm config
# ######################
export NVM_DIR="$HOME/.nvm"
export NVM_SYMLINK_CURRENT=true
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nv

# z config
# ######################
. /usr/local/etc/profile.d/z.sh # This load z

# goku
# #####################
export GOKU_EDN_CONFIG_FILE="$HOME/.config/karabiner/karabiner.edn"


# added by Nix installer
if [ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then . "$HOME/.nix-profile/etc/profile.d/nix.sh"; fi

### added by zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# load a few important annexes, without turbo
# (this is currently required for annexes)
zinit light-mode for \
    zinit-zsh/z-a-rust \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-bin-gem-node

# a glance at the new for-syntax – load all of the above
# plugins with a single command. For more information see:
# https://zdharma.org/zinit/wiki/For-Syntax/

# powerlevel10k theme
# to customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
zinit light-mode for atload'source ~/.p10k.zsh' romkatv/powerlevel10k

# sensible defaults
zstyle ':prezto:*:*' color 'yes'
zinit light-mode for \
  id-as'prezto/environment' \
    https://github.com/sorin-ionescu/prezto/blob/master/modules/environment/init.zsh \
  id-as'prezto/history' \
    https://github.com/sorin-ionescu/prezto/blob/master/modules/history/init.zsh \
  id-as'prezto/directory' \
    https://github.com/sorin-ionescu/prezto/blob/master/modules/directory/init.zsh
HISTSIZE=200000
SAVEHIST=100000

# fzf completion
zinit light-mode for \
  id-as'fzf/completion' https://github.com/junegunn/fzf/blob/master/shell/completion.zsh \
  id-as'fzf/key-bindings' https://github.com/junegunn/fzf/blob/master/shell/key-bindings.zsh

# pyenv lazy init
zinit light-mode for davidparsson/zsh-pyenv-lazy

# auto-suggest how to install missing commands.
zinit light-mode for id-as'brew/command-not-found' \
  https://github.com/Homebrew/homebrew-command-not-found/blob/master/handler.sh

# fast-syntax-highlighting & autosuggestions
zinit wait"1" lucid for \
  atinit"ZINIT[COMPINIT_OPTS]=-C; zpcompinit; zpcdreplay" \
    zdharma/fast-syntax-highlighting \
  atload"!_zsh_autosuggest_start" \
    zsh-users/zsh-autosuggestions \
  blockf \
    zsh-users/zsh-completions
# fast navigation
zinit wait"1" lucid for \
    psprint/zsh-navigation-tools \
    zsh-users/zsh-history-substring-search \
  atinit'zstyle ":history-search-multi-word" page-size "7"' \
    zdharma/history-search-multi-word

### end of zinit's installer chunk

# you may need to manually set your language environment
# export LANG=en_US.UTF-8

# preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

# compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"
```
</details>

**Comment by stsewd** [comment] 2020-09-06 16:35
Looks like we are getting the same error for other file types as well (rst, ocaml)

**Comment by babygau** [comment] 2020-09-06 16:37
disable highlight then problem is gone
```
  highlight = {
    enable = true,         -- false will disable the whole extension
    disable = { "bash" },  -- list of language that will be disabled
  },
```

**Comment by stsewd** [comment] 2020-09-06 16:40
All those three grammars have in common is that they use a custom scanner. Maybe related to the changes in how ts compiles the grammar

**Comment by stsewd** [comment] 2020-09-06 17:01
Looks like this doesn't happen with any content. So maybe a capture group is giving some problems. Minimal reproducible example for rst.

```rst
.. |a| img:: test.jpg
```

**Comment by stsewd** [comment] 2020-09-06 17:07
For rst this was the problem https://github.com/nvim-treesitter/nvim-treesitter/pull/407

**Comment by stsewd** [comment] 2020-09-06 17:12
A minimal example for bash is

```bash
FOO=BAR
```

**Comment by stsewd** [comment] 2020-09-06 17:14
guessing something changed in neovim

**Comment by stsewd** [comment] 2020-09-06 17:19
OK, this is because some capture groups aren't declared in https://github.com/stsewd/nvim-treesitter/blob/rst-update-hl/lua/nvim-treesitter/highlight.lua

In bash this is because of `@identifier`

**Comment by stsewd** [comment] 2020-09-06 17:23
This is duplicated of https://github.com/nvim-treesitter/nvim-treesitter/issues/398

**Comment by stsewd** [comment] 2020-09-06 17:37
In ocaml is because of

https://github.com/nvim-treesitter/nvim-treesitter/blob/b69b43b712f335a8d0fc05b581819da7c5bcee92/queries/ocaml/highlights.scm#L74-L74

ping to the maintainer @undu

**Comment by kyazdani42** [comment] 2020-09-06 23:33
we definitely need a way to check queries are working. Maybe testing queries against a file for each language would work ? I'm not sure because this is related to upstream. This issue shouldn't be here since my PR preventing this was merged in neovim.

**Comment by babygau** [comment] 2020-09-07 00:01
i confirm bash highlight is fixed in new neovim update 👍

**Comment by stsewd** [comment] 2020-09-07 00:10
> we definitely need a way to check queries are working. Maybe testing queries against a file for each language would work ?

That would be a lot of testing, I think we should test that all capture groups are valid ones (except for auxiliary groups that start with `_`)

**Comment by vigoux** [comment] 2020-09-07 09:38
I am working on checking that the captures used in each queries are valid, and integrate that into our CI.

**Comment by vigoux** [comment] 2020-09-07 16:30
See #411 for reference for this now.

**Comment by yankeeinlondon** [comment] 2023-01-21 19:40
is anyone else having this issue again? I appear to be using **neovim** vvim `0.7.2` from **brew**. I'm a newbie so not sure if I'm doing something dumb but I just used the install instructions in the popular [kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim)

**Comment by clason** [comment] 2023-01-21 19:49
That version

**Closed** 2023-01-21 19:50 UTC
Labels: bug
