### ISSUE TITLE
Problem with typescript files

### ISSUE THREAD

**Issue by e2fletcher** [nvim-treesitter/nvim-treesitter#6046] opened 2024-02-02 20:40 UTC
### Describe the bug

Something seems to have broken with the latest update.
```

Failed to run `config` for nvim-treesitter

/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 5997 for language typescript

# stacktrace:
  - /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259 _in_ **get**
  - /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:114 _in_ **new**
  - /usr/share/nvim/runtime/lua/vim/treesitter.lua:61 _in_ **_create_parser**
  - /usr/share/nvim/runtime/lua/vim/treesitter.lua:131 _in_ **get_parser**
  - /usr/share/nvim/runtime/lua/vim/treesitter.lua:460 _in_ **start**
  - ~/.config/nvim/lua/plugins/configs/nvim-treesitter.lua:10 _in_ **config**
  - ~/.config/nvim/lua/astronvim/utils/init.lua:145
```

This happens when trying to load a typescript file, I have previously run TSUpdate, I have the latest version of neovim and nvim-treesitter.

### To Reproduce

The problem occurs when trying to open any typescript file.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.9 (98be227227af10cc7a269cb3ffb23686c0610b17) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.10.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.7.2-arch1-2",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Wed, 31 Jan 2024 09:22:15 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cmake               ✓ . ✓ ✓ .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - cuda                ✓ ✓ ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - http                ✓ . . . ✓
  - hurl                ✓ . ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - objc                ✓ ✓ ✓ ✓ ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - proto               ✓ . ✓ . .
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ x
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR typescript(injections): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 5997 for language typescript
  typescript(injections) is concatenated from the following files:
  |    [OK]:"/home/ender/.local/share/nvim/lazy/nvim-treesitter/queries/ecma/injections.scm"
  | [ERROR]:"/home/ender/.config/nvim/queries/typescript/injections.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 23 for language typescript
```

### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

     archivo "vimrc" del sistema: "$VIM/sysinit.vim"
            predefinido para $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by lucario387** [comment] 2024-02-03 02:27
Duplicate of #3092

**Closed** 2024-02-03 02:27 UTC
Labels: bug
