### ISSUE TITLE
E5108: Error executing lua ...r-textobjects/lua/nvim-treesitter/textobjects/select.lua:59: attempt to concatenate local 'query' 

### ISSUE THREAD

**Issue by desdic** [nvim-treesitter/nvim-treesitter#2318] opened 2022-01-21 16:59 UTC
### Describe the bug

when trying to edit a file (tested with .go and .py) I get 

```
E5108: Error executing lua ...r-textobjects/lua/nvim-treesitter/textobjects/select.lua:59: attempt to concatenate local 'query' (a table value)
stack traceback:
        ...r-textobjects/lua/nvim-treesitter/textobjects/select.lua:59: in function 'attach'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:458: in function 'attach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:481: in function 'reattach_module'
```

but no problems on .txt or .md

### To Reproduce

update treesitter
edit a file

### Expected behavior

no errors

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
 ========================================================================
 ## Installation
   - OK: `tree-sitter` found  0.20.2 (parser generator, only needed for :TSInstallFromGrammar)
   - OK: `node` found v17.3.0 (only needed for :TSInstallFromGrammar)
   - OK: `git` executable found.
   - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
     Version: cc (GCC) 11.1.0
   - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

 ## Parser/Features H L F I J
   - python         ✓ ✓ ✓ ✓ ✓-
   - lua            ✓ ✓ ✓ ✓ ✓-
   - json           ✓ ✓ ✓ ✓ .-
   - query          ✓ ✓ ✓ ✓ ✓-
   - cpp            ✓ ✓ ✓ ✓ ✓-
   - c              ✓ ✓ ✓ ✓ ✓-
   - bash           ✓ ✓ ✓ . ✓-
   - yaml           ✓ ✓ ✓ ✓ ✓-
   - toml           ✓ ✓ ✓ ✓ ✓-
   - go             ✓ ✓ ✓ ✓ ✓-
   - ruby           ✓ ✓ ✓ ✓ ✓-
   - dockerfile     ✓ . . . ✓-

   Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
          +) multiple parsers found, only one will be used
          x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment] 2022-01-21 17:01
That looks to be an issue with nvim-treesitter-textobjects; in fact, a duplicate of https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/171

**Closed by clason** 2022-01-21 17:01 UTC
Labels: bug
