### ISSUE TITLE
Links in vimdoc files are invisible with nvim-treesitter v0.9.2 and neovim nightly

### ISSUE THREAD

**Issue by godlygeek** [nvim-treesitter/nvim-treesitter#7072] opened 2024-08-23 05:07 UTC
### Describe the bug

With the latest tagged version of nvim-treesitter and the latest neovim (both nightly and the latest tagged version), `|links|` in `:help` become invisible.

### To Reproduce

```sh
cat >Dockerfile <<"EOF"
FROM ubuntu:24.04
ENV LANG=en_US.UTF-8
RUN apt update \
    && apt install -y --no-install-recommends ca-certificates locales curl git build-essential \
    && sed -i -e "s/# $LANG.*/$LANG UTF-8/" /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG=$LANG \
    && curl -LO "https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz" \
    && tar zxf nvim-linux64.tar.gz \
    && mkdir -p ~/.config/nvim/pack/nvim-treesitter/start \
    && git clone --branch=v0.9.2 https://github.com/nvim-treesitter/nvim-treesitter.git ~/.config/nvim/pack/nvim-treesitter/start/nvim-treesitter
RUN /nvim-linux64/bin/nvim \
         -c "TSInstallSync! c" \
         -c "TSInstallSync! lua" \
         -c "TSInstallSync! markdown" \
         -c "TSInstallSync! markdown_inline" \
         -c "TSInstallSync! query" \
         -c "TSInstallSync! vim" \
         -c "TSInstallSync! vimdoc" \
         -c q
ENTRYPOINT /nvim-linux64/bin/nvim -c 'checkhealth|help reference_toc'
EOF
```
Then
```
docker build -t nvimts .
docker run --rm -it nvimts
```

Observe that all of the treesitter healthchecks pass, and that the parsers installed by TSInstallSync all take precedence over the ones bundled with neovim, but that the help window looks like this:
![image](https://github.com/user-attachments/assets/c08616f0-6537-4de5-a397-c6b9169929b9)

Then, observe that running `:set conceallevel=0` in the help window causes the display to change to this:
![image](https://github.com/user-attachments/assets/cc0a8a2a-468b-4b58-bb01-597f75313b62)

### Expected behavior

The `|links|` in the help should be visible regardless of conceallevel.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation
- WARNING tree-sitter executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- WARNING node executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK git executable found.
- OK cc executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.15.153.1-microsoft-standard-WSL2",
  sysname = "Linux",
  version = "#1 SMP Fri Mar 29 23:14:13 UTC 2024"
}

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.11.0-dev-648+g3bd7492a6
Build type: RelWithDebInfo
LuaJIT 2.1.1724232689
Run "nvim -V1 -v" for more info
```

### Additional context

This occurs with neovim 0.10.1 as well as the latest nightly, and reproduces on RHEL 7 and Ubuntu 24.04.

The behavior is different with the latest master of nvim-treesitter, but still wrong: the links display as:
![image](https://github.com/user-attachments/assets/452720e5-3e64-4c71-aadc-1db9f80fe71f)
with a U+2500 "BOX DRAWINGS LIGHT HORIZONTAL" character on either side of each link.

Without nvim-treesitter installed at all, these links instead look like:
![image](https://github.com/user-attachments/assets/cbbe2caf-703d-49fc-9bdb-2565c867388e)
which is better than the behavior with either nvim-treesitter master or v0.9.2

This was previously reported in #6705, but that seems to have been closed without the problem actually being solved.

**Comment by clason** [comment] 2024-08-23 06:46
Duplicate of #6989 as well. This is a config issue related to your colorscheme, not a bug.

**Closed by clason** 2024-08-23 06:46 UTC
Labels: bug

**Comment by godlygeek** [comment] 2024-08-23 07:26
> This plugin doesn't make releases so you should not pin to tags

OK, good to know, but...

> This is a config issue related to your colorscheme

This is with the `default` colorscheme, and also occurs with the `vim` colorscheme. Try with a Dockerfile of:

```
FROM ubuntu:24.04
ENV LANG=en_US.UTF-8
RUN apt update \
    && apt install -y --no-install-recommends ca-certificates locales curl git build-essential \
    && sed -i -e "s/# $LANG.*/$LANG UTF-8/" /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG=$LANG \
    && curl -LO "https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz" \
    && tar zxf nvim-linux64.tar.gz \
    && mkdir -p ~/.config/nvim/pack/nvim-treesitter/start \
    && git clone https://github.com/nvim-treesitter/nvim-treesitter.git ~/.config/nvim/pack/nvim-treesitter/start/nvim-treesitter
RUN /nvim-linux64/bin/nvim \
         -c "TSInstallSync! c" \
         -c "TSInstallSync! lua" \
         -c "TSInstallSync! markdown" \
         -c "TSInstallSync! markdown_inline" \
         -c "TSInstallSync! query" \
         -c "TSInstallSync! vim" \
         -c "TSInstallSync! vimdoc" \
         -c q
ENTRYPOINT /nvim-linux64/bin/nvim -c 'checkhealth|help reference_toc'
```

and you'll see that, with the latest `master` branch of `nvim-treesitter`, there are spurious U+2500 BOX DRAWINGS LIGHT HORIZONTAL characters surrounding all help tags, with the default nvim colorscheme.

Can you explain what exactly is wrong with colorscheme?

**Comment by clason** [comment] 2024-08-23 07:30
The usual issue here is colorschemes somehow defaulting to an empty foreground color for such tags.

The box drawing characters are a separate issue, but nothing in this project can account for them. Since the vimdoc parser and queries are bundled with Neovim, you should be able to reproduce it with `nvim --clean` (without docker). Please open an issue in Neovim then.

**Comment by godlygeek** [comment] 2024-08-23 07:35
> you should be able to reproduce it with `nvim --clean`

I cannot. Update the entrypoint of the Dockerfile to:
```
ENTRYPOINT /nvim-linux64/bin/nvim --clean -c 'checkhealth|help reference_toc'
```
and the problem goes away, no box drawing characters to be seen:
![image](https://github.com/user-attachments/assets/2f16f935-9470-4435-b109-59098661d9db)

I don't know how or why, but it is this plugin causing them.

**Comment by clason** [comment] 2024-08-23 07:36
> I don't know how or why, but it is this plugin causing them.

But this is not possible, since the vimdoc parser and queries are identical (comparing master to master, which is the only thing that matters here) and highlighting and conceal are completely handled by Neovim.

**Comment by godlygeek** [comment] 2024-08-23 07:39
The same occurs without Docker. I originally encountered the problem outside of Docker, and set about crafting the Dockerfile as a minimal reproducer to demonstrate that this is a real issue, with a reproducible self-contained environment that clearly has no external dependencies (for instance, no colorscheme being set!)

**Comment by clason** [comment] 2024-08-23 07:42
That is very weird. Can you try to minimize the repro further? What happens if you just `curl` (not clone!) the `vimdoc/highlights.scm` from here into your config directory?

**Comment by godlygeek** [comment] 2024-08-23 08:26
> I notice you're not actually calling `setup` for nvim-treesitter

Adding `-c "lua require'nvim-treesitter.configs'.setup {}"` to the command line doesn't change the behavior

> What happens if you just `curl` (not clone!) the `vimdoc/highlights.scm` from here into your config directory?

Placing it in ~/.config/nvim/queries/vimdoc/highlights.scm IIUC? If so, the issue doesn't occur.

> can you `diff` the cloned query against the ones in Neovim's `runtime`?

There are no differences in either the `highlights.scm` or the `injections.scm`

Wait, ok, hm - this problem doesn't happen if I run
```
/nvim-linux64/bin/nvim -c "lua require'nvim-treesitter.configs'.setup {}" -c 'help reference_toc'
```
as the entrypoint, but does happen if I run
```
/nvim-linux64/bin/nvim -c "lua require'nvim-treesitter.configs'.setup {}" -c 'checkhealth|help reference_toc'
```
but still only if `nvim-treesitter` is installed and enabled...

Somehow, running `:checkhealth` first causes the behavior of `:help` to change, adding the box drawing characters only when `nvim-treesitter` is installed.

So, OK, this is a separate problem than the original one that I set out to debug, and that one really was just caused by running the old tag of nvim-treesitter instead of the latest master. But there is still something weird happening here...

**Comment by clason** [comment] 2024-08-23 08:48
Ok, now we're getting somewhere... I still can't reproduce this, and I can't explain the outcome, but that's at least something to investigate. Can you bisect the `health.lua` to find the exact lines responsible? I suspect it's the characters used for `check_status` -- try replacing those with basic ASCII letters.

(The issue must be related to your terminal and/or font -- which are you using?)

**Comment by godlygeek** [comment] 2024-08-23 09:18
> Can you bisect the `health.lua` to find the exact lines responsible?

It disappears if I comment out `table.insert(parser_installation, legend)` - even though there are no non-ascii characters in `legend`. And it _doesn't_ go away if I remove the one non-ascii character in `health.lua` (the ✓ in `query_status`).

> (The issue must be related to your terminal and/or font -- which are you using?)

wsltty, Iosevka Term SS15, and tmux - though it seems to reproduce reliably outside of tmux. But you're right, I'm not able to reproduce it at all in Windows Terminal. Hm...

**Comment by clason** [comment] 2024-08-23 09:31
> It disappears if I comment out table.insert(parser_installation, legend) - even though there are no non-ascii characters in legend.

OK, then the next step is to create a minimal `health.lua` you can place in your config's `lua/box/health.lua` (so `:check box` will print it) that only prints this multiline string. Try removing each line (including the empty one!). I can't see any non-printable characters, but there might be som line-ending shenanigans.

> wsltty, Iosevka Term SS15, and tmux - though it seems to reproduce reliably outside of tmux. But you're right, I'm not able to reproduce it at all in Windows Terminal. Hm...

Can you replace the font with a standard font?

**Comment by godlygeek** [comment] 2024-08-26 02:33
I am occasionally able to reproduce in `nvim --clean`, so indeed, this does appear to be a bug in neovim. Thank you for your help in diagnosing this. 

This observation:

> The context here is that checkhealth uses a custom syntax file (that inherits the help syntax) that adds this box drawing character as a conceal for the check separator `=`. This seems to somehow get "stuck" as conceal character for the proper help buffer.

was really crucial, and I wasn't aware of that.

I've entered https://github.com/neovim/neovim/issues/30144 for it.
