### ISSUE TITLE
Error in vimdoc query

### ISSUE THREAD

**Issue by mimre25** [nvim-treesitter/nvim-treesitter#6607] opened 2024-05-10 16:53 UTC
### Describe the bug

When going through any docs inside of `neovim` I get an error in every line.

<details><summary>Screenshot</summary>

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/2582811/b01c1445-0cf5-4ad8-81f8-e8526e2359e2)

</details> 

### To Reproduce

My lazy installtion installation:
```
    {
        "nvim-treesitter/nvim-treesitter",
        tag = "v0.9.2",
        build = function()
            local ts_update = require("nvim-treesitter.install").update({ with_sync = true })
            ts_update()
        end,
    },
```

Note: I've recently upgraded treesitter from `v0.9.1` to `v0.9.2` and ever since I'm getting errors that usually go away when I do `TSInstall <language>`.
However, for `vimdoc` that doesn't work.

Prior to the update there were no errors.

### Expected behavior

Not getting errors :sweat_smile: 

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.5.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.15.0-88-generic",
  sysname = "Linux",
  version = "#98~20.04.1-Ubuntu SMP Mon Oct 9 16:43:45 UTC 2023"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - scheme              ✓ . ✓ . ✓
  - sql                 ✓ . . ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              x . . . ✓
  - vue                 ✓ . ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR vimdoc(highlights): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 615 for language vimdoc
  vimdoc(highlights) is concatenated from the following files:
  | [ERROR]:"/home/martin/.local/share/nvim/lazy/nvim-treesitter/queries/vimdoc/highlights.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 615 for language vimdoc
```
```


### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1692716794
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/martin/Tools/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/martin/Tools/neovim/.deps/usr/include -I/home/martin/Tools/neovim/build/src/nvim/auto -I/home/martin/Tools/neovim/build/include -I/home/martin/Tools/neovim/build/cmake.config -I/home/martin/Tools/neovim/src -I/usr/include -I/home/martin/Tools/neovim/.deps/usr/include -I/home/martin/Tools/neovim/.deps/usr/include -I/home/martin/Tools/neovim/.deps/usr/include -I/home/martin/Tools/neovim/.deps/usr/include -I/home/martin/Tools/neovim/.deps/usr/include -I/home/martin/Tools/neovim/.deps/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
```


### Additional context

Happy to provide more context if needed. :slightly_smiling_face: 

CC @clason (you're listed as `vimdoc` maintainer :slightly_smiling_face: )

**Comment by clason** [comment] 2024-05-10 16:58
Duplicate of #3092; please follow the steps there. If in doubt, uninstall the plugin completely, make sure you don't have stray queries and parsers lying around, and reinstall.

**Closed by clason** 2024-05-10 16:58 UTC
Labels: bug
