### ISSUE TITLE
Treesitter not working in some places in html

### ISSUE THREAD

**Issue by melsiir** [nvim-treesitter/nvim-treesitter#2240] opened 2022-01-12 05:57 UTC
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`
- [X] I have read the [troubleshooting section](https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting)

### Describe the bug

On html some tags get it's highlights disappear 

https://user-images.githubusercontent.com/73516767/149071925-6e89c48c-a9bd-4123-85c6-2ca8f10ec548.mp4

![Screenshot_٢٠٢٢٠١١١-١٤٤١٤٠_Termux](https://user-images.githubusercontent.com/73516767/149071934-44e685a0-0339-44df-889e-6ab238350928.jpg)
![Screenshot_٢٠٢٢٠١١١-١٢٠٤٤٨_Termux](https://user-images.githubusercontent.com/73516767/149071936-fb3e7ad8-0473-4d7e-b187-abf6b6b512c5.jpg)

### To Reproduce

Just start typing html

### Expected behavior

Highlight is consistent

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v17.3.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: clang version 13.0.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - graphql        ✓ . . ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - vim            ✓ ✓ . . ✓ 
  - dockerfile     ✓ . . . ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - dot            ✓ . . . ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
:version                                          NVIM v0.6.1                                       Build type: Release                               LuaJIT 2.1.0-beta3                                Compiled by builder@be4e75c1a477                                                                    Features: +acl +iconv +tui                        See ":help feature-compile"                                                                            system vimrc file: "$VIM/sysinit.vim"            fall-back for $VIM: "                           /data/data/com.termux/files/usr/share/nvim"                                                         Run :checkhealth for more info
```

### Additional context

My treesitter setup :

local present, ts_config = pcall(require, "nvim-treesitter.configs")

if not present then
   return
end

ts_config.setup {
   ensure_installed = {
      "lua",
      "vim",
      "css",
      "typescript", "javascript",
      "tsx", "graphql", "html",
      "scss", "python", "dockerfile",
      "dot", "json", "bash", "fish",
      "hjson", "vue", "svelt",
   },
   highlight = {
      enable = true,
      use_languagetree = true,
   },
   autotag = {
    enable = true,
  }
}

**Comment by kaddkaka** [comment] 2022-01-12 13:14
Is the parsing/grammar correct? One idea could be to look at the syntax tree using nvim-treesitter/playground plugin, to see if it's OK at that point or not.

**Comment by Rimann91** [comment] 2022-01-19 21:22
Just noting that I have the same issue, also having issues with autoindent but I don't know if it is tree sitter related

**Comment by stsewd** [comment] 2022-01-21 23:00
This is a duplicate of https://github.com/nvim-treesitter/nvim-treesitter/issues/1788

**Closed by stsewd** 2022-01-21 23:00 UTC
Labels: bug
