### ISSUE TITLE
memory leak when opens specific file.

### ISSUE THREAD

**Issue by iujakchu** [nvim-treesitter/nvim-treesitter#4037] opened 2022-12-26 07:15 UTC
### Describe the bug

When I opened this [file](https://github.com/rxyhn/dotfiles/blob/84502dc09b63837e77ba1e58ae98c9f624895736/home/rxyhn/modules/desktop/waybar/default.nix) with only lazy.nvim and nvim-treesitter.
Neovim swallowed all my memory.

### To Reproduce

install lazy.nvim and nvim-treesitter with this minimal setup:
```lua
    require("nvim-treesitter.configs").setup {
        ensure_installed = {
            "lua",
            "nix",
        }, --
        highlight = {
            enable = true, -- false will disable the whole extension
        },
    }

```

### Expected behavior

open file normally

### Output of `:checkhealth nvim-treesitter`

```markdown
vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for bash: ABI version 14
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for cpp: ABI version 14
  - OK: Loaded parser for dart: ABI version 13
  - OK: Loaded parser for fennel: ABI version 13
  - OK: Loaded parser for fish: ABI version 14
  - OK: Loaded parser for glsl: ABI version 14
  - OK: Loaded parser for haskell: ABI version 14
  - OK: Loaded parser for javascript: ABI version 14
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for markdown: ABI version 13
  - OK: Loaded parser for nix: ABI version 13
  - OK: Loaded parser for norg: ABI version 14
  - OK: Loaded parser for org: ABI version 14
  - OK: Loaded parser for python: ABI version 14
  - OK: Loaded parser for qmljs: ABI version 14
  - OK: Loaded parser for rust: ABI version 14
  - OK: Loaded parser for scheme: ABI version 14
  - OK: Loaded parser for scss: ABI version 13
  - OK: Loaded parser for slint: ABI version 13
  - OK: Loaded parser for solidity: ABI version 13
  - OK: Loaded parser for typescript: ABI version 14
  - OK: Loaded parser for yaml: ABI version 13
```

### Output of `nvim --version`

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/zfyninsb38hzxkx3rxvwz3lxdxnsfz0j-neovim-unwrapped-0.8.1/share/nvim
"

Run :checkhealth for more info
```

### Additional context

I'm currently using nixos:
`
❯ nixos-version
23.05.20221222.652e92b (Stoat)
`

**Comment by nbCloud91** [comment] 2022-12-29 15:09
I have a similar issue, treesitter eats up all the memory while opening my home.nix file. Even before this issue, earlier that file used to have messed up coloring for a certain chunk of code. I narrowed it down with a minimal example and indeed it is that chunk which has caused this problem now.

``` nix
{
  somevar = {
    othervar = {
      preview_title= "rgb(235, 219, 178) rgb(40, 40, 40) / rgb(189, 174, 147) rgb(40, 40, 40)";
      preview= "rgb(235, 219, 178) rgb(40, 40, 40) / rgb(235, 219, 178) rgb(40, 40, 40)";
    };
  };
}
```
I am using
`
nixos-version 23.05pre438362.e182da8622a (Stoat)
`

**Comment by folke** [comment] 2023-01-16 22:52
I think I know what's causing this. Something to do with recursive injections.
Neovim also becomes totally unresponsive right?
I've been planning to fix this upstream (Neovim). Will see if I can do this tomorrow.

**Comment by folke** [comment] 2023-01-16 22:59
Just tested with that file and this is indeed caused by recursive injections. Will work on a fix...

**Comment by clason** [comment] 2023-01-17 11:57
Closed by https://github.com/neovim/neovim/pull/21858

**Closed by clason** 2023-01-17 11:57 UTC
Labels: bug
