### ISSUE TITLE
vim.treesitter.get_node() throw error invalid node type for language typescript. Doesn't do the same for javascript file

### ISSUE THREAD

**Issue by Herob527** [nvim-treesitter/nvim-treesitter#5108] opened 2023-07-15 08:50 UTC
### Describe the bug

After recent update, I noticed my snippet using vim.treesitter.get_node() stoped working for typescript as well

For JS it works
![for js file](https://github.com/nvim-treesitter/nvim-treesitter/assets/61355107/6959ffbb-cf1e-49d7-ab1c-3d23df273f3f)

For TS
![for ts file](https://github.com/nvim-treesitter/nvim-treesitter/assets/61355107/20eb59cc-3a25-4bf8-9c69-f4a784b71560)

For tsx and jsx no found parser, so old error not fixed yet

Minimal reproduction bracnh
[Link](https://github.com/Herob527/nvim/tree/check-issue-with-luasnip-snippets)

Also I created repo with boilerplate for manual testing snipepts (for now, i have console snippet that has this issue)
I don't know how to automate testing, so help is appreciated
[Link](https://github.com/Herob527/test_nvim_snippets)

Snippet
```lua
local luasnip = require("luasnip")
local i = luasnip.insert_node
local sn = luasnip.snippet
local t = luasnip.text_node
local s = luasnip.snippet_node
local d = luasnip.dynamic_node
local fmt = require("luasnip.extras.fmt").fmt
local ts = vim.treesitter
local ts_query = ts.query

--- @param node TSNode | nil
--- @param ts_elements table<string>
--- @returns TSNode | nil
local function seek_function_root(node, ts_elements)
	if node == nil then
		return nil
	end
	local node_type = node:type()
	if vim.tbl_contains(ts_elements, node_type) or node_type == "program" then
		return node
	end

	local parent = node:parent()

	return seek_function_root(parent, ts_elements)
end

--- @param node TSNode | nil
-- TODO: This has potential to work in other langauges - just dehardcode it someday
local function get_data(node)
	local filetype = vim.bo.filetype
	local query_lang = filetype == "javascriptreact" and "jsx" or filetype
	if node == nil then
		return nil
	end
	local node_type = node:type()
	if node_type == "program" then
		return "global"
	end
	local query_str = [[
    (variable_declarator (identifier) @name)
    (function_declaration (identifier) @name)
    (method_definition (property_identifier) @name)
    (field_definition (property_identifier) @name)
]]
	local parsed_query = ts_query.parse(query_lang, query_str)
	-- print("[get_data]")
	for _, parsed_node, _ in parsed_query:iter_captures(node, 0, node:start(), node:end_()) do
		return ts.get_node_text(parsed_node, 0)
	end
end

local console = sn(
	"con",
	fmt([[ console.log("[{function_name} - {var}]",{var})]], {
		function_name = d(1, function(args)
			--- @type string
			local search = args[1][1]
			local ts_node = ts.get_node()
			local function_root = seek_function_root(
				ts_node,
				{ "function_declaration", "variable_declarator", "method_definition", "field_definition" }
			)
			vim.print(search)
			local data = function_root ~= nil and get_data(function_root) or ""
			local output = t(data)
			return s(nil, { output })
		end, { 2 }),
		var = i(2),
	}, {
		repeat_duplicates = true,
	})
)

return console
```

### To Reproduce

1. Use vim.treesitter.get_node() in typescript file

### Expected behavior

I expected this not to throw error

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (d4c1bf7ce78051b7f4a381d1508d68928512ed5f) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v19.5.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.19.0-46-generic",
  sysname = "Linux",
  version = "#47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - dockerfile          ✓ . . . ✓
  - git_config          ✓ . . . .
  - gitignore           ✓ . . . .
  - go                  ✓ ✓ ✓ ✓ ✓
  - graphql             ✓ . . ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - ini                 ✓ . ✓ . .
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - ruby                ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - vue                 ✓ . ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.2-dev-51+gd3ac24980
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

**Comment by clason** [comment] 2023-07-15 08:55
Duplicate of #3092

**Closed by clason** 2023-07-15 08:55 UTC
Labels: bug

**Comment by Herob527** [comment] 2023-07-15 08:59
I ran `:TSUpdate`, I have the latest parsers
 
Even I ran `:TSInstall!` typescript and issue persists

**Comment by clason** [comment] 2023-07-15 09:14
Read the linked issue. Other plugins may distribute queries, and these will have to be updated as well.

**Comment by Herob527** [comment] 2023-07-15 11:32
This error happens, when I call `vim.treesitter.get_node()`, not in general

As I understand mentioned link, it's all about highlights, which aren't broken here

Also, these screenshots come from branch minimum plugins required to launch snippets (for minimal reproduction)

**Comment by clason** [comment] 2023-07-15 11:50
No, the error message specifically mentions an invalid node, which means the queries do not match the parser. This can happen any time you `:TSUpdate`, so you need to pay attention and adapt queries you have written yourself (like the ones inlined in your code snippet).

**Comment by Herob527** [comment] 2023-07-15 15:18
I double checked and I figured why it was crashing

There is no field_definition in typescript, but public_field_definition and private_field_definition

Thanks for pointing it out @clason ^^
