### ISSUE TITLE
Neovim hangs when an open buffer is modified externally and foldexpr is enabled.

### ISSUE THREAD

**Issue by freddiehaddad** [nvim-treesitter/nvim-treesitter#5508] opened 2023-10-12 02:52 UTC
### Describe the bug

When a buffer is open in neovim and the same file is edited outside of neovim, neovim will hang if treesitter plugin is installed with folding feature enabled.

### To Reproduce

Set the following vim options:

```lua
vim.opt.foldenable = false
vim.opt.foldmethod = 'expr'
vim.opt.foldexpr = 'v:lua.vim.treesitter.foldexpr()'
```

Set the following treesitter options:

```lua
opts = {
	auto_install = true,
	highlight = {
		enable = true,
	},
	incremental_selection = {
		enable = true,
		keymaps = {
			init_selection = '<c-i>',
			node_incremental = '<c-i>',
			scope_incremental = false,
			node_decremental = '<bs>',
		},
	},
	indent = {
		enable = true,
	},
}
```

1. Modify a git-tracked file inside neovim and save it. Leave the buffer visible and open.
2. In a separate terminal, restore the file using git restore
3. Go back to neovim

It will hang with high cpu utilization.

### Expected behavior

Neovim should not hang.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v18.17.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.5.6-arch2-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Sat, 07 Oct 2023 08:14:55 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - git_rebase          ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
0.9.4
```

### Additional context

Performing the same steps with the following options NOT set yields expected behavior. Neovim does not freeze.

```lua
-- vim.opt.foldenable = false
-- vim.opt.foldmethod = 'expr'
-- vim.opt.foldexpr = 'v:lua.vim.treesitter.foldexpr()'
```

**Comment by clason** [comment] 2023-10-12 07:29
Duplicate of https://github.com/neovim/neovim/issues/25608 (please don't cross-post issues).

**Closed by clason** 2023-10-12 07:29 UTC
Labels: bug

**Comment by freddiehaddad** [comment] 2023-10-12 11:27
Sorry, wasn't sure where it was appropriate. Seemed like a plugin issue so I posted here but then saw treesitter related issues also posted in neovim.

**Comment by clason** [comment] 2023-10-12 12:51
It depends on what is triggering the issue; since folds and highlighting are handled by Neovim, nvim-treesitter doesn't play a role (or shouldn't -- this is why I'm so keen on removing `indent` from the reproduction steps).
