### ISSUE TITLE
Incorrect indentation level of new lines when using "o" in Python files

### ISSUE THREAD

**Issue by bool3max** [nvim-treesitter/nvim-treesitter#1284] opened 2021-05-08 23:31 UTC
Using latest `neovim` master, `tree-sitter`, and `nvim-treesitter`. 

I have noticed that, when using the `o` key when the cursor is in the middle of a line whose ending implies that the next line should be indented (i.e. any line ending in a colon `:`) in a Python file, the indentation in the new, created line, is wrong. 

Example:

```python
                      # my cursor is here, I'm in normal mode, and I press "o"
                      ^
                      |
                      |
with sqlite3.connect(...) as conn:
^    ^                   
|    |                   
|    |                    
|    |
|    |
|    | 
|    ... # while it should've ended up here
|
|
|      
# now my cursor is here
```

Basically, no indentation gets performed. If I'm in insert mode, and at the end of the line, and I press the return key, the next line is properly indented though.

**Comment by kyazdani42** [comment] 2021-05-25 18:51
duplicate of #1136

**Closed** 2021-06-05 15:47 UTC
Labels: bug, duplicate
