### ISSUE TITLE
🐛 BUG: Windows nvim treesitter throwing errors reading comments

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [nvim-treesitter/nvim-treesitter#5058] opened 2023-07-03 15:23 UTC
In various languages treesitter is moaning about invalid node type for language comment and refers to this line.

https://github.com/nvim-treesitter/nvim-treesitter/blob/c42a8f96d37be82cf32934c4351150d7736f93f5/lua/nvim-treesitter/query.lua#L259

I experienced this in .lua files and .vue files

**Comment by clason** [comment] 2023-07-03 15:24
Duplicate of #3092

**Closed by clason** 2023-07-03 15:24 UTC

**Comment by sschneider-ihre-pvs** [comment] 2023-07-03 15:28
it is a bit of a different line though

**Comment by sschneider-ihre-pvs** [comment] 2023-07-03 15:31
I also checked step 1-3 and no change. I have done tsupdate as well as the othe commands and checking the folders.

**Comment by sschneider-ihre-pvs** [comment] 2023-07-03 15:32
```
The following errors have been detected: ~
- ERROR comment(highlights): ...im-win64\share\nvim\runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 1143 for language comment
  comment(highlights) is concatenated from the following files:
  | [ERROR]:"$HOME\AppData\Roaming\lunarvim\site\pack\lazy\opt\nvim-treesitter\queries\comment\highlights.scm", failed to load: ...im-win64\share\nvim\runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 1143 for language comment
```

**Comment by sschneider-ihre-pvs** [comment] 2023-07-03 15:33
I did :TSUpdate lua but I already have the latest version

**Comment by sschneider-ihre-pvs** [comment] 2023-07-03 15:34
Also, the error only shows if the commment line is in the viewport

**Comment by sschneider-ihre-pvs** [comment] 2023-07-03 15:35
And highighting works while navigating, flashing the whole code from color to grey

**Comment by clason** [comment] 2023-07-03 15:35
Yes, that _is_ the same error; try more of the steps listed in that issue. 

Further than that, there's nothing I can offer -- we can't and don't support LunarVim, which interferes too much with Neovim internals.

**Comment by sschneider-ihre-pvs** [comment] 2023-07-04 08:43
Any information I can provide additionally somehow?

**Comment by sschneider-ihre-pvs** [comment] 2023-07-04 08:58
Ok I tried to resinstall some parses via TSInstall and that gave me an access denied error. Seems like there may be some file access issues in windows depending on what created the so files.
I deleted them manually in the explorer and reinstalled and now it seems to work.
