### ISSUE TITLE
Swift error

### ISSUE THREAD

**Issue by alex-heinz** [nvim-treesitter/nvim-treesitter#7364] opened 2024-11-15 11:57 UTC
### Describe the bug

when trying to open `.swift` file the following error appears:

```
Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...0.10.2_1/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 275:4. Invalid node type "try":
  "try?"
   ^

stack traceback:
        [C]: in function '_ts_parse_query'
        ...0.10.2_1/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
        ...im/0.10.2_1/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
        ...im/0.10.2_1/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
        ..._1/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
        ..._1/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:243: in function 'get_query'
        ..._1/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:191: in function 'fn'
        ...1/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
        ..._1/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:178: in function 'prepare_highlight_states'
        ..._1/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:40
```

### To Reproduce

open any .swift file

### Expected behavior

no errors

### Output of `:checkhealth nvim-treesitter`

```markdown
- ok `tree-sitter` found 0.24.4 (parser generator, only needed for :tsinstallfromgrammar)
- ok `node` found v22.11.0 (only needed for :tsinstallfromgrammar)
- ok `git` executable found.
- ok `cc` executable found. selected from { vim.nil, "cc", "gcc", "clang", "cl", "zig" }
  version: apple clang version 16.0.0 (clang-1600.0.26.4)
- ok neovim was compiled with tree-sitter runtime abi version 14 (required >=13). parsers must be compatible with runtime abi.

os info:
{
  machine = "arm64",
  release = "24.1.0",
  sysname = "darwin",
  version = "darwin kernel version 24.1.0: thu oct 10 21:05:23 pdt 2024; root:xnu-11215.41.3~2/release_arm64_t6031"
} ~

parser/features         h l f i j
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - comment             ✓ . . . .
  - diff                ✓ . . . .
  - dockerfile          ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . .
  - groovy              ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - hurl                ✓ . ✓ ✓ ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - kotlin              ✓ ✓ ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - properties          ✓ ✓ . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - scss                ✓ . ✓ ✓ .
  - sql                 ✓ . . ✓ ✓
  - swift               x ✓ . ✓ .
  - tmux                ✓ . . . ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  legend: h[ighlight], l[ocals], f[olds], i[ndents], in[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :tsupdate {lang} ~

the following errors have been detected: ~
- error swift(highlights): ...0.10.2_1/share/nvim/runtime/lua/vim/treesitter/query.lua:252: query error at 275:4. invalid node type "try":
    "try?"
     ^
  
  swift(highlights) is concatenated from the following files:
  | [error]:"~/.local/share/lunarvim/site/pack/lazy/opt/nvim-treesitter/queries/swift/highlights.scm", failed to load: ...0.10.2_1/share/nvim/runtime/lua/vim/treesitter/query.lua:252: query error at 275:4. invalid node type "try":
    "try?"
     ^
```

### Output of `nvim --version`

```text
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1731485912
Run "nvim -V1 -v" for more info
```

**Comment by clason** [comment] 2024-11-15 11:58
Duplicate of #3092

**Closed by clason** 2024-11-15 11:58 UTC
Labels: bug

**Comment by gigq** [comment] 2025-01-12 04:25
So I tried going through the troubleshooting steps in #3092 but it didn't help me. To anyone running into the same error that comes across this issue, what worked for me was just deleting try? And try! from nvim-treesitter/queries/swift/highlights.scm
