### ISSUE TITLE
latest update to vimdoc error

### ISSUE THREAD

**Issue by alexxShandsome** [nvim-treesitter/nvim-treesitter#6738] opened 2024-06-07 03:13 UTC
### Describe the bug

when i access the documentation in ```:h``` and error shows this error
```
Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...x/.local/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 99:3. Impossible pattern:
  "~" @markup.raw.delimiter
  ^

stack traceback:
        [C]: in function '_ts_parse_query'
        ...x/.local/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
        ...alex/.local/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
        ...alex/.local/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:240: in function 'get_query'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:188: in function 'fn'
        ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:175: in function 'prepare_highlight_states'
        ...al/share/nvim/runtime/lua/vim/treesitter/highli
Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...x/.local/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 99:3. Impossible pattern:
  "~" @markup.raw.delimiter
  ^
```

### To Reproduce

1. I updated the nvim-treesitter by doing ```:Lazy update nvim-treesitter```.
2. I quit and reopen the editor just to be sure.
3. Then I typed anything in the help command, ```:help help```.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.17.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.15.0-107-generic",
  sysname = "Linux",
  version = "#117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              x . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR vimdoc(highlights): ...x/.local/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 99:3. Impossible pattern:
    "~" @markup.raw.delimiter
    ^
  
  vimdoc(highlights) is concatenated from the following files:
  |    [OK]:"/home/alex/.local/share/nvim/lazy/nvim-treesitter/queries/vimdoc/highlights.scm"
  | [ERROR]:"/home/alex/.local/share/nvim/lazy/newpaper.nvim/after/queries/vimdoc/highlights.scm", failed to load: ...x/.local/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 26:3. Impossible pattern:
    "~" @markup.raw.delimiter
    ^
```

### Output of `nvim --version`

```text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

**Comment by alexxShandsome** [comment] 2024-06-07 03:18
my fix for now is going back to commit ```5a8e9644``` and uninstalling the vimdoc parser

**Comment by clason** [comment] 2024-06-07 06:18
Duplicate of #3092

**Closed by clason** 2024-06-07 06:18 UTC
Labels: bug

**Comment by clason** [comment] 2024-06-07 06:21
This is a custom query, so check where that is coming from. Parsers make breaking changes to the grammar all the time (some more, some less often) and you need to adapt custom queries to any changes. If you actually check the commits, you will see what changes need to be made (since they are made to the queries here, which are always compatible with the parser version we install).

**Comment by alexxShandsome** [comment] 2024-06-07 09:14
> Duplicate of #3092

I already did the stuff mentioned here, yet there's still an error

**Comment by clason** [comment] 2024-06-07 10:10
No, the query must come from somewhere else since the capture group is wrong. Use the approach in the linked issue to find any outdated stray queries in your runtimepath.

**Comment by alexxShandsome** [comment] 2024-06-07 10:27
I already fixed my problem

**Comment by gsheru** [comment] 2024-06-26 10:32
> I already fixed my problem

It would be very helpful if you explain how you fixed this for anyone who has the same problem and finds this thread.

Don't you think?

**Comment by genki** [comment] 2024-09-27 21:44
`:TSInstall! vimdoc` solves this issue in my case.
