### ISSUE TITLE
error after updating nvim-treesitter

### ISSUE THREAD

**Issue by bryant-the-coder** [nvim-treesitter/nvim-treesitter#3454] opened 2022-09-08 11:25 UTC
![image](https://user-images.githubusercontent.com/92417638/189110463-21433077-b24e-401a-827b-3254628b24c6.png)

**Comment by bryant-the-coder** [comment] 2022-09-08 11:26
when i pin it to `commit = "2a63ea5665a6de96acd31a045d9d4d73272ff5a9",` it doesnt show any errors

**Comment by clason** [comment] 2022-09-08 11:51
Duplicate of #3092

**Comment by clason** [comment] 2022-09-08 11:52
If you use Neovim nightlies, you need to keep them at the latest commit, or things _will_ break.

**Closed by clason** 2022-09-08 11:51 UTC

**Comment by bryant-the-coder** [comment] 2022-09-08 15:59
i did all the steps. the error stopped. but now highlighting isnt working
