### ISSUE TITLE
Highlight breaks at random HTML tag or at specific cursor position

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [nvim-treesitter/nvim-treesitter#2151] opened 2021-12-21 08:42 UTC
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`
- [X] I have read the [troubleshooting section](https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting)

### Describe the bug

Highlight randomly (_or at specific tag/line_) break when at HTML tag, whether in html, jsx, tsx and svelte (or maybe more). Issue on [Svelte](https://github.com/Himujjal/tree-sitter-svelte/issues/21#issue-1083837311) 

### To Reproduce

**This video are using Treesitter highlight**

https://user-images.githubusercontent.com/73665622/146897950-6c458fee-721f-4217-97f5-845a5f206c72.mp4

> Already test without Treesitter highlight and using default syntax highlight, it worked fine.

### Expected behavior

As we expected to be ...

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim_treesitter: health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.1 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.13.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - org            ✓ . . . ✓ 
  - svelte         ✓ . ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - vim            ✓ ✓ . . ✓ 
  - markdown       ✓ . ✓ . ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az32-74

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"
```

**Comment by stsewd** [comment] 2021-12-21 15:43
This is a duplicate of https://github.com/nvim-treesitter/nvim-treesitter/issues/1788

**Closed by stsewd** 2021-12-21 15:43 UTC
Labels: bug
