### ISSUE TITLE
Python f-strings are not highlighted properly on latest nightly

### ISSUE THREAD

**Issue by pappasam** [nvim-treesitter/nvim-treesitter#6317] opened 2024-03-18 06:13 UTC
I have the same issue, please help me! I will (try to) donate you if you kindly help me!

screenshot:

![Screenshot from 2024-03-17 14-32-58](https://github.com/nvim-treesitter/nvim-treesitter/assets/45907809/a2b1e450-fca7-4b60-a44d-e50d26a977c1)

The `+ ( int is not` inside the interpolation are correctly rendered, but the functions and variables are rendered as strings. **Maybe it's related to priority**, but I don't know how to modify them.

Neovim version: 
```
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
checkhealth:
```md
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v18.17.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.5.0-25-generic",
  sysname = "Linux",
  version = "#25~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Feb 20 16:09:15 UTC 2"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

do `:Inspect` at the `round`:

![Screenshot from 2024-03-17 14-01-19](https://github.com/nvim-treesitter/nvim-treesitter/assets/45907809/dac2059e-7f71-4f24-9cea-7e747e8b2513)

do `:InspectTree`:
```
        (string ; [3, 6] - [3, 54]
          (string_start) ; [3, 6] - [3, 8]
          (string_content) ; [3, 8] - [3, 13]
          (interpolation ; [3, 13] - [3, 18]
            expression: (binary_operator ; [3, 14] - [3, 17]
              left: (integer) ; [3, 14] - [3, 15]
              right: (integer))) ; [3, 16] - [3, 17]
          (string_content) ; [3, 18] - [3, 19]
          (interpolation ; [3, 19] - [3, 22]
            expression: (identifier)) ; [3, 20] - [3, 21]
          (string_content) ; [3, 22] - [3, 23]
          (interpolation ; [3, 23] - [3, 40]
            expression: (comparison_operator ; [3, 24] - [3, 39]
              (identifier) ; [3, 24] - [3, 27]
              (none))) ; [3, 35] - [3, 39]
          (string_content) ; [3, 40] - [3, 41]
          (interpolation ; [3, 41] - [3, 53]
            expression: (call ; [3, 42] - [3, 52]
              function: (identifier) ; [3, 42] - [3, 47]
              arguments: (argument_list ; [3, 47] - [3, 52]
                (float)))) ; [3, 48] - [3, 51]
          (string_end))))) ; [3, 53] - [3, 54]
```
colorscheme: [navarasu/onedark.nvim](https://github.com/navarasu/onedark.nvim) with some customizations
`nvim-treesitter` configs:
```lua
require('nvim-treesitter.configs').setup {
    -- A directory to install the parsers into.
    -- If this is excluded or nil parsers are installed
    -- to either the package dir, or the "site" dir.
    -- If a custom path is used (not nil) it must be added to the runtimepath.
    -- parser_install_dir = "/some/path/to/store/parsers",

    -- A list of parser names, or "all"
    ensure_installed = { "c", "lua", "python" },

    -- Install parsers synchronously (only applied to `ensure_installed`)
    sync_install = true,

    -- Automatically install missing parsers when entering buffer
    auto_install = true,

    -- List of parsers to ignore installing (for "all")
    -- ignore_install = { "javascript" },

    highlight = {
      -- `false` will disable the whole extension
      enable = true,

      -- list of language that will be disabled
      disable = {},

      -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
      -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
      -- Using this option may slow down your editor, and you may see some duplicate highlights.
      -- Instead of true it can also be a list of languages
	  additional_vim_regex_highlighting = false,
    },
  }
```
part of the onedark highlights config (the 4 variable lines didn't work inside interpolation, but the punctuation worked):
```lua
		["@variable"] = {fg = '$fg'},
		["@variable.parameter"] = {fg = '$cyan'},
		["@variable.member"] = {fg = '$fg'},
		["@variable.builtin"] = {fg = '#FF69Bf'},  -- pink
		["@punctuation.bracket"] = {fg = '$fg'},
		["@punctuation.delimiter"] = {fg = '$fg'},
```

Please help me! I'll provide more information if you need!

_Originally posted by @LZDQ in https://github.com/nvim-treesitter/nvim-treesitter/issues/2588#issuecomment-2002332019_

**Comment by pappasam** [comment] 2024-03-18 06:21
Here's a small example using the latest nightly and the default colorscheme:

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/3723671/c9a089c8-4590-4314-a09d-e31c886ad23e)

```python
class Hello:

    def hello(self, x):
        return "world"

    def test(self):
        y = self.hello()
        print(f"hello, {self.hello()}")
```

Notice how GitHub highlights `self.hello()` differently than Neovim?

**Comment by amaanq** [comment] 2024-03-18 06:22
dupe of #6314, also what? you just copied his post without checking the recent list of issues, not to mention this was *just* fixed in https://github.com/neovim/neovim/pull/27901

**Closed by amaanq** 2024-03-18 06:22 UTC

**Comment by lucario387** [comment] 2024-03-18 06:51
It's not even nightly smh my head
