### ISSUE TITLE
Error `end_col value outside range` when edit

### ISSUE THREAD

**Issue by xaljer** [nvim-treesitter/nvim-treesitter#651] opened 2020-11-14 05:19 UTC
**Describe the bug**

`lua/vim/treesitter/highlighter.lua:157: end_col value outside range`

**To Reproduce**
It happens sometimes when do editing like delete lines.

**Expected behavior**
Highlight always work no matter how I edit a file.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

Paste the output here

</code>
</details>

**Output of `nvim --version`**
0.5

**Additional context**

**Comment by p00f** [comment] 2020-11-14 06:06
i think for `nvim --version` you need to give the full version, like `NVIM v0.5.0-830-g4ae31c46f`. This contains the commit (4ae31c46f in my case)

**Comment by xaljer** [comment] 2020-11-15 13:40
v0.5.0-812-gd17e50879

sorry can't paste all outputs to here. It happens on several versions of nvim.

**Comment by vigoux** [comment] 2020-11-16 08:26
Hi, can you provide a simple file + repro steps ? That should be an upstream issue, that we'll be able to fix with your repro steps.

**Comment by jim-at-jibba** [comment] 2020-11-17 14:28
I am experiencing the same issue v0.5.0-828-g0a95549d6

**Comment by tami5** [comment] 2020-11-17 21:05
I am experiencing the same issue NVIM v0.5.0-828-g0a95549d6

`treesitter/highlighter: Error executing lua: /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:157: end_col value outside range`

**Comment by jim-at-jibba** [comment] 2020-11-18 10:35
@tami5 This seems to have helped. Thanks

**Comment by tami5** [comment] 2020-11-18 11:02
I'm still toying around with the edit on L157 . It seems to have side effect on some aspect I don't know what.

np @jim-at-jibba

**Comment by steelsojka** [comment] 2020-11-18 18:58
@vigoux I think a lot of this is fixed by the language tree integration upstream. I used to get these errors until we implemented the language tree.

**Comment by vigoux** [comment] 2020-11-18 19:13
Then lets wait until the `LanguageTree` is pushed, after that we'll start digging into those.

**Comment by kyazdani42** [comment] 2020-11-18 22:25
@tami5 this is not the place where the bug is coming from. This end_col thing happens because the parsing and the buffer updates are getting out of sync (i think ^^)

**Comment by sl8vz** [comment] 2020-12-05 19:58
Hi,
Same issue which happens when updating the file out of nvim and then when the files is re-loaded in nvim same kind of error. Correlates with @kyazdani42 comment.

`treesitter/highlighter: Error executing lua: ...sr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:219: end_col value outside range`

Using NVIM v0.5.0-31787a9

**Comment by ojroques** [comment] 2020-12-06 21:00
I run into the same issue almost every times when using `:sort`. With the tree-sitter for python enabled and this file:
```py
fruits = [
  "apple",
  "banana",
  "pear",
  "orange",
  "cherry",
]
```
Running `:sort` on the entries gives me the error. After a few tests it seems it only happens when the first or the last entry is out of order which is the case here.

**Comment by steelsojka** [comment] 2020-12-07 12:48
This is an issue upstream with the highlighter/parser. The tree update isn't getting triggered and/or the byte updates aren't getting applied correctly to the tree. So, when the highlighter runs the nodes are out of range for the actual buffer line. It only will error if the node range is larger than the actual line length. This is why it's only intermittent. We'll have to investigate it and submit a PR upstream.

**Comment by thorlucas** [comment] 2021-02-08 07:34
Same issue on NVIM v0.5.0-dev+971-g8c8cc3592

**Comment by Happy-Dude** [comment] 2021-02-14 21:27
Just wanted to give this issue a poke and wonder if the latest HEAD changes re: tree-sitter and undofile helps? https://github.com/neovim/neovim/pull/13935

**Comment by rexagod** [comment] 2021-02-15 19:23
Experiencing this on `NVIM v0.5.0-dev+1087-g5ad32885d` as well, quite frequently actually.

**Comment by kyazdani42** [comment] 2021-02-18 21:09
these issues are neovim related, this plugin has nothing to do with it.

**Comment by sarahkittyy** [comment] 2021-03-18 08:46
I am also getting these errors: `NVIM v0.5.0-dev+1157-g0ab88c2ea`
![image](https://user-images.githubusercontent.com/31551546/111597542-a5253f00-87a4-11eb-9f90-7221d6e63c2d.png)
![image](https://user-images.githubusercontent.com/31551546/111597631-bf5f1d00-87a4-11eb-82a3-e22b38cd5959.png)

When I hit tab in this buffer (and seemingly only this buffer, persistent across restarts), this error pops up.
I found in possibly another related issue that someone said doing `:w | :e | TSBufEnable highlight` fixes it, but that does not work.

This is super annoying? This pops up every single time I hit tab. Does anyone have a solution?

**Comment by akinsho** [comment] 2021-03-18 08:59
@sarahkittyy this is an upstream issue in neovim itself see https://github.com/neovim/neovim/issues/12861#issuecomment-800536140, the neovim devs need specific steps to reproduce the issues as they appear so they can look into fixing the specific causes. If you have a minimum number of steps to reproduce I recommend sharing it there.

**Comment by kaddkaka** [comment] 2021-04-06 13:12
Here is a minimal example to get this error using tree-sitter-python and highlights module:

1. open a python file with following content: `a=1`
2. perform :luado return "aa"

I think there has to be highlighted color on column that will be outside the new text, therefore the short string `aa`. With a longer string (3 or more character) the error is not produced.

**Comment by vigoux** [comment] 2021-04-06 18:06
Hehe actually, most neovim devs working on this kind of issues try to follow both issues, but still, it's more convenient to have everything in the upstream issue 😉

**Comment by kaddkaka** [comment] 2021-04-06 21:51
I copied my comment to there as well and mentioned it on gitter. I would have guessed this to be an easy fix if you know the codebase?

**Comment by vigoux** [comment] 2021-04-07 03:35
I can't say for sure now, but I'll look into it and see, the thing is having clear repro steps, which are basically the only way for us to trigger and fix buffer updates bugs.

**Comment by kaddkaka** [comment] 2021-04-07 05:30
@vigoux of course, but the steps are super simple right? Were you able to reproduce it?

**Comment by Pocco81** [comment] 2021-06-09 01:03
I'm experiencing the same issue here...

**Comment by vigoux** [comment] 2021-06-09 06:23
Which steps are you following to encounter the issue?
As mentioned throughout this thread, we need clear repro steps, otherwise we can't do anything.

**Comment by desprit** [comment] 2021-06-09 06:33
@vigoux 

It happens to me very often when I select several lines and delete. E.g. `V10jd`. The problem is I can't reproduce it. It happens randomly.

**Comment by vigoux** [comment] 2021-06-09 06:36
I'll try and see if I can reproduce with, that only, if you find a set of text reproducing the issue, please send it to us here, it may be dependent on the text you select.

**Comment by theHamsta** [comment] 2021-12-13 19:49
I think this isn't an issue anymore most of the time. At least it shouldn't be a pinned issue.

**Comment by theHamsta** [comment] 2022-01-16 13:18
I think this issue stood for various different problems. To avoid confusion please open a new updated one for the concrete problems that happen with current versions of Neovim.

**Comment by ramfattah** [comment] 2023-09-27 17:33
I'm able to reproduce this issue while in virtual edit mode `:set ve=all` and after placing the cursor with no white spaces and copying the whole line.

**Comment by kaddkaka** [comment] 2023-09-27 18:38
> I'm able to reproduce this issue while in virtual edit mode `:set ve=all` and after placing the cursor with no white spaces and copying the whole line.

That's not enough for me to reproduce it. Please create a new issue with specifics.

-Neovim version 
-Minimal config file
-etc.

**Comment by jyc** [comment] 2024-02-22 01:14
I also ended up in this state on HEAD. It was especially bad because pressing ENTER just caused the error message to reappear, so I had to kill the entire Neovim process. If I find out how to repro it I'll create a minimal config file.

```
→ nvim --version
NVIM v0.10.0-dev-2201+g226466a46-Homebrew
Build type: Release
LuaJIT 2.1.1703358377
Run "nvim -V1 -v" for more info
```

```
Error in decoration provider vim_lsp_semantic_tokens.win:                                                                                                       
Error executing lua: ...6466a/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:455: Invalid 'end_col': out of range                                           
stack traceback:                                                                                                                                                
        [C]: in function 'nvim_buf_set_extmark'                                                                                                                 
        ...6466a/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:455: in function 'set_mark'                                                                 
        ...6466a/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:471: in function 'on_win'                                                                   
        ...6466a/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:799: in function <...6466a/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:796>
```

**Comment by lucario387** [comment] 2024-02-22 04:33
Please don't report LSP issues to nvim-treesitter. We don't do anything related to it

**Closed** 2024-02-22 04:34 UTC
Labels: bug, duplicate, upstream Neovim
