### ISSUE TITLE
Folds are calculated before the tree-sitter tree is updated

### ISSUE THREAD

**Issue by Snyssfx** [nvim-treesitter/nvim-treesitter#1424] opened 2021-06-24 14:00 UTC
**Describe the bug**

The bug reproduces for `json` and `go` files for me, and @akinsho said it reproduces for `lua` files as well (see [the comment](https://github.com/nvim-treesitter/nvim-treesitter/issues/1337#issuecomment-867547708))

Folds in any file disappear when the text is passed through any external program (I use it for format programs), for example `%!goimports`, `%!jq` and even `%!cat`.
**To Reproduce**

1. Open any `json` file with enabled treesitter folding, for example [using this minimal configuration and the file](https://github.com/nvim-treesitter/nvim-treesitter/issues/1337#issuecomment-864205387) from #1337
2. There you can close and open folds as usual.
3. Pass the existing file through an external program via `:%!cat<CR>`, and folding disappear, and you cannot close any folds.
4. `:write | edit` fixes the problem.

**Expected behavior**

The text in the buffer can be folded.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.5 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.3.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - gomod          ✓ . . . . 
  - yaml           ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+1433-g0d7e33bc1
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/snyssfx/.cache/yay/neovim-git/src/build/config -I/home/snyssfx/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/snyssfx/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/snyssfx/.cache/yay/neovim-git/src/build/include
Compiled by snyssfx

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
</code>
</details>

**Comment by stsewd** [comment] 2021-06-25 23:21
Looks like this also happens when you delete the whole buffer and undo:

```
gg
dG
u
```

I guess the same is done when passing the text through an external program. Looks like a problem with the cache.

**Comment by stsewd** [comment] 2021-06-26 00:55
Looks like possible a race condition or a missing update to the tree https://github.com/nvim-treesitter/nvim-treesitter/blob/5e500cbc8816d5cec7ad21398f6be2fe608583e6/lua/nvim-treesitter/fold.lua#L16-L22

That returns 0 results when being called just after the undo/external command.

**Comment by stsewd** [comment] 2021-06-26 01:48
I think this is something to do with _when_ the function is called by nvim to calculate the folds, even without the cache I'm able to reproduce the problem.

Neovim doesn't call the fold function every time a `za` and friends are called, but instead only on some situations.

- The whole buffer content is deleted
- TS is updated
- Neovim calls the fold function for the first line
- Undo is triggered
- Neovim calls the fold function for every line with TS having the old content in memory (empty buffer)
- TS is updated

That order is the root of the problem, TS should be updated before the calls to the fold function.
Another workaround is to `ddu`, that would call the fold function again with the new content.

**Comment by stsewd** [comment] 2021-06-26 01:53
This can be replicated when deleting one node (that is part of a fold) too.

- TS has the current content, with let's say 5 folds
- One fold is deleted
- Neovim calls the fold function, it has 5 folds!
- TS is updated to have 4 folds
- Undo is triggered
- Neovim calls the fold function, it has 4 folds!
- TS is updated to have 5 folds

So, the folds would end out of sync at some point when nodes that are folded are deleted.

**Comment by stsewd** [comment] 2021-06-26 02:08
So, this is probably an upstream issue, @vigoux or @bfredl may know better where to fix this.

**Comment by whereistejas** [comment] 2021-08-25 08:39
Hi, any updates on this? Has anyone found a workaround for this issue?

**Comment by akinsho** [comment] 2021-08-25 08:56
@whereistejas you should subscribe to the upstream neovim issue since the fix won't be in this repo (alone anyway). Not aware of a workaround, I just ignore the issue for now.

**Comment by Snyssfx** [comment] 2021-08-31 12:15
@whereistejas currently I store folds, apply formatters and then edit the file and restore the folds with this code:
```vim
augroup goimports_and_gofumpt
autocmd!
autocmd BufWritePre *.go mkview! | %!goimports | gofumpt
autocmd BufWritePost *.go edit | loadview
augroup END

```

**Comment by nyngwang** [comment] 2022-11-29 20:44
By calling `:edit` all existing folds will be expanded. So if you want to fix the current fold while keeping the other existing folds, you can use these lines (I put it into my own plugin) as a hot fix:

https://github.com/nyngwang/NeoClear.lua/blob/66eb9a74eb63dcc7632407fd9a1122c866f18ade/lua/neo-clear.lua#L20_L23

**Comment by lewis6991** [comment] 2023-05-17 09:58
Folds are now managed in Neovim core so closing this here.

**Closed by lewis6991** 2023-05-17 09:58 UTC
Labels: bug, upstream Neovim

**Comment by nyngwang** [comment] 2023-05-17 11:44
@lewis6991 Thank you! Does it mean that plugins like https://github.com/kevinhwang91/nvim-ufo would go deprecated?

**Comment by lewis6991** [comment] 2023-05-17 11:59
I don't know, ask the maintainer.
