### ISSUE TITLE
Highlighting Issue After Undo or Large Text Addition in Markdown Files

### ISSUE THREAD

**Issue by yuukibarns** [nvim-treesitter/nvim-treesitter#7127] opened 2024-09-08 09:47 UTC
### Describe the bug

I have encountered an issue where the syntax highlighting in Neovim occasionally fails after performing an undo operation on a large block of text or adding a significant amount of text to a Markdown file. The issue does not occur consistently, making it difficult to reproduce reliably.

### To Reproduce

1. Open a Markdown file in Neovim.
2. Add a large block of text (e.g., several paragraphs).
3. Perform an undo operation (e.g., `u` in normal mode).
4. Observe the syntax highlighting.

### Expected behavior

After performing an undo operation, the syntax highlighting should remain consistent and correctly highlight the text according to the Markdown syntax rules.
**Actual Behavior:**
The syntax highlighting of the previous paragraph or section may fail, displaying incorrect or missing highlighting.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.23.0 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.19.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.8.0-41-generic",
  sysname = "Linux",
  version = "#41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - bibtex              ✓ . ✓ ✓ ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cmake               ✓ . ✓ ✓ ✓
  - comment             ✓ . . . .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . . . ✓
  - git_rebase          ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - luap                ✓ . . . .
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - powershell          ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068
```

### Additional context

If anyone has experienced a similar issue or has any suggestions on how to resolve this, I would greatly appreciate your input.

**Comment by clason** [comment] 2024-09-08 09:58
As highlighting is completely handled by Neovim, this is out of scope here. I suspect it's a duplicate of https://github.com/neovim/neovim/issues/30184.

**Closed by clason** 2024-09-08 09:58 UTC
Labels: bug
