### ISSUE TITLE
`#set!` directive is always being applied to the 1st capture no matter what

### ISSUE THREAD

**Issue by RaafatTurki** [nvim-treesitter/nvim-treesitter#4179] opened 2023-01-19 17:35 UTC
### Describe the bug

This could be a duplicate, if so I apologize in advance.

As I understand it, it's currently not possible to conceal html class values using `/after/queries/html/highlights.scm`
```html
<!-- what I have -->
<h1 class="red"> Hi </h1>
<!-- what I want -->
<h1 class="…"> Hi </h1>
```
The following query selects the class values in the TS playground (for the `@att_val` capture)
```
(
  attribute (attribute_name) @att_name (#eq? @att_name "class")
  (quoted_attribute_value (attribute_value) @att_val)
)
```
The docs (`:h treesitter-directive-set!`) specify a first optional parameter `capture_id` and even showcases an example:
```
((identifier) @foo (#set! @foo "kind" "parameter"))
```
However it appears as though the `#set!` directive is always being applied to the 1st capture no matter what:
```
(attribute (attribute_name) @att_name (#eq? @att_name "class")
  (quoted_attribute_value (attribute_value) @att_val (#set! @att_val conceal "…")
  )
)
```
```html
<!-- what I have -->
<h1 class="red"> Hi </h1>
<!-- what I get-->
<h1 …="red"> Hi </h1>
```

### To Reproduce

Apply the above queries over the above html snippet

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.19.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "6.1.6-zen1-1-zen",
  sysname = "Linux",
  version = "#1 ZEN SMP PREEMPT_DYNAMIC Sat, 14 Jan 2023 13:09:38 +0000"
}

## Parser/Features         H L F I J
  - comment             ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - vim                 ✓ ✓ ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - bash                ✓ ✓ ✓ . ✓
  - make                ✓ . ✓ . ✓
  - cmake               ✓ . ✓ . .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - elm                 ✓ . . . ✓
  - fish                ✓ ✓ ✓ ✓ ✓
  - gdscript            ✓ ✓ . ✓ ✓
  - glsl                ✓ ✓ ✓ ✓ ✓
  - godot_resource      ✓ ✓ ✓ . .
  - gomod               ✓ . . . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - http                ✓ . . . ✓
  - java                ✓ ✓ . ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - latex               ✓ . ✓ . ✓
  - markdown            ✓ . ✓ . ✓
  - meson               ✓ . ✓ . ✓
  - nix                 ✓ ✓ ✓ . ✓
  - org                 . . . . .
  - php                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ .
  - sql                 ✓ . . . ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - help                ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . .
  - sxhkdrc             ✓ . ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - c_sharp             ✓ ✓ ✓ . ✓
  - regex               ✓ . . . .
  - svelte              ✓ . ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

### Additional context

Others seem to be facing the [same issue](https://www.reddit.com/r/neovim/comments/y1xr05/conditionally_selecting_and_concealing_in/)

**Comment by mactep** [comment] 2023-01-27 03:30
Related to #3611. 

Also, I've been trying to gather some information regarding this behaviour and I noticed that the `raw_iter` method inside `query:iter_captures` only returns a match for the first capture, which may lead to this issue.

Even if we consider the previous behaviour as intended, we still have an issue regarding the capture group attribute of the `#set!` directive. If we ran the query as shown below, the `class` name would not be concealed.

```scheme
attribute (attribute_name) @att_name (#eq? @att_name "class")
  (quoted_attribute_value (attribute_value) @att_val (#set! @att_name conceal "…")
  )
)
```

A way to fix the conceal in the previous case is to access the table inside `metadata` before returning from `iter_captures` like so:

```lua
     ...
      if not active then
        return iter() -- tail call: try next match
      end

      self:apply_directives(match, match.pattern, source, metadata)
    end
    **metadata = metadata[capture] or metadata**

    return capture, captured_node, metadata
  end
  return iter
end
...
```

It looks like we would get the "expected" behaviour if we return an `match` and get the table indexed by the capture inside `metadata`. Is the code working as intended? Otherwise, could someone guide me on what to do next? At the moment I'm trying to understand the `node_rawquery` in `treesitter.c`

**Comment by rostero1** [comment] 2023-06-10 14:32
I would really love to have the ability to conceal JSX/TSX className values in neovim.  Is this what's blocking that from happening?

**Comment by clason** [comment] 2023-12-17 17:23
https://github.com/neovim/neovim/issues/23664

This is non-trivial to fix, likely requiring a complete redesign of the function.

**Comment by clason** [comment] 2024-03-27 10:41
Fixed in #28033.

**Closed by clason** 2024-03-27 10:41 UTC
Labels: bug, upstream Neovim

**Comment by barrett-ruth** [comment] 2024-04-02 23:48
@rostero1 now that this is resolved, are you aware of any solutions fixing this? I'd love to have a class concealer as well.

**Comment by groig** [comment] 2024-04-02 23:51
@barrett-ruth i use this for heex files:

`after/queries/heex/highlights.scm`

```
;; extends
(attribute (attribute_name) @att_name (#eq? @att_name "class")
  (quoted_attribute_value (attribute_value) @att_val (#set! @att_val conceal "…")
  )
)
```

**Comment by barrett-ruth** [comment] 2024-04-03 00:46
```scm
(jsx_attribute (property_identifier) @att_name (#eq? @att_name "className")
  (string (string_fragment) @att_val (#set! @att_val conceal ".")
  )
)
```

Thanks @groig  that approached worked directly with html. 
however, it doesnt work with jsx/tsx with the above query, even though the nodes are highlighted by the query as seen below here:

<img width="1497" alt="image" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/62671086/d4aa3478-04c0-48ba-accc-a83573bf0e47">


Don't mean to spam this thread, but I'm not sure if this is an ongoing issue with implementation or something
