### ISSUE TITLE
[lua(highlights)] /usr/local/src/neovim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 1

### ISSUE THREAD

**Issue by hereGittyGitty** [nvim-treesitter/nvim-treesitter#2338] opened 2022-01-23 09:41 UTC
### Describe the bug

Syntax highlighting with `lua` files does not work anymore.
The source code in `lua` has no syntax highlighting at all, and an error message appears as a _virtual text_ on arbitrary lines. The error messages look the same as the one when executing `:checkhealth nvim-treesitter`.

### To Reproduce

1. build the latest _neovim_ from source
2. `git clone` `nvim-treesitter`
3. start _neovim_ with a minimal init file like that:
`VIMRUNTIME=/usr/local/src/neovim/runtime /usr/local/src/neovim/build/bin/nvim -u /usr/local/src/neovim_minimal_stuff/minimal_init.vim`
(adjust the paths to our freshly build _neovim_ and _minimal init_ of course)
4. invoke `:TSInstall lua`
5. invoke `:checkhealth nvim-treesitter`

You should get an error message at the appropriate line

### Expected behavior

`:checkhealth nvim-treesitter` shows no error, and opening a `lua` file shows colorful highlighting.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.2 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.13.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Gentoo 11.2.0 p1) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - c              ✓ ✓ ✓ ✓ ✓ 
  - lua            x ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: lua(highlights): /usr/local/src/neovim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 1
```

### Output of `nvim --version`

```text
NVIM v0.7.0-dev+914-g7717f38d3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by lorenz@chicken

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Additional context

my _minimal init_ file (`minimal_init.vim`) looks like this:
```
set nocompatible

set runtimepath+=/usr/local/src/neovim_minimal_stuff/nvim-treesitter

lua << EOF
require'nvim-treesitter.configs'.setup {
    highlight = {
        enable = true,
    }
}
EOF
```
Thank you very much...

**Comment by clason** [comment] 2022-01-23 09:50
Duplicate of #2295 

From your issue, it sounds like you have a plugin that is shipping with incompatible queries. (You need to use `nvim --clean` to avoid loading installed packages.)

**Closed by clason** 2022-01-23 09:50 UTC
Labels: bug

**Comment by hereGittyGitty** [comment] 2022-01-23 10:48
Yes, `nvim --clean` got me on the right track. `TSEditQuery highlights` was the command that made me find the troublemakers.

It were the _colorschemes_

- `kosmikoa.nvim`
- `zephyr-nvim`

Thanks a lot, clason. Saved the rest of my weekend.

**Comment by mxiaole** [comment] 2022-04-10 01:37
remove zephyr-nvim is useful for me
