### ISSUE TITLE
TS javascript slow on Ubuntu

### ISSUE THREAD

**Issue by OlegGulevskyy** [nvim-treesitter/nvim-treesitter#3870] opened 2022-11-25 11:52 UTC
### Describe the bug

It appears that my setup with tree-sitter is not able to process files with 1.3k lines without serious lagging.
It works great on a smaller files without any issues. It's the first time I opened such a big file and found these lags.
I am on Dell XPS with 16 Gb of ram. I had no similar issues on Macbook with M1, any files were parsed easily. Now I am working on Ubuntu, with Dell XPS mentioned earlier and facing this.
I recorded a video illustrating the issue, it's 1 minute video, I appreciate you taking your time to look at it in advance
https://webm.red/RWmn

In the video I am showing how my typing is affected with TS enabled, there is a delay of each key press about half a second. Then i switch tabs and disable tree sitter, going back to the same file - I can now type normally.
I am also showing how big the file is.

### To Reproduce

Hard to say, nothing much special. Ubuntu 22.04, pretty much clean (installed few days ago).
I'd be happy to provide anything else that you might think help
I have no idea how to troubleshoot it, I am novice with neovim unfortunately

### Expected behavior

No lags or a workaround, I guess

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.18.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - racket         ✓ . ✓ . ✓
  - v              ✓ ✓ ✓ ✓ ✓
  - scheme         ✓ . ✓ . ✓
  - bibtex         ✓ . ✓ ✓ .
  - rego           ✓ . . . ✓
  - zig            ✓ . ✓ ✓ ✓
  - embedded_template✓ . . . ✓
  - proto          ✓ . ✓ . .
  - clojure        ✓ ✓ ✓ . ✓
  - help           ✓ . . . .
  - json5          ✓ . . . ✓
  - cpp            ✓ ✓ ✓ ✓ ✓
  - pioasm         ✓ . . . ✓
  - cuda           ✓ ✓ ✓ ✓ ✓
  - hjson          ✓ ✓ ✓ ✓ ✓
  - hocon          ✓ . . . ✓
  - glsl           ✓ ✓ ✓ ✓ ✓
  - hlsl           ✓ ✓ ✓ ✓ ✓
  - dockerfile     ✓ . . . ✓
  - dot            ✓ . . . ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - fusion         ✓ ✓ ✓ ✓ .
  - markdown       ✓ . ✓ . ✓
  - gomod          ✓ . . . ✓
  - gowork         ✓ . . . ✓
  - graphql        ✓ . . ✓ ✓
  - ruby           ✓ ✓ ✓ ✓ ✓
  - perl           ✓ . ✓ . .
  - d              ✓ . ✓ ✓ ✓
  - fish           ✓ ✓ ✓ ✓ ✓
  - r              ✓ ✓ . ✓ ✓
  - make           ✓ . ✓ . ✓
  - php            ✓ ✓ ✓ ✓ ✓
  - java           ✓ ✓ . ✓ ✓
  - kotlin         ✓ ✓ ✓ . ✓
  - julia          ✓ ✓ ✓ ✓ ✓
  - jsonnet        ✓ . . . .
  - css            ✓ . ✓ ✓ ✓
  - scss           ✓ . . ✓ .
  - erlang         ✓ . ✓ . .
  - elixir         ✓ ✓ ✓ ✓ ✓
  - gleam          ✓ ✓ ✓ ✓ ✓
  - surface        ✓ . ✓ ✓ ✓
  - eex            ✓ . . . ✓
  - heex           ✓ ✓ ✓ ✓ ✓
  - ocaml          ✓ ✓ ✓ . ✓
  - ocaml_interface✓ ✓ ✓ . ✓
  - regex          ✓ . . . .
  - ocamllex       ✓ . . . ✓
  - menhir         ✓ . . . ✓
  - org            . . . . .
  - swift          ✓ ✓ . . .
  - diff           ✓ . . . .
  - todotxt        ✓ . . . .
  - typescript     ✓ ✓ ✓ ✓ ✓
  - rasi           ✓ ✓ ✓ ✓ .
  - scala          ✓ . ✓ . ✓
  - supercollider  ✓ ✓ ✓ ✓ ✓
  - norg           . . . . .
  - slint          ✓ . . ✓ .
  - haskell        ✓ . ✓ . ✓
  - json           ✓ ✓ ✓ ✓ .
  - vim            ✓ ✓ ✓ . ✓
  - vala           ✓ . ✓ . .
  - lalrpop        ✓ ✓ . . .
  - markdown_inline✓ . . . ✓
  - solidity       ✓ . . . .
  - tlaplus        ✓ ✓ ✓ . ✓
  - cooklang       ✓ . . . .
  - elvish         ✓ . . . ✓
  - astro          ✓ ✓ ✓ ✓ ✓
  - wgsl           ✓ . ✓ ✓ .
  - m68k           ✓ ✓ ✓ . ✓
  - jsonc          ✓ ✓ ✓ ✓ ✓
  - elm            ✓ . . . ✓
  - yaml           ✓ ✓ ✓ ✓ ✓
  - tiger          ✓ ✓ ✓ ✓ ✓
  - mermaid        ✓ . . . .
  - jq             ✓ . . . ✓
  - sxhkdrc        ✓ . ✓ . ✓
  - arduino        ✓ ✓ ✓ ✓ ✓
  - awk            ✓ . . . ✓
  - gitignore      ✓ . . . .
  - python         ✓ ✓ ✓ ✓ ✓
  - nickel         ✓ . . . .
  - dart           ✓ ✓ . ✓ ✓
  - gitattributes  ✓ . . . ✓
  - prisma         ✓ . . . .
  - rst            ✓ ✓ . . ✓
  - git_rebase     ✓ . . . ✓
  - fennel         ✓ ✓ . . ✓
  - commonlisp     ✓ ✓ ✓ . .
  - c              ✓ ✓ ✓ ✓ ✓
  - blueprint      ✓ . . . .
  - vue            ✓ . ✓ ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - twig           ✓ . . . ✓
  - fortran        ✓ . ✓ ✓ .
  - ledger         ✓ . ✓ ✓ ✓
  - bash           ✓ ✓ ✓ . ✓
  - pascal         ✓ ✓ ✓ ✓ ✓
  - html           ✓ ✓ ✓ ✓ ✓
  - ninja          ✓ . ✓ ✓ .
  - query          ✓ ✓ ✓ ✓ ✓
  - hcl            ✓ . ✓ ✓ ✓
  - verilog        ✓ ✓ ✓ . ✓
  - comment        ✓ . . . .
  - go             ✓ ✓ ✓ ✓ ✓
  - jsdoc          ✓ . . . .
  - tsx            ✓ ✓ ✓ ✓ ✓
  - latex          ✓ . ✓ . ✓
  - glimmer        ✓ . . . .
  - sparql         ✓ ✓ ✓ ✓ ✓
  - foam           ✓ ✓ ✓ ✓ ✓
  - teal           ✓ ✓ ✓ ✓ ✓
  - sql            ✓ . . . ✓
  - ql             ✓ ✓ ✓ ✓ ✓
  - c_sharp        ✓ ✓ ✓ . ✓
  - gdscript       ✓ ✓ . ✓ ✓
  - vhs            ✓ . . . .
  - toml           ✓ ✓ ✓ ✓ ✓
  - rnoweb         ✓ . ✓ . ✓
  - godot_resource ✓ ✓ ✓ . .
  - lua            ✓ ✓ ✓ ✓ ✓
  - yang           ✓ . ✓ ✓ .
  - llvm           ✓ . . . .
  - agda           ✓ . ✓ . .
  - turtle         ✓ ✓ ✓ ✓ ✓
  - nix            ✓ ✓ ✓ . ✓
  - devicetree     ✓ ✓ ✓ ✓ ✓
  - http           ✓ . . . ✓
  - pug            ✓ . . . ✓
  - cmake          ✓ . ✓ . .
  - svelte         ✓ . ✓ ✓ ✓
  - meson          ✓ . ✓ . ✓
  - hack           ✓ . . . .
  - qmljs          ✓ . ✓ . .
  - beancount      ✓ . ✓ . .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az178-366

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment] 2022-11-25 11:55
Duplicate of #3581

**Closed by clason** 2022-11-25 11:55 UTC
Labels: bug
