### ISSUE TITLE
query error for bash in recent neovim nightlies

### ISSUE THREAD

**Issue by gongfarmer** [nvim-treesitter/nvim-treesitter#5680] opened 2023-11-16 19:39 UTC
### Describe the bug

Opening nvim on a *.sh file (even if the file is empty or does not exist) causes an error message:

```
 Error  12:56:46 PM msg_show.lua_error    Error executing vim.schedule lua callback: ...jHC8/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:248: Query error at 9:4. Invalid node type "heredoc_end":
  (heredoc_end) @injection.language)
   ^

stack traceback:
	[C]: in function '_ts_parse_query'
	...jHC8/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:248: in function 'fn'
	...mEPjHC8/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:54: in function 'fn'
	...mEPjHC8/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:54: in function 'get'
	...r/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:132: in function 'new'
	...nvimEPjHC8/usr/share/nvim/runtime/lua/vim/treesitter.lua:64: in function '_create_parser'
	...nvimEPjHC8/usr/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser'
	...share/nvim/lazy/nvim-ts-rainbow/lua/rainbow/internal.lua:189: in function 'attach'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:118: in function 'enable_module'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:155: in function 'enable_all'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:438: in function 'accumulator'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:246: in function 'recurse_modules'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:435: in function 'setup'
	....local/share/nvim/lazy/go.nvim/lua/go/ts/textobjects.lua:12: in function 'setup'
	...a/home/fhanson/.local/share/nvim/lazy/go.nvim/lua/go.lua:224: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

When opening an actual shell script file, there is no syntax highlighting.

Additionally `:checkhealth` reports errors.

Environment:
Running nvim on debian amd64 using the nightly neovim appimage.

`:TSUpdateSync` has been run.

### To Reproduce

`nvim test.sh`

Does not matter if the test.sh file exists.
`:se filetype` in the buffer reports `filetype=sh`.

### Expected behavior

Expect no error when loading *.sh files.
Syntax highlighting should work.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.0.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Debian 10.2.1-6) 10.2.1 20210110
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.10.0-26-amd64",
  sysname = "Linux",
  version = "#1 SMP Debian 5.10.197-1 (2023-09-29)"
} ~

Parser/Features         H L F I J
  - awk                 ✓ . . . ✓
  - bash                x ✓ ✓ . x
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . . . .
  - git_config          ✓ . . . .
  - git_rebase          ✓ . . . ✓
  - gitattributes       ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . .
  - go                  ✓ ✓ ✓ ✓ ✓
  - gosum               ✓ . . . .
  - html                ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luap                ✓ . . . .
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - pem                 ✓ . ✓ . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - ruby                ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - xml                 ✓ . ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR bash(highlights): ...jHC8/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:248: Query error at 37:3. Invalid node type "":
   "<&-"
    ^
  
  bash(highlights) is concatenated from the following files:
  | [ERROR]:"/data/home/fhanson/.local/share/nvim/lazy/nvim-treesitter/queries/bash/highlights.scm", failed to load: ...jHC8/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:248: Query error at 37:3. Invalid node type "":
   "<&-"
    ^
  
- ERROR bash(injections): ...jHC8/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:248: Query error at 9:4. Invalid node type "heredoc_end":
    (heredoc_end) @injection.language)
     ^
  
  bash(injections) is concatenated from the following files:
  | [ERROR]:"/data/home/fhanson/.local/share/nvim/lazy/nvim-treesitter/queries/bash/injections.scm", failed to load: ...jHC8/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:248: Query error at 9:4. Invalid node type "heredoc_end":
    (heredoc_end) @injection.language)
     ^
```
```


### Output of `nvim --version`

```text
NVIM v0.10.0-dev-64c2c7c
Build type: RelWithDebInfo
LuaJIT 2.1.1699801871
Compilation: /usr/bin/gcc-10 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fsigned-char -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/home/runner/work/neovim/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/runner/work/neovim/neovim/.deps/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment] 2023-11-16 19:42
You need to install the bash parser if you use nightly neovim.

**Comment by gongfarmer** [comment] 2023-11-16 19:48
Additionally, `:TSModuleInfo` reports errors before showing output now, in any buffer:

```
E5108: Error executing lua ...CGAa/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:248: Query error at 22:9. Impossible pattern:
   ["/" ">"]+ @self-closing-tag-end
        ^

stack traceback:
	[C]: in function '_ts_parse_query'
	...CGAa/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:248: in function 'fn'
	...mb1CGAa/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:54: in function 'fn'
	...mb1CGAa/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:54: in function 'get_query'
	.../nvim/lazy/nvim-treesitter/lua/nvim-treesitter/query.lua:108: in function 'get_query'
	...n/.local/share/nvim/lazy/nvim-ts-rainbow/lua/rainbow.lua:8: in function 'is_supported'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:387: in function 'is_enabled'
	...e/nvim/lazy/nvim-treesitter/lua/nvim-treesitter/info.lua:91: in function 'append_module_table'
	...e/nvim/lazy/nvim-treesitter/lua/nvim-treesitter/info.lua:125: in function 'print_info_modules'
	...e/nvim/lazy/nvim-treesitter/lua/nvim-treesitter/info.lua:159: in function 'run'
	[string ":lua"]:1: in main chunk
```

**Comment by clason** [comment] 2023-11-16 19:52
Check your other plugins. If you can't reproduce this with a minimal config (which we require), that's your issue.

**Comment by gongfarmer** [comment] 2023-11-16 19:54
> You need to install the bash parser if you use nightly neovim, and make sure the nvim-treesitter queries have the same precedence on runtimepath as the parsers. This depends on how you installed this plugin.

Bash parser was installed with `:TSInstall bash`. 
Based on the output of `:TSModuleInfo`, it does seem to be installed (it has checkmarks under highlight, incremental_selection, and rainbow but not indent.)

I will pursue this angle further.  I am behind a firewall without direct internet access, only proxy servers.  It could be that `:TSInstall` is failing in a non-obvious way.

Where should downloaded tree sitter modules end up?  Somewhere under ~/.local/share/nvim/?

**Comment by gongfarmer** [comment] 2023-11-16 19:58
Runtimepath: 

/home/gongfarmer/.config/nvim
/home/gongfarmer/.local/share/nvim/lazy/lazy.nvim
/home/gongfarmer/.local/share/nvim/lazy/guihua.lua
/home/gongfarmer/.local/share/nvim/lazy/go.nvim
/home/gongfarmer/.local/share/nvim/lazy/NeoSolarized
/home/gongfarmer/.local/share/nvim/lazy/neotest-rspec
/home/gongfarmer/.local/share/nvim/lazy/neotest-plenary
/home/gongfarmer/.local/share/nvim/lazy/neotest
/home/gongfarmer/.local/share/nvim/lazy/conform.nvim
/home/gongfarmer/.local/share/nvim/lazy/lspkind-nvim
/home/gongfarmer/.local/share/nvim/lazy/cmp_luasnip
/home/gongfarmer/.local/share/nvim/lazy/cmp-cmdline
/home/gongfarmer/.local/share/nvim/lazy/cmp-path
/home/gongfarmer/.local/share/nvim/lazy/cmp-buffer
/home/gongfarmer/.local/share/nvim/lazy/cmp-nvim-lsp
/home/gongfarmer/.local/share/nvim/lazy/nvim-cmp
/home/gongfarmer/.local/share/nvim/lazy/nvim-bqf
/home/gongfarmer/.local/share/nvim/lazy/vim-abolish
/home/gongfarmer/.local/share/nvim/lazy/telescope-fzf-native.nvim
/home/gongfarmer/.local/share/nvim/lazy/nvim-colorizer.lua
/home/gongfarmer/.local/share/nvim/lazy/diffview.nvim
/home/gongfarmer/.local/share/nvim/lazy/neogit
/home/gongfarmer/.local/share/nvim/lazy/black-nvim
/home/gongfarmer/.local/share/nvim/lazy/nvim-navic
/home/gongfarmer/.local/share/nvim/lazy/nvim-osc52
/home/gongfarmer/.local/share/nvim/lazy/lualine.nvim
/home/gongfarmer/.local/share/nvim/lazy/indent-blankline.nvim
/home/gongfarmer/.local/share/nvim/lazy/plenary.nvim
/home/gongfarmer/.local/share/nvim/lazy/telescope.nvim
/home/gongfarmer/.local/share/nvim/lazy/telescope-file-browser.nvim
/home/gongfarmer/.local/share/nvim/lazy/jsonpath.nvim
/home/gongfarmer/.local/share/nvim/lazy/which-key.nvim
/home/gongfarmer/.local/share/nvim/lazy/nvim-web-devicons
/home/gongfarmer/.local/share/nvim/lazy/winbar.nvim
/home/gongfarmer/.local/share/nvim/lazy/vim-projectionist
/home/gongfarmer/.local/share/nvim/lazy/nvim-ts-rainbow
/home/gongfarmer/.local/share/nvim/lazy/neodev.nvim
/home/gongfarmer/.local/share/nvim/lazy/fidget.nvim
/home/gongfarmer/.local/share/nvim/lazy/mason-lspconfig.nvim
/home/gongfarmer/.local/share/nvim/lazy/mason.nvim
/home/gongfarmer/.local/share/nvim/lazy/nvim-lspconfig
/home/gongfarmer/.local/share/nvim/lazy/nvim-autopairs
/home/gongfarmer/.local/share/nvim/lazy/vim-startuptime
/home/gongfarmer/.local/share/nvim/lazy/jsregexp
/home/gongfarmer/.local/share/nvim/lazy/LuaSnip
/home/gongfarmer/.local/share/nvim/lazy/aerial.nvim
/home/gongfarmer/.local/share/nvim/lazy/gitsigns.nvim
/home/gongfarmer/.local/share/nvim/lazy/git-time-lapse
/home/gongfarmer/.local/share/nvim/lazy/vim-fugitive
/home/gongfarmer/.local/share/nvim/lazy/nvim-notify
/home/gongfarmer/.local/share/nvim/lazy/nui.nvim
/home/gongfarmer/.local/share/nvim/lazy/noice.nvim
/home/gongfarmer/.local/share/nvim/lazy/nvim-treesitter-textobjects
/home/gongfarmer/.local/share/nvim/lazy/nvim-treesitter
/home/gongfarmer/.local/share/nvim/lazy/gruvbox-material
/home/gongfarmer/.local/share/nvim/lazy/nvim-surround
/tmp/.mount_nvimHq03Dl/usr/share/nvim/runtime
/tmp/.mount_nvimHq03Dl/usr/lib/nvim
/home/gongfarmer/.local/share/nvim/lazy/go.nvim/after
/home/gongfarmer/.local/share/nvim/lazy/cmp_luasnip/after
/home/gongfarmer/.local/share/nvim/lazy/cmp-cmdline/after
/home/gongfarmer/.local/share/nvim/lazy/cmp-path/after
/home/gongfarmer/.local/share/nvim/lazy/cmp-buffer/after
/home/gongfarmer/.local/share/nvim/lazy/cmp-nvim-lsp/after
/home/gongfarmer/.local/share/nvim/lazy/nvim-bqf/after
/home/gongfarmer/.local/share/nvim/lazy/indent-blankline.nvim/after
/home/gongfarmer/.config/nvim/after
/home/gongfarmer/.local/state/nvim/lazy/readme


Looks healthy to me, because the treesitter dir precedes the appimage dirs:
```
/home/gongfarmer/.local/share/nvim/lazy/nvim-treesitter
...
/tmp/.mount_nvimHq03Dl/usr/share/nvim/runtime
/tmp/.mount_nvimHq03Dl/usr/lib/nvim
```

**Comment by antoineco** [comment] 2023-11-23 09:52
@gongfarmer I was running into the same error message. For some reason Neovim was showing the `bash` parser as installed, but I had to run `:TSInstall bash` manually to install it. Now the error is gone.

FYI I'm currently on https://github.com/neovim/neovim/commit/62dc1f26632fd0c915e7521a4e13a823142ec44d

> Where should downloaded tree sitter modules end up? Somewhere under ~/.local/share/nvim/?

Mine are written to `~/.local/share/nvim/lazy/nvim-treesitter/parser/`

**Comment by clason** [comment] 2023-11-23 10:03
Duplicate of #3092

**Closed by clason** 2023-11-23 10:03 UTC
Labels: bug

**Comment by RobertoMaurizzi** [comment] 2024-07-19 09:39
I had the `["/" ">"]+ @self-closing-tag-end` error using LazyVim on JS/TS/JSX files and it turned out it was caused by `nvim-ts-rainbow` (removing it avoids the problem, at least. I'm writing this because I've been searching for the reason of that error for a month and didn't find anything online)

**Comment by alexsmartens** [comment] 2024-09-11 22:17
The `["/" ">"]+ @self-closing-tag-end` error is coming from here: https://github.com/p00f/nvim-ts-rainbow/blob/ef95c15a935f97c65a80e48e12fe72d49aacf9b9/queries/jsx/parens.scm#L11

Has anyone tried to modify this file?

**Comment by RobertoMaurizzi** [comment] 2024-09-12 09:42
> Has anyone tried to modify this file?

It turned out that `nvim-ts-rainbow` has been deprecated and archived.... I replaced it with `rainbow-delimiters`
