### ISSUE TITLE
no syntax highlight in lua

### ISSUE THREAD

**Issue by aarthurddragon** [nvim-treesitter/nvim-treesitter#3774] opened 2022-11-06 11:33 UTC
### Describe the bug

no syntax highlight in lua, but other languages such as c are correctly hightlighting.

### To Reproduce

1. update nvim-treesitter plugin to the latest version. (plugin manager packer has reminded me that some breaking change may occur. After that, highlight in lua invalided. At that time, the neovim version was 0.7. )
2. update lua parser to latest version, the problem still exsits. 
3. update neovim to version 0.8, the problem still exists. 

### Expected behavior

may hightlight in lua should be correct. 

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v18.0.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `zig` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: info: Usage: zig [command] [options]
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - rust           ✓ ✓ ✓ ✓ ✓
  - help           ✓ . . . .
  - vim            ✓ ✓ ✓ . ✓
  - lua            x ✓ ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - kotlin         ✓ ✓ ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: lua(highlights): ...les\Nvim\share\nvim\runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 1141 for language lua
    lua(highlights) is concatenated from the following files:
    | [ERROR]:"C:\Users\Ar\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\lua\highlights.scm", failed to load: ...les\Nvim\share\nvim\runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 1141 for language lua
```

### Output of `nvim --version`

```text
NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az177-603

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment] 2022-11-06 13:31
Duplicate of https://github.com/nvim-treesitter/nvim-treesitter/issues/3092

**Closed by clason** 2022-11-06 13:31 UTC
Labels: bug

**Comment by aarthurddragon** [comment] 2022-11-06 13:57
sorry, I didn't notice the pinned issue, that's my problem.

**Comment by clason** [comment] 2022-11-06 14:00
I suspect that the issue is Windows-specific: For some reason, it prefers the bundled Lua parser over the one in nvim-treesitter, which the queries are written for.

**Comment by BitInByte** [comment] 2022-11-07 12:16
I'm also having this issue and even the lsp is not attaching at startup (even though the lsp info shows the correct root folder and says that it's enable to start on startup). 

It also gives me an error (E13: File exists (add ! to override)) and if I start the LSP and treesitter manually, everything works (unless the weird file exists error). Have been exploring about it and can't find a solution for this :(
