### ISSUE TITLE
ERROR: vim(highlights): ...im/0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim

### ISSUE THREAD

**Issue by Arend-Jan** [nvim-treesitter/nvim-treesitter#4008] opened 2022-12-21 18:55 UTC
### Describe the bug

I got a vanilla installation of [kickstart](https://github.com/nvim-lua/kickstart.nvim) in my `$HOME/.config/nvim/init.lua`

When I open `$HOME/.config/nvim/init.lua`, I get the following error:

```
ERROR: vim(highlights): ...im/0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
```

### To reproduce
1. Install [kickstarter](https://github.com/nvim-lua/kickstart.nvim) with de default installation steps
2. Open the init.lua `nvim ~/.config/nvim/init.lua'

### Expected behavior

No errors

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v19.3.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 14.0.0 (clang-1400.0.29.202)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "arm64",
  release = "22.2.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000"
}

## Parser/Features         H L F I J
  - lua                 ✓ ✓ ✓ ✓ ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - vim                 x ✓ ✓ . ✓
  - help                ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: vim(highlights): ...im/0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
    vim(highlights) is concatenated from the following files:
    | [ERROR]:"/Users/arend-janoosterveld/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/vim/highlights.scm", failed to load: ...im/0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
```

### Output of `nvim --version`

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.1/share/nvim"

Run :checkhealth for more info
```

### Additional context

Rerun of `:PackerInstall` or `:PackerUpdate` doesn't solve the issue

**Comment by clason** [comment] 2022-12-21 18:56
Duplicate of #3092

**Closed by clason** 2022-12-21 18:56 UTC
Labels: bug

**Comment by Arend-Jan** [comment] 2022-12-21 21:16
@clason I look at the duplicated issue and I tried al the solutions, but the didn't work. However, my problem seem te be solved by up-stepping my neovim to a nightly version instead of the latest stable on brew (v0.8.1)

**Comment by amdlemos** [comment] 2023-01-18 13:52
In your case try `:TSInstall vim` it worked for me.
