### ISSUE TITLE
Query error. Invalid node type ""

### ISSUE THREAD

**Issue by adelarsq** [nvim-treesitter/nvim-treesitter#7342] opened 2024-11-09 20:18 UTC
### Describe the bug

After https://github.com/nvim-treesitter/nvim-treesitter/commit/eab2005cb5a839abb4af9961a76bbf819650a1a9 I got some errors while using Neovim (with Noice) like `share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 9:4. Invalid node type ""`.

Workaround: Install the plugin before the commit.

### To Reproduce

1. Update for the lastest Neovim, nvim-treesitter and noice
2. Press / or ? to search for text

### Expected behavior

No error.

### Output of `:checkhealth nvim-treesitter`

```markdown
Installation ~
- OK `tree-sitter` found 0.19.5 (8d8690538ef0029885c7ef1f163b0e32f256a5aa) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.12.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 12.0.0 (clang-1200.0.32.29)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "19.6.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - dockerfile          ✓ . . . ✓
  - editorconfig        ✓ . ✓ . ✓
  - elixir              ✓ ✓ ✓ ✓ ✓
  - fennel              ✓ ✓ ✓ . ✓
  - fsharp              ✓ . . . ✓
  - git_config          ✓ . ✓ . ✓
  - gitattributes       ✓ ✓ . . ✓
  - gitignore           ✓ . . . ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - gomod               ✓ . . . ✓
  - gosum               ✓ . . . .
  - html                ✓ ✓ ✓ ✓ ✓
  - http                ✓ . . . ✓
  - ini                 ✓ . ✓ . ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - robots              ✓ . . . ✓
  - svelte              ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - v                   ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓
  - zig                 ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.11.0-dev-1116+gb7e1bbfb50
Build type: RelWithDebInfo
LuaJIT 2.1.1727870382
```

### Additional context

For some reason I can not reproduce the error on macOS. Confirmed on Windows.

**Comment by clason** [comment] 2024-11-09 20:19
Duplicate of the pinned issue. (The empty node in the error is a display issue and being worked on.)

**Comment by clason** [comment] 2024-11-09 20:20
General comment: If you need a different plugin to reproduce the issue, report it there first.

**Closed** 2024-11-09 20:19 UTC
Labels: bug
