### ISSUE TITLE
Some queries not highlighted until init.vim re-sourced

### ISSUE THREAD

**Issue by jdrouhard** [nvim-treesitter/nvim-treesitter#595] opened 2020-10-19 17:03 UTC
Not sure how wide-spread this is, but it could be a plugin loading issue. At least for my cpp files, there are some queries that have highlights that are not applied unless I manually re-source my init.vim after starting neovim. Example:

```cpp
void foo() {
    bar<int>();
}
```
In the above, the token "bar" does not receive the `@function` highlight (`TSFunction`). If I re-source my init.vim file, then "bar" starts being highlighted as a function.  The other tokens (the keyword void, "foo", the parentheses, braces, and semicolons) are all highlighted properly before the re-source.

I use vim-plug and simply have `Plug 'nvim-treesitter/nvim-treesitter'` in my list of plugins, as well as:

```
 lua <<EOF
  require'nvim-treesitter.configs'.setup {
    highlight = {
      enable = true,
    },
  }
EOF
```

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

  health#nvim_treesitter#check
  ========================================================================
  ## Installation
    - OK: git executable found.
    - OK: cc executable found.

  ## c parser healthcheck
    - OK: c parser found.
    - OK: highlights.scm found.
    - OK: locals.scm found.
    - WARNING: No textobjects.scm query found for c
      - ADVICE:
        - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
    - OK: folds.scm found.

  ## python parser healthcheck
    - OK: python parser found.
    - OK: highlights.scm found.
    - OK: locals.scm found.
    - WARNING: No textobjects.scm query found for python
      - ADVICE:
        - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
    - OK: folds.scm found.

  ## query parser healthcheck
    - OK: query parser found.
    - OK: highlights.scm found.
    - OK: locals.scm found.
    - WARNING: No textobjects.scm query found for query
      - ADVICE:
        - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
    - WARNING: No folds.scm query found for query
      - ADVICE:
        - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

  ## cpp parser healthcheck
    - OK: cpp parser found.
    - OK: highlights.scm found.
    - OK: locals.scm found.
    - WARNING: No textobjects.scm query found for cpp
      - ADVICE:
        - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
    - OK: folds.scm found.

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-763-geaee3d929
Build type: Release
LuaJIT 2.0.4
```

**Additional context**
Relevant query:
```
(template_function
  name: (identifier) @function)
```

Parsed tree of example:
```
  function_definition [0, 0] - [2, 1]
    type: primitive_type [0, 0] - [0, 4]
    declarator: function_declarator [0, 5] - [0, 10]
      declarator: identifier [0, 5] - [0, 8]
      parameters: parameter_list [0, 8] - [0, 10]
    body: compound_statement [0, 11] - [2, 1]
      expression_statement [1, 2] - [1, 13]
        call_expression [1, 2] - [1, 12]
          function: template_function [1, 2] - [1, 10]
            name: identifier [1, 2] - [1, 5]
            arguments: template_argument_list [1, 5] - [1, 10]
              type_descriptor [1, 6] - [1, 9]
                type: primitive_type [1, 6] - [1, 9]
          arguments: argument_list [1, 10] - [1, 12]
```

**Comment by kyazdani42** [comment] 2020-10-19 17:19
@vigoux could this have anything to do with the language tree impl ?

**Comment by vigoux** [comment] 2020-10-19 17:21
I highly doubt it is, as the LanguageTree landed on master just today, while this seems to be a long standing issue. Am I right ?

**Comment by jdrouhard** [comment] 2020-10-19 17:25
Actually, I think it's relatively new. I don't recall exactly when I started seeing this, but I typically pull latest master of neovim and do a `:PlugUpdate` daily. I could be mistaken; I can try to find a neovim/nvim-treesitter version pair that did work and try to bisect if you'd like.

**Comment by vigoux** [comment] 2020-10-19 17:26
Has that appeared today ? This is when the LanguageTree landed in master.

**Comment by jdrouhard** [comment] 2020-10-19 17:28
No, my nvim-treesitter checkout is still at e9b6e2d which does not include the LanguageTree feature.

**Comment by vigoux** [comment] 2020-10-19 17:33
Okay, cool, where are you putting the query you put in the report ?

**Comment by jdrouhard** [comment] 2020-10-19 17:35
For the issue description, I just copied the relevant query from the cpp query included as part of nvim-treesitter. I've done no extra configuration or manual setup of anything. I've reproduced this with vanilla nvim-treesitter and that example.

**Comment by theHamsta** [comment] 2020-10-19 18:06
Duplicate of https://github.com/nvim-treesitter/nvim-treesitter/issues/583? Does removing TSError and TSVariable help?

**Comment by jdrouhard** [comment] 2020-10-19 18:13
Interesting, adding:

```
highlight default link TSNone TSConstant
```

causes the "foo" token to highlight as a constant, so I do think this is related. Re-sourcing init.vim with the above leaves it highlighted as a constant instead of fixing it to be TSFunction, however.

**Comment by theHamsta** [comment] 2020-10-19 18:35
But what happens if you delete TSVariable in nvim-treesitter.vim or highlight.lua

**Comment by jdrouhard** [comment] 2020-10-19 18:39
That appears to fix the issue, so this definitely seems like a dup of #583.

**Closed** 2020-10-19 21:03 UTC
Labels: bug
