### ISSUE TITLE
HTML/svelte syntax highligh disappears when scrolling a large file

### ISSUE THREAD

**Issue by JS-junky** [nvim-treesitter/nvim-treesitter#1788] opened 2021-09-04 12:00 UTC
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

well as you can see the syntax highlighting for html files doesn't work properly. when opening an html file some parts of the file are just white text with no highlighting this also occurs when writing an html file, they just turn white all of a sudden and then it turns back to normal but the lines that were white stay that way and it starts to become white again regardless of the syntax error or the html you are writing.
![Screenshot_20210904_160201](https://user-images.githubusercontent.com/68812862/132093716-fa904971-3b81-4f57-b5eb-512990a65017.png)

### To Reproduce

1. open or write an html file

### Output of `:checkhealth nvim_treesitter`

```markdown
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.17.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - julia          ✓ ✓ ✓ ✓ ✓ 
  - regex          ✓ . . . . 
  - json           ✓ ✓ ✓ ✓ . 
  - css            ✓ . ✓ ✓ ✓ 
  - fortran        ✓ . ✓ ✓ . 
  - scss           ✓ . . ✓ . 
  - cmake          ✓ . ✓ . . 
  - erlang         . . . . . 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - ocaml_interface✓ ✓ ✓ . ✓ 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - scala          ✓ . ✓ . ✓ 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - glimmer        ✓ . . . . 
  - haskell        ✓ . . . ✓ 
  - hcl            ✓ . ✓ ✓ ✓ 
  - vue            ✓ . ✓ . ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - elm            . . . . . 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - yang           ✓ . ✓ . . 
  - nix            ✓ ✓ ✓ . ✓ 
  - clojure        ✓ ✓ ✓ . ✓ 
  - dart           ✓ ✓ . ✓ ✓ 
  - commonlisp     ✓ ✓ ✓ . . 
  - rst            ✓ ✓ . . ✓ 
  - fennel         ✓ ✓ . . ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - cuda           ✓ ✓ ✓ ✓ ✓ 
  - ql             ✓ ✓ . ✓ ✓ 
  - dockerfile     ✓ . . . ✓ 
  - verilog        ✓ ✓ ✓ . ✓ 
  - comment        ✓ . . . . 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - jsdoc          ✓ . . . . 
  - ledger         ✓ . ✓ ✓ ✓ 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - gomod          ✓ . . . . 
  - graphql        ✓ . . ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - zig            ✓ . ✓ ✓ ✓ 
  - bibtex         ✓ . ✓ ✓ . 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - latex          ✓ . ✓ . ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - beancount      ✓ . ✓ . . 
  - r              ✓ ✓ . . . 
  - kotlin         ✓ . . . ✓ 
  - svelte         ✓ . ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210704-5099-1dv0lhc/neovim-0.5.0/build/config -I/tmp/neovim-20210704-5099-1dv0lhc/neovim-0.5.0/src -I/home/linuxbrew/.linuxbrew/include -I/usr/include -I/tmp/neovim-20210704-5099-1dv0lhc/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210704-5099-1dv0lhc/neovim-0.5.0/build/include
Compiled by linuxbrew@e4b9819dd4f3

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/linuxbrew/.linuxbrew/Cellar/neovim/0.5.0/share/nvim"

Run :checkhealth for more info
```

**Comment by reynerdev** [comment] 2021-09-07 02:33
I have a similiar issue 

![Screenshot from 2021-09-06 01-42-16](https://user-images.githubusercontent.com/58928047/132274985-d1f88090-1bdf-4d71-a5e3-f3d21af78ac1.png)

![Screenshot from 2021-09-06 00-54-41](https://user-images.githubusercontent.com/58928047/132274975-59b0e0a8-0324-4863-9587-93c935dd1e83.png)

https://drive.google.com/file/d/1DCrs6diD4yOK220papj-z6TF8zVX_iyx/view?usp=sharing

**Comment by vigoux** [comment] 2021-09-08 16:53
Should be fixed upstream by https://github.com/neovim/neovim/pull/15316

**Comment by stsewd** [comment] 2021-09-10 17:13
@reynerdev that's the same as https://github.com/nvim-treesitter/nvim-treesitter/issues/1506

@JS-junky can you share the html file so we can test it locally? Might be the same as the other issue

**Comment by JS-junky** [comment] 2021-09-11 05:14
> @reynerdev that's the same as #1506
> 
> @JS-junky can you share the html file so we can test it locally? Might be the same as the other issue

well it's not just this html file that has this problem. it's every html file!
also github won't allow me to attach the html file here.

**Comment by stsewd** [comment] 2021-09-17 18:50
> well it's not just this html file that has this problem. it's every html file!
also github won't allow me to attach the html file here.

yeah, that's why it could be the same problem, we just need the file so we can test if it's the same problem. You can share it as a gist or codeblock.

**Comment by JS-junky** [comment] 2021-09-18 07:51
> > well it's not just this html file that has this problem. it's every html file!
> > also github won't allow me to attach the html file here.
> 
> yeah, that's why it could be the same problem, we just need the file so we can test if it's the same problem. You can share it as a gist or codeblock.

ok here's the code block:
````html

<!DOCTYPE html>
<html lang="en">
  <head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Request Metrics | Website performance monitoring, simplified. Get easy metrics and actionable alerts to make your website go faster. | Request Metrics</title>
  <meta name="description" content="Website performance monitoring, simplified. Get easy metrics and actionable alerts to make your website go faster.">
  <link rel="me" href="https://twitter.com/requestmetrics">

  <link rel="apple-touch-icon" sizes="180x180" href="/assets/images/favicon/apple-touch-icon.min.png">
  <link rel="icon" type="image.min.png" sizes="32x32" href="/assets/images/favicon/favicon-32x32.min.png">
  <link rel="icon" type="image.min.png" sizes="16x16" href="/assets/images/favicon/favicon-16x16.min.png">
  <link rel="manifest" href="/assets/images/favicon/site.webmanifest.json">

  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,700;1,400&family=Source+Code+Pro&display=auto">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Muli:wght@400;600;700&family=Poppins:wght@400;600&display=auto">
  <link rel="stylesheet" href="/assets/css/main.css">

</head>

  <body class=" index">
    <header class="site-header flex" role="banner">
  <div class="container">
    <div class="spacer"></div>
    <div class="site-logo">
      <a class="site-title" href="/">
        <img src="/assets/images/request_metrics_logo.min.png" alt="Request Metrics"/>
      </a>
    </div>
    <nav class="site-nav flex">
      <input type="checkbox" id="drawer-activator" name="drawer-activator" />
      <label for="drawer-activator" class="hamburger" title="Menu">
        <div class="icon">&#9776;</div>
      </label>
      <label for="drawer-activator" class="hamburger-close" title="Close">
        <div class="icon">&#10005;</div>
      </label>
      <div class="drawer">
        <div class="site-links flex">
        </div>
        <div class="site-cta flex">
          <a href="https://app.requestmetrics.com/" class="signin">
            <span>Log In</span>
          </a>
          <a href="https://app.requestmetrics.com/signup" class="btn btn-blue signup">
            Sign Up
          </a>
        </div>
      </div>
    </nav>
  </div>
</header>
<main class="default-layout-content" aria-label="Content">
  <section class="hero relative">
  <div class="background-wrap">
    <img class="background" src="/assets/images/illustrations/flying_sloth_2.min.png" alt="Sloth riding a rocket" />
  </div>

  <div class="container relative">
    <div class="cta">
      <h2>Faster websites for just $10/month</h2>
      <h1>Website performance monitoring</h1>
      <p>
        Web performance monitoring doesn't have to be complicated, <em>or expensive</em>.
        Get simplified performance metrics and actionable alerts to make your website go fast&mdash;without breaking your budget.
      </p>
      <div class="flex cta-buttons">
        <div class="flex-column start">
          <a class="btn btn-big btn-blue" href="https://app.requestmetrics.com/signup">
            Start Your Free Trial
          </a>
          <em class="no-credit">No credit card required</em>
        </div>
        <a class="btn btn-big btn-grey" href="https://app.requestmetrics.com/demo">
          See Live Demo
        </a>
      </div>
    </div>
  </div>
</section>

<section class="explainer">
  <div class="container">
    <h2>How It Works</h2>
    <div class="video">
      <div class="vimeo">
        <iframe src="" data-src="https://www.youtube.com/embed/NhTcdbd-zYA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>
      </div>
    </div>
  </div>
</section>

<section class="what-we-do">
  <div class="container flex">

    <div class="we-do">
      <h2>Our Features</h2>
      <ul>
        <li class="do flex">
          <img src="/assets/images/checkmark-circle.min.svg" alt="checkmark">
          <span>Real User Performance Monitoring</span>
        </li>
        <li class="do flex">
          <img src="/assets/images/checkmark-circle.min.svg" alt="checkmark">
          <span>Core Web Vital Metrics</span>
        </li>
        <li class="do flex">
          <img src="/assets/images/checkmark-circle.min.svg" alt="checkmark">
          <span>Simple Reports &amp; Alerting</span>
        </li>
        <li class="do flex">
          <img src="/assets/images/checkmark-circle.min.svg" alt="checkmark">
          <span>Predictably Affordable</span>
        </li>
      </ul>
    </div>

    <div class="we-dont">
      <h2>Their Features</h2>
      <ul>
        <li class="dont flex">
          <img src="/assets/images/xmark-circle.min.svg" alt="No checkmark">
          <span>Fake "Synthetic" Performance</span>
        </li>
        <li class="dont flex">
          <img src="/assets/images/xmark-circle.min.svg" alt="No checkmark">
          <span>Complex Query-Based Reporting</span>
        </li>
        <li class="dont flex">
          <img src="/assets/images/xmark-circle.min.svg" alt="No checkmark">
          <span>Information Overload</span>
        </li>
        <li class="dont flex">
          <img src="/assets/images/xmark-circle.min.svg" alt="No checkmark">
          <span>Unknowable Metered Pricing</span>
        </li>
      </ul>
    </div>

  </div>
</section>

<section class="callouts">
  <div class="container flex-column">

    <div class="callout flex">
      <div class="picture">
        <a href="/assets/images/callouts/callout-distribution-2400.min.png" target="_blank">
          <img src="" data-src="/assets/images/callouts/callout-distribution-2400.min.png"
            alt="Chart page views and the distribution user load time" />
        </a>
      </div>
      <div class="blurb">
        <h2>Uncover Real User Experience</h2>
        <p>
          Quickly understand how real users experience your website&apos;s performance
          for each page and API endpoint. <strong>Load Time Distribution</strong> shows you how many of
          your users are frustrated with slow performance.
        </p>
      </div>
    </div>

    <div class="callout left flex">
      <div class="picture">
        <a href="/assets/images/callouts/callout-breakdown-2400.min.png" target="_blank">
          <img src="" data-src="/assets/images/callouts/callout-breakdown-2400.min.png"
            alt="Chart page views and the distribution user load time" />
        </a>
      </div>
      <div class="blurb">
        <h2>See What's Making Your Pages Slow</h2>
        <p>
          Easily see what is slowing down your users. <strong>Page Load Breakdown</strong>
          shows you where to find opportunities to improve performance.
        </p>
      </div>
    </div>

    <div class="callout flex">
      <div class="picture">
        <a href="/assets/images/callouts/callout-webvital-2400.min.png" target="_blank">
          <img src="" data-src="/assets/images/callouts/callout-webvital-2400.min.png"
              alt="Chart page views and the distribution user load time" />
        </a>
      </div>
      <div class="blurb">
        <h2>Web Vital Performance Metrics</h2>
        <p>
          Get the whole performance picture by understanding your
          Core Web Vitals.
          See when your user&apos;s experience <strong>delayed rendering</strong>, <strong>jank</strong>, or <strong>slow interactions</strong>.
        </p>
      </div>
    </div>

  </div>
</section>


<section class="privacy">
  <div class="container">
    <div class="box flex">

      <div class="blurb" style="min-width: 0">
        <h2>Protected User Privacy</h2>
        <p>
          Request Metrics does not place cookies, store data, or capture anything
          identifiable about your website visitors. We aggregate data across useful metrics
          to give you the visibility you need, without sacrificing user privacy.
        </p>
        <p>
          <a href="/web-performance/ethical-privacy-web-analytics">Learn more about user privacy.</a>
        </p>
      </div>

      <div class="illustration">
        <img src="" data-src="/assets/images/illustrations/sloth_concerned.min.svg" alt="Sloth concerned."/>
      </div>

    </div>
  </div>
</section>

<section class="advantages">
  <div class="container flex-column">

    <div class="flex box">

      <div class="illustration">
        <h2 class="text-center">Your Website, Faster</h2>
        <img src="" data-src="/assets/images/illustrations/sloth_building_rocket.min.svg" alt="Sloth building a rocket"/>
      </div>

      <div class="advantage-list flex-column">
        <div class="advantage">
          <h3>Monitor Performance From Real Users</h3>
          <p>
            We gather metrics from <em>real users</em> visiting your website and
            aggregate their experience to show you the performance that really matters.
          </p>
        </div>
        <div class="advantage">
          <h3>Measure Your Performance Over Time</h3>
          <p>
            We rollup your performance statistics to minutes, hours, and days so you
            can understand how you compare to last week, last month, or last year.
          </p>
        </div>
        <div class="advantage">
          <h3>Know When Your Website Slows Down</h3>
          <p>
            When something is slowing down and your users are frustrated, we'll let you know
            with a detailed alert report about what's happening and the impact.
          </p>
        </div>
        <div class="advantage">
          <h3>Worth The Price</h3>
          <p>
            No suite of tools to deploy, training to attend, or budget approvals. We show you
            the most important performance metrics you need, simplified, at a price that fits
            any team's budget.
          </p>
        </div>
      </div>

    </div>

  </div>
</section>

<section class="price">
  <div class="container">
    <div class="box flex">

      <div class="cta">
        <h2>Only $10/month</h2>
        <p class="subtext">for up to 50,000 page views per month</p>

        <div class="buttons">
          <a class="btn btn-big btn-blue" href="https://app.requestmetrics.com/signup">
            Start Your Free Trial
          </a>
        </div>
      </div>

    </div>
  </div>
</section>

<section class="demo">
  <div class="container flex-column">

    <h2 class="text-center">Check Out A Live Demo</h2>
    <p class="text-center">
      You'll have to see this to believe it. View the live performance metrics for our own
      websites in Request Metrics.
    </p>
    <div class="buttons text-center">
      <a class="btn btn-big btn-blue" href="https://app.requestmetrics.com/demo">
        See Live Demo
      </a>
    </div>

  </div>
</section>

</main><footer class="site-footer">
  <div class="container flex">

    <div class="footer-about">
      <div class="footer-logo">
        <a href="/">
          <img src="" data-src="/assets/images/request_metrics_logo_dark.min.svg" alt="Request Metrics" />
        </a>
      </div>
      <div class="footer-text">
        <p>
          Request Metrics is the simplest, fastest, and most affordable way to monitor
          your website performance. We're bringing fast websites back <em>for everyone</em>.
        </p>
      </div>
      <div class="footer-social flex">
        <a href="https://www.twitter.com/RequestMetrics" title="Twitter">
          <i class="icon-twitter-squared"></i>
        </a>
        <a href="https://www.linkedin.com/showcase/request-metrics/" title="LinkedIn">
          <i class="icon-linkedin-squared"></i>
        </a>
        <a href="https://www.youtube.com/channel/UCIklNDcnPT8_eVFM1oOoQyA" title="Youtube">
          <i class="icon-youtube-squared"></i>
        </a>
      </div>
    </div>

    <div class="footer-links flex">
      <div class="footer-links-1 flex-column">

      </div>
      <div class="footer-links-2 flex-column">

      </div>
    </div>

  </div>
  <div class="container">
    <div class="legal text-center text-width">
      <p>All content appearing on this website is proprietary, copyrighted, and owned or licensed by <a href="https://trackjs.com/">TrackJS LLC</a>. Any unauthorized use of trademarks or content from this website is strictly prohibited. All rights reserved.</p>
      <p>&copy; 2019-2021 <a href="https://trackjs.com/">TrackJS LLC</a>.</p>
    </div>
  </div>

</footer>

  <script defer src="/assets/js/util/perf.js"></script>
  <script defer src="/assets/js/util/lazyloader.js"></script>
  <script defer src="/assets/js/banner.js"></script>

  <script>
    // Configuration of inline chat widget Chatty.
    // Options:
    //   open @Boolean True if chat is open on load. False if closed.
    window._chatty = { open: true };
  </script>
  <script defer src="http://localhost:3001/assets/vendor/chatty/chatty.js"></script>
  </body>
</html>

````

**Comment by reynerdev** [comment] 2021-09-18 16:42
it also happens to me with every html files

**Comment by stsewd** [comment] 2021-09-18 16:45
Okay I can confirm this is a different problem from https://github.com/nvim-treesitter/nvim-treesitter/issues/1506, or at least the solutions for https://github.com/nvim-treesitter/nvim-treesitter/issues/1506 don't solve the blank hightlights.

**Comment by reynerdev** [comment] 2021-09-18 16:57
> Okay I can confirm this is a different problem from #1506, or at least the solutions for #1506 don't solve the blank hightlights.

This happens to me

https://user-images.githubusercontent.com/58928047/133896454-20e89043-8186-433c-9a39-d65ff143f25f.mp4

**Comment by stsewd** [comment] 2021-09-18 17:08
@reynerdev that problem is https://github.com/nvim-treesitter/nvim-treesitter/issues/1506

**Comment by stsewd** [comment] 2021-10-13 02:40
Nope, this needs some debugging on the neovim side.

**Comment by theHamsta** [comment] 2021-10-13 05:12
@vigoux created a PR on upstream Tree-Sitter that might be related https://github.com/tree-sitter/tree-sitter/pull/1372

**Comment by stsewd** [comment] 2021-10-13 13:34
> @vigoux created a related PR on upstream Tree-Sitter [tree-sitter/tree-sitter#1372](https://github.com/tree-sitter/tree-sitter/pull/1372)

The PR was merged on the neovim side https://github.com/neovim/neovim/pull/15316, but it doesn't fix this problem, it fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/1506

**Comment by bushblade** [comment] 2021-10-13 15:29
I've just disabled treesitter highlighting in html for now.
```lua
  highlight = {
    enable = true,
    disable = { "html" },
  },
```

**Comment by JS-junky** [comment] 2021-11-03 11:42
@stsewd any new updates on this issue?

**Comment by charbelnicolas** [comment] 2021-11-03 15:34
https://user-images.githubusercontent.com/14960414/140092224-6b0bbb4c-4885-4603-b6c9-e894b5c9999d.mp4

**Comment by sagarreddypatil** [comment] 2021-11-18 05:24
Any update on this? I am having this problem on neovim nightly from AUR

**Comment by mark-lumbao** [comment] 2021-11-18 11:06
I am having the same issue here. What I do is I just run the command `:TSBufDisable highlight` whenever the error happens. It only occurs on large html/svelte files though. Hopefully this get fixed soon. Thanks maintainers for the hard work!

**Comment by charbelnicolas** [comment] 2021-11-30 18:16
"Please consider the experience with this plug-in as experimental until Neovim 0.6 is released!", guess us web developers will have to wait until 0.7!

**Comment by vigoux** [comment] 2021-12-02 10:38
Sorry, we forgot to change that banner, but this plugin will be stable one tree-sitter will be stable upstream, which we don't have a date for now.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by GreatestOfAllTimee** [comment] 2021-12-21 16:42
I have the same issue #2151 . Still no update yet for this issue ?

**Comment by paniash** [comment] 2021-12-30 17:55
Any updates on this?

**Comment by rodhash** [comment] 2022-01-01 18:21
> Any updates on this?

Not sure about updates but I noticed that version 0.7.0-dev seems to not suffer from this issue, I'm using for a week or so and seems to be working fine.

**Comment by paniash** [comment] 2022-01-01 18:26
> Not sure about updates but I noticed that version 0.7.0-dev seems to not suffer from this issue, I'm using for a week or so and seems to be working fine.

I am using 0.7.0-dev and do see the issue still present.

**Comment by stsewd** [comment] 2022-01-22 16:55
This may be related to this upstream bug https://github.com/neovim/neovim/issues/17170.

**Comment by dattran1232003** [comment] 2022-04-07 03:27
Hello guys, any update on this?

**Comment by kyazdani42** [comment] 2022-04-09 12:19
please see upstream, this is unrelated to nvim-treesitter itself.

**Comment by wadinj** [comment] 2022-04-17 11:06
Hello guys,

I asked in https://github.com/neovim/neovim/issues/17170 and upgrade to nvim 0.7 containing the fix ; but I still have the same issue. 

Context : 
[](https://user-images.githubusercontent.com/6746970/163271812-69062525-000c-4743-b0fb-fd7c51622951.png)

Few infos :
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3

Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}

My treesitter plugin is up to date ; with :
html [✓] installed

Terminal :
iTerm 3.4.15

nvim .config :
set termguicolors

Sometimes, when I open a big HTML file, the syntax highlighting are disabled by portion. The code is completely white and syntax highlight can comeback when I save or scroll up & down ; An example :
image

I'm using Angular so maybe some of our custom HTML tag from custom component are breaking up the syntax highlight

**Comment by dattran1232003** [comment] 2022-04-26 04:45
![image](https://user-images.githubusercontent.com/57513789/165222846-0e322be9-4f6c-463f-a5c1-6e549ea88cfc.png)

I'm on v0.8.0-dev and confirm this issue still has not been fixed.

**Comment by GreatestOfAllTimee** [comment] 2022-04-26 05:24
I guess, they still don't know what the cause is. There are several filetypes having this issue _(not just Html/Svelte)_.

**Comment by charbelnicolas** [comment] 2022-04-26 16:56
Yeah, I had to switch to VS Code for the time being to do web development as this is an annoying bug...

**Comment by fedepujol** [comment] 2022-04-26 17:03
> Yeah, I had to switch to VS Code for the time being to do web development as this is an annoying bug...

I've disable the highlight feature for HTML files... It's not perfect but at least the highlight doesn't change

**Comment by bushblade** [comment] 2022-04-26 17:28
Yeah just disable treesitter for html, the default highlighting is perfectly good.

**Comment by jgarciaokode** [comment] 2022-05-03 08:08
Any news on this? Wonder if we could help somehow

**Comment by vigoux** [comment] 2022-05-03 08:22
It is being worked on in nvim upstream at the moment.
The problem arises from multiple sources but my attempt to fix the problem is https://github.com/neovim/neovim/pull/18109

**Comment by jgarciaokode** [comment] 2022-05-03 09:03
Many thanks for the information @vigoux

**Comment by stsewd** [comment] 2022-06-27 17:17
@charbelnicolas that's your colorscheme, it's overriding the `TSText` highlight group.

**Comment by charbelnicolas** [comment] 2022-06-27 19:27
> @charbelnicolas that's your colorscheme, it's overriding the `TSText` highlight group.

Thank you, you were right!

**Comment by JoseEscobarBendezu** [comment] 2022-07-02 17:12
In neovim 0.7.2, on the left is html file with the html parser disabled, on the right with the template string in the javascript file.
[
![problema](https://user-images.githubusercontent.com/38388653/177009633-4571e357-0c77-43c2-b1a4-844b75574081.png)
](url)

I changed the template theme but the problem persists.

**Comment by vigoux** [comment] 2022-07-07 07:08
So, we have a clear view as of now about what is happening with this: the queries have limited "complexity" parameter that tunes performance things. The problem is that (from what we know) this complexity somehow is not computed correctly, and because of that seemingly simple queries / trees, will stop (showing this kind of behavior).

For reference about this issue see https://github.com/tree-sitter/tree-sitter/issues/1057

I am thus closing this as a wontfix.

**Closed by vigoux** 2022-07-07 07:08 UTC
Labels: bug
