### ISSUE TITLE
Slow on big JSON file

### ISSUE THREAD

**Issue by kuznetsss** [nvim-treesitter/nvim-treesitter#905] opened 2021-02-02 16:56 UTC
**Describe the bug**

Nvim is unusable when open big JSON file.

**To Reproduce**

Open any JSON file with size at least 350 Kb. For me the file with such size had only one line.

**Expected behavior**

Nvim works smooth with big JSON files.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## json parser healthcheck
  - OK: json parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+1062-gcc1851c9f
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/kuzns/.cache/yay/neovim-git/src/build/config -I/home/kuzns/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/kuzns/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/kuzns/.cache/yay/neovim-git/src/build/include
Compiled by kuzns@kuzns-LIN

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
</code>
</details>

**Comment by kyazdani42** [comment] 2021-02-02 18:20
duplicate of #898 i believe. @vigoux could you confirm ?

**Comment by theHamsta** [comment] 2021-02-02 18:24
We should really tackle the duplicate queries. Probably not the only problem but double the highlights could account for double latency

**Comment by stsewd** [comment] 2021-02-06 22:41
Closing as duplicate of #898, I've hit this as well with minimized js files, makes the editor unresponsive for some minutes

**Closed by stsewd** 2021-02-06 22:41 UTC
Labels: bug, duplicate

**Comment by xavierlesa** [comment] 2025-02-08 14:57
I know this issue is closed, but I'm still having the same problem, even with small `JSON` files. 
In my case, I’ve noticed that unformatted `JSON` files are very slow, so I found a simple workaround: preformatting with `jq`.

Here’s my approach:

```lua
-- preformat json with jq
vim.api.nvim_create_autocmd({"BufReadPost", "BufWritePost"}, {
  pattern = "*.json",
  command = ":%!jq ."
})
```
