### ISSUE TITLE
Query: invalid structure at position 1288 for language go

### ISSUE THREAD

**Issue by sergii4** [nvim-treesitter/nvim-treesitter#5273] opened 2023-08-17 10:26 UTC
### Describe the bug

Nvim tree-sitter doesn't work in neotest plugin [adapter](https://github.com/nvim-neotest/neotest-go):
> query: invalid structure at position 1288 for language go
            stack traceback:
                [C]: in function '_ts_parse_query'
                ...-d0d132f/share/nvim/runtime/lua/vim/treesitter/query.lua:277: in function 'parse_query'
                ...packer/start/neotest/lua/neotest/lib/treesitter/init.lua:104: in function 'normalise_query'
                ...packer/start/neotest/lua/neotest/lib/treesitter/init.lua:161: in function 'parse_positions_from_string'
                ...packer/start/neotest/lua/neotest/lib/treesitter/init.lua:207: in function 'discover_positions'
                ...acker/start/neotest-go/lua/spec/neotest-go/init_spec.lua:45: in function <...acker/start/neotest-go/lua/spec/neotest-go/init_spec.lua:43>

### To Reproduce

1. Install [neotest-go](https://github.com/nvim-neotest/neotest-go#installation)
2. Go to test [file](https://github.com/nvim-neotest/neotest-go/blob/main/lua/spec/neotest-go/init_spec.lua) 
3. Run [plenary](https://github.com/nvim-lua/plenary.nvim) test `nmap <leader>t <Plug>PlenaryTestFile`

### Expected behavior

Tests execute successfully

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v16.20.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "22.5.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - fish                ✓ ✓ ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-2219+gfb78c1983-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3
```

### Additional context

<details>
<summary> Tree-sitter query itself</summary>

[Link](https://github.com/nvim-neotest/neotest-go/blob/main/lua/neotest-go/init.lua#L52C1-L133C60)

```
;;query
((function_declaration
  name: (identifier) @test.name)
  (#match? @test.name "^(Test|Example)"))
  @test.definition

(method_declaration
  name: (field_identifier) @test.name
  (#match? @test.name "^(Test|Example)")) @test.definition

(call_expression
  function: (selector_expression
    field: (field_identifier) @test.method)
    (#match? @test.method "^Run$")
  arguments: (argument_list . (interpreted_string_literal) @test.name))
  @test.definition

;; query for list table tests
    (block
      (short_var_declaration
        left: (expression_list
          (identifier) @test.cases)
        right: (expression_list
          (composite_literal
            (literal_value
              (literal_element
                (literal_value
                  (keyed_element
                    (literal_element
                      (identifier) @test.field.name)
                    (literal_element
                      (interpreted_string_literal) @test.name)))) @test.definition))))
      (for_statement
        (range_clause
          left: (expression_list
            (identifier) @test.case)
          right: (identifier) @test.cases1
            (#eq? @test.cases @test.cases1))
        body: (block
          (call_expression
            function: (selector_expression
              field: (field_identifier) @test.method)
              (#match? @test.method "^Run$")
            arguments: (argument_list
              (selector_expression
                operand: (identifier) @test.case1
                (#eq? @test.case @test.case1)
                field: (field_identifier) @test.field.name1
                (#eq? @test.field.name @test.field.name1)))))))

;; query for map table tests 
	(block
      (short_var_declaration
        left: (expression_list
          (identifier) @test.cases)
        right: (expression_list
          (composite_literal
            (literal_value
              (keyed_element
            	(literal_element
                  (interpreted_string_literal)  @test.name)
                (literal_element
                  (literal_value)  @test.definition))))))
	  (for_statement
       (range_clause
          left: (expression_list
            ((identifier) @test.key.name)
            ((identifier) @test.case))
          right: (identifier) @test.cases1
            (#eq? @test.cases @test.cases1))
	      body: (block
            (call_expression
              function: (selector_expression
                field: (field_identifier) @test.method)
                (#match? @test.method "^Run$")
                arguments: (argument_list
                ((identifier) @test.key.name1
                (#eq? @test.key.name @test.key.name1)))))))
```

</details>

`echo nvim_get_runtime_file('parser', v:true)` returns:

```
['/Users/user/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser']
```

**Comment by clason** [comment] 2023-08-17 10:27
Duplicate of #3092

This is a neotest issue, not nvim-treesitter. Always report for the most downstream component.

**Closed by clason** 2023-08-17 10:27 UTC
Labels: bug

**Comment by sergii4** [comment] 2023-08-17 10:46
@clason I'm sorry how is it neotest issue? There are nothing changed in neotest related to parsers, queries

**Comment by clason** [comment] 2023-08-17 11:01
That's the problem; they have to to keep compatible with parser changes.

**Comment by clason** [comment] 2023-09-09 13:00
Gotta ask with neotest(-go), then.

**Comment by sergii4** [comment] 2023-09-09 18:53
I am a maintainer in neotest-go which is used by neotest. What ask for? What changes has been made?

**Comment by clason** [comment] 2023-09-09 19:05
If you ship tree-sitter queries, you need to keep them up-to-date with the parsers provided by this repo.

**Comment by sergii4** [comment] 2023-09-09 19:23
How I can keep them update? Are there any linters? How has query language changed? Could you please enlighten me?

**Comment by clason** [comment] 2023-09-09 19:47
No, sorry, it is up to you to keep up with parser changes if you provide queries.
