### ISSUE TITLE
"Error in decoration provider treesitter/highlighter.win" inescapable error opening LaTeX files on Ubuntu

### ISSUE THREAD

**Issue by MMachado05** [nvim-treesitter/nvim-treesitter#6880] opened 2024-07-07 13:06 UTC
### Describe the bug

Exclusively when opening a LaTeX file, I get an error appearing in a bottom split window of my NeoVim instance telling me there's a query error with a pretty long stacktrace. I've tested opening python files, java files, and markdown files, and everything works fine. The issue even persists when opening a newly-created (by trying to open a non-existent) LaTeX file. I would provide the stacktrace in full, but I'm not sure where to find where it's printed out, so I'll just be using the one I can see (which unfortunately truncates some stuff).

I had been using the AppImage until I realized that running it was making a second parser in my `/tmp/` directory (created at runtime, so immpossible to delete), so I deleted that and used the tarball instead, but the issue persists.

I also have VimTex, but I've never had a problem with that plugin before. I thought this was only happening with the new version of NeoVim, but even going back to 0.9.5 (last functioning version), I'm still getting errors and no syntax highlighting.)

Below is the error, or at least what I can see of it. No matter how many times I press "Enter," it just keeps showing. Please let me know if there's a more complete version in some log file somewhere so I can provide it!

```text
Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...-linux64/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 8:6. Invalid node type "":
    "\\shortintertext"
     ^

stack traceback:
        [C]: in function '_ts_parse_query'
        ...-linux64/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
        ...vim-linux64/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
        ...vim-linux64/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
        ...64/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
        ...64/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:240: in function 'get_query'
        ...64/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:188: in function 'fn'
        ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
        ...64/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:175: in function 'prepare_highlight_states'
        ...64/share/nvim/runtime/lua/vim/treesitter/highlig
```

That's where the stacktrace cuts off.

### To Reproduce

1. Install Neovim 0.10.0
2. Install nvim-treesitter
3. Install vimtex
4. Open a LaTeX file

### Expected behavior

It opens, showing treesitter-assisted syntax highlighting

### Output of `:checkhealth nvim-treesitter`

```text
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v12.22.9 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.5.0-41-generic",
  sysname = "Linux",
  version = "#41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - diff                ✓ . . . ✓
  - gitignore           ✓ . . . ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - xml                 ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM V0.10.0
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

**Comment by clason** [comment] 2024-07-07 13:08
Duplicate of #3092

**Closed by clason** 2024-07-07 13:08 UTC
Labels: bug

**Comment by clason** [comment] 2024-07-07 13:09
> Install vimtex

If you use VimTeX, don't install the LaTeX parser since that will disable a bunch of useful VimTeX features (and give you worse highlighting than VimTeX's _very_ extensive syntax files).

**Comment by im-n1** [comment] 2024-07-11 13:52
Uninstalling `latex` treesitter highlighter solved my issue - `TSUninstall latex`.
