### ISSUE TITLE
Ruby indent incorrectly with hanging class methods

### ISSUE THREAD

**Issue by b-sep** [nvim-treesitter/nvim-treesitter#4745] opened 2023-05-01 17:44 UTC
### Describe the bug

on the left im using indent enabled as true, on the right as false, it should behave like that?

[Screencast from 2023-05-01 13-58-41.webm](https://user-images.githubusercontent.com/65205717/235494947-245f3e86-324a-4aca-9af3-aa4fddc19347.webm)

### To Reproduce

Just create a ruby file and write a simple class.

### Expected behavior

i expected that the indentation to stay the same when i tip self. something

### Output of `:checkhealth nvim-treesitter`

```markdown
Installation
  tree-sitter found 0.20.8 (0c49d6745b3fc4822ab02e0018770cd6383a779c) (parser generator, only needed for :TSInstallFromGrammar)
  node found v18.12.1 (only needed for :TSInstallFromGrammar)
  git executable found.
  OK cc executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 12.2.0-17ubuntu1) 12.2.0
  Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.
```

### Output of `nvim --version`

```text
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by lucario387** [comment] 2023-05-09 01:57
Yes, that's a bug.

**Comment by chikcne** [comment] 2023-05-10 14:32
Perhaps we could rename this issue to be more descriptive? It is a pretty big bug affecting lots of users after all.

**Comment by lucario387** [comment] 2023-05-10 14:39
This probably? require an upstream change, as it recognizes `x.end` as the func (or not, haven't check)

**Comment by b-sep** [comment] 2023-05-10 16:27
yep, it recognizes .end as a method called on self

**Comment by lucario387** [comment] 2023-05-10 16:30
One-off-ing this case only I fear will cause issues elsewhere. Will try to compromise somehow. But most likely, having parser changes will be easier

**Comment by dgmora** [comment] 2023-05-14 09:03
There's an existing issue about that https://github.com/nvim-treesitter/nvim-treesitter/issues/3363, would be great to be able to use treesitter indent with ruby 🙏

**Comment by theHamsta** [comment] 2023-05-14 13:37
Closing as duplicate of #3363

**Closed by theHamsta** 2023-05-14 13:37 UTC
Labels: bug, indent
