### ISSUE TITLE
Treesitter error in help file

### ISSUE THREAD

**Issue by kaddkaka** [nvim-treesitter/nvim-treesitter#6396] opened 2024-04-03 20:28 UTC
### Describe the bug

When I open a help page I get a treesitter error.

### To Reproduce

`:help` in `nvim 0.9.1` or `nvim 0.9.5`

### Expected behavior

No Errors

### Output of `:checkhealth nvim-treesitter`

```markdown
The following errors have been detected:
- ERROR vimdoc(highlights): ...BG7Z/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 615 for language vimdoc
  vimdoc(highlights) is concatenated from the following files:
  | [ERROR]:"/home/kaddkaka/.local/share/nvim/plugged/nvim-treesitter/queries/vimdoc/highlights.scm", failed to load: ...BG7Z/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at
  position 615 for language vimdoc
```
```


### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```
```


### Additional context

I tried with latest nvim-treesitter and the one tagged `v0.9.2` but got the same behavior.

**Comment by kaddkaka** [comment] 2024-04-03 20:29
`:checkhealth vim.treesitter` shows this error:

```
- ERROR Parser "help" failed to load (path:
  /home/kaddkaka/.local/share/nvim/plugged/nvim-treesitter/parser/help.so): Failed to load parser: uv_dlsym: /home/kaddkaka/.local/share/nvim/plugged/nvim-treesitter/parser/
help.so: undefined symbol: tree_sitter_help
```

**Comment by kaddkaka** [comment] 2024-04-03 20:35
This might me an nvim AppImage (I'm not sure, but maybe), if I try to `:TSUninstall lua` I get this error:

```
Parser for lua is installed! But not by nvim-treesitter! Please manually remove the following files: 
/tmp/.mount_nvimGRP9iq/usr/lib/nvim/parser/lua.so
```

And looking in that folder shows:
```console
$ ls /tmp/.mount_nvimGRP9iq/usr/lib/nvim/parser/
c.so  lua.so  query.so  vimdoc.so  vim.so
```

**Comment by clason** [comment] 2024-04-03 20:36
Duplicate of #3092

**Comment by clason** [comment] 2024-04-03 20:37
Duplicate of #3587

**Closed by clason** 2024-04-03 20:36 UTC
Labels: bug

**Comment by kaddkaka** [comment] 2024-04-03 21:38
What is the solution? I couldnt really tell from that issue.

**Comment by clason** [comment] 2024-04-03 21:41
Delete and reinstall; make sure you have a valid build environment.

**Comment by kaddkaka** [comment] 2024-04-03 21:41
Delete what?

**Comment by clason** [comment] 2024-04-03 21:42
The parser and, if needed, the plugin. (If you're using Nix, you're on your own.)

**Comment by kaddkaka** [comment] 2024-04-03 21:43
I'm om Ubuntu and AppImage (I think), what should I delete more specifically. Where are the parsers?

**Comment by clason** [comment] 2024-04-03 21:45
I would wipe everything, to be honest; something is messed up (stray/incompatible parsers somewhere on your runtimepath). Please read the pinned issue about "invalid node" and follow the steps.

**Comment by kaddkaka** [comment] 2024-04-03 22:25
How to perform this step?

> If the error persists, remove nvim-treesitter completely and reinstall it together with all parsers.

**Comment by kaddkaka** [comment] 2024-04-04 06:00
Should I go through all paths in runtimepath and `rm -rf queries` ? For example `/usr/local/share/nvim/runtime`

**Comment by kaddkaka** [comment] 2024-04-04 06:09
I think both `nvim 0.9.5` and `nvim 0.10.0` were using the path `/usr/local/share/nvim/runtime`.

doing a `make install` when building the 0.10 version seems to have fixed the above issue.

**Comment by clason** [comment] 2024-04-04 07:50
> I think both nvim 0.9.5 and nvim 0.10.0 were using the path /usr/local/share/nvim/runtime.

Yes, that will completely mess things up (and is impossible to diagnose from outside).
