### ISSUE TITLE
HTML parser not working. all parser working right but html parser not

### ISSUE THREAD

**Issue by Kebabrock0** [nvim-treesitter/nvim-treesitter#4254] opened 2023-02-01 12:03 UTC
### Describe the highlighting problem

I am using nvim-treesitter for html but i don't know why only html parser not working 

![image](https://user-images.githubusercontent.com/97029034/216036059-a991f77b-a98e-4520-9713-a9c933b458fd.png)

### Example snippet that causes the problem

Error detected while processing function <SNR>60_NetrwBrowseChgDir[197]..BufReadPost Autocommands for "*":
Error executing lua callback: C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:22: Error executing lua: C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:23: Vim(append):Error executing lua callback: Failed to load parser: uv_dlopen: The specified procedure could not be found.

stack traceback:
        [C]: in function '_ts_add_language'
        ...eovim\share\nvim\runtime/lua/vim/treesitter/language.lua:36: in function 'require_language'
        ...s\Neovim\share\nvim\runtime/lua/vim/treesitter/query.lua:213: in function 'get_query'
        ...cker\start\nvim-treesitter/lua/nvim-treesitter/query.lua:104: in function 'get_query'
        ...a\site\pack\packer\start\nvim-ts-rainbow/lua/rainbow.lua:26: in function 'is_supported'
        ...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:385: in function 'is_enabled'
        ...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:503: in function 'attach_module'
        ...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:528: in function 'reattach_module'
        ...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:131: in function <...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:130>
        [C]: in function 'nvim_cmd'
        C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:23: in function <C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:22: in function <C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:11>
stack traceback:
        [C]: in function 'nvim_cmd'
        C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:23: in function <C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:22: in function <C:\Program Files\Neovim\share\nvim\runt

### Tree-sitter parsing result

Error executing Lua callback: ...t\playground/lua/nvim-treesitter-playground/internal.lua:643: Vim(append):Error executing lua callback: Failed to load parser: uv_dlopen: The specified procedure could not be found.

stack traceback:
        [C]: in function '_ts_add_language'
        ...eovim\share\nvim\runtime/lua/vim/treesitter/language.lua:36: in function 'require_language'
        ...m Files\Neovim\share\nvim\runtime/lua/vim/treesitter.lua:38: in function '_create_parser'
        ...m Files\Neovim\share\nvim\runtime/lua/vim/treesitter.lua:96: in function 'get_parser'
        ...rt\playground/lua/nvim-treesitter-playground/printer.lua:99: in function 'process'
        ...t\playground/lua/nvim-treesitter-playground/internal.lua:693: in function 'update'
        ...t\playground/lua/nvim-treesitter-playground/internal.lua:205: in function <...t\playground/lua/nvim-treesitter-playground/internal.lua:204>
        [C]: in function 'cmd'
        ...t\playground/lua/nvim-treesitter-playground/internal.lua:643: in function 'open'
        ...t\playground/lua/nvim-treesitter-playground/internal.lua:670: in function 'toggle'
        ...r\start\playground\plugin\nvim-treesitter-playground.lua:17: in function <...r\start\playground\plugin\nvim-treesitter-playground.lua:16>
stack traceback:
        [C]: in function 'cmd'
        ...t\playground/lua/nvim-treesitter-playground/internal.lua:643: in function 'open'
        ...t\playground/lua/nvim-treesitter-playground/internal.lua:670: in function 'toggle'
        ...r\start\playground\plugin\nvim-treesitter-playground.lua:17: in function <...r\start\playground\plugin\nvim-treesitter-playground.lua:16>

### Example screenshot

![image](https://user-images.githubusercontent.com/97029034/216036434-540cbb4d-8105-484d-8e5e-c5e5908385d3.png)

![image](https://user-images.githubusercontent.com/97029034/216036633-046cada5-ddb0-410b-8f81-dfe532fc8767.png)

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v19.2.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Rev10, Built by MSYS2 project) 12.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "10.0.19044",
  sysname = "Windows_NT",
  version = "Windows 10 Pro"
}

## Parser/Features         H L F I J
  - help                ✓ . . . ✓
  - scheme              ✓ . ✓ . ✓
  - json5               ✓ . . . ✓
  - rego                ✓ . . . ✓
  - clojure             ✓ ✓ ✓ . ✓
  - commonlisp          ✓ ✓ ✓ . .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - cuda                ✓ ✓ ✓ ✓ ✓
  - elsa                ✓ . . . .
  - glsl                ✓ ✓ ✓ ✓ ✓
  - hlsl                ✓ ✓ ✓ ✓ ✓
  - dockerfile          ✓ . . . ✓
  - dot                 ✓ . . . ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - fsh                 ✓ . . . .
  - fusion              ✓ ✓ ✓ ✓ .
  - ledger              ✓ . ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - ruby                ✓ ✓ ✓ ✓ ✓
  - gomod               ✓ . . . ✓
  - gowork              ✓ . . . ✓
  - graphql             ✓ . . ✓ ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ . ✓ ✓
  - kdl                 ✓ . ✓ . .
  - jsonnet             ✓ . . . .
  - css                 ✓ . ✓ ✓ ✓
  - diff                ✓ . . . .
  - scss                ✓ . ✓ ✓ .
  - erlang              ✓ . ✓ . .
  - llvm                ✓ . . . .
  - http                ✓ . . . ✓
  - gleam               ✓ ✓ ✓ ✓ ✓
  - prisma              ✓ . . . .
  - make                ✓ . ✓ . ✓
  - eex                 ✓ . . . ✓
  - rasi                ✓ ✓ ✓ ✓ .
  - ocaml               ✓ ✓ ✓ . ✓
  - json                ✓ ✓ ✓ ✓ .
  - vim                 ✓ ✓ ✓ . ✓
  - hack                ✓ . . . .
  - ocamllex            ✓ . . . ✓
  - menhir              ✓ . . . ✓
  - vala                ✓ . ✓ . .
  - swift               ✓ ✓ . . .
  - lalrpop             ✓ ✓ . . ✓
  - solidity            ✓ . . . .
  - elvish              ✓ . . . ✓
  - smali               ✓ . . . ✓
  - smithy              ✓ . . . .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - haskell             ✓ . ✓ . ✓
  - hcl                 ✓ . ✓ ✓ ✓
  - terraform           ✓ . ✓ ✓ ✓
  - thrift              ✓ . ✓ . .
  - markdown_inline     ✓ . . . ✓
  - tiger               ✓ ✓ ✓ ✓ ✓
  - t32                 ✓ ✓ ✓ . ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - sxhkdrc             ✓ . ✓ . ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - v                   ✓ ✓ ✓ ✓ ✓
  - pug                 ✓ . . . ✓
  - gitattributes       ✓ . . . ✓
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - elm                 ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - markdown            ✓ . ✓ . ✓
  - yang                ✓ . ✓ ✓ ✓
  - zig                 ✓ . ✓ ✓ ✓
  - git_rebase          ✓ . . . ✓
  - nix                 ✓ ✓ ✓ . ✓
  - awk                 ✓ . . . ✓
  - htmldjango          ✓ . ✓ ✓ ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - jq                  ✓ . . . ✓
  - rst                 ✓ ✓ . . ✓
  - mermaid             ✓ . . . .
  - fennel              ✓ ✓ ✓ . ✓
  - ebnf                ✓ . . . .
  - arduino             ✓ ✓ ✓ ✓ ✓
  - todotxt             ✓ . . . .
  - ql                  ✓ ✓ ✓ ✓ ✓
  - twig                ✓ . . . ✓
  - blueprint           ✓ . . . .
  - nickel              ✓ . . . .
  - gitignore           ✓ . . . .
  - proto               ✓ . ✓ . .
  - phpdoc              ✓ . . . .
  - m68k                ✓ ✓ ✓ . ✓
  - wgsl_bevy           ✓ . ✓ ✓ .
  - wgsl                ✓ . ✓ ✓ .
  - comment             ✓ . . . .
  - capnp               ✓ . ✓ . .
  - jsdoc               ✓ . . . .
  - slint               ✓ . . ✓ .
  - supercollider       ✓ ✓ ✓ ✓ ✓
  - bash                ✓ ✓ ✓ . ✓
  - sparql              ✓ ✓ ✓ ✓ ✓
  - hocon               ✓ . . . ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . . ✓
  - glimmer             ✓ . . . .
  - scala               ✓ . ✓ . ✓
  - gdscript            ✓ ✓ . ✓ ✓
  - fish                ✓ ✓ ✓ ✓ ✓
  - latex               ✓ . ✓ . ✓
  - godot_resource      ✓ ✓ ✓ . .
  - foam                ✓ ✓ ✓ ✓ ✓
  - julia               ✓ ✓ ✓ ✓ ✓
  - kotlin              ✓ ✓ ✓ . ✓
  - c_sharp             ✓ ✓ ✓ . ✓
  - turtle              ✓ ✓ ✓ ✓ ✓
  - vhs                 ✓ . . . .
  - ini                 ✓ . ✓ . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - surface             ✓ . ✓ ✓ ✓
  - elixir              ✓ ✓ ✓ ✓ ✓
  - heex                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - ada                 ✓ ✓ ✓ . .
  - ocaml_interface     ✓ ✓ ✓ . ✓
  - rnoweb              ✓ . ✓ . ✓
  - svelte              ✓ . ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - verilog             ✓ ✓ ✓ . ✓
  - bibtex              ✓ . ✓ ✓ .
  - html                x x x x x
  - meson               ✓ . ✓ . ✓
  - r                   ✓ ✓ . ✓ ✓
  - qmljs               ✓ . ✓ . .
  - pioasm              ✓ . . . ✓
  - cmake               ✓ . ✓ . .
  - racket              ✓ . ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: html(highlights): Failed to load parser: uv_dlopen: The specified procedure could not be found.
    
    html(highlights) is concatenated from the following files:
    | [ERROR]:"C:\Users\muham\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html_tags\highlights.scm", failed to load: Failed to load parser: uv_dlopen: The specified procedure could not be found.
    
    | [ERROR]:"C:\Users\muham\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html\highlights.scm", failed to load: Failed to load parser: uv_dlopen: The specified procedure could not be found.
  - ERROR: html(locals): Failed to load parser: uv_dlopen: The specified procedure could not be found.
    
    html(locals) is concatenated from the following files:
    | [ERROR]:"C:\Users\muham\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html\locals.scm", failed to load: Failed to load parser: uv_dlopen: The specified procedure could not be found.
  - ERROR: html(folds): Failed to load parser: uv_dlopen: The specified procedure could not be found.
    
    html(folds) is concatenated from the following files:
    | [ERROR]:"C:\Users\muham\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html\folds.scm", failed to load: Failed to load parser: uv_dlopen: The specified procedure could not be found.
  - ERROR: html(indents): Failed to load parser: uv_dlopen: The specified procedure could not be found.
    
    html(indents) is concatenated from the following files:
    | [ERROR]:"C:\Users\muham\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html_tags\indents.scm", failed to load: Failed to load parser: uv_dlopen: The specified procedure could not be found.
    
    | [ERROR]:"C:\Users\muham\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html\indents.scm", failed to load: Failed to load parser: uv_dlopen: The specified procedure could not be found.
  - ERROR: html(injections): Failed to load parser: uv_dlopen: The specified procedure could not be found.
    
    html(injections) is concatenated from the following files:
    | [ERROR]:"C:\Users\muham\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html_tags\injections.scm", failed to load: Failed to load parser: uv_dlopen: The specified procedure could not be found.
    
    | [ERROR]:"C:\Users\muham\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html\injections.scm", failed to load: Failed to load parser: uv_dlopen: The specified procedure could not be found.
```

### Output of `nvim --version`

```text
NVIM v0.8.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az28-353

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment] 2023-02-01 14:31
I think the problem is your (compiler) setup, not the parser.

**Comment by Kebabrock0** [comment] 2023-02-01 14:37
![image](https://user-images.githubusercontent.com/97029034/216072509-f02ab1c6-d02b-4165-905f-f50334405421.png)
 
still giving the same error

**Comment by clason** [comment] 2023-02-01 14:39
Must be Windows specific, then; I can't reproduce that. (But make sure you don't have any _other_ html parsers lying around; the `vim.treesitter` health check will tell you.)

**Comment by clason** [comment] 2023-02-01 14:40
Duplicate of #3587

**Closed by clason** 2023-02-01 14:40 UTC
Labels: platform Windows

**Comment by Kebabrock0** [comment] 2023-02-01 21:33
I uninstall nvim with all features and reinstall that fixed my problem
