### ISSUE TITLE
Lua highlighting stopped and make nvim crash

### ISSUE THREAD

**Issue by melsiir** [nvim-treesitter/nvim-treesitter#2299] opened 2022-01-19 14:19 UTC
### Describe the bug

I just updated treesitter and Lua treesitter parser and no lw the highlighting is not working in Lua only but in other languages it work fine when I disabled Lua treesitter highlights I got no error but when enabled the error shows and will I am editing my Lua file I got this annoying error in all my lines  :

ensure_installed = { treesitter/highlighter: Error executing lua: ...iles/usr/share/nvim/runt

And when I ignore this error I got this too:

E5108: Error executing lua ...iles/usr/share/nvim/runtime/l
ua/vim/treesitter/query.lua:161: query: invalid node type a
t position 1
stack traceback:
        [C]: in function '_ts_parse_query'
        ...iles/usr/share/nvim/runtime/lua/vim/treesitter/q
uery.lua:161: in function 'get_query'
        ...sr/share/nvim/runtime/lua/vim/treesitter/highlig
hter.lua:98: in function 'new'                                     ...sr/share/nvim/runtime/lua/vim/treesitter/highlig
hter.lua:223: in function 'get_query'
        ...m-matchup/lua/treesitter-matchup/third-party/hl-
info.lua:31: in function 'fn'
        ...r/share/nvim/runtime/lua/vim/treesitter/language
tree.lua:194: in function 'for_each_tree'
        ...m-matchup/lua/treesitter-matchup/third-party/hl-info.lua:22: in function 'get_treesitter_hl'
        ...packer/opt/vim-matchup/lua/treesitter-matchup/syntax.lua:83: in function 'synID'                                   [string "luaeval()"]:1: in main chunk

### To Reproduce

Just update the Lua parser and treesitter
Open and Lua file and start scrolling and the error will keep showing

### Expected behavior

Everything should work fine

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v17.3.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: clang version 13.0.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - dot            ✓ . . . ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - vim            ✓ ✓ . . ✓ 
  - scss           ✓ . . ✓ . 
  - lua            x ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - dockerfile     ✓ . . . ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: lua(highlights): ...iles/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 1
```

### Output of `nvim --version`

```text
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builder@56072df56e66

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/data/data/com.termux/files/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment] 2022-01-19 14:23
Duplicate of https://github.com/nvim-treesitter/nvim-treesitter/issues/2295 (please subscribe to the pinned issue to be notified of breaking changes).

**Closed by clason** 2022-01-19 14:23 UTC
Labels: bug
