### ISSUE TITLE
Inconsistent Commenting Behavior for Markdown Files

### ISSUE THREAD

**Issue by yuukibarns** [nvim-treesitter/nvim-treesitter#7183] opened 2024-09-26 13:17 UTC
### Describe the bug

When opening a Markdown file in Neovim and attempting to comment a line using the `gc` command, the commenting behavior appears to be inconsistent and changeable. Specifically, the comment format alternates between the expected HTML comment (`<!--%s-->`) and a hash-style comment (`# %s`), even though the `commentstring` is consistently set to the default `<!--%s-->`.

https://github.com/user-attachments/assets/db5ca765-6bb0-44a5-83fe-49d5401acad4

Here is my minimal configuration:
```lua
local path = "~/nvim-treesitter"
vim.opt.rtp:prepend(path)

require("nvim-treesitter.configs").setup({
	modules = {},
	sync_install = false,
	ignore_install = {},
	auto_install = true,
	ensure_installed = {
		"markdown",
		"markdown_inline",
	},
	highlight = { enable = true },
})
```

### To Reproduce

1. Open a Markdown file in Neovim.
2. Type `gc` to comment a line, for example:
   ```markdown
   This is a test
   ```
3. Observe that the line is initially commented correctly as:
   ```markdown
   <!--This is a test-->
   ```
4. Quit Neovim and reopen the file.
5. Repeat the `gc` command on the same line.
6. Notice that the line is now commented as:
   ```markdown
   # This is a test
   ```
7. Repeat steps 4-6 multiple times, and observe that the commenting method alternates randomly between the two formats.

### Expected behavior

The line should always be commented using the `commentstring` specified in Neovim, which is `<!--%s-->` for Markdown files. Therefore, the line should consistently be commented as:
```markdown
<!--This is a test-->
```

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.23.0 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.19.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.8.0-45-generic",
  sysname = "Linux",
  version = "#45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068
```

### Additional context

Comes from neovim/neovim#30522

**Comment by clason** [comment] 2024-09-26 13:20
Cannot reproduce it here, either. I expect you are testing with `nvim --clean -u test.lua` (if not, do that). What does `:set ft?` show in each instance? What does `:InspectTree` show (press `I` to toggle language display)?

**Comment by yuukibarns** [comment] 2024-09-26 13:38
use `nvim --clean -u test.lua` the weird commenting behavior persists... 
Now it stably comments like this:
```markdown
# This is a test
```
`:set ft` shows `filetype=markdown`
`:InspectTree` and press `I` show:
![test](https://github.com/user-attachments/assets/664c8656-63ac-46b1-bec5-1ba8ea99bb9a)

**Comment by yuukibarns** [comment] 2024-09-26 13:46
use nightly the only difference is the output of `:set commentstring`. it shows `commentstring=<!-- %s -->` now.

**Comment by yuukibarns** [comment] 2024-09-26 13:50
And it keeps popping up `No parse for the given buffer` warning when i use my full configuration...

**Comment by clason** [comment] 2024-09-26 13:54
Out of scope here. Please test with `nvim --clean -u test.lua`.

**Comment by clason** [comment] 2024-09-26 13:56
Sorry, I cannot reproduce this, and I have no explanation for what you observe.

**Comment by yuukibarns** [comment] 2024-09-26 14:01
I installed `nvim-treesitter` using `lazy.nvim` with an empty `ensure_install` list and then moved it to a different directory (`~/nvim-treesitter/`). I suspect that the issue might be related to `lazy.nvim`. Is there an alternative method to install `nvim-treesitter` neatly?

**Comment by clason** [comment] 2024-09-26 14:06
Just clone the directory and add it to your runtimepath, as in your minimal config (which is what I assumed you did). I strongly suspect that you're seeing -- for some reason I can't fathom -- a different mapping than the builtin commenting (which would use `gcc` for un/commenting a single line, mind you).

**Comment by yuukibarns** [comment] 2024-09-26 14:19
The same result... :confused:

**Comment by igorlfs** [comment] 2024-09-26 19:25
> Is there anyone who can reproduce it?

I'm also having this issue, though I haven't found a consistent way of reproducing

> try several times

It happens fairly often with me, I'd say around half the time.

nvim version is the lastest commit from main, NVIM v0.11.0-dev-840+gf2fa4ca97e, and I'm on Linux

**Comment by clason** [comment] 2024-09-26 19:45
Needs details: installation, minimal config, exact reproduction steps. A simple "Me too" does not help in any way whatsoever.

**Comment by clason** [comment] 2024-09-26 19:46
And don't use main.

**Comment by igorlfs** [comment] 2024-09-27 00:07
> Needs details: installation, minimal config, exact reproduction steps. A simple "Me too" does not help in any way whatsoever.

I'm sorry. I provided the details I assumed were relevant (nvim version/OS). Since you couldn't reproduce this behavior at all, I assumed you were using another OS. 

When I made that comment, I was using specifically @yuukibarns minimal config (the one in the OP), but of course this also happens with my regular config.

I realize that without exact reproduction steps, there's little to gain here, but as @yuukibarns described, this behavior only happens sometimes, and I wasn't able to craft a consistent setup. My intent was to highlight that OP isn't the only one with the issue, so our setups must share something yours is missing.

**Comment by yuukibarns** [comment] 2024-09-27 01:34
I can reproduce it on windows 10 vm.

**Comment by yuukibarns** [comment] 2024-09-27 04:20
With this config `minimal.lua`
```lua
local path = "~/nvim-treesitter"
vim.opt.rtp:prepend(path)
```
where directly `git clone https://github.com/nvim-treesitter/nvim-treesitter` at `~` directory.
And use `nvim --clean -u minimal.lua test.md`, `test.md` as follows:
[test.md](https://github.com/user-attachments/files/17158933/test.md)
I can consistently reproduce the problem and even inside lua block `require("nvim-treesitter")` is commented as `# require("nvim-treesitter")`.

But with `nvim -u minimal.lua test.md`,  inside lua block the same line is normally commented as `-- require("nvim-treesitter")`, but outside the lua block the problem persists.

**Comment by clason** [comment] 2024-09-27 07:54
What _exactly_ are you typing (`gc` by itself does nothing)? What does `:map gc` say, in the setting where it inserts `#` instead of the correct comment marker?

**Comment by yuukibarns** [comment] 2024-09-27 08:34
Of course `gcc` or `gc`+`motion`, what else can i use?... Here is the output of `:map gc`,
```
o  gc          * <Lua 13: vim/_defaults.lua:0>
                 Comment textobject
n  gcc         * <Lua 12: vim/_defaults.lua:0>
                 Toggle comment line
x  gc          * <Lua 11: vim/_defaults.lua:0>
                 Toggle comment
n  gc          * <Lua 10: vim/_defaults.lua:0>
                 Toggle comment
```

**Comment by yuukibarns** [comment] 2024-09-27 08:42
> I can consistently reproduce the problem
I can't consistently reproduce the problem now,  just now i opened the same file with `nvim --clean -u minimal.lua test.md`, the commenting behaves normally, but it is very rare and i can't figure out why...

**Comment by seblj** [comment] 2024-10-01 16:52
I think the reason this is happening, is because markdown is registered for rmd and quarto, and them both have `# %s` as commentstring. See: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/parsers.lua#L15-L16

**Comment by clason** [comment] 2024-10-01 19:02
Indeed, and that is already the case on `main`. I'll hotfix this now. Thanks!

**Closed by clason** 2024-10-01 19:02 UTC
Labels: bug

**Comment by jalvesaq** [comment] 2024-10-02 13:58
I used to be the maintainer of `runtime/ftplugin/rmd.vim`... 

The value of `commentstring` is defined dynamically by the function `SetRmdCommentStr()` unless the user has disabled this feature (which depends on the `CursorMoved` autocommand): https://github.com/neovim/neovim/blob/391c5084d1181a6742ebd8551efda4db7e8ca46e/runtime/ftplugin/rmd.vim#L39

However, this is a feature useful for Vim. For Neovim, I believe that it would be better if comment plugins got the language of embedded code and chose the comment string accordingly.

**Comment by jalvesaq** [comment] 2024-10-02 15:20
Thanks for the reply, @clason! We will do this for our users in [R.nvim](https://github.com/R-nvim/R.nvim).
