### ISSUE TITLE
Strange line before some html block with `tree-sitter-html`

### ISSUE THREAD

**Issue by Ogromny** [nvim-treesitter/nvim-treesitter#1371] opened 2021-06-08 07:44 UTC
**Describe the bug**

I have these strange lines before some block on every `html` file:
![bug](https://i.imgur.com/cu6VUXg.png)

I think the bug is due to `tree-sitter-html` trying to apply to every `text` node, each `@text.*` corresponding highlight group:
![bug](https://i.imgur.com/2M3Qdu2.png)

**To Reproduce**

install `nvim-treesitter`, `tree-sitter-html`, turn on highlighting for `html`, open a `html` file

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.5 (8d8690538ef0029885c7ef1f163b0e32f256a5aa) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.16.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - latex          ✓ . ✓ . . 
  - c_sharp        ✓ . ✓ . ✓ 
  - zig            ✓ ✓ ✓ ✓ ✓ 
  - svelte         ✓ . ✓ ✓ ✓ 
  - beancount      ✓ . ✓ . . 
  - bibtex         ✓ . ✓ ✓ . 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - fortran        ✓ . ✓ ✓ . 
  - teal           ✓ ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - r              ✓ ✓ . . . 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . . 
  - gomod          ✓ . . . . 
  - dart           ✓ ✓ . ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - devicetree     ✓ ✓ ✓ ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - regex          ✓ . . . . 
  - scss           ✓ . . ✓ . 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - jsdoc          ✓ . . . . 
  - ledger         ✓ . ✓ ✓ ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - julia          ✓ ✓ ✓ . ✓ 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - gdscript       ✓ ✓ . . ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - verilog        ✓ ✓ ✓ . ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - ql             ✓ ✓ . ✓ ✓ 
  - fennel         ✓ ✓ . . ✓ 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - rst            ✓ ✓ . . ✓ 
  - nix            ✓ ✓ ✓ . ✓ 
  - swift          . . . . . 
  - elm            . . . . . 
  - vue            ✓ . ✓ . ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - elixir         ✓ ✓ . ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - haskell        . . . . . 
  - kotlin         ✓ . . . ✓ 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - ocamllex       ✓ . . . ✓ 
  - scala          . . . . . 
  - dockerfile     ✓ . . . ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - ocaml_interface✓ ✓ ✓ . ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - glimmer        ✓ . . . . 
  - erlang         . . . . . 
  - clojure        ✓ ✓ ✓ . ✓ 
  - commonlisp     ✓ ✓ ✓ . . 
  - tsx            ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+1384-gf2906a466-dirty
Build type: Gentoo
LuaJIT 2.0.5
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -march=native -O2 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/config -I/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src -I/usr/include -I/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/include
Compilé par portage@localhost

Features: +acl +iconv +tui
See ":help feature-compile"

         fichier vimrc système : "/etc/vim/sysinit.vim"
               $VIM par défaut : "/usr/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

Here is config if this can help:

> init.vim
<details>

```lua
lua require('plugins')
```

</details>

> plugins.lua
<details>

```lua
vim.cmd "packadd packer.nvim"

local packer = require "packer"
local use = packer.use

vim.o.swapfile = false
vim.o.signcolumn = "number"
vim.o.relativenumber = true
vim.o.hidden = true
vim.o.tabstop = 4
vim.o.shiftwidth = 4
vim.o.expandtab = false

vim.api.nvim_set_keymap("n", "<Up>", "<Nop>", {noremap = true})
vim.api.nvim_set_keymap("n", "<Down>", "<Nop>", {noremap = true})
vim.api.nvim_set_keymap("n", "<Left>", "<Nop>", {noremap = true})
vim.api.nvim_set_keymap("n", "<Right>", "<Nop>", {noremap = true})

-- vim.cmd "filetype on"
-- vim.cmd "syntax enable"

-- NOTE: see https://github.com/neovim/neovim/issues/9876
vim.cmd "highlight! link PmenuSel DiffText"

return packer.startup(function()
    use {
		"wbthomason/packer.nvim",
		opt = true
	}
	use {
		"folke/tokyonight.nvim",
		config = function ()
			vim.g.tokyonight_style = "night"
			vim.g.tokyonight_transparent = true
			vim.g.tokyonight_hide_inactive_statusline = true
			vim.cmd "colorscheme tokyonight"
			vim.cmd "highlight! LspDiagnosticsVirtualTextError guibg=None"
			vim.cmd "highlight! LspDiagnosticsVirtualTextHint guibg=None"
			vim.cmd "highlight! LspDiagnosticsVirtualTextInformation guibg=None"
			vim.cmd "highlight! LspDiagnosticsVirtualTextWarning guibg=None"
			vim.cmd "highlight! NormalFloat guibg=None"
		end
	}
    use {
		"folke/lsp-colors.nvim",
		config = function()
			require("lsp-colors").setup {}
		end
	}
    use {
        "hoob3rt/lualine.nvim",
		requires = {
			"kyazdani42/nvim-web-devicons",
		},
        config = function()
			require("nvim-web-devicons").setup {
				default = true
			}
			require("lualine").setup {
				options = {
					theme = "tokyonight"
				}
			}
        end
    }
	use {
		"nvim-telescope/telescope.nvim",
		requires = {
			"nvim-lua/popup.nvim",
			"nvim-lua/plenary.nvim",
			"nvim-telescope/telescope-project.nvim"
		},
		config = function()
			local telescope = require("telescope")
			telescope.setup {}
			telescope.load_extension("project")

			vim.api.nvim_set_keymap(
				"n",
				"<leader><leader>",
				":Telescope find_files<CR>",
				{
					silent = true,
					noremap = true
				}
			)
			vim.api.nvim_set_keymap(
				"n",
				"<leader>g",
				":Telescope live_grep<CR>",
				{
					silent = true,
					noremap = true
				}
			)
			vim.api.nvim_set_keymap(
				"n",
				"<leader>b",
				":Telescope buffers<CR>",
				{
					silent = true,
					noremap = true
				}
			)
			vim.api.nvim_set_keymap(
				"n",
				"<leader>p",
				":lua require('telescope').extensions.project.project()<CR>",
				{
					silent = true,
					noremap = true
				}
			)
		end
	}
    use {
        "lewis6991/gitsigns.nvim",
        requires = {
			"nvim-lua/plenary.nvim"
		},
        config = function()
            require("gitsigns").setup {}
        end
    }
    use {
        "hrsh7th/nvim-compe",
        config = function()
            require("compe").setup {
                enabled = true,
                autocomplete = true,
                debug = false,
                min_length = 0,
                preselect = "enable",
                throttle_time = 80,
                source_timeout = 200,
                incomplete_delay = 400,
                max_abbr_width = 100,
                max_kind_width = 100,
                max_menu_width = 100,
                documentation = true,
                source = {
                    path = true,
                    buffer = false,
                    calc = true,
                    vsnip = false,
                    nvim_lsp = true,
                    nvim_lua = true,
                    spell = true,
                    tags = true,
                    snippets_nvim = true,
                    treesitter = true
                }
            }

            local t = function(str)
                return vim.api.nvim_replace_termcodes(str, true, true, true)
            end

            local check_back_space = function()
                local col = vim.fn.col(".") - 1
                if col == 0 or vim.fn.getline("."):sub(col, col):match("%s") then
                    return true
                else
                    return false
                end
            end

			_G.tab_complete = function()
				if vim.fn.pumvisible() == 1 then
					return t "<C-n>"
				-- elseif vim.fn.call("vsnip#available", {1}) == 1 then
				-- 	return t "<Plug>(vsnip-expand-or-jump)"
				elseif check_back_space() then
					return t "<Tab>"
				else
					return vim.fn["compe#complete"]()
				end
			end

			_G.s_tab_complete = function()
				if vim.fn.pumvisible() == 1 then
					return t "<C-p>"
				-- elseif vim.fn.call("vsnip#jumpable", {-1}) == 1 then
				-- 	return t "<Plug>(vsnip-jump-prev)"
				else
					return t "<S-Tab>"
				end
			end

            vim.o.completeopt = "menuone,noselect"

            vim.api.nvim_set_keymap(
				"i",
				"<Tab>",
				"v:lua.tab_complete()",
                {
					expr = true
				}
			)
            vim.api.nvim_set_keymap(
				"s",
				"<Tab>",
				"v:lua.tab_complete()",
				{
					expr = true
				}
			)
            vim.api.nvim_set_keymap(
				"i",
				"<S-Tab>",
				"v:lua.s_tab_complete()",
				{
					expr = true
				}
			)
            vim.api.nvim_set_keymap(
				"s",
				"<S-Tab>",
				"v:lua.s_tab_complete()",
				{
					expr = true
				}
			)
            vim.api.nvim_set_keymap(
				"i",
				"<C-Space>",
				"compe#complete()",
				{
					silent = true,
					expr = true,
					noremap = true
				}
			)
            vim.api.nvim_set_keymap(
				"i",
				"<CR>",
				"compe#confirm('<CR>')",
				{
					silent = true,
					expr = true,
					noremap = true
				}
			)
        end
    }
    use {
        "neovim/nvim-lspconfig",
        config = function()
            local config = require "lspconfig"
			local signature = require "lsp_signature"

			-- NOTE: UTILS
			local on_attach = function ()
				signature.on_attach {
					bind = true,
					floating_window = true,
					hint_enable = true,
					hint_prefix = ":) ",
					hint_scheme = "Error",
					use_lspsaga = false,
					hi_parameter = "Error"
				}
			end

			local setup = function (name, cfg)
				cfg.on_attach = on_attach
				config[name].setup(cfg)
			end

			-- NOTE: SERVERS
			local luaLSPDir = "/home/ogromny/.local/bin/lua-language-server"
			setup("sumneko_lua", {
                cmd = {
					luaLSPDir .. "/bin/Linux/lua-language-server",
					"-E",
					luaLSPDir .. "/main.lua"
                },
                settings = {
                    Lua = {
                        runtime = {
                            version = "LuaJIT",
                            path = vim.split(package.path, ";")
                        },
                        diagnostics = {enable = true, globals = {"vim"}},
                        workspace = {
                            library = {
                                [vim.fn.expand("$VIMRUNTIME/lua")] = true,
                                [vim.fn.expand("$VIMRUNTIME/lua/vim/lsp")] = true
                            }
                        }
                    }
                }
			})

			setup("clangd", {})
			-- setup("phpactor", {})
			setup("intelephense", {})
			-- setup("html", {})
			-- setup("css", {})

			-- NOTE: neovim related
			vim.api.nvim_set_keymap(
				"n",
				"<leader>ac",
				":lua vim.lsp.buf.code_action()<CR>",
				{
					silent = true,
					noremap = true
				}
			)
			vim.api.nvim_set_keymap(
				"v",
				"<leader>ac",
				":lua vim.lsp.buf.range_code_action()<CR>",
				{
					silent = true,
					noremap = true
				}
			)

			vim.api.nvim_set_keymap(
				"n",
				"gd",
				":lua vim.lsp.buf.declaration()<CR>",
				{
					silent = true,
					noremap = true
				}
			)

			vim.api.nvim_set_keymap(
				"n",
				"<leader>r",
				":lua vim.lsp.buf.rename()<CR>",
				{
					silent = true,
					noremap = true
				}
			)

			-- TODO: function table to string
			local popup_opts = {
				border = "single",
				focusable = false
			}

			vim.lsp.handlers["textDocument/hover"] = vim.lsp.with(
				vim.lsp.handlers.hover,
				popup_opts
			)
			vim.api.nvim_set_keymap(
				"n",
				"K",
				":lua vim.lsp.buf.hover()<CR>",
				{
					silent = true,
					noremap = true
				}
			)

			vim.api.nvim_set_keymap(
				"n",
				"[g",
				":lua vim.lsp.diagnostic.goto_prev {popup_opts={border='single', focusable = false}} <CR>",
				{
					silent = true,
					noremap = true
				}
			)
			vim.api.nvim_set_keymap(
				"n",
				"]g",
				":lua vim.lsp.diagnostic.goto_next {popup_opts={border='single', focusable = false}} <CR>",
				{
					silent = true,
					noremap = true
				}
			)

			-- NOTE: https://github.com/neovim/neovim/pull/12378
			vim.cmd "autocmd CursorHold,CursorHoldI * :lua vim.lsp.diagnostic.show_line_diagnostics {border='single', focusable = false}"
            vim.o.updatetime = 300
        end
    }
    use {
        "nvim-treesitter/nvim-treesitter",
        run = ":TSUpdate",
		requires = {
			"nvim-treesitter/playground"
		},
        config = function()
            require("nvim-treesitter.configs").setup {
				highlight = {
					enable = true
				},
				playground = {
					enable = true,
					disable = {},
					updatetime = 25, -- Debounced time for highlighting nodes in the playground from source code
					persist_queries = false, -- Whether the query persists across vim sessions
					keybindings = {
						toggle_query_editor = 'o',
						toggle_hl_groups = 'i',
						toggle_injected_languages = 't',
						toggle_anonymous_nodes = 'a',
						toggle_language_display = 'I',
						focus_language = 'f',
						unfocus_language = 'F',
						update = 'R',
						goto_node = '<cr>',
						show_help = '?',
					},
				}
			}
        end
    }
    use {
		"ray-x/lsp_signature.nvim"
	}
    use {
        "folke/todo-comments.nvim",
        requires = {
			"nvim-lua/plenary.nvim"
		},
        config = function()
			require("todo-comments").setup {}
            vim.o.signcolumn = "yes"
		end
    }
    use {
        "steelsojka/pears.nvim",
        config = function()
            require("pears").setup(function(conf)
                conf.on_enter(function(pears_handle)
                    if vim.fn.pumvisible() == 1 and
                        vim.fn.complete_info().selected ~= -1 then
                        return vim.fn["compe#confirm"]("<CR>")
                    else
                        pears_handle()
                    end
                end)
            end)
        end
    }
end)
```

</details>

**Comment by stsewd** [comment] 2021-06-08 13:48
I have experienced this as well, queries look correct in the playground https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/html/highlights.scm. Is like all highlights under `@text.*` are being captured.

**Comment by Ogromny** [comment] 2021-06-08 14:06
Yep and it only happen with html, did you manage to fix it ?

**Comment by stsewd** [comment] 2021-06-08 14:10
Was playing around with the queries without luck, maybe the problem is somewhere else.

**Comment by adamansky** [comment] 2021-06-21 05:03
I think here is the wrong behavior of `TSURI` context (which is underlined) - it is wrongly propagated after end of uri

**Comment by fcomoreira1** [comment] 2021-06-26 17:48
Is this fixed already? These lines are so annoying

**Comment by gegoune** [comment] 2021-07-05 09:32
Seeing the same in vue with TS enabled.

**Comment by theHamsta** [comment] 2021-07-05 21:03
This is the same issue as #1506
```
;((element (start_tag (tag_name) @_tag) (text) @text.title)
 ;(#match? @_tag "^(h[0-9]|title)$"))

;((element (start_tag (tag_name) @_tag) (text) @text.strong)
 ;(#match? @_tag "^(strong|b)$"))

;((element (start_tag (tag_name) @_tag) (text) @text.emphasis)
 ;(#match? @_tag "^(em|i)$"))

;((element (start_tag (tag_name) @_tag) (text) @text.strike)
 ;(#match? @_tag "^(s|del)$"))

;((element (start_tag (tag_name) @_tag) (text) @text.underline)
 ;(#eq? @_tag "u"))

;((element (start_tag (tag_name) @_tag) (text) @text.literal)
 ;(#match? @_tag "^(code|kbd)$"))

;((element (start_tag (tag_name) @_tag) (text) @text.uri)
 ;(#eq? @_tag "a"))

;((attribute
   ;(attribute_name) @_attr
   ;(quoted_attribute_value (attribute_value) @text.uri))
 ;(#match? @_attr "^(href|src)$"))
```
those queries in `html_tags/highlights` are the culprits. Apparently due to a change in tree-sitter or Neovim itself the `@_attr` captures are just ignored.

**Comment by theHamsta** [comment] 2021-07-05 21:15
Any one with too much time to bisect Neovim or Tree-sitter runtime versions? :smile:

**Comment by stsewd** [comment] 2021-07-10 02:33
Looks like vim's syntax hl is being enabled together with treesitter. Can you all check the output of `:set syntax?` in a html file.

**Comment by stsewd** [comment] 2021-07-10 02:34
tested this without extra plugins, so some runtime file is maybe activating it.

**Comment by charbelnicolas** [comment] 2021-07-10 02:38
![20210709_213743](https://user-images.githubusercontent.com/14960414/125149320-01b6bc00-e0fe-11eb-9009-9434f78d653a.png)

Syntax comes up empty here...

**Comment by stsewd** [comment] 2021-07-10 02:59
I still get the stricken text after setting `syntax off`, so isn't related, but still problem worth tracking...

**Comment by stsewd** [comment] 2021-07-10 03:43
I think this has to do with the parser capturing whitespaces as tokens and/or nvim not handling extmarks over spaces correctly.

**Comment by stsewd** [comment] 2021-07-10 05:44
This fixed the problem for me on the file I was testing https://github.com/stsewd/tree-sitter-html/commit/e978f539b0ea7f49f71d261bd342c70082a6b04a

Can someone test if this also fix the problems for other languages that embed html? You can edit the `lua/nvim-treesitter/parsers.lua` file with

```lua
list.html = {
  install_info = {
    url = "https://github.com/stsewd/tree-sitter-html",
    branch = "dont-include-trailing-spaces",
    files = { "src/parser.c", "src/scanner.cc" },
  },
  used_by = { "html_tags" },
  maintainers = { "@TravonteD" },
}
```

And edit the lockfile

```json
  "html": {
    "revision": "e978f539b0ea7f49f71d261bd342c70082a6b04a"
  },

```

Sent a PR https://github.com/tree-sitter/tree-sitter-html/pull/27

But we still should take a look at neovim, I think there is also a problem where it's trying to highlight the EOL char.

**Comment by stsewd** [comment] 2021-07-11 20:22
PR was merged upstream, but the problem is still present (but a little less noisy), closing in favor of https://github.com/nvim-treesitter/nvim-treesitter/issues/1506#issuecomment-877740522

**Closed by stsewd** 2021-07-11 20:22 UTC
Labels: bug
