### ISSUE TITLE
Invalid node type at position for language bash

### ISSUE THREAD

**Issue by Maritsu** [nvim-treesitter/nvim-treesitter#5345] opened 2023-09-02 16:58 UTC
### Describe the bug

Upon trying to do **anything** in a bash script, NVIM errors out, saying "invalid node type at position <insert some integer> for language bash".

### To Reproduce

1. Install treesitter
2. Open a file with the filetype `bash`
3. Try to write some text

### Expected behavior

No errors pop up, everything works just fine.

### Output of `:checkhealth nvim-treesitter`

```markdown
-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.5.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.4.12-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:38:14 +0000"
} ~

Parser/Features         H L F I J
  - bash                x ✓ ✓ . x
  /* all other parsers are fine */

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR bash(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 242 for language bash
  bash(highlights) is concatenated from the following files:
  | [ERROR]:"/home/bit/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/bash/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 242 for language bash
- ERROR bash(injections): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 195 for language bash
  bash(injections) is concatenated from the following files:
  | [ERROR]:"/home/bit/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/bash/injections.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 195 for language bash
```

### Output of `nvim --version`

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.1692616192
```

### Additional context

This started happening right after updating Treesitter.

**Comment by clason** [comment] 2023-09-02 16:59
Duplicate of #3092

**Closed by clason** 2023-09-02 16:59 UTC
Labels: bug

**Comment by sergii4** [comment] 2023-09-09 18:57
Hi @Maritsu, did #3092 work for you?

**Comment by Maritsu** [comment] 2023-09-09 18:58
> Hi @Maritsu, did #3092 work for you?

I haven't really had time to do anything related to configuring, i'll try it out tomorrow.

**Comment by zapling** [comment] 2023-09-19 14:51
Just ran into this issue myself and deleting my `nvim-treesitter` plugin directory (in my case `~/.local/share/nvim/lazy/nvim-treesitter/` ) and letting my package manager re-download it solve the issue.
