### ISSUE TITLE
Invalid Node Type, Typescript

### ISSUE THREAD

**Issue by owlwres** [nvim-treesitter/nvim-treesitter#6985] opened 2024-07-27 16:20 UTC
### Describe the bug

I get the following message whenever I open a Typescript file for the first time:

```
Error executing lua callback: /usr/local/share/nvim/runtime/filetype.lua:36: BufReadPost Autocommands for "*"..FileType Autocommands for "*": Vim(append):Error executing lua callback: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 4:2. Invalid node type "function_expression":
(function_expression
 ^

stack traceback:
	[C]: in function '_ts_parse_query'
	/usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
	/usr/local/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
	/usr/local/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get_query'
	...r-textobjects/lua/nvim-treesitter/textobjects/shared.lua:99: in function 'available_textobjects'
	...r-textobjects/lua/nvim-treesitter/textobjects/select.lua:173: in function 'attach'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:132>
	[C]: in function 'nvim_cmd'
	/usr/local/share/nvim/runtime/filetype.lua:36: in function </usr/local/share/nvim/runtime/filetype.lua:35>
	[C]: in function 'pcall'
	vim/shared.lua: in function <vim/shared.lua:0>
	[C]: in function '_with'
	/usr/local/share/nvim/runtime/filetype.lua:35: in function </usr/local/share/nvim/runtime/filetype.lua:10>
stack traceback:
	[C]: in function '_with'
	/usr/local/share/nvim/runtime/filetype.lua:35: in function </usr/local/share/nvim/runtime/filetype.lua:10>
```
I deleted every directory given by `:echo nvim_get_runtime_file('parser', v:true)`, deleted all of my `nvim-treesitter` plugin directories, built the latest `master`, ran `:TSUpdate`, and it persists.

### To Reproduce

See the above.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.6 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v22.5.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.8.0-38-generic",
  sysname = "Linux",
  version = "#38-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 15:25:01 UTC 2024"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c_sharp             ✓ ✓ ✓ . ✓
  - fennel              ✓ ✓ ✓ . ✓
  - haskell             ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - org                 ✓ . ✓ . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.11.0-dev-508+gaee4254b7
Build type: Debug
LuaJIT 2.1.1720049189
Run "nvim -V1 -v" for more info
```

**Comment by clason** [comment] 2024-07-27 16:22
Duplicate of #3092

**Comment by clason** [comment] 2024-07-27 16:23
You also need to check your other plugins that use treesitter queries; in this case the error is coming from textobjects.

**Closed by clason** 2024-07-27 16:22 UTC
Labels: bug
